/** Compiled FORGE account workflow. Synthetic identities only; no live provider/account is contacted. */
import {createRequire} from 'node:module';
import {readFileSync,readdirSync,realpathSync,statSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(realpathSync('node_modules/wrangler/package.json'));
const {Miniflare,Log,LogLevel}=require('miniflare');
function walk(dir){return readdirSync(dir).flatMap(n=>{const p=resolve(dir,n);return statSync(p).isDirectory()?walk(p):p.endsWith('.js')?[p]:[];});}
const modules=[resolve('dist/server/index.js'),...walk('dist/server').filter(p=>p!==resolve('dist/server/index.js'))].map(path=>({type:'ESModule',path}));
const mf=new Miniflare({modules,modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],outboundService:()=>{throw Error('Unexpected provider request in email account test');},log:new Log(LogLevel.ERROR)});
let passed=0;const results=[];
async function check(name,fn){await fn();passed++;results.push({name,status:'PASS'});console.log('PASS '+name);}
function cookies(response){const set=response.headers.getSetCookie?.()||[response.headers.get('set-cookie')||''];return set.flatMap(x=>x.split(/, (?=[A-Za-z_])/)).map(x=>x.split(';')[0]).join('; ');}
async function call(path,{body,status=200,cookie='',headers={},method,origin=true}={}){const h={...headers};if(cookie)h.cookie=cookie;if(body){h['content-type']='application/json';if(origin&&!h.origin)h.origin='https://forge.test';}const response=await mf.dispatchFetch('https://forge.test'+path,{method:method||(body?'POST':'GET'),headers:h,...(body?{body:JSON.stringify(body)}:{})});assert.equal(response.status,status,`${path}: ${await response.clone().text()}`);return response;}
const strong='synthetic FORGE password 2026';
try{
 const db=await mf.getD1Database('DB');for(const file of readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())for(const sql of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()))await db.prepare(sql).run();
 await check('anonymous session is explicit and Google remains unconfigured',async()=>{const r=await call('/api/auth/session'),d=await r.json();assert.equal(d.user,null);assert.equal(d.googleAvailable,false);assert.equal(d.passwordRecoveryAvailable,false);});
 await check('anonymous saved workspace access rejected',()=>call('/api/forge',{status:401}));
 await check('signup rejects cross-origin requests',()=>call('/api/auth/signup',{body:{email:'a@example.test',name:'A User',password:strong},headers:{origin:'https://evil.test'},status:403}));
 await check('signup enforces minimum password length',()=>call('/api/auth/signup',{body:{email:'short@example.test',name:'Short User',password:'short'},status:400}));
 await check('signup enforces UTF-8 byte ceiling',()=>call('/api/auth/signup',{body:{email:'bytes@example.test',name:'Byte User',password:'界'.repeat(25)},status:400}));
 await check('account payload is bounded',()=>call('/api/auth/signup',{body:{email:'size@example.test',name:'Large User',password:strong,padding:'x'.repeat(5000)},status:413}));
 let emailCookie,userId,workspace;
 await check('manual signup saves a private unverified identity and secure opaque session',async()=>{const r=await call('/api/auth/signup',{body:{email:'OWNER@Example.test',name:'Synthetic Owner',password:strong,returnTo:'https://evil.test'}});emailCookie=cookies(r);const h=r.headers.get('set-cookie');assert.ok(h.includes('HttpOnly')&&h.includes('Secure')&&h.includes('SameSite=Lax'));assert.equal((await r.json()).returnTo,'/app');const d=await (await call('/api/auth/session',{cookie:emailCookie})).json();userId=d.user.userId;assert.ok(userId.startsWith('forge:'));assert.equal(d.user.emailVerified,false);const a=await db.prepare('SELECT password_hash FROM forge_auth_accounts WHERE id=?').bind(userId).first();assert.ok(a.password_hash.startsWith('$2'));assert.notEqual(a.password_hash,strong);});
 await check('duplicate email does not create another account',()=>call('/api/auth/signup',{body:{email:'owner@example.test',name:'Other User',password:strong},status:409}));
 await check('own account creates and reads a persistent workspace',async()=>{const r=await call('/api/forge',{cookie:emailCookie,body:{action:'createWorkspace',name:'Synthetic account workspace',product:'Synthetic Product'},status:201});workspace=await r.json();const rows=await (await call('/api/forge',{cookie:emailCookie})).json();assert.equal(rows.workspaces.length,1);const fresh=await (await call('/api/forge?workspace='+workspace.id,{cookie:emailCookie})).json();assert.equal(fresh.role,'owner');assert.equal(fresh.state.product,'Synthetic Product');});
 let otherCookie,otherId;
 await check('FORGE login panel renders password and account controls',async()=>{const text=await (await call('/login')).text();assert.ok(text.includes('forge-password')&&text.includes('Create account')&&text.includes('Show'));});
 await check('own account enters the server-rendered workspace without a platform user header',async()=>{const text=await (await call('/app',{cookie:emailCookie})).text();assert.ok(text.includes('Synthetic Owner'),'Own account name reaches the server-rendered workspace');assert.ok(text.includes('Opening your evidence workspace'),'Workspace loads saved records on hydration');});
 await check('different account cannot read another workspace',async()=>{otherCookie=cookies(await call('/api/auth/signup',{body:{email:'other@example.test',name:'Other Owner',password:strong}}));otherId=(await (await call('/api/auth/session',{cookie:otherCookie})).json()).user.userId;await call('/api/forge?workspace='+workspace.id,{cookie:otherCookie,status:403});});
 await check('unverified manual identity cannot receive shared membership',()=>call('/api/forge',{cookie:emailCookie,body:{action:'membership',workspaceId:workspace.id,userId:otherId,role:'reviewer'},status:403}));
 await check('SQL shared membership boundary also blocks bypass',async()=>{await assert.rejects(()=>db.prepare("INSERT INTO memberships(id,workspace_id,user_id,role,active,created_at) VALUES('unverified-direct',?,?,'reviewer',1,?)").bind(workspace.id,otherId,new Date().toISOString()).run(),/Verified identity/);});
 await check('wrong password returns generic rejection',()=>call('/api/auth/login',{body:{email:'owner@example.test',password:'synthetic wrong password 2026'},status:401}));
 await check('unknown account returns the same rejection',async()=>{const r=await call('/api/auth/login',{body:{email:'unknown@example.test',password:strong},status:401});assert.equal((await r.json()).error,'Email or password was not accepted.');});
 let freshCookie;
 await check('login rotates session and invalidates the previous token',async()=>{freshCookie=cookies(await call('/api/auth/login',{cookie:emailCookie,body:{email:'owner@example.test',password:strong}}));assert.equal((await (await call('/api/auth/session',{cookie:emailCookie})).json()).user,null);assert.equal((await (await call('/api/auth/session',{cookie:freshCookie})).json()).user.userId,userId);});
 await check('expired session is rejected',async()=>{await db.prepare("UPDATE forge_auth_sessions SET expires_at='2000-01-01T00:00:00.000Z' WHERE account_id=?").bind(otherId).run();assert.equal((await (await call('/api/auth/session',{cookie:otherCookie})).json()).user,null);});
 await check('logout requires same origin',()=>call('/api/auth/logout',{cookie:freshCookie,body:{},origin:false,status:403}));
 await check('logout revokes session and suppresses implicit platform fallback',async()=>{const r=await call('/api/auth/logout',{cookie:freshCookie,body:{}});assert.equal((await (await call('/api/auth/session',{cookie:freshCookie})).json()).user,null);const logged=cookies(r);const d=await (await call('/api/auth/session',{cookie:logged,headers:{'oai-authenticated-user-id':'trusted-old','oai-authenticated-user-email':'old@example.test'}})).json();assert.equal(d.user,null);});
 await check('missing Google configuration is a visible failure',()=>call('/api/auth/google/start',{status:503}));
 const legacyHeaders={'oai-authenticated-user-id':'trusted-old','oai-authenticated-user-email':'old@example.test'};
 let linkCookie,legacyWorkspace,linkId;
 await check('existing trusted platform workspace remains accessible',async()=>{const r=await call('/api/forge',{headers:legacyHeaders,body:{action:'createWorkspace',name:'Existing trusted workspace',product:'Historical Product'},status:201});legacyWorkspace=await r.json();assert.equal((await (await call('/api/forge?workspace='+legacyWorkspace.id,{headers:legacyHeaders})).json()).state.product,'Historical Product');});
 await check('new account plus trusted session exposes explicit link choice',async()=>{linkCookie=cookies(await call('/api/auth/signup',{body:{email:'link@example.test',name:'Link Owner',password:strong}}));const d=await (await call('/api/auth/session',{cookie:linkCookie,headers:legacyHeaders})).json();linkId=d.user.userId;assert.equal(d.legacyLinkAvailable,true);});
 await check('linking requires own session, trusted session and confirmation',async()=>{await call('/api/auth/link-legacy',{cookie:linkCookie,body:{confirm:'LINK_EXISTING_WORKSPACE'},status:403});await call('/api/auth/link-legacy',{cookie:linkCookie,headers:legacyHeaders,body:{confirm:'wrong'},status:400});});
 await check('explicit dual-proof link preserves saved workspace and identity',async()=>{await call('/api/auth/link-legacy',{cookie:linkCookie,headers:legacyHeaders,body:{confirm:'LINK_EXISTING_WORKSPACE'}});const d=await (await call('/api/auth/session',{cookie:linkCookie})).json();assert.equal(d.user.userId,'trusted-old');const w=await (await call('/api/forge?workspace='+legacyWorkspace.id,{cookie:linkCookie})).json();assert.equal(w.state.product,'Historical Product');assert.equal(w.role,'owner');});
 await check('linked identity cannot receive late writes under retired account',async()=>{await assert.rejects(()=>db.prepare("INSERT INTO workspaces(id,name,owner_id,state,version,created_at,updated_at) VALUES('late','Late',?,'{}',0,?,?)").bind(linkId,new Date().toISOString(),new Date().toISOString()).run(),/Linked identity changed/);});
 await check('link is immutable',async()=>{await assert.rejects(()=>db.prepare("UPDATE forge_auth_legacy_links SET legacy_user_id='other' WHERE account_id=?").bind(linkId).run(),/immutable/);});
 const nonemptyCookie=cookies(await call('/api/auth/login',{body:{email:'owner@example.test',password:strong}}));
 await check('nonempty new workspace cannot link and disappear',()=>call('/api/auth/link-legacy',{cookie:cookiesPlaceholder(),headers:{'oai-authenticated-user-id':'different-trusted','oai-authenticated-user-email':'different@example.test'},body:{confirm:'LINK_EXISTING_WORKSPACE'},status:409}));
 await check('concurrent workspace creation enforces the owner cap atomically',async()=>{const results=await Promise.all(Array.from({length:22},(_,i)=>mf.dispatchFetch('https://forge.test/api/forge',{method:'POST',headers:{cookie:nonemptyCookie,origin:'https://forge.test','content-type':'application/json'},body:JSON.stringify({action:'createWorkspace',name:'Quota fixture '+i,product:'Synthetic'})})));assert.equal(results.filter(r=>r.status===201).length,19);assert.ok(results.every(r=>[201,409].includes(r.status)));const n=await db.prepare('SELECT COUNT(*) AS n FROM workspaces WHERE owner_id=?').bind(userId).first();assert.equal(n.n,20);});
 await check('quota rejection leaves no orphan owner membership',async()=>{const n=await db.prepare('SELECT COUNT(*) AS n FROM memberships m LEFT JOIN workspaces w ON w.id=m.workspace_id WHERE w.id IS NULL').first();assert.equal(n.n,0);});
 function cookiesPlaceholder(){return nonemptyCookie;}
}catch(e){console.error(e);process.exitCode=1;}finally{await mf.dispose();writeFileSync('docs/proof/account-results.json',JSON.stringify({at:new Date().toISOString(),passed,failed:process.exitCode?1:0,cases:results,scope:'Compiled Worker with local synthetic identities and D1. Not hosted Google, browser or production qualification.'},null,2));}
console.log(JSON.stringify({suite:'FORGE compiled account/security checks',passed,scope:'Local synthetic identities and storage. Not live Google or production qualification.'}));
