import assert from 'node:assert/strict';
import fs from 'node:fs';
import {initialState,command,SYNTHETIC_SOURCES,hash} from '../lib/core.mjs';
import {branchOverview} from '../lib/branches.mjs';
import {effectiveStatus} from '../lib/lifecycle.mjs';
const AUTHOR={id:'branch-author',role:'author'},REVIEW={id:'independent-reviewer',role:'reviewer'},OWNER={id:'owner',role:'owner'},ADMIN={id:'admin',role:'admin'};
const cases=[];async function test(name,ids,fn){try{await fn();cases.push({name,ids,status:'PASS'});}catch(e){cases.push({name,ids,status:'FAIL',error:e.message});console.error(name,e.stack);}}
const invoke=async(s,input,actor=AUTHOR)=>(await command(s,{...input,expectedVersion:s.version},actor)).state;
const reject=(fn,code)=>assert.rejects(fn,e=>e.code===code);
async function fixture(){let s=initialState('Branch fixture','Synthetic formulation');const src={...SYNTHETIC_SOURCES[0],text:JSON.stringify({note:'SYNTHETIC ONLY. Market-A requires assay source evidence. MINOR is a locally cited candidate category.',...JSON.parse(SYNTHETIC_SOURCES[0].text)})};s=await invoke(s,{action:'intake',...src,permission:'Synthetic frozen fixture'});s=await invoke(s,{action:'extract',id:s.sources[0].id});for(const f of s.fields)s=await invoke(s,{action:'review',kind:'field',id:f.id,revision:f.revision,choice:'APPROVE',reason:'Exact original fixture inspected.'},REVIEW);s=await invoke(s,{action:'draft',title:'Controlled base'});s=await invoke(s,{action:'review',kind:'draft',id:s.drafts[0].id,revision:1,choice:'APPROVE',reason:'Independent base content checked.'},REVIEW);return s;}
async function create(s,kind='DRAFT',targetId=s.drafts[0].id){return invoke(s,{action:'branch',operation:'create',kind,targetId,name:'Proposed controlled revision',reason:'Improve wording under source evidence.'});}
const b=s=>s.ext.controlledBranches.records.at(-1);
async function op(s,operation,extra={},actor=AUTHOR){const x=b(s);return invoke(s,{action:'branch',operation,id:x.id,revision:x.revision,digest:x.digest,reason:'Exact proposal and evidence inspected.',...extra},actor);}
async function edit(s){return op(s,'update',{statementId:b(s).candidate.statements[0].id,text:b(s).candidate.statements[0].text+' Source inspected.'});}
async function submitted(){return op(await edit(await create(await fixture())),'submit');}
async function reviewed(){return op(await submitted(),'review',{choice:'APPROVE'},REVIEW);}
async function ruleFixture(){let s=await fixture(),source=s.sources[0],note=JSON.parse(source.text).note,start=source.text.indexOf(note),r=await command(s,{action:'lifecycle',operation:'rule',expectedVersion:s.version,label:'Local assay control',kind:'REQUIREMENT',market:'Market-A',parameters:['assay'],expression:{op:'REQUIRED_PARAMETER',count:1},requirementIds:[],evidenceRefs:[{fieldId:s.fields[0].id,revision:1}],citations:[{sourceId:source.id,version:1,start,end:start+note.length}]},AUTHOR);return {s:r.state,id:r.result.recordId};}
await test('Branch pins exact base, policy, fact and source without changing approved content',['D08','P02'],async()=>{let s=await fixture();const d=structuredClone(s.drafts[0]),sources=JSON.stringify(s.sources);s=await create(s);assert.deepEqual(s.drafts[0],d);assert.equal(JSON.stringify(s.sources),sources);assert.equal(b(s).baseRevision,1);assert.equal(b(s).evidencePins.sources[0].hash,s.sources[0].hash);assert.equal(b(s).release,false);});
await test('Viewer and scientific reviewer cannot author a branch',['D08','L02'],async()=>{const s=await fixture();for(const actor of [{id:'viewer',role:'viewer'},REVIEW])await reject(()=>createAs(s,actor),'FORBIDDEN');});
function createAs(s,actor){return invoke(s,{action:'branch',operation:'create',kind:'DRAFT',targetId:s.drafts[0].id,name:'Unauthorised',reason:'Attempted scoped operation.'},actor);}
await test('Cross-object branch target is rejected',['D08','L01'],async()=>reject(()=>create(initialState(),'DRAFT','foreign-draft'),'BRANCH_TARGET'));
await test('Unsupported branch properties cannot inject scientific values',['D08','P01'],async()=>{const s=await fixture();await reject(()=>invoke(s,{action:'branch',operation:'create',kind:'DRAFT',targetId:s.drafts[0].id,name:'Unsafe',reason:'Fixture',value:999}),'BRANCH_SCHEMA');});
await test('Editing retains immutable candidate history and exact source pins',['D08','F12'],async()=>{let s=await create(await fixture());const prior=structuredClone(b(s));s=await edit(s);assert.equal(b(s).revision,2);assert.notEqual(b(s).digest,prior.digest);assert.deepEqual(b(s).history[0].candidate,prior.candidate);assert.deepEqual(b(s).evidencePins,prior.evidencePins);assert.equal(s.drafts[0].revision,1);});
await test('A second author cannot edit the named proposal',['D08','L02'],async()=>{const s=await create(await fixture());await reject(()=>op(s,'update',{statementId:b(s).candidate.statements[0].id,text:'Other author edit.'},{id:'other-author',role:'author'}),'BRANCH_AUTHOR_REQUIRED');});
await test('Old branch digest fails even with current workspace revision',['D09','X47'],async()=>{let s=await create(await fixture());const old=structuredClone(b(s));s=await edit(s);await reject(()=>op(s,'submit',{revision:old.revision,digest:old.digest}),'STALE_BRANCH_REVISION');});
await test('No-change proposals cannot consume a review approval',['D09'],async()=>reject(async()=>op(await create(await fixture()),'submit'),'BRANCH_NO_CHANGE'));
await test('Unsupported numeric claims fail proposal QC before review',['D08','D09','P01'],async()=>{let s=await create(await fixture());s=await op(s,'update',{statementId:b(s).candidate.statements[0].id,text:b(s).candidate.statements[0].text+' Accuracy is 999 percent.'});await reject(()=>op(s,'submit'),'BRANCH_QC_FAILED');});
await test('Author cannot self-approve submitted branch',['D09','L02'],async()=>reject(async()=>op(await submitted(),'review',{choice:'APPROVE'},AUTHOR),'FORBIDDEN'));
await test('Owner contributor cannot self-approve despite owner authority',['D09','L02'],async()=>{let s=await fixture();s=await createAs(s,OWNER);s=await op(s,'update',{statementId:b(s).candidate.statements[0].id,text:b(s).candidate.statements[0].text+' Source inspected.'},OWNER);s=await op(s,'submit',{},OWNER);await reject(()=>op(s,'review',{choice:'APPROVE'},OWNER),'INDEPENDENT_REVIEW_REQUIRED');});
await test('Admin authoring role does not grant independent scientific review',['D09','L02'],async()=>reject(async()=>op(await submitted(),'review',{choice:'APPROVE'},ADMIN),'FORBIDDEN'));
await test('Independent decision binds exact candidate digest',['D09','X47'],async()=>{const s=await reviewed();assert.equal(b(s).review.reviewer,REVIEW.id);assert.equal(b(s).review.digest,b(s).digest);assert.equal(b(s).review.revision,b(s).revision);});
await test('Review request and rejection block merge',['D09'],async()=>{for(const choice of ['REQUEST_EVIDENCE','REJECT']){const s=await op(await submitted(),'review',{choice},REVIEW);await reject(()=>op(s,'merge'),'BRANCH_APPROVAL_REQUIRED');}});
await test('New proposal revision invalidates independent branch approval',['D08','D09'],async()=>{let s=await reviewed();s=await edit(s);assert.equal(b(s).status,'WORKING');assert.equal(b(s).review,null);assert.equal(s.ext.controlledBranches.reviews.length,1);await reject(()=>op(s,'merge'),'BRANCH_APPROVAL_REQUIRED');});
await test('Reviewed merge creates a candidate and stales prior main approval',['D09','X48'],async()=>{let s=await reviewed();s=await op(s,'merge');assert.equal(b(s).status,'MERGED');assert.equal(s.drafts[0].revision,2);assert.equal(s.drafts[0].status,'CANDIDATE');assert.equal(s.decisions.find(d=>d.kind==='draft').status,'STALE');assert.equal(s.drafts[0].branchMerge.branchDigest,b(s).digest);assert.equal(s.policy.release,false);});
await test('Merged contributor still cannot approve resulting scientific content',['D09','L02'],async()=>{const s=await op(await reviewed(),'merge');await reject(()=>invoke(s,{action:'review',kind:'draft',id:s.drafts[0].id,revision:2,choice:'APPROVE',reason:'Attempted self review.'},AUTHOR),'FORBIDDEN');await reject(()=>invoke(s,{action:'review',kind:'draft',id:s.drafts[0].id,revision:2,choice:'APPROVE',reason:'Contributor changed role.'},{...AUTHOR,role:'owner'}),'INDEPENDENT_REVIEW_REQUIRED');});
await test('Fresh independent scientific approval is required after proposal merge',['D09','X47'],async()=>{let s=await op(await reviewed(),'merge');s=await invoke(s,{action:'review',kind:'draft',id:s.drafts[0].id,revision:2,choice:'APPROVE',reason:'Merged exact content independently checked.'},REVIEW);assert.equal(s.drafts[0].status,'APPROVED');assert.equal(s.decisions.at(-1).revision,2);});
await test('Changed base blocks approved proposal merge rather than overwriting',['D09','P02'],async()=>{let s=await reviewed();s=await invoke(s,{action:'editDraft',id:s.drafts[0].id,statementId:s.drafts[0].statements[0].id,text:s.drafts[0].statements[0].text+' Main changed.'});await reject(()=>op(s,'merge'),'STALE_BRANCH_BASE');assert.equal(b(s).status,'APPROVED');});
await test('Source replacement blocks merge and marks branch stale on read',['D09','F-P01'],async()=>{let s=await reviewed();s=await invoke(s,{action:'change',id:s.sources[0].id,text:s.sources[0].text,reason:'New synthetic source revision.'});await reject(()=>op(s,'merge'),'STALE_BRANCH_BASE');assert.equal((await branchOverview(s)).records[0].effectiveStatus,'STALE');});
await test('Changed governing policy blocks branch review',['D09','P04'],async()=>{const s=await submitted();s.policy.version='reviewed-policy/2';await reject(()=>op(s,'review',{choice:'APPROVE'},REVIEW),'STALE_BRANCH_EVIDENCE');});
await test('Abandon preserves history even when source is stale',['D08'],async()=>{let s=await create(await fixture());s=await invoke(s,{action:'change',id:s.sources[0].id,text:s.sources[0].text,reason:'Synthetic revision.'});s=await op(s,'abandon');assert.equal(b(s).status,'ABANDONED');assert.equal(b(s).history.length,1);});
await test('Repeated merge is rejected and cannot duplicate a main revision',['D09'],async()=>{const s=await op(await reviewed(),'merge');await reject(()=>op(s,'merge'),'BRANCH_CLOSED');assert.equal(s.drafts[0].revision,2);});
await test('Rule branch cannot inject executable DSL or invented categories',['D08','X44'],async()=>{const f=await ruleFixture();let s=await create(f.s,'RULE',f.id);for(const candidate of [{...b(s).candidate,expression:{op:'EXECUTE_SCRIPT',count:1}},{...b(s).candidate,kind:'CLASSIFICATION',category:'INVENTED_CATEGORY'},{...b(s).candidate,operation:'entity'}])await assert.rejects(()=>op(s,'update',{candidate}),e=>['UNSAFE_RULE','UNSUPPORTED_CLASSIFICATION','BRANCH_SCHEMA'].includes(e.code));});
await test('Rule merge preserves predecessor and creates an unapproved source-cited revision',['D08','D09','X44'],async()=>{const f=await ruleFixture();let s=await create(f.s,'RULE',f.id),old=structuredClone(s.ext.lifecycle.rules[0]);s=await op(s,'update',{candidate:{...b(s).candidate,expression:{op:'REQUIRED_PARAMETER',count:2}}});s=await op(s,'submit');s=await op(s,'review',{choice:'APPROVE'},REVIEW);s=await op(s,'merge');const next=s.ext.lifecycle.rules.at(-1);assert.deepEqual(s.ext.lifecycle.rules[0],old);assert.equal(next.predecessorId,old.id);assert.equal(next.revision,2);assert.equal(effectiveStatus(s,next.id),'CANDIDATE');assert.equal(effectiveStatus(s,old.id),'STALE');assert.equal(next.citations[0].sourceHash,s.sources[0].hash);});
await test('Branch inspection is pure and never silently mutates workspace',['D08','P02'],async()=>{const s=await fixture(),before=await hash(JSON.stringify(s));await branchOverview(s);assert.equal(await hash(JSON.stringify(s)),before);});
const passed=cases.filter(c=>c.status==='PASS').length,failed=cases.length-passed;fs.mkdirSync('docs/proof',{recursive:true});fs.writeFileSync('docs/proof/branch-results.json',JSON.stringify({at:new Date().toISOString(),passed,failed,cases,boundary:'Synthetic engineering checks for isolated draft/rule proposals, independent exact-revision review, merge/staleness and fresh approval. No production acceptance or scientific validity claim.'},null,2));console.log(JSON.stringify({passed,failed,total:cases.length}));if(failed)process.exitCode=1;
