import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {inferCollaboration,validateAllocation,validateTeamReview} from '../lib/model-gateway.mjs';
import {seedSynthetic,hash,qcDraft} from '../lib/core.mjs';
import {executeRuntimeJob,failureTransition} from '../lib/runtime.mjs';
const config={apiKey:'synthetic-protocol-key',model:'fixture-author/1',reviewerModel:'fixture-reviewer/1',operationId:'synthetic-operation'},cases=[];
const facts=[{id:'f1',status:'APPROVED',parameter:'assay',value:98.6,unit:'%',batch:'B1',method:'HPLC',sourceVersion:1,sourceHash:'fixture-hash'},{id:'f2',status:'APPROVED',parameter:'water',value:1.2,unit:'%',batch:'B1',method:'KF',sourceVersion:1,sourceHash:'fixture-hash'}];
const plan={allocations:[{role:'ANALYTICAL_FACTS',fieldIds:['f1']},{role:'CMC_FACTS',fieldIds:['f2']}]};
const statements=facts.map(f=>({fieldId:f.id,text:`Recorded ${f.parameter} is ${f.value} ${f.unit} for batch ${f.batch} using ${f.method}.`}));
const review={checks:statements.map(s=>({fieldId:s.fieldId,supported:true,reason:'Matches the supplied exact fact.'}))};
const reject=(fn,code)=>assert.rejects(fn,e=>e.code===code);
async function test(name,fn){try{await fn();cases.push({name,status:'PASS'});}catch(e){cases.push({name,status:'FAIL',error:e.message});console.error(name,e.stack);}}
function provider(options={}){let active=0,maxActive=0,calls=[];const fetcher=async(url,init)=>{assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(init.redirect,'manual');const b=JSON.parse(init.body),name=b.text.format.name;calls.push({model:b.model,name,key:init.headers['Idempotency-Key'],body:b});let value;if(name==='forge_bounded_allocation')value=options.plan||plan;else if(name==='forge_independent_evidence_review')value=options.review||review;else{active++;maxActive=Math.max(maxActive,active);await new Promise(r=>setTimeout(r,5));active--;if(options.failAuthor&&JSON.parse(b.input).approvedFacts[0].fieldId==='f2')return new Response('synthetic unavailable',{status:503});value={statements:JSON.parse(b.input).approvedFacts.map(f=>statements.find(s=>s.fieldId===f.fieldId))};}return Response.json({id:'fixture-'+calls.length,model:options.drift===name?'wrong-model':b.model,status:options.incomplete===name?'incomplete':'completed',usage:{input_tokens:10,output_tokens:10},output:[{content:[{type:'output_text',text:JSON.stringify(value)}]}]});};return {fetcher,calls,get maxActive(){return maxActive;}};}
await test('No key or missing distinct reviewer makes zero network calls',async()=>{for(const cfg of [{},{...config,apiKey:null},{...config,reviewerModel:null},{...config,reviewerModel:config.model}]){let calls=0;await reject(()=>inferCollaboration(facts,cfg,()=>calls++),'MODEL_UNAVAILABLE');assert.equal(calls,0);}});
await test('Unapproved fact cannot reach a model',()=>reject(()=>inferCollaboration([{...facts[0],status:'NEEDS_REVIEW'}],config),'MODEL_INPUT_LIMIT'));
await test('More than one hundred facts cannot reach a model',()=>reject(()=>inferCollaboration(Array.from({length:101},(_,i)=>({...facts[0],id:String(i)})),config),'MODEL_INPUT_LIMIT'));
await test('Duplicate input facts cannot reach a model',()=>reject(()=>inferCollaboration([facts[0],facts[0]],config),'MODEL_INPUT_LIMIT'));
await test('Planner directs concurrent specialists and distinct reviewer',async()=>{const p=provider(),r=await inferCollaboration(facts,config,p.fetcher);assert.equal(p.maxActive,2);assert.equal(p.calls.length,4);assert.deepEqual(p.calls.map(c=>c.model),[config.model,config.model,config.model,config.reviewerModel]);assert.equal(r.runs.length,4);assert.equal(r.state,'CANDIDATE_ONLY');assert.equal(r.release,false);assert.equal(r.evidenceHash,await hash(JSON.stringify(facts.map(f=>({fieldId:f.id,parameter:f.parameter,value:f.value,unit:f.unit,batch:f.batch,method:f.method,sourceVersion:f.sourceVersion,sourceHash:f.sourceHash})))));assert.ok(!JSON.stringify(r).includes(config.apiKey));});
await test('Each role has a stable separate idempotency key and no external tools',async()=>{const p=provider();await inferCollaboration(facts,config,p.fetcher);assert.equal(new Set(p.calls.map(c=>c.key)).size,4);assert.ok(p.calls.every(c=>c.body.store===false&&!c.body.tools));assert.ok(p.calls.every(c=>c.body.instructions.includes('untrusted data')));});
for(const [name,value] of [['omitted fact',{allocations:[plan.allocations[0]]}],['duplicate ID',{allocations:[{role:'CMC_FACTS',fieldIds:['f1','f1']}]}],['foreign ID',{allocations:[{role:'CMC_FACTS',fieldIds:['foreign','f2']}]}],['unknown agent',{allocations:[{role:'RELEASE_AGENT',fieldIds:['f1','f2']}]}],['three agents',{allocations:[...plan.allocations,plan.allocations[0]]}],['empty agent',{allocations:[{role:'CMC_FACTS',fieldIds:[]}]}]])await test('Planner rejects '+name,()=>assert.throws(()=>validateAllocation(value,facts),e=>e.code==='MODEL_ALLOCATION_FAILURE'));
await test('Invalid plan stops before authors',async()=>{const p=provider({plan:{allocations:[plan.allocations[0]]}});await reject(()=>inferCollaboration(facts,config,p.fetcher),'MODEL_ALLOCATION_FAILURE');assert.equal(p.calls.length,1);});
for(const [name,value] of [['omitted review',{checks:[review.checks[0]]}],['duplicate review',{checks:[review.checks[0],review.checks[0]]}],['foreign review',{checks:[review.checks[0],{...review.checks[1],fieldId:'foreign'}]}],['null review',{checks:[null,review.checks[1]]}]])await test('Reviewer rejects '+name,()=>assert.throws(()=>validateTeamReview(value,statements),e=>e.code==='MODEL_REVIEW_FAILURE'));
await test('Reviewer rejection never publishes statements as accepted',async()=>{const p=provider({review:{checks:[review.checks[0],{...review.checks[1],supported:false}]}});await reject(()=>inferCollaboration(facts,config,p.fetcher),'MODEL_REVIEW_REJECTED');});
await test('Failure in one author waits for all work and preserves failure traces',async()=>{const p=provider({failAuthor:true});let e;try{await inferCollaboration(facts,config,p.fetcher);assert.fail();}catch(error){e=error;}assert.equal(e.code,'TRANSIENT_MODEL_FAILURE');assert.equal(e.modelRuns.length,3);assert.ok(e.modelRuns.some(r=>r.state==='FAILED'));assert.equal(p.calls.length,3);const held=failureTransition({attempts:4},e);assert.equal(held.status,'DLQ');assert.equal(held.failure.modelRuns.length,3);});
for(const name of ['forge_bounded_allocation','forge_source_bound_draft','forge_independent_evidence_review'])await test('Pinned identity enforced for '+name,()=>reject(()=>inferCollaboration(facts,config,provider({drift:name}).fetcher),'MODEL_VERSION_DRIFT'));
await test('Incomplete reviewer is a failure rather than success',()=>reject(()=>inferCollaboration(facts,config,provider({incomplete:'forge_independent_evidence_review'}).fetcher),'MODEL_INCOMPLETE'));
await test('Persisted runtime author path creates a candidate with model-team evidence',async()=>{const state=await seedSynthetic();for(const f of state.fields)f.status='APPROVED';let network=0;const fetcher=async(_url,init)=>{network++;const b=JSON.parse(init.body),p=JSON.parse(b.input);let value;if(b.text.format.name==='forge_bounded_allocation')value={allocations:[{role:'CMC_FACTS',fieldIds:p.approvedFacts.map(f=>f.fieldId)}]};else if(b.text.format.name==='forge_source_bound_draft')value={statements:p.approvedFacts.map(f=>({fieldId:f.fieldId,text:`Recorded ${f.parameter} is ${f.value} ${f.unit} for batch ${f.batch} using ${f.method}.`}))};else value={checks:p.statements.map(s=>({fieldId:s.fieldId,supported:true,reason:'Synthetic reviewed fact match.'}))};return Response.json({id:'fixture-runtime-'+network,model:b.model,status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(value)}]}]});};const job={id:'fixture-task',workflowId:'fixture-workflow',kind:'AUTHOR',inputRevision:state.version,inputHash:await hash(JSON.stringify(state)),payload:{mode:'AI_ASSISTED',providerPermission:true,title:'Synthetic candidate',section:'3.2.P'}};const r=await executeRuntimeJob(job,state,{id:'fixture-owner',role:'owner'},{...config,inferCollaboration:(f,c)=>inferCollaboration(f,c,fetcher)});assert.equal(network,3);assert.equal(r.status,'COMPLETE');assert.equal(r.state.drafts[0].status,'CANDIDATE');assert.equal(r.state.agentRuns[0].runs.length,3);assert.equal(r.output.collaboration.release,false);assert.equal(r.state.exports.length,0);assert.equal(r.state.decisions.length,0);});
const failed=cases.filter(c=>c.status==='FAIL').length;await fs.writeFile('docs/proof/collaboration-results.json',JSON.stringify({at:new Date().toISOString(),passed:cases.length-failed,failed,scope:'Synthetic model protocol plus runtime domain integration; not live inference or scientific validation.',cases},null,2));console.log(`${cases.length-failed}/${cases.length} collaboration checks passed`);if(failed)process.exitCode=1;
