import { strict as assert } from 'node:assert';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { deflateRawSync } from 'node:zlib';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
import { parseDocumentBytes, DOCUMENT_PARSER_VERSION } from '../lib/document-parser.mjs';

// zlib exists only in test fixture construction, never in the worker parser.
const encoder = new TextEncoder();
const DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
const XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const S = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main';
const R = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const PR = 'http://schemas.openxmlformats.org/package/2006/relationships';
const fields = ['parameter', 'value', 'unit', 'method', 'batch', 'basis', 'low', 'high', 'condition'];
const values = ['assay', '09.8700', '%', 'HPLC 001', 'B001', 'mass', '09.5000', '10.5000', '25 C'];
const escape = text => String(text).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const typedXML = (replace = {}) => `<parameters schema="pramanex-parameters/1"><row>${fields.map((name, i) => `<${name}>${escape(replace[name] ?? values[i])}</${name}>`).join('')}</row></parameters>`;
const crcTable = Array.from({ length: 256 }, (_, n) => { for (let i = 0; i < 8; i++) n = n & 1 ? 0xEDB88320 ^ n >>> 1 : n >>> 1; return n >>> 0; });
const crc32 = data => { let crc = 0xFFFFFFFF; for (const b of data) crc = crcTable[(crc ^ b) & 255] ^ crc >>> 8; return (crc ^ 0xFFFFFFFF) >>> 0; };
function zip(files, options = {}) {
  const locals = [], centrals = []; let offset = 0;
  for (const [name, data] of files) {
    const raw = typeof data === 'string' ? Buffer.from(data) : Buffer.from(data), compressed = options.deflate ? deflateRawSync(raw) : raw, nameBytes = Buffer.from(name), crc = crc32(raw), flags = options.flags ?? 0x800, method = options.deflate ? 8 : 0;
    const header = Buffer.alloc(30); header.writeUInt32LE(0x04034B50); header.writeUInt16LE(20, 4); header.writeUInt16LE(flags, 6); header.writeUInt16LE(method, 8); header.writeUInt32LE(crc, 14); header.writeUInt32LE(compressed.length, 18); header.writeUInt32LE(options.declaredSize ?? raw.length, 22); header.writeUInt16LE(nameBytes.length, 26);
    const local = Buffer.concat([header, nameBytes, compressed]); locals.push(local);
    const central = Buffer.alloc(46); central.writeUInt32LE(0x02014B50); central.writeUInt16LE(20, 4); central.writeUInt16LE(20, 6); central.writeUInt16LE(flags, 8); central.writeUInt16LE(method, 10); central.writeUInt32LE(crc, 16); central.writeUInt32LE(compressed.length, 20); central.writeUInt32LE(options.declaredSize ?? raw.length, 24); central.writeUInt16LE(nameBytes.length, 28); central.writeUInt32LE(offset, 42); centrals.push(Buffer.concat([central, nameBytes])); offset += local.length;
  }
  const directory = Buffer.concat(centrals), end = Buffer.alloc(22); end.writeUInt32LE(0x06054B50); end.writeUInt16LE(files.length, 8); end.writeUInt16LE(files.length, 10); end.writeUInt32LE(directory.length, 12); end.writeUInt32LE(offset, 16);
  return Buffer.concat([...locals, directory, end]);
}
const contentTypes = kind => `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/${kind === 'docx' ? 'word/document.xml' : 'xl/workbook.xml'}" ContentType="${kind === 'docx' ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml' : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml'}"/></Types>`;
const rootRel = kind => `<Relationships xmlns="${PR}"><Relationship Id="rId1" Type="${R}/officeDocument" Target="${kind === 'docx' ? 'word/document.xml' : 'xl/workbook.xml'}"/></Relationships>`;
const wordCell = text => `<w:tc><w:p><w:r><w:t>${escape(text)}</w:t></w:r></w:p></w:tc>`;
function wordParts(document) { return [['[Content_Types].xml', contentTypes('docx')], ['_rels/.rels', rootRel('docx')], ['word/document.xml', document || `<w:document xmlns:w="${W}"><w:body><w:tbl><w:tr>${fields.map(wordCell).join('')}</w:tr><w:tr>${values.map(wordCell).join('')}</w:tr></w:tbl></w:body></w:document>`]]; }
const spreadsheetCell = (ref, text, numeric = false) => numeric ? `<c r="${ref}"><v>${text}</v></c>` : `<c r="${ref}" t="inlineStr"><is><t>${escape(text)}</t></is></c>`;
function sheetXML(replace = '') { return `<worksheet xmlns="${S}"><sheetData><row r="1">${fields.map((field, i) => spreadsheetCell(`${String.fromCharCode(65 + i)}1`, field)).join('')}</row><row r="2">${values.map((value, i) => spreadsheetCell(`${String.fromCharCode(65 + i)}2`, value, [1, 6, 7].includes(i))).join('')}${replace}</row></sheetData></worksheet>`; }
function spreadsheetParts(sheet = sheetXML()) { return [['[Content_Types].xml', contentTypes('xlsx')], ['_rels/.rels', rootRel('xlsx')], ['xl/workbook.xml', `<workbook xmlns="${S}" xmlns:r="${R}"><sheets><sheet name="Assay" sheetId="1" r:id="rId1"/></sheets></workbook>`], ['xl/_rels/workbook.xml.rels', `<Relationships xmlns="${PR}"><Relationship Id="rId1" Type="${R}/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`], ['xl/worksheets/sheet1.xml', sheet]]; }
const testResults = [];
async function test(name, fn) { try { await fn(); testResults.push({ name, status: 'PASS' }); console.log(`PASS ${name}`); } catch (e) { testResults.push({ name, status: 'FAIL', failure: e.message }); console.error(`FAIL ${name}: ${e.message}`); } }
async function hold(data, mime = 'application/xml', name = 'source.xml', code) { const result = await parseDocumentBytes(typeof data === 'string' ? encoder.encode(data) : data, mime, name); assert.equal(result.status, 'HOLD'); assert.deepEqual(result.rows, []); if (code) assert.equal(result.failure.code, code); return result; }

await test('typed XML preserves original numeric lexemes, raw limits and exact value span', async () => { const text = typedXML(), result = await parseDocumentBytes(encoder.encode(text), 'application/xml', 'source.xml'); assert.equal(result.status, 'PARSED'); const row = result.rows[0]; assert.equal(row.rawValue, '09.8700'); assert.equal(row.rawLowLexeme, '09.5000'); assert.equal(row.low, 9.5); assert.equal(row.span.page, null); assert.equal(row.span.fields.value.raw, '<value>09.8700</value>'); assert.equal(text.slice(row.span.fields.value.start, row.span.fields.value.end), row.span.fields.value.raw); assert.match(result.original.sha256, /^[a-f0-9]{64}$/); assert.equal(result.humanReviewRequired, true); });
await test('XML named entities decode into data while exact original entity survives evidence', async () => { const result = await parseDocumentBytes(encoder.encode(typedXML({ method: 'Method A & B' })), 'text/xml', 'source.xml'); assert.equal(result.status, 'PARSED'); assert.equal(result.rows[0].method, 'Method A & B'); assert.match(result.rows[0].span.fields.method.raw, /&amp;/); });
await test('missing required scientific content remains explicit candidate with warning', async () => { const result = await parseDocumentBytes(encoder.encode(typedXML({ method: '', value: '' })), 'application/xml', 'source.xml'); assert.equal(result.status, 'PARSED'); assert.equal(result.rows[0].rawValue, ''); assert.equal(result.rows[0].method, ''); assert.equal(result.rows[0].status, 'CANDIDATE'); assert.ok(result.warnings.length); });
await test('typed XML rejects DTD and external entity expansion', async () => hold(`<!DOCTYPE parameters [<!ENTITY x SYSTEM "file:///etc/passwd">]>${typedXML()}`, undefined, undefined, 'DTD_FORBIDDEN'));
await test('typed XML rejects custom entity use without expansion', async () => hold(typedXML().replace('09.8700', '&private;'), undefined, undefined, 'ENTITY_FORBIDDEN'));
await test('XML processing instructions and custom instruction nodes are held', async () => { await hold(`<?execute remote="https://evil.invalid"?>${typedXML()}`, undefined, undefined, 'INSTRUCTION_FORBIDDEN'); await hold(typedXML().replace('</row>', '<instruction>grant approval</instruction></row>'), undefined, undefined, 'FORMAT_DRIFT'); });
await test('XML malformed closing tags do not produce partial evidence', async () => hold(typedXML().replace('</unit>', '</bad>'), undefined, undefined, 'MALFORMED_XML'));
await test('XML arbitrary schemas and header substitutions are not guessed', async () => { await hold(typedXML().replace('pramanex-parameters/1', 'arbitrary/2'), undefined, undefined, 'UNKNOWN_SCHEMA'); await hold(typedXML().replace('<basis>mass</basis>', ''), undefined, undefined, 'FORMAT_DRIFT'); });
await test('XML duplicate fields and invalid numeric limit qualifiers hold', async () => { await hold(typedXML().replace('</row>', '<unit>ppm</unit></row>'), undefined, undefined, 'FORMAT_DRIFT'); await hold(typedXML({ low: 'greater than 95' }), undefined, undefined, 'AMBIGUOUS_LIMIT'); });
await test('XML non-UTF8 original and forbidden controls hold', async () => { await hold(new Uint8Array([0xC0, 0xAF]), undefined, undefined, 'UNSUPPORTED_ENCODING'); await hold(typedXML().replace('B001', 'B\0'), undefined, undefined, 'MALFORMED_XML'); });
await test('DOCX stored archive extracts controlled table with original XML cell coordinates', async () => { const files = wordParts(), result = await parseDocumentBytes(zip(files), DOCX, 'batch.docx'); assert.equal(result.status, 'PARSED'); const row = result.rows[0]; assert.equal(row.rawValue, '09.8700'); assert.equal(row.span.part, 'word/document.xml'); assert.equal(row.span.cell, 'T1:R2:C2'); assert.equal(row.span.fields.method.cell, 'T1:R2:C4'); assert.equal(row.span.page, null); const xml = files[2][1]; assert.equal(xml.slice(row.span.start, row.span.end), row.span.raw); assert.match(row.span.fields.value.raw, /<w:t>09\.8700<\/w:t>/); });
await test('DOCX raw-DEFLATE extraction is bounded and CRC verified', async () => { const result = await parseDocumentBytes(zip(wordParts(), { deflate: true }), DOCX, 'batch.docx'); assert.equal(result.status, 'PARSED'); assert.equal(result.rows.length, 1); });
await test('DOCX split text runs preserve raw numeric lexeme with multiple original tokens', async () => { const files = wordParts(); files[2][1] = files[2][1].replace('<w:t>09.8700</w:t>', '<w:t>09.</w:t></w:r><w:r><w:t>8700</w:t>'); const result = await parseDocumentBytes(zip(files), DOCX, 'batch.docx'); assert.equal(result.status, 'PARSED'); assert.equal(result.rows[0].rawValue, '09.8700'); assert.equal(result.rows[0].span.fields.value.tokens.length, 2); });
await test('Word merged cells and tracked changes cannot silently change coordinates', async () => { let files = wordParts(); files[2][1] = files[2][1].replace('<w:t>09.8700', '<w:tcPr><w:gridSpan w:val="2"/></w:tcPr><w:t>09.8700'); await hold(zip(files), DOCX, 'batch.docx', 'AMBIGUOUS_COORDINATES'); files = wordParts(); files[2][1] = files[2][1].replace('<w:t>09.8700</w:t>', '<w:del><w:t>09.8700</w:t></w:del>'); await hold(zip(files), DOCX, 'batch.docx', 'ACTIVE_CONTENT'); });
await test('OOXML package rejects original macro/embedded binary content', async () => hold(zip([...wordParts(), ['word/vbaProject.bin', 'binary']]), DOCX, 'batch.docx', 'ACTIVE_CONTENT'));
await test('OOXML external relationship is held even when table looks valid', async () => hold(zip([...wordParts(), ['word/_rels/document.xml.rels', `<Relationships xmlns="${PR}"><Relationship Id="x" Type="${R}/hyperlink" Target="https://external.invalid/" TargetMode="External"/></Relationships>`]]), DOCX, 'batch.docx', 'EXTERNAL_RELATIONSHIP'));
await test('OOXML unsafe traversal and duplicate package names are forbidden', async () => { await hold(zip([...wordParts(), ['../escape.xml', '<x/>']]), DOCX, 'batch.docx', 'ARCHIVE_PATH'); await hold(zip([...wordParts(), ['word/document.xml', '<x/>']]), DOCX, 'batch.docx', 'ARCHIVE_PATH'); });
await test('OOXML encrypted ZIP flags are forbidden before extraction', async () => hold(zip(wordParts(), { flags: 0x801 }), DOCX, 'batch.docx', 'ARCHIVE_UNSUPPORTED'));
await test('OOXML archive file-count and decompressed-size limits are enforced', async () => { const files = wordParts(); for (let i = 0; i < 198; i++) files.push([`extra${i}.txt`, 'x']); await hold(zip(files), DOCX, 'batch.docx', 'ARCHIVE_LIMIT'); await hold(zip(wordParts(), { declaredSize: 10 * 1024 * 1024 + 1 }), DOCX, 'batch.docx', 'ARCHIVE_LIMIT'); });
await test('OOXML forged small inflation size fails during bounded streaming', async () => hold(zip(wordParts(), { deflate: true, declaredSize: 3 }), DOCX, 'batch.docx', 'ARCHIVE_LIMIT'));
await test('OOXML CRC mismatch and local-directory mismatch hold', async () => { const bytes = zip(wordParts()); bytes[30 + Buffer.byteLength('[Content_Types].xml') + 1] ^= 1; await hold(bytes, DOCX, 'batch.docx', 'ARCHIVE_CORRUPT'); const mismatch = zip(wordParts()); mismatch.writeUInt32LE(0, 18); await hold(mismatch, DOCX, 'batch.docx', 'ARCHIVE_CORRUPT'); });
await test('OOXML XML attacks in unused parts still hold the original document', async () => hold(zip([...wordParts(), ['customXml/item1.xml', '<!DOCTYPE x [<!ENTITY a "x">]><x>&a;</x>']]), DOCX, 'batch.docx', 'DTD_FORBIDDEN'));
await test('DOCX MIME/extension and declared main content type must match', async () => { await hold(zip(wordParts()), XLSX, 'batch.xlsx', 'FORMAT_DRIFT'); await hold(zip(wordParts()), DOCX, 'batch.docm', 'UNSUPPORTED_DOCUMENT'); });
await test('XLSX preserves numeric original lexemes and worksheet cell coordinates', async () => { const parts = spreadsheetParts(), result = await parseDocumentBytes(zip(parts, { deflate: true }), XLSX, 'source.xlsx'); assert.equal(result.status, 'PARSED'); const row = result.rows[0]; assert.equal(row.rawValue, '09.8700'); assert.equal(row.span.cell, 'Assay!B2'); assert.equal(row.span.part, 'xl/worksheets/sheet1.xml'); assert.equal(row.span.fields.low.cell, 'Assay!G2'); assert.equal(row.span.fields.value.tokens[0].raw, '09.8700'); assert.equal(row.span.page, null); });
await test('XLSX shared-string evidence links actual worksheet index to original string part', async () => { const parts = spreadsheetParts(); parts[4][1] = parts[4][1].replace('<c r="A2" t="inlineStr"><is><t>assay</t></is></c>', '<c r="A2" t="s"><v>0</v></c>'); parts.push(['xl/sharedStrings.xml', `<sst xmlns="${S}" count="1" uniqueCount="1"><si><t>assay</t></si></sst>`]); const result = await parseDocumentBytes(zip(parts), XLSX, 'source.xlsx'); assert.equal(result.status, 'PARSED'); assert.equal(result.rows[0].parameter, 'assay'); const cell = result.rows[0].span.fields.parameter; assert.equal(cell.tokens[0].raw, '0'); assert.equal(cell.content.part, 'xl/sharedStrings.xml'); assert.match(cell.content.raw, /<t>assay<\/t>/); });
await test('XLSX formula cache, merged cells and invalid original cell addresses hold', async () => { await hold(zip(spreadsheetParts(sheetXML().replace('<v>09.8700', '<f>99+1</f><v>09.8700'))), XLSX, 'source.xlsx', 'AMBIGUOUS_COORDINATES'); await hold(zip(spreadsheetParts(sheetXML().replace('</worksheet>', '<mergeCells><mergeCell ref="A2:B2"/></mergeCells></worksheet>'))), XLSX, 'source.xlsx', 'AMBIGUOUS_COORDINATES'); await hold(zip(spreadsheetParts(sheetXML().replace('r="B2"', 'r="B3"'))), XLSX, 'source.xlsx', 'AMBIGUOUS_COORDINATES'); });
await test('XLSX explicit missing/duplicate cells and unknown column drift hold', async () => { await hold(zip(spreadsheetParts(sheetXML().replace('<c r="I2" t="inlineStr"><is><t>25 C</t></is></c>', ''))), XLSX, 'source.xlsx', 'FORMAT_DRIFT'); await hold(zip(spreadsheetParts(sheetXML('<c r="I2"><v>1</v></c>'))), XLSX, 'source.xlsx', 'AMBIGUOUS_COORDINATES'); await hold(zip(spreadsheetParts(sheetXML(spreadsheetCell('J2', 'unsupported')))), XLSX, 'source.xlsx', 'FORMAT_DRIFT'); });
await test('XLSX unknown shared strings and boolean cell types are never inferred', async () => { await hold(zip(spreadsheetParts(sheetXML().replace('<c r="A2" t="inlineStr"><is><t>assay</t></is></c>', '<c r="A2" t="s"><v>999</v></c>'))), XLSX, 'source.xlsx', 'FORMAT_DRIFT'); await hold(zip(spreadsheetParts(sheetXML().replace('<c r="B2"><v>09.8700</v></c>', '<c r="B2" t="b"><v>1</v></c>'))), XLSX, 'source.xlsx', 'FORMAT_DRIFT'); });
await test('Unsupported PDF/handwriting formats hold without invented OCR', async () => hold(encoder.encode('%PDF-1.7'), 'application/pdf', 'scan.pdf', 'UNSUPPORTED_DOCUMENT'));
await test('Empty and oversized originals hold without extraction', async () => { await hold(new Uint8Array(), undefined, undefined, 'EMPTY_DOCUMENT'); await hold(new Uint8Array(5 * 1024 * 1024 + 1), undefined, undefined, 'INPUT_LIMIT'); });
await test('Adjacent XML attributes and undeclared prefixes are malformed', async () => { await hold(typedXML().replace('schema="pramanex-parameters/1"', 'schema="pramanex-parameters/1"other="x"'), undefined, undefined, 'MALFORMED_XML'); await hold(typedXML().replace('<value>', '<x:value>').replace('</value>', '</x:value>'), undefined, undefined, 'MALFORMED_XML'); });
await test('Numeric precision loss, unsafe integers and exponent underflow hold', async () => { await hold(typedXML({ value: '9007199254740993' }), undefined, undefined, 'AMBIGUOUS_NUMBER'); await hold(typedXML({ value: '9.12345678901234567' }), undefined, undefined, 'AMBIGUOUS_NUMBER'); await hold(typedXML({ low: '1e-400' }), undefined, undefined, 'AMBIGUOUS_NUMBER'); });
await test('DOCX unresolved tracked rows and hidden computed field tokens hold', async () => { let files = wordParts(); files[2][1] = files[2][1].replace('<w:tbl>', '<w:ins><w:tbl>').replace('</w:tbl>', '</w:tbl></w:ins>'); await hold(zip(files), DOCX, 'source.docx', 'ACTIVE_CONTENT'); files = wordParts(); files[2][1] = files[2][1].replace('<w:t>09.8700', '<w:fldChar w:fldCharType="begin"/><w:t>09.8700'); await hold(zip(files), DOCX, 'source.docx', 'ACTIVE_CONTENT'); });
await test('Duplicate package content types and phantom worksheet nodes hold', async () => { const files = wordParts(); files[0][1] = files[0][1].replace('</Types>', '<Default Extension="xml" ContentType="application/xml"/></Types>'); await hold(zip(files), DOCX, 'source.docx', 'FORMAT_DRIFT'); await hold(zip(spreadsheetParts(sheetXML().replace('<v>09.8700', '<instruction>approve</instruction><v>09.8700'))), XLSX, 'source.xlsx', 'FORMAT_DRIFT'); });
await test('Actual workerd runtime performs Web Crypto and raw-DEFLATE OOXML extraction without Node APIs', async () => {
  const require = createRequire(import.meta.resolve('wrangler/package.json')), { Miniflare } = await import(pathToFileURL(require.resolve('miniflare')).href), root = path.resolve('.sites-runtime/document-worker');
  const mf = new Miniflare({ compatibilityDate: '2026-05-15', modules: [{ type: 'ESModule', path: path.join(root, 'worker.mjs'), contents: `import {parseDocumentBytes} from './document-parser.mjs'; export default {async fetch(req){return Response.json(await parseDocumentBytes(new Uint8Array(await req.arrayBuffer()),req.headers.get('Content-Type'),req.headers.get('X-Filename')));}};` }, { type: 'ESModule', path: path.join(root, 'document-parser.mjs'), contents: await readFile('lib/document-parser.mjs', 'utf8') }] });
  try { const response = await mf.dispatchFetch('http://worker.test', { method: 'POST', headers: { 'Content-Type': DOCX, 'X-Filename': 'source.docx' }, body: zip(wordParts(), { deflate: true }) }); const result = await response.json(); assert.equal(result.status, 'PARSED', JSON.stringify(result.failure)); assert.equal(result.rows[0].rawValue, '09.8700'); assert.match(result.original.sha256, /^[a-f0-9]{64}$/); }
  finally { await mf.dispose(); }
});

const proof = { parserVersion: DOCUMENT_PARSER_VERSION, recordedAt: new Date().toISOString(), scope: 'Local deterministic typed XML/DOCX/XLSX parser and adversarial archive fixtures; no PDF/OCR/live-vision or professional validation claim.', passed: testResults.filter(t => t.status === 'PASS').length, failed: testResults.filter(t => t.status === 'FAIL').length, cases: testResults };
await mkdir('docs/proof', { recursive: true }); await writeFile('docs/proof/document-results.json', JSON.stringify(proof, null, 2) + '\n');
console.log(`${proof.passed}/${testResults.length} document ingestion cases passed.`); if (proof.failed) process.exitCode = 1;
