import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {seedSynthetic, command, hash} from '../lib/core.mjs';
import {signatureRecord} from '../lib/signature.mjs';
import {formatEvidence, preflightPackage, packageEvidence, evidenceTables, artifactCRC32, safeExportFilename} from '../lib/format-export.mjs';
const directory='.sites-runtime/export-checks';fs.mkdirSync(directory,{recursive:true});const cases=[];
async function test(name,ids,fn){const start=performance.now();try{await fn();cases.push({name,ids,status:'PASS',latencyMs:Math.round(performance.now()-start)});}catch(e){cases.push({name,ids,status:'FAIL',error:e.message});console.error(name,e.stack);}}
let state=await seedSynthetic();const reviewer={id:'export-test-reviewer',role:'owner'},author={id:'export-test-author',role:'author'};
async function invoke(input,actor=reviewer){state=(await command(state,{...input,expectedVersion:state.version},actor)).state;}
const conflict=state.conflicts[0];await invoke({action:'resolveConflict',id:conflict.id,selectedId:conflict.fieldIds[0],reason:'Frozen synthetic answer key selects the CoA.'});
for(const f of state.fields.filter(f=>f.status==='CANDIDATE'))await invoke({action:'review',kind:'field',id:f.id,revision:f.revision,choice:'APPROVE',reason:'Independent synthetic source inspected.'});
await invoke({action:'draft',title:'Synthetic quality α β µg 10⁻³ ≤',section:'3.2.P'},author);
await invoke({action:'review',kind:'draft',id:state.drafts[0].id,revision:state.drafts[0].revision,choice:'APPROVE',reason:'Exact source-backed draft and QC inspected.'});
await invoke({action:'export',id:state.drafts[0].id});const record=structuredClone(state.exports[0]),manifest=record.manifest,options={exportRecord:record};
const artifacts={};
function unzip(bytes){const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),members=new Map();let offset=0;while(view.getUint32(offset,true)===0x04034b50){const flags=view.getUint16(offset+6,true),method=view.getUint16(offset+8,true),crc=view.getUint32(offset+14,true),len=view.getUint32(offset+18,true),nameLength=view.getUint16(offset+26,true),extraLength=view.getUint16(offset+28,true),name=new TextDecoder().decode(bytes.slice(offset+30,offset+30+nameLength)),start=offset+30+nameLength+extraLength,data=bytes.slice(start,start+len);assert.equal(flags,0x800);assert.equal(method,0);assert.equal(artifactCRC32(data),crc);assert.ok(!members.has(name));members.set(name,data);offset=start+len;}assert.equal(view.getUint32(offset,true),0x02014b50);assert.equal(view.getUint32(bytes.length-22,true),0x06054b50);assert.equal(view.getUint16(bytes.length-12,true),members.size);return members;}
await test('Frozen approved source package passes technical profile',['F14','X30','X31'],async()=>{const r=await preflightPackage(manifest,options);assert.equal(r.ok,true);assert.equal(r.release,false);assert.equal(r.signatureState,'UNSIGNED');assert.equal(r.manifestChecksum,await hash(JSON.stringify(manifest)));assert.ok(r.checks.some(c=>c.id==='ECTD_BOUNDARY'&&c.status==='WARNING'));});
await test('DOCX is an actual OOXML ZIP with CRC and exact frozen XML',['F14','X30'],async()=>{artifacts.docx=await formatEvidence(manifest,{...options,format:'docx'});const members=unzip(artifacts.docx.bytes);for(const name of ['[Content_Types].xml','_rels/.rels','word/document.xml','word/styles.xml','forge/manifest.json'])assert.ok(members.has(name));const xml=new TextDecoder().decode(members.get('word/document.xml'));assert.ok(xml.includes('µg 10⁻³'));assert.ok(xml.includes('986 mg/g'));assert.ok(xml.includes('98.6 %'));assert.ok(xml.includes('source version 1'));assert.ok(xml.includes('UNSIGNED'));assert.deepEqual(JSON.parse(new TextDecoder().decode(members.get('forge/manifest.json'))),manifest);assert.match(artifacts.docx.mime,/wordprocessingml/);fs.writeFileSync(path.join(directory,'evidence.docx'),artifacts.docx.bytes);});
await test('PDF embeds Unicode and is a genuine multipage PDF',['F14','X30'],async()=>{artifacts.pdf=await formatEvidence(manifest,{...options,format:'pdf'});assert.equal(new TextDecoder().decode(artifacts.pdf.bytes.slice(0,5)),'%PDF-');assert.equal(artifacts.pdf.mime,'application/pdf');fs.writeFileSync(path.join(directory,'evidence.pdf'),artifacts.pdf.bytes);});
await test('HTML escapes untrusted text and disallows active content',['F14','X30','L10'],async()=>{const m=structuredClone(manifest);m.product='<script>alert("x")</script>';const a=await formatEvidence(m,{format:'html'}),html=new TextDecoder().decode(a.bytes);assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));assert.ok(html.includes("default-src 'none'"));assert.ok(html.includes('release=false'));artifacts.html=await formatEvidence(manifest,{...options,format:'html'});});
await test('A source citation gap blocks all artifact formats',['F04','F14','X30','X31'],async()=>{const m=structuredClone(manifest);m.fields[0].sourceHash='0'.repeat(64);const p=await preflightPackage(m);assert.equal(p.ok,false);assert.ok(p.checks.some(c=>c.id==='SOURCE_CITATION_INTEGRITY'&&c.status==='FAIL'));for(const format of ['docx','pdf','html'])await assert.rejects(()=>formatEvidence(m,{format}),e=>e.code==='EXPORT_PREFLIGHT_FAILED');});
await test('Unsupported draft statements cannot be formatted',['F14','X30','L10'],async()=>{const m=structuredClone(manifest);m.draft.statements[0].value=777;assert.equal((await preflightPackage(m)).ok,false);await assert.rejects(()=>formatEvidence(m,{format:'pdf'}),e=>e.code==='EXPORT_PREFLIGHT_FAILED');});
await test('Release=true or stale approval cannot pass technical handoff',['F14','X31','L10'],async()=>{for(const change of [m=>m.release=true,m=>m.decision.status='STALE',m=>m.decision.revision++]){const m=structuredClone(manifest);change(m);assert.equal((await preflightPackage(m)).ok,false);}});
await test('Frozen snapshot and artifacts stay independent of live source edits',['F14','X30','X51'],async()=>{const before=JSON.stringify(manifest),wordBefore=artifacts.docx.bytes.slice();await invoke({action:'change',id:state.sources[0].id,text:state.sources[0].text.replace('98.6','98.7'),reason:'Independent new synthetic source version'},author);assert.equal(JSON.stringify(record.manifest),before);const word=await formatEvidence(record.manifest,{...options,format:'docx'});assert.deepEqual(word.bytes,wordBefore);assert.ok(!new TextDecoder().decode(unzip(word.bytes).get('word/document.xml')).includes('98.7 %'));});
await test('Server-owned manifest checksum mismatch blocks rendering',['F14','X47','L10'],async()=>{const m=structuredClone(manifest);m.product='Altered snapshot';await assert.rejects(()=>formatEvidence(m,{...options,format:'docx'}),e=>e.code==='EXPORT_PREFLIGHT_FAILED');});
await test('Signature-bound record is displayed only when exact payload binds',['F14','X30','X47'],async()=>{const signed=structuredClone(record);signed.finalized=true;signed.signature=await signatureRecord('test-signing-human','approver','Technical Review',manifest.signingPayload);let r=await preflightPackage(manifest,{exportRecord:signed});assert.equal(r.signatureState,'SIGNATURE_BOUND_TECHNICAL_RECORD');assert.equal(r.release,false);const a=await formatEvidence(manifest,{format:'html',exportRecord:signed});assert.ok(new TextDecoder().decode(a.bytes).includes('test-signing-human'));signed.signature.revisionHash='0'.repeat(64);assert.equal((await preflightPackage(manifest,{exportRecord:signed})).ok,false);});
await test('Unsupported PDF glyph visibly rejects while DOCX preserves Unicode',['F14','X30','L10'],async()=>{const m=structuredClone(manifest);m.product='Unsupported document script हिन्दी';await assert.rejects(()=>formatEvidence(m,{format:'pdf'}),e=>e.code==='UNSUPPORTED_PDF_CHARACTER');const a=await formatEvidence(m,{format:'docx'});assert.ok(new TextDecoder().decode(unzip(a.bytes).get('word/document.xml')).includes('हिन्दी'));});
await test('Traversal, extension mismatch and internal controls are blocked',['F14','L10'],async()=>{for(const name of ['../file.pdf','/file.pdf','a\\file.pdf','.hidden.pdf','x\nfile.pdf'])assert.throws(()=>safeExportFilename(name,'pdf'),e=>e.code==='UNSAFE_EXPORT_FILENAME');await assert.rejects(()=>formatEvidence(manifest,{format:'pdf',filename:'not-a-pdf.docx'}),e=>e.code==='EXPORT_EXTENSION_MISMATCH');const m=structuredClone(manifest);m.product='Control\u0000text';await assert.rejects(()=>formatEvidence(m,{format:'docx'}),e=>e.code==='UNSUPPORTED_CONTROL_CHARACTER');});
await test('Table and reference CSV retain raw/normalized values and source IDs',['F14','X30'],()=>{const tables=evidenceTables(manifest);assert.equal(tables.length,2);const table=new TextDecoder().decode(tables[0].bytes);assert.ok(table.includes('"986 mg/g"'));assert.ok(table.includes('"98.6 %"'));assert.ok(table.includes(manifest.fields[0].sourceId));assert.ok(new TextDecoder().decode(tables[1].bytes).includes(manifest.sources[0].hash));});
await test('Handoff ZIP has true formats, checksums and a safe technical XML skeleton',['F14','X30','X31'],async()=>{const a=await packageEvidence(manifest,options),files=unzip(a.bytes);assert.equal(a.release,false);assert.ok(files.has('index.xml'));assert.ok(files.has('evidence-table.csv'));assert.ok(files.has('reference-register.csv'));assert.deepEqual(JSON.parse(new TextDecoder().decode(files.get('manifest.json'))),manifest);const checks=JSON.parse(new TextDecoder().decode(files.get('technical-checks.json')));for(const file of checks.files)assert.equal(await hash(files.get(file.name)),file.sha256);assert.ok(new TextDecoder().decode(files.get('index.xml')).includes('<forge-package'));fs.writeFileSync(path.join(directory,'handoff.zip'),a.bytes);});
await test('Unknown regional publishing profile is visibly not implemented',['X32'],async()=>{const r=await preflightPackage(manifest,{profile:'REGULATOR_ECTD_ACCEPTED'});assert.equal(r.ok,false);assert.ok(r.checks.some(c=>c.id==='TECHNICAL_PROFILE'&&c.status==='FAIL'));});
await test('Independent Python PDF, OOXML, attachment and package XML readers verify generated files',['F14','X30','X31'],()=>{
 const python=spawnSync('python',['-c',`import json,zipfile,xml.etree.ElementTree as ET\nfrom pypdf import PdfReader\nroot=${JSON.stringify(directory)}\nr=PdfReader(root+'/evidence.pdf',strict=True)\nassert len(r.pages)>1\ntext='\\n'.join(p.extract_text() or '' for p in r.pages)\nfor phrase in ['α β µg 10⁻³','UNSIGNED','release=false','986 mg/g','98.6 %','Recorded human decision']:\n assert phrase in text,repr(phrase)\nassert 'frozen-manifest.json' in r.attachments\nattached=json.loads(r.attachments['frozen-manifest.json'][0])\nassert attached['release'] is False\nwith zipfile.ZipFile(root+'/evidence.docx') as z:\n assert z.testzip() is None\n for n in z.namelist():\n  if n.endswith('.xml') or n.endswith('.rels'):ET.fromstring(z.read(n))\n assert json.loads(z.read('forge/manifest.json'))==attached\nwith zipfile.ZipFile(root+'/handoff.zip') as z:\n assert z.testzip() is None\n xml=ET.fromstring(z.read('index.xml'))\n assert xml.tag=='forge-package' and xml.attrib['release']=='false'\n assert xml.find('section').attrib['code']=='3.2.P'\nprint(json.dumps({'pages':len(r.pages),'verified':['PDF text','PDF frozen attachment','OOXML parts','ZIP CRC','technical XML']}))`],{encoding:'utf8'});assert.equal(python.status,0,python.stderr||python.stdout);console.log(python.stdout.trim());});
const passed=cases.filter(c=>c.status==='PASS').length,failed=cases.length-passed;const report={executed:true,at:new Date().toISOString(),passed,failed,cases,boundary:'Executed synthetic artifact and file-format engineering checks. Passing technical handoff checks does not establish agency acceptance, production eCTD conformance, scientific regulatory accuracy or organizational qualification.'};fs.mkdirSync('docs/proof',{recursive:true});fs.writeFileSync('docs/proof/export-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed,failed,total:cases.length}));if(failed)process.exitCode=1;
