import assert from 'node:assert/strict';
import fs from 'node:fs';
import {initialState,command,hash} from '../lib/core.mjs';
import {retrieveMemory,executeRole} from '../lib/agentic.mjs';
import {capability} from '../lib/capabilities.mjs';
import {hydrateLifecycle,lifecycleAction,lifecycleProjection,lifecycleGraph,invalidateLifecycle,effectiveStatus,LIFECYCLE_IDS,LIFECYCLE_VERSION} from '../lib/lifecycle.mjs';
const AUTHOR={id:'fixture-author',role:'author'},REVIEW={id:'fixture-independent-reviewer',role:'reviewer'},OWNER={id:'fixture-owner',role:'owner'};
const results=[];
const invoke=async(s,input,actor=OWNER)=>(await command(s,{...input,expectedVersion:s.version},actor)).state;
const reject=(fn,code)=>assert.rejects(fn,e=>e.code===code);
async function test(name,ids,fn){const start=performance.now();try{await fn();results.push({name,ids,status:'PASS',latencyMs:Math.round(performance.now()-start)});}catch(e){results.push({name,ids,status:'FAIL',error:e.message});console.error(name,e.stack);}}
const toRef=f=>({fieldId:f.id,revision:f.revision});
const note='SYNTHETIC fixture only. Product-A, Substance-A, Material-A, Intermediate-A, Site-A, Site-B, Process-A, Process-B, Equipment-A, Specification-A. Market-A requires assay, water and impurity evidence in 3.2.P and 2.3.P. Market-A assay change can be a MINOR reporting candidate under locally reviewed rule. Market-A impurity change can be a MAJOR reporting candidate. Stages DEVELOPMENT SCALE_UP COMMERCIAL. Question: Explain the recorded assay evidence. Outcome: ACKNOWLEDGED. Template controls COMPACT TECHNICAL.';
function sourceDoc(time,batch='B1',assay=98){return JSON.stringify({note,parameters:[{parameter:'assay',value:assay,unit:'%',method:'HPLC-A',batch,product:'Product-A',facility:'Site-A',basis:'mass',condition:'25 C / 60% RH',low:95,high:105,timePoint:time,timeUnit:'month'},{parameter:'water',value:0.2+time/100,unit:'%',method:'KF-A',batch,product:'Product-A',facility:'Site-A',basis:'mass',condition:'25 C / 60% RH',low:0,high:1,timePoint:time,timeUnit:'month'},{parameter:'impurity',value:0.1+time/100,unit:'%',method:'HPLC-I',batch,product:'Product-A',facility:'Site-A',basis:'mass',condition:'25 C / 60% RH',low:0,high:1,timePoint:time,timeUnit:'month'},{parameter:'stability time',value:time,unit:'month',method:'Protocol-A',batch,product:'Product-A',facility:'Site-A',basis:'recorded protocol time',condition:'25 C / 60% RH',timePoint:time,timeUnit:'month'}]});}
async function fixture(){let s=initialState('Synthetic lifecycle fixture','Product-A');for(const [time,batch,value] of [[0,'B1',98],[6,'B1',97],[0,'B2',99]]){s=await invoke(s,{action:'intake',name:`fixture-${batch}-${time}.json`,type:'application/json',text:sourceDoc(time,batch,value),permission:'Synthetic frozen test fixture',dataLabel:'SYNTHETIC'});s=await invoke(s,{action:'extract',id:s.sources.at(-1).id});}for(const f of s.fields)s=await invoke(s,{action:'review',kind:'field',id:f.id,revision:f.revision,choice:'APPROVE',reason:'Independent frozen source fixture answer inspected.'});hydrateLifecycle(s);return s;}
function cite(s,source=s.sources[0]){const start=source.text.indexOf(note);return {sourceId:source.id,version:source.version,start,end:start+note.length};}
async function lc(s,input,actor=AUTHOR){return lifecycleAction(s,input,actor);}
async function approve(s,result,actor=REVIEW){return lc(s,{operation:'approve',id:result.recordId,revision:result.revision,digest:result.digest,choice:'APPROVE',reason:'Independent exact source, dependency and version inspected.'},actor);}
async function entity(s,kind,label,field=s.fields[0]){const r=await lc(s,{operation:'entity',kind,label,evidenceRefs:[toRef(field)],citations:[cite(s)]});await approve(s,r);return r.recordId;}
async function setup(){const s=await fixture(),product=await entity(s,'product','Product-A'),batch=await entity(s,'batch','B1'),siteA=await entity(s,'site','Site-A'),siteB=await entity(s,'site','Site-B'),process=await entity(s,'process','Process-A'),material=await entity(s,'material','Material-A'),intermediate=await entity(s,'material','Intermediate-A');const req=await lc(s,{operation:'requirement',label:'Recorded assay requirement',parameter:'assay',market:'Market-A',sections:['3.2.P','2.3.P'],citations:[cite(s)],minCount:1});await approve(s,req);return {s,product,batch,siteA,siteB,process,material,intermediate,req:req.recordId};}
async function block(s,predecessorId){const fields=s.fields.filter(f=>f.sourceId===s.sources[0].id&&f.parameter!=='stability time');s=await invoke(s,{action:'draft',title:'Synthetic controlled quality content',section:'3.2.P',fieldIds:fields.map(f=>f.id)},AUTHOR);s=await invoke(s,{action:'review',kind:'draft',id:s.drafts.at(-1).id,revision:1,choice:'APPROVE',reason:'Independent source facts and exact citation QC checked.'},REVIEW);const r=await lc(s,{operation:'contentBlock',label:'Controlled source quality block',draftId:s.drafts.at(-1).id,draftRevision:1,market:'Market-A',predecessorId});await approve(s,r);return {s,id:r.recordId,revision:r.revision};}
await test('Lifecycle hydration preserves all existing source data',['X11','P02'],async()=>{const s=await fixture(),before=JSON.stringify(s.sources);hydrateLifecycle(s);assert.equal(s.ext.lifecycle.version,LIFECYCLE_VERSION);assert.equal(JSON.stringify(s.sources),before);});
await test('Source-backed entity stores exact fact and source revisions',['X08','X11'],async()=>{const s=await fixture(),r=await lc(s,{operation:'entity',kind:'product',label:'Product-A',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]});const x=s.ext.lifecycle.entities[0];assert.equal(x.evidenceRefs[0].sourceHash,s.sources[0].hash);assert.equal(x.scientificProperties[0].value,98);assert.equal(effectiveStatus(s,r.recordId),'CANDIDATE');});
await test('Anonymous lifecycle write blocked',['L02','P04'],()=>reject(()=>lc(initialState(),{operation:'entity'},{}),'UNAUTHENTICATED'));
await test('Viewer lifecycle write blocked',['L02','P04'],()=>reject(()=>lc(initialState(),{operation:'entity'},{id:'viewer',role:'viewer'}),'FORBIDDEN'));
await test('Invented scientific scalar rejected by strict schema',['X08','P01'],async()=>{const s=await fixture();await reject(()=>lc(s,{operation:'entity',kind:'product',label:'Product-A',value:123,evidenceRefs:[toRef(s.fields[0])]}),'LIFECYCLE_SCHEMA');});
await test('Invented object identity rejected',['X08'],async()=>{const s=await fixture();await reject(()=>lc(s,{operation:'entity',kind:'product',label:'Nonexistent scientific product',evidenceRefs:[toRef(s.fields[0])]}),'UNSUPPORTED_LABEL');});
await test('Missing actual stored fact rejected',['X08','X10'],async()=>{const s=await fixture();await reject(()=>lc(s,{operation:'entity',kind:'product',label:'Product-A',evidenceRefs:[{fieldId:'fabricated',revision:1}]}),'EVIDENCE_FACT');});
await test('Duplicate fact cannot inflate evidence count',['X10','X45'],async()=>{const s=await fixture();await reject(()=>lc(s,{operation:'entity',kind:'product',label:'Product-A',evidenceRefs:[toRef(s.fields[0]),toRef(s.fields[0])]}),'DUPLICATE_EVIDENCE');});
await test('Citation bounds and unknown source blocked',['X09','P01'],async()=>{const s=await fixture();await reject(()=>lc(s,{operation:'requirement',label:'Assay',parameter:'assay',market:'Market-A',sections:['3.2.P'],citations:[{...cite(s),end:1e6}]}),'LIFECYCLE_INPUT');});
await test('Entity author cannot approve their own revision',['X46','P04'],async()=>{const s=await fixture(),r=await lc(s,{operation:'entity',kind:'product',label:'Product-A',evidenceRefs:[toRef(s.fields[0])]});await reject(()=>approve(s,r,{...AUTHOR,role:'owner'}),'INDEPENDENT_REVIEW_REQUIRED');});
await test('Technical administrator cannot grant scientific approval',['L02','X46'],async()=>{const s=await fixture(),r=await lc(s,{operation:'entity',kind:'product',label:'Product-A',evidenceRefs:[toRef(s.fields[0])]});await reject(()=>approve(s,r,{id:'technical-admin',role:'admin'}),'FORBIDDEN');});
await test('Revision and digest mismatch reject approval',['X46','P02'],async()=>{const s=await fixture(),r=await lc(s,{operation:'entity',kind:'product',label:'Product-A',evidenceRefs:[toRef(s.fields[0])]});await reject(()=>lc(s,{operation:'approve',id:r.recordId,revision:99,choice:'APPROVE',reason:'Mismatch'},REVIEW),'STALE_REVISION');await reject(()=>lc(s,{operation:'approve',id:r.recordId,revision:r.revision,digest:'forged',choice:'APPROVE',reason:'Mismatch'},REVIEW),'STALE_REVISION');});
await test('Approved revision binds independent identity, sources and policy',['X46','P02'],async()=>{const s=await fixture(),r=await lc(s,{operation:'entity',kind:'product',label:'Product-A',evidenceRefs:[toRef(s.fields[0])]});await approve(s,r);const d=s.ext.lifecycle.decisions[0];assert.equal(d.reviewer,REVIEW.id);assert.equal(d.bindingHash,await hash(JSON.stringify(d.binding)));assert.equal(effectiveStatus(s,r.recordId),'APPROVED');});
await test('Entity predecessor remains immutable; only newest version current',['X11','P02'],async()=>{const s=await fixture(),r=await lc(s,{operation:'entity',kind:'product',label:'Product-A',evidenceRefs:[toRef(s.fields[0])]});await approve(s,r);const snapshot=JSON.stringify(s.ext.lifecycle.entities[0]);const next=await lc(s,{operation:'entity',kind:'product',label:'Product-A',evidenceRefs:[toRef(s.fields[0])],predecessorId:r.recordId});assert.equal(next.revision,2);assert.equal(JSON.stringify(s.ext.lifecycle.entities[0]),snapshot);assert.equal(effectiveStatus(s,r.recordId),'STALE');assert.equal(effectiveStatus(s,next.recordId),'CANDIDATE');});
await test('Genealogy creates source-linked material to intermediate to batch',['X12'],async()=>{const {s,material,intermediate,batch}=await setup();for(const [fromId,toId,relationType] of [[material,intermediate,'RAW_MATERIAL_TO_INTERMEDIATE'],[intermediate,batch,'INTERMEDIATE_TO_BATCH']]){const r=await lc(s,{operation:'relation',fromId,toId,relationType,evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]});await approve(s,r);}assert.equal(lifecycleProjection(s,'X12').data.edges.length,2);assert.equal(lifecycleProjection(s,'X12').data.nodes.length,3);});
await test('Genealogy cycles blocked before scientific interpretation',['X12','X13'],async()=>{const {s,material,intermediate}=await setup();const r=await lc(s,{operation:'relation',fromId:material,toId:intermediate,relationType:'RAW_MATERIAL_TO_INTERMEDIATE',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]});await approve(s,r);await reject(()=>lc(s,{operation:'relation',fromId:intermediate,toId:material,relationType:'RAW_MATERIAL_TO_INTERMEDIATE',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]}),'GENEALOGY_CYCLE');});
await test('Process graph validates equipment/site relation types',['X13'],async()=>{const {s,process,siteA,product}=await setup();const r=await lc(s,{operation:'relation',fromId:process,toId:siteA,relationType:'AT_SITE',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]});await approve(s,r);assert.equal(lifecycleProjection(s,'X13').data.edges[0].relationType,'AT_SITE');await reject(()=>lc(s,{operation:'relation',fromId:product,toId:siteA,relationType:'AT_SITE',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]}),'ENTITY_TYPE');});
await test('Requirement identity and market require real cited evidence',['X09','X10'],async()=>{const {s}=await setup();await reject(()=>lc(s,{operation:'requirement',label:'Invented',parameter:'never measured',market:'Market-A',sections:['3.2.P'],citations:[cite(s)]}),'UNSUPPORTED_REQUIREMENT');await reject(()=>lc(s,{operation:'requirement',label:'Invented',parameter:'assay',market:'Made-up jurisdiction',sections:['3.2.P'],citations:[cite(s)]}),'UNSUPPORTED_REQUIREMENT');});
await test('Arbitrary policy code and uncited category blocked',['X37','X44'],async()=>{const {s}=await setup();await reject(()=>lc(s,{operation:'rule',label:'Bad code',kind:'WORKFLOW',market:'Market-A',parameters:['assay'],expression:{op:'eval(process.env)'},citations:[cite(s)]}),'UNSAFE_RULE');await reject(()=>lc(s,{operation:'rule',label:'Bad category',kind:'CLASSIFICATION',market:'Market-A',parameters:['assay'],expression:{op:'NO_OPEN_CONFLICTS'},category:'LEGAL_CLEARANCE',citations:[cite(s)]}),'UNSUPPORTED_CLASSIFICATION');});
await test('Versioned requirement DSL executes actual approved count check',['X09','X44','X45'],async()=>{const {s,req}=await setup();const r=await lc(s,{operation:'rule',label:'Assay coverage rule',kind:'REQUIREMENT',market:'Market-A',parameters:['assay'],expression:{op:'REQUIRED_PARAMETER',count:1},requirementIds:[req],citations:[cite(s)]});await approve(s,r);assert.equal(lifecycleProjection(s,'X44').data.rules[0].execution.passed,true);assert.equal(lifecycleProjection(s,'X45').data.coverage[0].executableCoverage,true);});
await test('Content block and controlled reuse preserve scientific text',['X23','X26','X27'],async()=>{let {s,req}=await setup();const b=await block(s);s=b.s;const tpl=await lc(s,{operation:'template',label:'Source controlled style',sections:['3.2.P'],style:{headingCase:'SENTENCE',density:'TECHNICAL',referenceStyle:'EXACT_SPAN',factOrder:'PARAMETER'},citations:[cite(s)]});await approve(s,tpl);const r=await lc(s,{operation:'reuseContent',blockId:b.id,blockRevision:b.revision,market:'Market-A',section:'3.2.P.5.1',templateId:tpl.recordId,requirementIds:[req],reason:'Exact approved content in target controlled section.'});assert.equal(s.ext.lifecycle.reuses[0].text,s.ext.lifecycle.blocks[0].text);assert.equal(s.ext.lifecycle.reuses[0].scientificTextChanged,false);await approve(s,r);assert.equal(lifecycleProjection(s,'X26').data.reuses[0].status,'APPROVED');});
await test('Content cannot reuse an unapproved block or wrong revision',['X23','X26'],async()=>{let {s}=await setup();const b=await block(s);s=b.s;await reject(()=>lc(s,{operation:'reuseContent',blockId:b.id,blockRevision:99,market:'Market-A',section:'3.2.P',reason:'Wrong revision'}),'CONTENT_REVISION');s.ext.lifecycle.decisions=[];await reject(()=>lc(s,{operation:'reuseContent',blockId:b.id,blockRevision:1,market:'Market-A',section:'3.2.P',reason:'Unreviewed'}),'UNAPPROVED_DEPENDENCY');});
await test('Approved dossier maps actual obligation evidence and sections',['X10','X31','X36'],async()=>{const {s,product,req}=await setup();const r=await lc(s,{operation:'dossier',label:'Synthetic Market-A dossier',productId:product,market:'Market-A',section:'3.2.P',evidenceRefs:[toRef(s.fields[0])],requirementIds:[req],stateLabel:'RECORDED_FILING',citations:[cite(s)]});await approve(s,r);assert.equal(lifecycleProjection(s,'X31').data.results[0].passed,true);assert.equal(lifecycleProjection(s,'X36').data.markets[0].dossiers[0].filingClaim,'SUPPLIED_RECORD_ONLY');assert.equal(lifecycleProjection(s,'X10').data.requirements[0].mappedDossiers[0].coverage.covered,true);});
await test('Dossier with missing required parameter cannot be approved',['X31','X58'],async()=>{const {s,product,req}=await setup();const water=s.fields.find(f=>f.parameter==='water');const r=await lc(s,{operation:'dossier',label:'Synthetic missing assay dossier',productId:product,market:'Market-A',section:'3.2.P',evidenceRefs:[toRef(water)],requirementIds:[req]});await reject(()=>approve(s,r),'REQUIREMENT_GAP');assert.equal(lifecycleProjection(s,'X58').data.candidates[0].state,'PREDICTION');assert.equal(lifecycleProjection(s,'X58').data.candidates[0].probability,null);});
await test('Cross-dossier conflicts are measured with exact cited records',['X17','X18'],async()=>{const {s,product,req}=await setup();for(const [section,field] of [['2.3.P',s.fields[0]],['3.2.P',s.fields[4]]]){const r=await lc(s,{operation:'dossier',label:`Synthetic ${section} record`,productId:product,market:'Market-A',section,evidenceRefs:[toRef(field)],requirementIds:[req]});await approve(s,r);}assert.equal(lifecycleProjection(s,'X17').data.checks[0].scientificValueConflict,true);assert.ok(lifecycleProjection(s,'X18').data.specifications.length);});
await test('Observed stability trend has no extrapolation or shelf-life claim',['X19','X21'],async()=>{const {s,batch}=await setup();for(const source of s.sources.slice(0,2)){const fs=s.fields.filter(f=>f.sourceId===source.id),time=fs.find(f=>f.parameter==='stability time'),assay=fs.find(f=>f.parameter==='assay');const r=await lc(s,{operation:'stability',label:'Recorded stability observation',batchId:batch,timeRef:toRef(time),evidenceRefs:[toRef(assay)]});await approve(s,r);}const t=lifecycleProjection(s,'X19').data.trends[0];assert.equal(t.n,2);assert.equal(t.descriptiveSlope,-1/6);assert.equal(t.extrapolation,false);assert.equal(t.predictedShelfLife,null);});
await test('Stability batch mismatch cannot fabricate an observation',['X19'],async()=>{const {s,batch}=await setup(),fs=s.fields.filter(f=>f.batch==='B2');await reject(()=>lc(s,{operation:'stability',batchId:batch,timeRef:toRef(fs.find(f=>f.parameter==='stability time')),evidenceRefs:[toRef(fs[0])]}),'BATCH_CONTEXT');});
await test('Comparability and transfer are recorded evidence assessments',['X20','X22'],async()=>{const {s,batch,process,siteA,siteB}=await setup();const evidenceRefs=s.fields.filter(f=>f.parameter==='assay'&&f.timePoint===0).map(toRef);const r=await lc(s,{operation:'comparability',label:'Frozen descriptive batch comparison',batchIds:[batch],processIds:[process],evidenceRefs});await approve(s,r);assert.equal(lifecycleProjection(s,'X20').data.assessments[0].equivalenceEstablished,false);const t=await lc(s,{operation:'transfer',label:'Frozen scale-up evidence map',stage:'SCALE_UP',fromSiteId:siteA,toSiteId:siteB,processIds:[process],batchIds:[batch],comparabilityId:r.recordId,evidenceRefs,citations:[cite(s)]});await approve(s,t);assert.equal(lifecycleProjection(s,'X22').data.transfers[0].qualificationClaim,false);});
await test('Market classification is rule-backed candidate, never legal clearance',['X36','X37','X38'],async()=>{const {s,product}=await setup();const change=await lc(s,{operation:'marketChange',label:'Recorded source change',productId:product,oldSourceId:s.sources[0].id,newSourceId:s.sources[1].id,changedParameters:['assay'],evidenceRefs:[toRef(s.fields[4])]});await approve(s,change);const rule=await lc(s,{operation:'rule',label:'Recorded Market-A MINOR candidate rule',kind:'CLASSIFICATION',market:'Market-A',parameters:['assay'],expression:{op:'NO_OPEN_CONFLICTS'},category:'MINOR',citations:[cite(s)]});await approve(s,rule);const c=await lc(s,{operation:'classify',changeId:change.recordId,ruleIds:[rule.recordId],market:'Market-A'});await approve(s,c);const x=lifecycleProjection(s,'X37').data.classifications[0];assert.equal(x.candidateCategory,'MINOR');assert.equal(x.regulatoryAuthority,false);assert.equal(x.automaticFiling,false);});
await test('Unknown/conflicting reporting categories remain HOLD/CONFLICT',['X37'],async()=>{const {s,product}=await setup();const change=await lc(s,{operation:'marketChange',label:'Recorded source change',productId:product,oldSourceId:s.sources[0].id,newSourceId:s.sources[1].id,changedParameters:['assay'],evidenceRefs:[toRef(s.fields[4])]});await approve(s,change);const ruleIds=[];for(const category of ['MINOR','MAJOR']){const r=await lc(s,{operation:'rule',label:`Conflicting ${category} rule`,kind:'CLASSIFICATION',market:'Market-A',parameters:['assay'],expression:{op:'NO_OPEN_CONFLICTS'},category,citations:[cite(s)]});await approve(s,r);ruleIds.push(r.recordId);}const c=await lc(s,{operation:'classify',changeId:change.recordId,ruleIds,market:'Market-A'});assert.equal(lifecycleProjection(s,'X37').data.classifications[0].candidateState,'CONFLICT');await reject(()=>approve(s,c),'CLASSIFICATION_HOLD');});
await test('Change simulation creates read-only scientific branch snapshot',['X39','D07','D08'],async()=>{const {s}=await setup(),before=JSON.stringify(s.fields);const r=await lc(s,{operation:'simulation',label:'Frozen proposed assay replacement',sourceId:s.sources[0].id,replacements:[{fromFieldId:s.fields[0].id,fromRevision:1,toFieldId:s.fields[4].id,toRevision:1}],reason:'Measure downstream recorded dependencies before source adoption.'});assert.equal(JSON.stringify(s.fields),before);assert.equal(s.ext.lifecycle.branches[0].branchPolicy.autoMerge,false);assert.equal(s.ext.lifecycle.branches[0].replacements[0].toValue,97);await approve(s,r);assert.equal(lifecycleProjection(s,'X39').data.productionStateMutated,false);});
await test('Simulated unsupported parameter replacement rejected',['X39','D07'],async()=>{const {s}=await setup();await reject(()=>lc(s,{operation:'simulation',label:'Bad replacement',sourceId:s.sources[0].id,replacements:[{fromFieldId:s.fields[0].id,fromRevision:1,toFieldId:s.fields[1].id,toRevision:1}],reason:'Bad replacement'}),'SIMULATION_CONTEXT');});
await test('Graph blast radius includes causal rule/content decisions and excludes unrelated facts',['X40','X41','X46'],async()=>{const {s,product}=await setup();const g=lifecycleGraph(s);assert.ok(g.edges.some(e=>e.to===product&&e.dependency));const x=lifecycleProjection(s,'X40',{sourceId:s.sources[0].id}).data;assert.ok(x.included.some(n=>n.id===product));assert.ok(x.excluded.some(n=>n.id===s.fields[8].id));assert.equal(lifecycleProjection(s,'X41',{sourceId:s.sources[0].id}).data.globalNonImpactClaim,false);});
await test('Selective staleness preserves immutable records and independent source data',['X42','P03'],async()=>{const {s,product}=await setup(),records=JSON.stringify(s.ext.lifecycle.entities),decision=JSON.stringify(s.ext.lifecycle.decisions);const result=invalidateLifecycle(s,s.sources[0].id);assert.ok(result.invalidated.some(i=>i.recordId===product));assert.equal(JSON.stringify(s.ext.lifecycle.entities),records);assert.equal(JSON.stringify(s.ext.lifecycle.decisions),decision);assert.equal(s.fields[8].status,'APPROVED');assert.equal(effectiveStatus(s,product),'STALE');});
await test('Source revision change automatically invalidates expanded lifecycle graph',['X42','P03'],async()=>{const {s,product}=await setup();const changed=await invoke(s,{action:'change',id:s.sources[0].id,text:sourceDoc(0,'B1',98.5),reason:'New frozen fixture source revision.'},AUTHOR);assert.equal(effectiveStatus(changed,product),'STALE');assert.ok(changed.ext.lifecycle.invalidations.length);});
await test('Regression runs persist expected/actual rule and coverage checks',['X43','D05','D06'],async()=>{const {s,product,req}=await setup();const rule=await lc(s,{operation:'rule',label:'Actual assay requirement test',kind:'REQUIREMENT',market:'Market-A',parameters:['assay'],expression:{op:'REQUIRED_PARAMETER',count:1},requirementIds:[req],citations:[cite(s)]});await approve(s,rule);const dossier=await lc(s,{operation:'dossier',label:'Regression target dossier',productId:product,market:'Market-A',section:'3.2.P',evidenceRefs:[toRef(s.fields[0])],requirementIds:[req]});await approve(s,dossier);const r=await lc(s,{operation:'regression',ruleIds:[rule.recordId],dossierIds:[dossier.recordId]},REVIEW);const run=s.ext.lifecycle.regressions.find(x=>x.id===r.recordId);assert.equal(run.denominator,2);assert.equal(run.passed,true);assert.equal(run.noRegulatoryValidationClaim,true);});
await test('Empty regression cannot fabricate success',['X43'],async()=>{const {s}=await setup();await reject(()=>lc(s,{operation:'regression',ruleIds:[],dossierIds:[]},REVIEW),'REGRESSION_SCOPE');});
await test('Actual source-linked HAQ and approved outcome enter governed memory',['X53','X54','X55','X56','X57'],async()=>{const {s}=await setup();const q=await lc(s,{operation:'haq',title:'Explain the recorded assay evidence.',label:'Recorded HAQ evidence question',market:'Market-A',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]});await approve(s,q);const o=await lc(s,{operation:'haqOutcome',haqId:q.recordId,outcome:'ACKNOWLEDGED',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]});assert.equal(lifecycleProjection(s,'X57').data.memory.length,0);await approve(s,o);assert.equal(lifecycleProjection(s,'X54',{query:'assay'}).data.memory.length,1);assert.equal(lifecycleProjection(s,'X55').data.questions[0].response[0].sourceId,s.sources[0].id);});
await test('Invented authority question or outcome cannot enter memory',['X53','X57'],async()=>{const {s}=await setup();await reject(()=>lc(s,{operation:'haq',title:'Invented regulator acceptance',label:'Invented',market:'Market-A',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]}),'QUESTION_SOURCE');});
await test('Source staleness removes approved HAQ outcome from current memory',['X54','X57','P03'],async()=>{const {s}=await setup();const q=await lc(s,{operation:'haq',title:'Explain the recorded assay evidence.',label:'Recorded HAQ',market:'Market-A',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]});await approve(s,q);const o=await lc(s,{operation:'haqOutcome',haqId:q.recordId,outcome:'ACKNOWLEDGED',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]});await approve(s,o);invalidateLifecycle(s,s.sources[0].id);assert.equal(lifecycleProjection(s,'X57').data.memory.length,0);});
await test('Closure compares exact expected versus actual source evidence',['X64'],async()=>{const {s}=await setup();const a=await lc(s,{operation:'closure',label:'Frozen effectiveness action',owner:AUTHOR.id,expectedChecks:[{operator:'WITHIN_RECORDED_LIMITS',expected:toRef(s.fields[0]),actual:toRef(s.fields[4])}]});const v=await lc(s,{operation:'verifyClosure',id:a.recordId,revision:a.revision,reason:'Independent expected/actual limits, context and source hashes checked.'},REVIEW);assert.equal(s.ext.lifecycle.verifications[0].passed,true);assert.equal(lifecycleProjection(s,'X64').data.actions[0].actionStatus,'CLOSED_WITH_EVIDENCE');assert.equal(v.collection,'verifications');});
await test('Owner cannot close their own action and mismatched evidence remains open',['X64','P04'],async()=>{const {s}=await setup();const a=await lc(s,{operation:'closure',label:'Frozen action mismatch',owner:AUTHOR.id,expectedChecks:[{operator:'EQUAL',expected:toRef(s.fields[0]),actual:toRef(s.fields[4])}]});await reject(()=>lc(s,{operation:'verifyClosure',id:a.recordId,revision:a.revision,reason:'Self close'},{...AUTHOR,role:'owner'}),'INDEPENDENT_REVIEW_REQUIRED');await lc(s,{operation:'verifyClosure',id:a.recordId,revision:a.revision,reason:'The actual numeric value differs from the recorded expected value.'},REVIEW);assert.equal(s.ext.lifecycle.verifications[0].passed,false);assert.equal(lifecycleProjection(s,'X64').data.actions[0].actionStatus,'OPEN');});
await test('Later source change reopens closure without rewriting original verification',['X65','P03'],async()=>{const {s}=await setup();const a=await lc(s,{operation:'closure',label:'Reopen fixture action',expectedChecks:[{operator:'CURRENT_APPROVED',expected:toRef(s.fields[0]),actual:toRef(s.fields[0])}]});await lc(s,{operation:'verifyClosure',id:a.recordId,revision:a.revision,reason:'Exact original source-backed outcome verified.'},REVIEW);const snapshot=JSON.stringify(s.ext.lifecycle.verifications);invalidateLifecycle(s,s.sources[0].id);assert.equal(lifecycleProjection(s,'X65').data.actions[0].actionStatus,'REOPENED');assert.equal(JSON.stringify(s.ext.lifecycle.verifications),snapshot);});
await test('Controlled correction makes new dependent candidates and transfers no approval',['X61','X26'],async()=>{let {s,req}=await setup();const b=await block(s);s=b.s;const r=await lc(s,{operation:'reuseContent',blockId:b.id,blockRevision:1,market:'Market-A',section:'3.2.P',requirementIds:[req],reason:'Controlled baseline reuse.'});await approve(s,r);const original=JSON.stringify(s.ext.lifecycle.reuses[0]);const next=await block(s,b.id);s=next.s;const correction=await lc(s,{operation:'correction',fromBlockId:b.id,toBlockId:next.id,reuseIds:[r.recordId],reason:'Propagate exact independently approved replacement block.'});assert.equal(JSON.stringify(s.ext.lifecycle.reuses[0]),original);const newReuse=s.ext.lifecycle.reuses.at(-1);assert.equal(newReuse.revision,2);assert.equal(newReuse.previousApprovalTransferred,false);assert.equal(effectiveStatus(s,newReuse.id),'CANDIDATE');assert.equal(correction.collection,'corrections');});
await test('Every covered source identifier exposes bounded executable projection',['X08','X09','X10','X11','X12','X13','X17','X18','X19','X20','X21','X22','X23','X26','X27','X31','X36','X37','X38','X39','X40','X41','X42','X43','X44','X45','X46','X58','X61'],async()=>{const {s}=await setup();for(const id of LIFECYCLE_IDS){const p=lifecycleProjection(s,id,{sourceId:s.sources[0].id});assert.equal(p.id,id);assert.equal(p.humanAuthority,false);assert.equal(p.maturityNotAutomaticallyPromoted,true);assert.ok(p.data);}});
await test('Capability dispatch returns real controlled lifecycle projections',['X08','X11','X44'],async()=>{const {s,product}=await setup();assert.ok(capability(s,'X11').data.entities.some(e=>e.id===product));assert.equal(capability(s,'X44').data.arbitraryCodeExecution,false);});
await test('Content-linked graph renders exact approved draft edge without mutation',['X23','X46'],async()=>{let {s}=await setup();const b=await block(s);s=b.s;const before=JSON.stringify(s);const graph=lifecycleGraph(s);assert.ok(graph.edges.some(e=>e.to===b.id&&e.reason==='exact approved draft revision'));assert.equal(JSON.stringify(s),before);});
await test('Rejected dependency revokes downstream current approval',['X42','X46'],async()=>{const {s,product,req}=await setup();const d=await lc(s,{operation:'dossier',label:'Controlled dependency check',productId:product,market:'Market-A',section:'3.2.P',evidenceRefs:[toRef(s.fields[0])],requirementIds:[req]});await approve(s,d);const p=s.ext.lifecycle.entities.find(e=>e.id===product);await lc(s,{operation:'approve',id:p.id,revision:p.revision,digest:p.digest,choice:'REJECT',reason:'New independent review found missing product evidence.'},REVIEW);assert.equal(effectiveStatus(s,d.recordId),'STALE');});
await test('Wrong-market requirement cannot authorize dossier approval',['X10','X36'],async()=>{const {s,product,req}=await setup();const d=await lc(s,{operation:'dossier',label:'Wrong market candidate',productId:product,market:'Different-Market',section:'3.2.P',evidenceRefs:[toRef(s.fields[0])],requirementIds:[req]});await reject(()=>approve(s,d),'REQUIREMENT_GAP');});
await test('No requirement profile cannot pass dossier approval',['X31','X45'],async()=>{const {s,product}=await setup();const d=await lc(s,{operation:'dossier',label:'Unconfigured requirements',productId:product,market:'Market-A',section:'3.2.P',evidenceRefs:[toRef(s.fields[0])],requirementIds:[]});await reject(()=>approve(s,d),'REQUIREMENT_GAP');});
await test('Change candidate rejects evidence from a different source',['X38'],async()=>{const {s,product}=await setup();await reject(()=>lc(s,{operation:'marketChange',label:'Mismatched source change',productId:product,oldSourceId:s.sources[0].id,newSourceId:s.sources[1].id,changedParameters:['assay'],evidenceRefs:[toRef(s.fields[0])]}),'CHANGE_CONTEXT');});
await test('Simulation cannot borrow baseline facts from another source',['X39'],async()=>{const {s}=await setup();await reject(()=>lc(s,{operation:'simulation',label:'Mismatched baseline',sourceId:s.sources[1].id,replacements:[{fromFieldId:s.fields[0].id,fromRevision:1,toFieldId:s.fields[4].id,toRevision:1}],reason:'Wrong selected baseline.'}),'SIMULATION_CONTEXT');});
await test('Governed memory excludes legacy free-text response comments',['X54','X57','X66'],async()=>{const {s}=await setup();s.queries.push({id:'legacy-unverified',status:'APPROVED',title:'Assay accepted',outcome:'Regulator accepted',fieldIds:[s.fields[0].id]});assert.ok(!retrieveMemory(s,'assay',50).some(r=>r.id==='legacy-unverified'));});
await test('Governed memory admits exact approved lifecycle outcomes and removes stale ones',['X54','X57','X66'],async()=>{const {s}=await setup();const q=await lc(s,{operation:'haq',title:'Explain the recorded assay evidence.',label:'Actual question',market:'Market-A',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]});await approve(s,q);const o=await lc(s,{operation:'haqOutcome',haqId:q.recordId,outcome:'ACKNOWLEDGED',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]});assert.ok(!retrieveMemory(s,'assay',50).some(r=>r.id===o.recordId));await approve(s,o);assert.ok(retrieveMemory(s,'assay',50).some(r=>r.id===o.recordId&&r.type==='approved HA outcome'&&r.regulatorAcceptance===false));invalidateLifecycle(s,s.sources[0].id);assert.ok(!retrieveMemory(s,'assay',50).some(r=>r.id===o.recordId));});
await test('Typed specialists project actual controlled records without human authority',['A2','A6','A7','A8','A13','A15','A17'],async()=>{const {s,product}=await setup();assert.equal(executeRole(s,'A2').output.visionAvailability,'CHECK_AUTHENTICATED_SERVER_CONFIGURATION');assert.ok(executeRole(s,'A7').output.requirements.requirements.length);assert.equal(executeRole(s,'A8').output.equivalenceAuthority,false);for(const role of ['A6','A13','A15','A17'])assert.equal(executeRole(s,role).humanAuthority,false);});
await test('A regression cannot pass an unconfigured dossier obligation profile',['X31','X43'],async()=>{const {s,product}=await setup();const d=await lc(s,{operation:'dossier',label:'Unconfigured requirements regression',productId:product,market:'Market-A',section:'3.2.P',evidenceRefs:[toRef(s.fields[0])],requirementIds:[]});const r=await lc(s,{operation:'regression',dossierIds:[d.recordId]},REVIEW);assert.equal(s.ext.lifecycle.regressions.find(x=>x.id===r.recordId).passed,false);});
await test('Actual question cannot invent its jurisdiction',['X53','X55'],async()=>{const {s}=await setup();await reject(()=>lc(s,{operation:'haq',title:'Explain the recorded assay evidence.',market:'Invented-Market',evidenceRefs:[toRef(s.fields[0])],citations:[cite(s)]}),'QUESTION_SOURCE');});
await test('All typed specialists hydrate a copy of legacy state without mutating workspace',['A1','A18','L09'],async()=>{const s=await fixture();delete s.ext;const before=JSON.stringify(s);for(let i=1;i<=18;i++){const result=executeRole(s,`A${i}`,{sourceId:s.sources[0].id});assert.equal(result.humanAuthority,false);assert.ok(result.output);}assert.equal(JSON.stringify(s),before);});
const proof={suite:'FORGE expanded lifecycle domain',version:LIFECYCLE_VERSION,scope:'Local synthetic exact-source adversarial domain fixtures. No browser/hosted/provider/scientific/regulatory validation claim.',at:new Date().toISOString(),passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,results};fs.mkdirSync('docs/proof',{recursive:true});fs.writeFileSync('docs/proof/lifecycle-results.json',JSON.stringify(proof,null,2));console.log(`${proof.passed}/${results.length} expanded lifecycle cases passed`);if(proof.failed)process.exitCode=1;
