/** Compiled Worker + local D1/R2 + synthetic model protocol. No live provider or company data. */
import {createRequire} from 'node:module';
import {readFileSync,readdirSync,realpathSync,statSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
import {SYNTHETIC_SOURCES} from '../lib/core.mjs';
const require=createRequire(realpathSync('node_modules/wrangler/package.json')),{Miniflare,Log,LogLevel}=require('miniflare');
function walk(dir){return readdirSync(dir).flatMap(n=>{const p=resolve(dir,n);return statSync(p).isDirectory()?walk(p):p.endsWith('.js')?[p]:[];});}
const modules=[resolve('dist/server/index.js'),...walk('dist/server').filter(p=>p!==resolve('dist/server/index.js'))].map(path=>({type:'ESModule',path}));
let calls=0,rejectReviewer=false;const models=[],keys=[];
const mf=new Miniflare({modules,modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{OPENAI_API_KEY:'synthetic-test-only',FORGE_MODEL:'synthetic-author/1',FORGE_REVIEWER_MODEL:'synthetic-reviewer/1'},outboundService:async request=>{assert.equal(request.url,'https://api.openai.com/v1/responses');calls++;const b=await request.json(),p=JSON.parse(b.input);models.push(b.model);keys.push(request.headers.get('idempotency-key'));let value;if(b.text.format.name==='forge_bounded_allocation')value={allocations:[{role:'ANALYTICAL_FACTS',fieldIds:[p.approvedFacts[0].fieldId]},{role:'CMC_FACTS',fieldIds:p.approvedFacts.slice(1).map(f=>f.fieldId)}]};else if(b.text.format.name==='forge_source_bound_draft')value={statements:p.approvedFacts.map(f=>({fieldId:f.fieldId,text:`Recorded ${f.parameter} is ${f.value} ${f.unit} for batch ${f.batch} using ${f.method}.`}))};else value={checks:p.statements.map(s=>({fieldId:s.fieldId,supported:!rejectReviewer,reason:rejectReviewer?'Synthetic unsupported claim.':'Synthetic exact match.'}))};return Response.json({id:'fixture-'+calls,model:b.model,status:'completed',usage:{input_tokens:10,output_tokens:10},output:[{content:[{type:'output_text',text:JSON.stringify(value)}]}]});},log:new Log(LogLevel.ERROR)});
const results=[];async function check(name,fn){await fn();results.push({name,status:'PASS'});}
async function call(path,{body,status=200,key=crypto.randomUUID(),user='fixture-owner'}={}){const headers={'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test',origin:'https://forge.test','idempotency-key':key};if(body)headers['content-type']='application/json';const r=await mf.dispatchFetch('https://forge.test'+path,{method:body?'POST':'GET',headers,...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();assert.equal(r.status,status,text.slice(0,300));return JSON.parse(text);}
try{
 const db=await mf.getD1Database('DB');for(const f of readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())for(const sql of readFileSync('drizzle/'+f,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()))await db.prepare(sql).run();
 let w=await call('/api/forge',{body:{action:'createWorkspace',name:'Synthetic AI integration',product:'Synthetic Product'},status:201});
 async function action(payload,opts={}){const r=await call('/api/forge',{...opts,body:{workspaceId:w.id,expectedVersion:w.state.version,...payload}});if(r.state)w.state=r.state;return r;}
 await action({action:'intake',...SYNTHETIC_SOURCES[0],permission:'Synthetic fixture only'});await action({action:'extract',id:w.state.sources[0].id});for(const f of [...w.state.fields])await action({action:'review',kind:'field',id:f.id,revision:f.revision,choice:'APPROVE',reason:'Named synthetic reviewer inspected exact source evidence.'});
 await check('Distinct configuration is visible without exposing a key',async()=>{const d=await call('/api/forge');assert.equal(d.runtime.aiConfigured,true);assert.ok(!JSON.stringify(d).includes('synthetic-test-only'));});
 await check('Provider consent is enforced before any model call',async()=>{await action({action:'aiDraft',providerPermission:false},{status:403});assert.equal(calls,0);});
 let teamDraft,request,opKey;
 await check('Compiled authoring routes planner, parallel authors and distinct reviewer into saved state',async()=>{opKey=crypto.randomUUID();request={action:'aiDraft',workspaceId:w.id,expectedVersion:w.state.version,providerPermission:true,title:'Synthetic reviewed model candidate',section:'3.2.P'};const r=await call('/api/forge',{body:request,key:opKey});w.state=r.state;assert.equal(calls,4);assert.equal(r.result.state,'CANDIDATE_READY');teamDraft=r.state.drafts[0];assert.equal(teamDraft.status,'CANDIDATE');assert.equal(teamDraft.reviewerModel,'synthetic-reviewer/1');assert.equal(r.state.agentRuns[0].runs.length,4);assert.equal(r.state.exports.length,0);assert.ok(!r.state.decisions.some(d=>d.targetId===teamDraft.id));assert.equal(models.at(-1),'synthetic-reviewer/1');assert.equal(new Set(keys).size,4);});
 await check('Persisted readback contains exact role receipts and evidence fingerprint',async()=>{const d=await call('/api/forge?workspace='+w.id);assert.equal(d.state.drafts[0].modelTeam,w.state.agentRuns[0].id);assert.equal(d.state.agentRuns[0].evidenceHash.length,64);assert.equal(d.state.agentRuns[0].release,false);});
 await check('Idempotent replay makes no additional provider calls',async()=>{const d=await call('/api/forge',{body:request,key:opKey});assert.equal(d.idempotent,true);assert.equal(calls,4);});
 await check('Independent rejection saves failure traces and creates no additional draft',async()=>{rejectReviewer=true;const r=await action({action:'aiDraft',providerPermission:true,title:'Synthetic rejected draft'});assert.equal(r.result.state,'DLQ');assert.equal(r.state.drafts.length,1);assert.equal(r.state.jobs.at(-1).modelRuns.length,4);assert.equal(r.state.exports.length,0);});
 await check('Foreign workspace access is rejected before provider transmission',async()=>{const before=calls;await call('/api/forge',{user:'foreign',body:{action:'aiDraft',workspaceId:w.id,expectedVersion:w.state.version,providerPermission:true},status:403});assert.equal(calls,before);});
}catch(e){console.error(e);process.exitCode=1;}finally{await mf.dispose();writeFileSync('docs/proof/model-runtime-results.json',JSON.stringify({at:new Date().toISOString(),passed:results.length,failed:process.exitCode?1:0,cases:results,scope:'Compiled local Worker, D1/R2 and synthetic model responses; not live provider or scientific validation.'},null,2));}
console.log(`${results.length}/7 compiled model-team checks passed`);
