import {providerConfig,providerConfigured} from '../../../lib/provider-config.mjs';
import {env} from 'cloudflare:workers';
import {boundedBody} from '../../../lib/http.mjs';
import {getChatGPTUser} from '../../chatgpt-auth';
import {command,ForgeError,requireValue,hash,uid,seedSynthetic,VERSION,qcDraft,actorCan,audit,normalizeField,checkState,signaturePayload} from '../../../lib/core.mjs';
import {database,listWorkspaces,createWorkspace,loadWorkspace,rateLimit,previousOperation,commitWorkspace,history,verifyAudit,addMember,membership} from '../../../lib/repository';
import {inferDocument,runtimeFailure,inferCollaboration} from '../../../lib/model-gateway.mjs';
import {base32,encryptSecret,decryptSecret,verifyTOTP,signatureRecord} from '../../../lib/signature.mjs';
import {branchOverview} from '../../../lib/branches.mjs';
import {parseDocumentBytes} from '../../../lib/document-parser.mjs';
export const dynamic='force-dynamic';
const secureHeaders={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'};
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:secureHeaders});
function error(e:unknown){if(e instanceof ForgeError)return json({error:e.message,code:e.code},e.status);console.error('forge_api_failure',e instanceof Error?e.name:'unknown');return json({error:'The operation could not be completed. Retry safely or contact your administrator.',code:'SERVICE_FAILURE'},503);}
async function user(){const u=await getChatGPTUser();if(!u)throw new ForgeError('UNAUTHENTICATED','Sign in to access persistent workspaces.',401);return u;}
export async function GET(request:Request){try{const u=await user(),url=new URL(request.url),id=url.searchParams.get('workspace');if(!id)return json({user:{id:u.userId,name:u.displayName},workspaces:await listWorkspaces(u.userId),runtime:{version:VERSION,storage:Boolean(env.DB&&env.BUCKET),aiConfigured:providerConfigured(env),signatureConfigured:Boolean((env as any).FORGE_SIGNING_KEY)}});if(url.searchParams.has('history'))return json({history:await history(id,u.userId,url.searchParams.get('revision')?Number(url.searchParams.get('revision')):undefined)});if(url.searchParams.has('auditCheck'))return json(await verifyAudit(id,u.userId));const ws=await loadWorkspace(id,u.userId);if(url.searchParams.has('branches'))return json(await branchOverview(ws.state));return json(ws);}catch(e){return error(e);}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)throw new ForgeError('CROSS_ORIGIN_BLOCKED','Cross-origin writes are not allowed.',403);if(!request.headers.get('content-type')?.includes('application/json'))throw new ForgeError('UNSUPPORTED_MEDIA','Use JSON for this endpoint.',415);const length=Number(request.headers.get('content-length')||0);if(length>1_500_000)throw new ForgeError('PAYLOAD_TOO_LARGE','Maximum request size is 1.5 MB.',413);const text=new TextDecoder().decode(await boundedBody(request,1_500_000));if(text.length>1_500_000)throw new ForgeError('PAYLOAD_TOO_LARGE','Maximum request size is 1.5 MB.',413);let input:any;try{input=JSON.parse(text);}catch{throw new ForgeError('INVALID_JSON','Invalid JSON request.');}const u=await user();await rateLimit(u.userId);
 if(input.action==='createWorkspace')return json(await createWorkspace(u,requireValue(input.name,'Workspace name',100),requireValue(input.product,'Product',100)),201);
 if(input.action==='supersedeSource')throw new ForgeError('USE_UPLOAD','Replace an original through the controlled upload endpoint.');
 const id=requireValue(input.workspaceId,'Workspace ID',100),ws=await loadWorkspace(id,u.userId);
 if(input.action==='membership'){requireValue(input.userId,'Member user ID',100);await addMember(id,u.userId,input);return json({updated:true});}
 if(input.action==='factorSetup'){const secret=base32(crypto.getRandomValues(new Uint8Array(20))),encrypted=await encryptSecret(secret,(env as any).FORGE_SIGNING_KEY);const existing=await database().prepare('SELECT confirmed FROM signature_factors WHERE id=?').bind(u.userId).first<{confirmed:number}>();if(existing?.confirmed)throw new ForgeError('FACTOR_ALREADY_ENROLLED','An authenticator is already enrolled. Recovery requires administrator procedure.',409);await database().prepare('INSERT INTO signature_factors(id,user_id,encrypted_secret,confirmed,last_counter,created_at) VALUES(?,?,?,0,-1,?) ON CONFLICT(id) DO UPDATE SET encrypted_secret=excluded.encrypted_secret').bind(u.userId,u.userId,encrypted,new Date().toISOString()).run();return json({secret,uri:`otpauth://totp/FORGE:${encodeURIComponent(u.email)}?secret=${secret}&issuer=FORGE&algorithm=SHA1&digits=6&period=30`});}
 if(input.action==='factorConfirm'){const f=await database().prepare('SELECT encrypted_secret,last_counter FROM signature_factors WHERE id=?').bind(u.userId).first<{encrypted_secret:string;last_counter:number}>();if(!f)throw new ForgeError('FACTOR_NOT_ENROLLED','Set up an authenticator first.',409);const secret=await decryptSecret(f.encrypted_secret,(env as any).FORGE_SIGNING_KEY),counter=await verifyTOTP(secret,input.code,f.last_counter);const consumed=await database().prepare('UPDATE signature_factors SET confirmed=1,last_counter=? WHERE id=? AND last_counter<? AND encrypted_secret=?').bind(counter,u.userId,counter,f.encrypted_secret).run();if(!consumed.meta.changes)throw new ForgeError('OTP_REPLAY','Authenticator code already used or enrollment changed.',409);return json({confirmed:true});}
 const key=requireValue(request.headers.get('idempotency-key'),'Operation key',100);const digest=await hash(JSON.stringify(input)),prior=await previousOperation(id,u.userId,key,digest);if(prior)return json({...prior,idempotent:true});
 let result:any,after:any;const mergeAuthorities:Array<{userId:string;role:string}>=[];
 if(input.action==='branch'&&input.operation==='merge'){const branch=ws.state.ext?.controlledBranches?.records?.find((b:any)=>b.id===input.id);if(branch?.review){let authority;try{authority=await membership(id,branch.review.reviewer);}catch{throw new ForgeError('BRANCH_REVIEWER_REVOKED','The proposal reviewer no longer has active workspace review authority. Obtain a new independent review.',403);}if(!['owner','reviewer','approver'].includes(authority.role))throw new ForgeError('BRANCH_REVIEWER_REVOKED','The proposal reviewer no longer has scientific-review authority.',403);mergeAuthorities.push({userId:branch.review.reviewer,role:authority.role});}}
 if(input.action==='seedSynthetic'){if(!['owner','admin','author'].includes(ws.role))throw new ForgeError('FORBIDDEN','Source-authoring permission required.',403);if(input.expectedVersion!==ws.state.version||ws.state.sources.length)throw new ForgeError('INVALID_STATE','Load fixtures into an empty current workspace.',409);after=await seedSynthetic();after.name=ws.state.name;after.product=ws.state.product;for(const event of after.audit)event.actor=u.userId;result={seeded:true};}else if(input.action==='aiDraft'){
 if(!actorCan(ws.role,'draft'))throw new ForgeError('FORBIDDEN','Draft-authoring permission required.',403);
 if(input.expectedVersion!==ws.state.version)throw new ForgeError('STALE_REVISION','Workspace changed before AI inference.',409);
 if(input.providerPermission!==true)throw new ForgeError('PROVIDER_PERMISSION_REQUIRED','Explicit permission is required before transmitting approved facts to the AI provider.',403);
 after=structuredClone(ws.state);const job:any={id:uid('job'),role:'A10',inputRevision:after.version,status:'RUNNING',attempts:1,traceId:uid('run'),at:new Date().toISOString()};
 try{const facts=after.fields.filter((f:any)=>f.status==='APPROVED');if(!facts.length)throw new ForgeError('NO_APPROVED_FACTS','Approve source-supported facts before AI authoring.',409);
 const candidate=await inferCollaboration(facts,{...providerConfig(env),operationId:key});
 const base=await command(after,{action:'draft',title:input.title||'AI-assisted Module 3 candidate',section:input.section,expectedVersion:after.version},{id:u.userId,role:ws.role,traceId:job.traceId});after=base.state;const draft=after.drafts[after.drafts.length-1];draft.authorPrincipal=candidate.principal;draft.modelVersion=candidate.model;draft.promptHash=candidate.promptHash;draft.modelTeam=candidate.id;draft.evidenceHash=candidate.evidenceHash;draft.reviewerModel=candidate.reviewerModel;draft.statements=draft.statements.map((st:any)=>({...st,text:candidate.statements.find((x:any)=>x.fieldId===st.fieldId)!.text}));draft.qc=qcDraft(after,draft);draft.status='CANDIDATE';job.status=draft.qc.passed?'CANDIDATE_READY':'HOLD';job.resultId=draft.id;after.agentRuns.push(candidate);result={draftId:draft.id,state:job.status};
 }catch(e:any){Object.assign(job,runtimeFailure(e),{modelRuns:e.modelRuns||[]});audit(after,{id:u.userId,role:ws.role,traceId:job.traceId},'aiDraftHeld',job.id,{code:e.code,state:job.status});after.version++;result={state:job.status,failure:e.message};}
 after.jobs.push(job);
 }else if(input.action==='documentExtract'){
 if(!actorCan(ws.role,'extract'))throw new ForgeError('FORBIDDEN','Extraction permission required.',403);if(input.expectedVersion!==ws.state.version)throw new ForgeError('STALE_REVISION','Refresh the current source workspace.',409);after=structuredClone(ws.state);const source=after.sources.find((x:any)=>x.id===input.id);if(!source?.objectKey)throw new ForgeError('ORIGINAL_REQUIRED','Upload a preserved original first.',409);if(source.status==='SUPERSEDED')throw new ForgeError('STALE_SOURCE','Use the current source revision.',409);if(source.status==='PARSED')return json({state:after,result:{idempotent:true}});const original=await env.BUCKET?.get(source.objectKey);if(!original)throw new ForgeError('SOURCE_FAILED','Original bytes are unavailable.',503);const bytes=await original.arrayBuffer();if(await hash(bytes)!==source.hash)throw new ForgeError('SOURCE_HASH_MISMATCH','Original bytes do not match the source hash.',409);const parsed:any=await parseDocumentBytes(bytes,source.type,source.name);source.parser=parsed.parserVersion;source.extractionWarnings=parsed.warnings;source.extractedAt=new Date().toISOString();if(parsed.status==='PARSED'){after.fields.push(...parsed.rows.map((r:any)=>normalizeField({...r,id:uid('fact'),sourceId:source.id,sourceVersion:source.version,sourceHash:source.hash,product:r.product||after.product,revision:1,at:new Date().toISOString(),extractionMode:parsed.evidenceMode})));source.status='PARSED';source.failure=null;checkState(after);result={count:parsed.rows.length};}else{source.status='NEEDS_REVIEW';source.failure=parsed.failure?.message||parsed.failure||'The original requires controlled manual verification.';result={state:'HOLD',failure:source.failure};}audit(after,{id:u.userId,role:ws.role,traceId:uid('run')},'documentExtract',source.id,{parser:source.parser,sourceHash:source.hash,state:source.status,count:parsed.rows.length});after.version++;
 }else if(input.action==='visionExtract'){
 if(!actorCan(ws.role,'extract'))throw new ForgeError('FORBIDDEN','Extraction permission required.',403);if(input.expectedVersion!==ws.state.version)throw new ForgeError('STALE_REVISION','Source workspace changed.',409);if(input.providerPermission!==true)throw new ForgeError('PROVIDER_PERMISSION_REQUIRED','Explicit permission is required before transmitting source bytes to the document provider.',403);
 after=structuredClone(ws.state);const source=after.sources.find((x:any)=>x.id===input.id);if(!source||!source.objectKey||!['application/pdf','image/png','image/jpeg'].includes(source.type))throw new ForgeError('ORIGINAL_REQUIRED','A stored supported original is required.',409);if(source.status==='PARSED'||source.status==='SUPERSEDED')throw new ForgeError('INVALID_STATE','Source is already parsed or superseded.',409);const job:any={id:uid('job'),role:'A2',inputRevision:after.version,status:'RUNNING',attempts:1,traceId:uid('run'),at:new Date().toISOString()};
 try{const original=await env.BUCKET?.get(source.objectKey);if(!original)throw new ForgeError('SOURCE_FAILED','Stored original unavailable.',503);const bytes=await original.arrayBuffer();if(await hash(bytes)!==source.hash)throw new ForgeError('SOURCE_HASH_MISMATCH','Original bytes fail the recorded hash.',409);const candidate=await inferDocument(bytes,source,{...providerConfig(env),model:providerConfig(env).visionModel,operationId:key});after.fields.push(...candidate.fields.map((f:any)=>({...normalizeField({id:uid('fact'),parameter:f.parameter.toLowerCase(),rawValue:f.rawValue,rawUnit:f.unit,method:f.method,batch:f.batch||'UNSPECIFIED',basis:f.basis,low:f.low,high:f.high,condition:'',sourceId:source.id,sourceVersion:source.version,sourceHash:source.hash,product:after.product,revision:1,at:new Date().toISOString(),span:{page:f.page,bbox:f.bbox,raw:f.rawQuote,path:'vision-candidate',offsetKind:'normalized page region'},extractionMode:'VISION_CANDIDATE',confidence:f.confidence,modelVersion:candidate.model,promptHash:candidate.promptHash}),status:'NEEDS_REVIEW'})));source.status='PARSED';source.parser=candidate.principal;source.modelVersion=candidate.model;source.extractedAt=new Date().toISOString();after.agentRuns.push(candidate);job.status='HUMAN_REVIEW_REQUIRED';checkState(after);result={count:candidate.fields.length,state:job.status};
 }catch(e:any){Object.assign(job,runtimeFailure(e));source.status='NEEDS_REVIEW';source.failure=e.message;result={state:job.status,failure:e.message};}
 after.jobs.push(job);audit(after,{id:u.userId,role:ws.role,traceId:job.traceId},'visionExtract',source.id,{state:job.status,sourceHash:source.hash});after.version++;
 }else{
 if(input.action==='export'&&input.finalize){const factor=await database().prepare('SELECT encrypted_secret,last_counter,confirmed FROM signature_factors WHERE id=?').bind(u.userId).first<{encrypted_secret:string;last_counter:number;confirmed:number}>();if(!factor?.confirmed)throw new ForgeError('SIGNATURE_REQUIRED','Enroll and confirm your authenticator before finalization.',409);const secret=await decryptSecret(factor.encrypted_secret,(env as any).FORGE_SIGNING_KEY),counter=await verifyTOTP(secret,input.code,factor.last_counter);const d=ws.state.drafts.find((x:any)=>x.id===input.id);if(!d)throw new ForgeError('NOT_FOUND','Draft unavailable.',404);input.verifiedSignature=await signatureRecord(u.userId,ws.role,input.signatureReason,signaturePayload(ws.state,d));const consumed=await database().prepare('UPDATE signature_factors SET last_counter=? WHERE id=? AND last_counter<?').bind(counter,u.userId,counter).run();if(!consumed.meta.changes)throw new ForgeError('OTP_REPLAY','Authenticator code already used.',409);
 }else delete input.verifiedSignature;
 if(input.action==='intake'){if(!['application/json','text/csv','text/plain'].includes(input.type))throw new ForgeError('USE_UPLOAD','Binary originals must use the permission-controlled file upload endpoint.');input.hash=await hash(input.text||'');delete input.objectKey;}if(input.action==='change'){delete input.hash;delete input.objectKey;}const r=await command(ws.state,input,{id:u.userId,role:ws.role,traceId:uid('run')});after=r.state;result=r.result;}
 await commitWorkspace(id,ws.state,after,u.userId,ws.role,key,digest,result,undefined,mergeAuthorities);return json({state:after,result});
 }catch(e){return error(e);}}
