'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {GitBranch,ArrowRight,Plus,ShieldCheck} from 'lucide-react';
import {branchOverview} from '../lib/branches.mjs';
import {effectiveStatus} from '../lib/lifecycle.mjs';
import {Status} from './ActionDialog';
type Props={state:any;role:string;userId:string;busy:boolean;act:(input:any)=>Promise<any>;form:(title:string,fields:any[],submit:(values:any)=>Promise<void>,description?:string,consent?:boolean,button?:string)=>void;inspect:(title:string,body:ReactNode)=>void;openSource:(source:any)=>void};
export default function BranchesPanel({state,role,userId,busy,act,form,inspect,openSource}:Props){
 const [report,setReport]=useState<any>({records:[]});
 useEffect(()=>{let cancelled=false;branchOverview(state).then(r=>{if(!cancelled)setReport(r);});return()=>{cancelled=true;};},[state]);
 const author=['owner','admin','author'].includes(role),reviewer=['owner','reviewer','approver'].includes(role);
 const drafts=state.drafts.filter((d:any)=>!['STALE','REJECTED'].includes(d.status)),rules=(state.ext?.lifecycle?.rules||[]).filter((r:any)=>!['STALE','REJECTED'].includes(effectiveStatus(structuredClone(state),r.id)));
 const start=(kind:string)=>{const targets=kind==='DRAFT'?drafts:rules;if(!targets.length){inspect('Current branch base required',<p>Create a source-backed draft or lifecycle rule with current evidence before branching.</p>);return;}form('Create an isolated '+kind.toLowerCase()+' branch',[{name:'targetId',label:'Exact base object',options:targets.map((x:any)=>({value:x.id,label:`${x.title||x.label} · revision ${x.revision} · ${x.id}`}))},{name:'name',label:'Branch name'},{name:'reason',label:'Why is this change needed?',type:'textarea'}],async v=>{await act({action:'branch',operation:'create',kind,...v});},'The current base revision and evidence are pinned. A source or base change blocks merge. The branch cannot change approved content automatically.',true,'Create controlled branch');};
 const action=(b:any,operation:string,extra:any={})=>form(operation==='merge'?'Merge reviewed proposal as a new candidate':operation==='submit'?'Submit this exact proposal for review':'Abandon this branch',[{name:'reason',label:'Action reason',type:'textarea'}],async v=>{await act({action:'branch',operation,id:b.id,revision:b.revision,digest:b.digest,...extra,...v});},operation==='merge'?'An independent approval of the exact proposal is required. Merge invalidates prior draft approval and requires fresh scientific review; release remains false.':'The operation binds this exact branch revision and is retained in audit history.',true);
 return <div className="stack"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">CONTROLLED PROPOSALS</span><h3>Change in isolation. Review before merge.</h3></div><GitBranch size={27}/></div><p>Draft and rule proposals preserve the base, source references and every candidate revision. A changed source blocks merge. Independent review authorizes only this proposal; the merged content still needs its own approval.</p><div className="row-actions"><button className="button small" disabled={!author||busy} onClick={()=>start('DRAFT')}><Plus size={15}/> Branch a draft</button><button className="button small secondary" disabled={!author||busy} onClick={()=>start('RULE')}><Plus size={15}/> Branch a rule</button></div></section>
 {!report.records.length&&<section className="panel"><h3>No controlled branches yet.</h3><p>Use a current draft or lifecycle rule as the exact base for your first proposal.</p></section>}
 {report.records.slice().reverse().map((b:any)=>{const editable=author&&b.createdBy===userId&&['WORKING','NEEDS_REVIEW','REJECTED','APPROVED'].includes(b.effectiveStatus),open=!['MERGED','ABANDONED','STALE'].includes(b.effectiveStatus);return <article className="panel" key={b.id}><div className="panel-heading"><div><span className="eyebrow">{b.kind} · BASE REVISION {b.baseRevision}</span><h3>{b.name}</h3><small className="mono">{b.id} · proposal {b.revision}</small></div><Status value={b.effectiveStatus}/></div>{b.problem&&<p className="callout">{b.problem.message}</p>}<div className="branch-comparison"><section><span className="eyebrow">PRESERVED BASE</span><h4>{b.base.title||b.base.label}</h4>{b.kind==='DRAFT'?b.base.statements.map((s:any)=><p className="statement" key={s.id}>{s.text}</p>):<pre>{JSON.stringify(b.base,null,2)}</pre>}</section><section><span className="eyebrow">ISOLATED PROPOSAL</span><h4>{b.candidate.title||b.candidate.label}</h4>{b.kind==='DRAFT'?b.candidate.statements.map((s:any)=><div key={s.id}><p className="statement">{s.text}</p>{editable&&<button className="inline-link" onClick={()=>form('Revise proposed statement',[{name:'text',label:'Candidate statement',value:s.text,type:'textarea'},{name:'reason',label:'Revision reason',type:'textarea'}],async v=>{await act({action:'branch',operation:'update',id:b.id,revision:b.revision,digest:b.digest,statementId:s.id,...v});},'Values, units, field IDs and citations remain bound to the preserved evidence. Revision invalidates any prior proposal approval.',true)}>Edit proposal</button>}</div>):<><pre>{JSON.stringify(b.candidate,null,2)}</pre>{editable&&<button className="inline-link" onClick={()=>form('Revise typed rule proposal',[{name:'candidate',label:'Complete rule proposal JSON',value:JSON.stringify(b.candidate,null,2),type:'textarea',maxLength:50000},{name:'reason',label:'Revision reason',type:'textarea'}],async v=>{let candidate;try{candidate=JSON.parse(v.candidate);}catch{throw Error('Use valid rule JSON.');}await act({action:'branch',operation:'update',id:b.id,revision:b.revision,digest:b.digest,candidate,reason:v.reason});},'Only the typed declarative rule schema and exact source-supported selectors are accepted. Script/code execution and invented categories are blocked.',true)}>Edit typed proposal</button>}</>}</section></div>
 {b.review&&<p className="subnote"><ShieldCheck size={14}/> {b.review.choice.replaceAll('_',' ')} by {b.review.reviewer} · exact proposal {b.review.revision} · {b.review.reason}</p>}
 {b.mergedTarget&&<p className="callout">Merged as {b.mergedTarget.id}, revision {b.mergedTarget.revision}. Status: CANDIDATE. Open drafts or lifecycle rules for fresh approval.</p>}
 <div className="row-actions">{b.evidencePins.sources.map((pin:any)=>{const source=state.sources.find((s:any)=>s.id===pin.id);return source?<button key={pin.id} className="inline-link" onClick={()=>openSource(source)}>Inspect {source.name} · v{pin.version}</button>:null;})}</div>
 <div className="row-actions">{editable&&b.status==='WORKING'&&<button className="button small" disabled={busy} onClick={()=>action(b,'submit')}>Submit exact proposal <ArrowRight size={15}/></button>}{reviewer&&open&&!b.contributors.includes(userId)&&['WAITING_HUMAN_REVIEW','APPROVED'].includes(b.status)&&<button className="button small secondary" disabled={busy} onClick={()=>form('Independently review exact proposal',[{name:'choice',label:'Review outcome',options:['APPROVE','REQUEST_EVIDENCE','REJECT']},{name:'reason',label:'Source and proposal review reason',type:'textarea'}],async v=>{await act({action:'branch',operation:'review',id:b.id,revision:b.revision,digest:b.digest,...v});},'Review the side-by-side content, evidence pins, technical QC and exact digest. Your decision applies only to this proposal.',true)}>Review proposal</button>}{author&&b.effectiveStatus==='APPROVED'&&<button className="button small" disabled={busy} onClick={()=>action(b,'merge')}>Merge as candidate</button>}{author&&['MERGED','ABANDONED'].every(s=>s!==b.status)&&(b.createdBy===userId||role==='owner')&&<button className="button small secondary" disabled={busy} onClick={()=>action(b,'abandon')}>Abandon</button>}<button className="inline-link" onClick={()=>inspect('Exact branch evidence and preserved revisions',<pre>{JSON.stringify(b,null,2)}</pre>)}>Inspect pins & history</button></div></article>;})}</div>;
}
