'use client';
import {useCallback,useEffect,useState} from 'react';
import {Plus,RefreshCw,MessageSquare,LockKeyhole,ArrowUpRight} from 'lucide-react';
type Props={workspaceId:string;demo?:boolean;version?:number;form:any;inspect:any;refresh?:()=>Promise<void>};
export default function CollaborationPanel({workspaceId,demo=false,version,form,inspect,refresh}:Props){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const read=useCallback(async()=>{if(demo||!workspaceId)return;try{const r=await fetch(`/api/sharing?workspace=${encodeURIComponent(workspaceId)}`),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e:any){setError(e.message);}},[workspaceId,demo]);useEffect(()=>{read();},[read,version]);
 async function write(input:any){setBusy(true);try{const r=await fetch('/api/sharing',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({workspaceId,expectedVersion:data.workspaceVersion,...input})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await read();await refresh?.();return d;}catch(e:any){setError(e.message);throw e;}finally{setBusy(false);}}
 function grant(o:any){form(`Share ${o.title}`,[{name:'granteeId',label:'Verified platform user ID'},{name:'permissions',label:'Exact-object permissions',options:['view','view,comment','view,comment,requestReview']},{name:'allowOriginal',label:'Original file access (source only)',options:o.type==='source'?['false','true']:['false']},{name:'permissionBasis',label:'Your authority / source permission to share',type:'textarea'},{name:'reason',label:'Specific collaboration purpose',type:'textarea'},{name:'expiresAt',label:'Access expires',type:'datetime-local',value:new Date(Date.now()+7*86400000).toISOString().slice(0,16)}],async(v:any)=>{await write({action:'grant',objectType:o.type,objectId:o.id,objectRevision:o.objectRevision,...v,permissions:v.permissions.split(','),allowOriginal:v.allowOriginal==='true',permissionConfirmed:true,expiresAt:new Date(v.expiresAt).toISOString()});},'The grantee needs access to this private Site separately. This grants only the selected revision. Field/draft access does not automatically reveal source originals or confer review authority.',true,'Grant selected access');}
 function note(o:any,action:string){form(action==='note'?'Add a shared note':'Request internal review',[{name:'body',label:'Evidence-based note (no personal identifiers)',type:'textarea'}],async(v:any)=>{await write({action,objectType:o.type,objectId:o.id,objectRevision:o.objectRevision,...v});},'A shared note or request is routed to authorized people. It cannot approve, change a scientific fact or close an action.',true,'Record note');}
 if(demo)return <section className="panel"><h3>Scoped partner collaboration</h3><p>Exact-object grants, notes, expiry and revocation are available in an authenticated persistent workspace.</p><a className="button small" href="/app?view=collaboration">Open collaboration <ArrowUpRight size={15}/></a></section>;
 return <div className="stack"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">CONTROLLED SHARING</span><h3>Share evidence with a clear boundary.</h3></div><button className="button small secondary" onClick={read} disabled={busy}><RefreshCw size={14}/> Refresh</button></div><p>Specific object. Exact revision. Recorded permission. Expiring access. Granting access creates no scientific authority.</p><div className="row-actions"><a className="button small secondary" href="/collaboration"><LockKeyhole size={14}/> Open partner portal</a><button className="inline-link" onClick={()=>inspect('Your platform identity',<p className="mono">The partner portal displays your signed-in platform user ID for verified access setup.</p>)}>How to identify a partner</button></div>{error&&<p className="error-banner" role="alert">{error}</p>}</section>
 {data?.canManage&&<><section className="panel"><h3>Available current evidence</h3><p className="subnote">Only records passing source permission, provenance and revision checks are offered.</p><div className="source-selection">{data.shareableObjects.map((o:any)=><div key={`${o.type}:${o.id}`}><span><strong>{o.title}</strong><small>{o.type} · {o.id} · {o.status}</small></span><button className="button small secondary" onClick={()=>grant(o)} disabled={busy}><Plus size={14}/> Grant access</button><button className="inline-link" onClick={()=>note(o,'note')}>Add note</button></div>)}</div>{!data.shareableObjects.length&&<p>No current evidence eligible for sharing. Add source evidence first.</p>}</section><section className="panel"><h3>Granted access & revocations</h3>{data.grants.map((g:any)=><div className="agent-run" key={g.id}><div><strong>{g.objectType} · {g.objectId}</strong><small>{g.granteeId} · {g.permissions.join(', ')} · {g.status}</small><small>Expires {new Date(g.expiresAt).toLocaleString()} · original {g.allowOriginal?'permitted':'restricted'}</small></div><button className="inline-link" onClick={()=>inspect('Exact grant evidence',<pre>{JSON.stringify(g,null,2)}</pre>)}>Inspect</button>{g.status==='ACTIVE'&&<button className="button small secondary" disabled={busy} onClick={()=>form('Revoke exact-object access',[{name:'reason',label:'Recorded reason',type:'textarea'}],async(v:any)=>{await write({action:'revoke',grantId:g.id,grantRevision:g.revision,...v});},'Revocation prevents new reads and writes through this grant.',true,'Revoke access')}>Revoke</button>}</div>)}</section></>}
 {data?.items?.map((o:any)=><article className="panel" key={`${o.type}:${o.id}`}><div className="panel-heading"><div><span className="eyebrow">{o.type} · {o.status}</span><h3>{o.title}</h3></div><LockKeyhole size={20}/></div><button className="inline-link" onClick={()=>inspect('Permitted object projection',<pre>{JSON.stringify(o,null,2)}</pre>)}>Inspect permitted evidence</button><p className="subnote">Access expires {new Date(o.expiresAt).toLocaleString()}. Hidden dependencies stay redacted.</p><div className="row-actions">{o.originalAvailable&&<button className="button small secondary" onClick={()=>form('Open permitted original',[],async()=>{window.open(o.originalPath,'_blank','noopener,noreferrer');},'This opens only the expressly granted current source original.',true,'Open original')}>Open original <ArrowUpRight size={14}/></button>}{o.permissions.includes('comment')&&<button className="button small secondary" onClick={()=>note(o,'note')}><MessageSquare size={14}/> Add note</button>}{o.permissions.includes('requestReview')&&<button className="button small secondary" onClick={()=>note(o,'requestReview')}>Request review</button>}</div>{o.notes?.map((n:any)=><div className="memory-row" key={n.id}><strong>{n.kind} · {n.status}</strong><p>{n.body}</p><small>{n.author} · {new Date(n.at).toLocaleString()}</small></div>)}</article>)}
 {data?.canReview&&<section className="panel"><h3>Requested internal reviews</h3>{data.reviewRequests.map((n:any)=><div className="memory-row" key={n.id}><strong>{n.objectType} · {n.status}{n.stale?' · stale':''}</strong><p>{n.body}</p>{n.status==='OPEN'&&!n.stale&&<button className="button small secondary" disabled={busy} onClick={()=>form('Resolve the review request',[{name:'reason',label:'Resolution reason',type:'textarea'}],async(v:any)=>{await write({action:'resolveNote',noteId:n.id,objectRevision:n.objectRevision,...v});},'Resolving the request grants no scientific approval. Record the actual review in the controlled review queue.',true,'Resolve request')}>Resolve request</button>}</div>)}{!data.reviewRequests.length&&<p>No review requests.</p>}</section>}
 </div>;
}
