'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {X,ArrowLeft,ArrowRight,ArrowUpRight,Maximize2,Network,Search,ChevronLeft,ChevronRight} from 'lucide-react';
import {dependencyGraph} from '../lib/core.mjs';
import {GROUPS,graphGroup,radialProjection} from '../lib/visual-projections.mjs';
import {Status} from './ActionDialog';
function useGraphCamera(target:number[],dragging:boolean){
 const element=useRef<SVGSVGElement>(null),current=useRef(target);
 useEffect(()=>{let frame=0;const start=current.current,at=performance.now();if(dragging||matchMedia('(prefers-reduced-motion: reduce)').matches){current.current=target;element.current?.setAttribute('viewBox',target.join(' '));return;}const move=(now:number)=>{const t=Math.min(1,(now-at)/320),e=1-Math.pow(1-t,3);current.current=start.map((n,i)=>n+(target[i]-n)*e);element.current?.setAttribute('viewBox',current.current.join(' '));if(t<1)frame=requestAnimationFrame(move);};frame=requestAnimationFrame(move);return()=>cancelAnimationFrame(frame);},[target[0],target[1],target[2],target[3],dragging]);
 return element;
}
export default function EvidenceGraph({state,inspect,original,initialSelected}:{state:any;inspect:any;original:(source:any)=>void;initialSelected?:string|null}){
 const [selected,setSelected]=useState<string|null>(initialSelected||null),[history,setHistory]=useState<string[]>([]),[zoom,setZoom]=useState(1),[search,setSearch]=useState(''),[mode,setMode]=useState('radial'),[group,setGroup]=useState<string|null>(null),[page,setPage]=useState(0),[pan,setPan]=useState({x:0,y:0}),[focus,setFocus]=useState(false);
 const drag=useRef<any>(null),inspector=useRef<HTMLElement>(null);
 const {graph,records}=useMemo(()=>{const graph=dependencyGraph(state),records=new Map();for(const x of [...state.sources,...state.fields,...state.drafts,...state.decisions,...state.exports,...(state.queries||[]),...(state.actions||[]),...Object.values(state.ext?.lifecycle||{}).filter(Array.isArray).flat()] as any[])if(x?.id)records.set(x.id,x);return {graph,records};},[state]);
 useEffect(()=>{if(selected&&!graph.nodes.some((n:any)=>n.id===selected)){setSelected(null);setFocus(false);}},[graph,selected]);
 const projection=useMemo(()=>radialProjection(graph,{group,page,selected}),[graph,group,page,selected]),node=graph.nodes.find((n:any)=>n.id===selected),record=records.get(selected),links=graph.edges.filter((e:any)=>e.from===selected||e.to===selected);
 const source=state.sources.find((s:any)=>s.id===(node?.type==='source'?selected:record?.sourceId||record?.citations?.[0]?.sourceId||record?.sourceIds?.[0]));
 const positions=mode==='radial'?projection.positions:new Map(projection.visible.map((n:any)=>{const i=GROUPS.findIndex(g=>g.id===graphGroup(n.type)),same=projection.visible.filter((p:any)=>graphGroup(p.type)===graphGroup(n.type)),j=same.findIndex((p:any)=>p.id===n.id);return [n.id,{x:120+i*140,y:165+j*68,group:graphGroup(n.type)}];}));
 const point=selected?positions.get(selected):null,w=(focus?680:940)/zoom,h=(focus?470:640)/zoom,vx=(focus&&point?point.x-w/2:(940-w)/2)+pan.x,vy=(focus&&point?point.y-h/2:(640-h)/2)+pan.y;
 const camera=useGraphCamera([vx,vy,w,h],Boolean(drag.current));
 function pick(id:string){if(selected&&id!==selected)setHistory([...history,selected]);const n=graph.nodes.find((n:any)=>n.id===id);if(n){const kind=graphGroup(n.type),index=graph.nodes.filter((n:any)=>graphGroup(n.type)===kind).findIndex((n:any)=>n.id===id);setGroup(kind);setPage(Math.floor(index/6));}setSelected(id);setFocus(true);setPan({x:0,y:0});}
 function overview(){setSelected(null);setHistory([]);setFocus(false);setZoom(1);setPan({x:0,y:0});}
 function back(){if(history.length){setSelected(history[history.length-1]);setHistory(history.slice(0,-1));setPan({x:0,y:0});}else overview();}
 const related=links.map((e:any)=>graph.nodes.find((n:any)=>n.id===(e.from===selected?e.to:e.from))).filter(Boolean),chosenGroup=projection.groups.find(g=>g.id===group);
 return <div className="qgen-explorer">
  <div className="qgen-toolbar"><div className="qgen-view-tabs"><button aria-pressed={mode==='radial'} onClick={()=>{setMode('radial');setPan({x:0,y:0});setFocus(false);}}>Evidence network</button><button aria-pressed={mode==='pathway'} onClick={()=>{setMode('pathway');setPan({x:0,y:0});setFocus(false);}}>Pathway</button></div><div className="qgen-tools"><button className="icon-button" onClick={back} aria-label="Back to previous node or overview" disabled={!selected}><ArrowLeft size={17}/></button><button className="icon-button" onClick={overview} aria-label="Fit graph overview"><Maximize2 size={17}/></button><label>Zoom <input aria-label="Graph zoom" type="range" min=".7" max="1.6" step=".1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label></div></div>
  <div className={`qgen-stage ${node?'with-detail':''}`}><div className="qgen-canvas"><div className="qgen-grid" aria-hidden="true"/>
   {graph.nodes.length?<svg ref={camera} viewBox="0 0 940 640" role="group" aria-label="Saved evidence network. Select nodes or use the searchable record list below." onPointerDown={e=>{if((e.target as Element).closest('[data-node]'))return;drag.current={x:e.clientX,y:e.clientY,pan};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const r=e.currentTarget.getBoundingClientRect();setPan({x:drag.current.pan.x-(e.clientX-drag.current.x)*w/r.width,y:drag.current.pan.y-(e.clientY-drag.current.y)*h/r.height});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
    <defs><radialGradient id="qgen-volume"><stop stopColor="#0b2422" stopOpacity=".04"/><stop offset=".74" stopColor="#1b8274" stopOpacity=".09"/><stop offset=".94" stopColor="#3d9e8e" stopOpacity=".23"/><stop offset="1" stopColor="#193d38" stopOpacity=".02"/></radialGradient><filter id="qgen-node-glow"><feGaussianBlur stdDeviation="4"/></filter></defs>
    <circle cx="470" cy="320" r="286" fill="url(#qgen-volume)" stroke="#286b62" strokeOpacity=".25"/>
    {mode==='radial'&&<g className="qgen-core" aria-hidden="true">{Array.from({length:9},(_,i)=><path key={i} d={`M${414+i*12} ${266+i%3*8} C${530-i*12} ${284-i%2*14} ${400+i*9} ${330+i%2*22} ${501-i*8} 364 S${470+i*8} 386 ${417+i*9} 349`} fill="none" stroke={GROUPS[i%6].color} strokeOpacity=".65" strokeWidth={i%2?2:3}/>)}</g>}
    {mode==='radial'&&projection.groups.map(g=>{const hub=projection.hubs.get(g.id);return <g key={g.id}><path d={`M470 320Q${470+(hub.x-470)*.45-28} ${320+(hub.y-320)*.45+25} ${hub.x} ${hub.y}`} fill="none" stroke={g.color} strokeOpacity=".2" strokeWidth="1.3"/>{projection.visible.filter((n:any)=>graphGroup(n.type)===g.id).map((n:any)=>{const p=positions.get(n.id);return <line key={n.id} x1={hub.x} y1={hub.y} x2={p.x} y2={p.y} stroke={g.color} strokeOpacity=".4"/>;})}<g data-node="group" role="button" tabIndex={0} aria-label={`${g.label}: ${g.nodes.length} saved records. Show this group.`} onClick={()=>{setGroup(g.id);setPage(0);setFocus(false);setPan({x:0,y:0});}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setGroup(g.id);setPage(0);setFocus(false);}}} className="qgen-hub"><circle cx={hub.x} cy={hub.y} r="31" fill={g.color} opacity=".28" filter="url(#qgen-node-glow)"/><path d={`M${hub.x} ${hub.y-26}L${hub.x+23} ${hub.y-13}V${hub.y+13}L${hub.x} ${hub.y+26}L${hub.x-23} ${hub.y+13}V${hub.y-13}Z`} fill="#192c2d" stroke={g.color} strokeWidth="1.6"/><text x={hub.x} y={hub.y+6} textAnchor="middle" fill={g.color}>{g.nodes.length}</text><text x={hub.x} y={hub.y-41} textAnchor="middle" className="qgen-hub-label">{g.label}</text></g></g>;})}
    {mode==='pathway'&&GROUPS.map((g,i)=><g key={g.id}><text x={120+i*140} y="84" textAnchor="middle" className="qgen-hub-label">{g.label}</text><line x1={120+i*140} y1="110" x2={120+i*140} y2="550" stroke={g.color} strokeOpacity=".13"/></g>)}
    {graph.edges.map((e:any,i:number)=>{const a=positions.get(e.from),b=positions.get(e.to);if(!a||!b)return null;const active=selected===e.from||selected===e.to;return <path key={`${e.from}-${e.to}-${i}`} d={`M${a.x} ${a.y}Q${(a.x+b.x)/2-20} ${(a.y+b.y)/2+35} ${b.x} ${b.y}`} fill="none" stroke={active?'#b1eee1':'#65a99d'} strokeWidth={active?2:1} strokeDasharray={e.dependency===false?'4 5':undefined} opacity={selected && !active ? .12 : active ? .95 : .28}><title>{e.reason}</title></path>;})}
    {projection.visible.map((n:any)=>{const p=positions.get(n.id),g=GROUPS.find(g=>g.id===graphGroup(n.type))!,active=selected===n.id;return <g key={n.id} data-node="record" role="button" tabIndex={0} aria-label={`${n.type}: ${n.label}. ${n.status}`} aria-pressed={active} onClick={()=>pick(n.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick(n.id);}}} className={`qgen-record ${active?'selected':''}`}><circle cx={p.x} cy={p.y} r={active?17:13} fill={g.color} opacity=".24" filter="url(#qgen-node-glow)"/><circle cx={p.x} cy={p.y} r={active?9:6.5} fill="#284846" stroke={g.color} strokeWidth={active?2.8:1.8}/>{active&&<circle cx={p.x} cy={p.y} r="17" fill="none" stroke={g.color} strokeOpacity=".65"/>}<text x={p.x+(p.x>470?14:-14)} y={p.y+4} textAnchor={p.x>470?'start':'end'} className="qgen-node-label">{n.label.length>16?n.label.slice(0,15)+'…':n.label}</text><title>{n.label} · {n.status} · {n.id}</title></g>;})}
   </svg>:<div className="qgen-empty"><Network size={35}/><h3>The network begins with your source.</h3><p>Save an original and extract its facts to create real evidence relationships.</p></div>}
   <div className="qgen-canvas-caption"><span>REV {state.version} · {graph.nodes.length} SAVED NODES · {graph.edges.length} RELATIONSHIPS</span><span>Radial spokes group records. Cross-links are saved dependencies.</span></div>
  </div>{node&&<aside className="qgen-inspector" ref={inspector} aria-label="Selected node details"><div className="qgen-detail-top"><button className="inline-link" onClick={back}><ArrowLeft size={14}/> Back</button><button className="icon-button" onClick={overview} aria-label="Close node details"><X size={18}/></button></div><span className="eyebrow">{node.type} / SAVED RECORD</span><h2>{node.label}</h2><Status value={node.status||'UNKNOWN'}/><p className="mono qgen-id">{node.id}</p><dl className="qgen-facts"><dt>Revision</dt><dd>{record?.revision??record?.version??'Recorded'}</dd>{record?.sourceVersion&&<><dt>Source version</dt><dd>{record.sourceVersion}</dd></>}{record?.rawValue!==undefined&&<><dt>Raw source value</dt><dd>{String(record.rawValue)} {record.rawUnit}</dd><dt>Candidate</dt><dd>{record.value??'MISSING'} {record.unit}</dd><dt>Method / batch</dt><dd>{record.method||'MISSING'} / {record.batch||'MISSING'}</dd></>}{record?.span&&<><dt>Exact location</dt><dd>{record.span.bbox?`Page ${record.span.page}`:`Line ${record.span.line??'—'} · row ${record.span.row??'—'}`}<small>{record.span.path}</small></dd></>}</dl>{record?.span?.raw&&<pre className="qgen-source-span">{record.span.raw}</pre>}{source&&<button className="button secondary" onClick={()=>original(source)}>Open original evidence <ArrowUpRight size={15}/></button>}<h3>Linked records <span>{links.length}</span></h3><div className="qgen-linked-records">{links.map((e:any,i:number)=>{const other=graph.nodes.find((n:any)=>n.id===(e.from===selected?e.to:e.from));return other?<button key={i} onClick={()=>pick(other.id)}><span><strong>{other.label}</strong><small>{e.reason}</small></span><ArrowRight size={14}/></button>:null;})}</div><button className="inline-link" onClick={()=>inspect(node.label,<pre>{JSON.stringify(record,null,2)}</pre>)}>Inspect complete saved record <ArrowUpRight size={14}/></button></aside>}</div>
  <div className="qgen-record-toolbar"><label className="search-field"><Search size={16}/><input aria-label="Search saved graph records" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find name, ID or status…"/></label><select aria-label="Filter record group" value={group||''} onChange={e=>{setGroup(e.target.value||null);setPage(0);}}><option value="">All record groups</option>{GROUPS.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select>{chosenGroup&&chosenGroup.pages>1&&<div className="qgen-page-controls"><button className="icon-button" disabled={page===0} onClick={()=>{setPage(page-1);setSelected(null);setFocus(false);}} aria-label="Previous graph records"><ChevronLeft size={17}/></button><span>{page+1}/{chosenGroup.pages}</span><button className="icon-button" disabled={page+1>=chosenGroup.pages} onClick={()=>{setPage(page+1);setSelected(null);setFocus(false);}} aria-label="Next graph records"><ChevronRight size={17}/></button></div>}</div>
  <div className="qgen-bottom-tables"><section><div className="qgen-table-heading"><h3>Saved evidence records</h3><span>{graph.nodes.filter((n:any)=>!group||graphGroup(n.type)===group).length} records</span></div><div className="table-scroll"><table><thead><tr><th>Record</th><th>Type</th><th>Status</th><th>Open</th></tr></thead><tbody>{graph.nodes.filter((n:any)=>(!group||graphGroup(n.type)===group)&&`${n.label} ${n.id} ${n.status}`.toLowerCase().includes(search.toLowerCase())).map((n:any)=><tr key={n.id} className={selected===n.id?'current':''}><td><strong>{n.label}</strong><small className="mono">{n.id}</small></td><td>{n.type}</td><td><Status value={n.status||'UNKNOWN'}/></td><td><button className="icon-button" onClick={()=>pick(n.id)} aria-label={`Select ${n.label}`}><ArrowUpRight size={16}/></button></td></tr>)}</tbody></table></div></section><section><div className="qgen-table-heading"><h3>{node?'Connected evidence':'Network summary'}</h3><span>{node?links.length:'6'} {node?'links':'groups'}</span></div><div className="table-scroll"><table><thead><tr><th>{node?'Record':'Group'}</th><th>{node?'State':'Count'}</th></tr></thead><tbody>{node?related.map((n:any,i:number)=><tr key={`${n.id}-${i}`}><td><button className="inline-link" onClick={()=>pick(n.id)}>{n.label}<ArrowUpRight size={13}/></button></td><td><Status value={n.status||'UNKNOWN'}/></td></tr>):projection.groups.map(g=><tr key={g.id}><td><button className="inline-link" onClick={()=>{setGroup(g.id);setPage(0);}}><i className="graph-group-dot" style={{background:g.color}}/>{g.label}</button></td><td>{g.nodes.length}</td></tr>)}</tbody></table></div><p className="qgen-graph-note">Up to six records per group appear in the canvas. Page through a group or select any saved record in the full list. Counts and relationships reflect this saved revision.</p></section></div>
 </div>;
}
