'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,Check,ChevronRight,FileText,GitBranch,Layers,Plus,ShieldCheck,X} from 'lucide-react';
import {effectiveStatus,lifecycleProjection,hydrateLifecycle} from '../lib/lifecycle.mjs';

type Props={state:any;act:(action:string,data?:any)=>Promise<any>;form:any;refresh?:()=>void;role?:string;userId?:string;initialTab?:string};
type Option={value:string;label:string};
type Entry={name:string;label:string;kind?:'text'|'textarea'|'number'|'select'|'multi';options?:Option[];value?:any;optional?:boolean;note?:string};
type Editor={operation:string;title:string;description:string;entries:Entry[];evidence:boolean;citation:boolean;optionalEvidence?:boolean;predecessorId?:string;initial?:any};
const TABS=[['twin','CMC twin'],['controls','Rules & obligations'],['content','Controlled content'],['dossiers','Market dossiers'],['analysis','Scientific evidence'],['changes','Change & regression'],['queries','HA questions'],['closure','Closure & monitoring']];
const OPS=['ALL_APPROVED','NO_OPEN_CONFLICTS','HAS_SOURCE_CONTEXT','REQUIRED_PARAMETER','SOURCE_REVISION_CURRENT'];
const RELATIONS=['RAW_MATERIAL_TO_INTERMEDIATE','INTERMEDIATE_TO_BATCH','BATCH_TO_FINISHED_PRODUCT','PROCESS_STEP_TO_CPP','PROCESS_STEP_TO_CQA','USES_EQUIPMENT','AT_SITE','USES_MATERIAL','USES_METHOD','HAS_SPECIFICATION','PROCESS_STEP_TO_STEP'];
const nice=(v:any)=>String(v||'').replaceAll('_',' ').toLowerCase();
const comma=(v:any)=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
const select=(name:string,label:string,options:Option[],optional=false):Entry=>({name,label,kind:'select',options,optional});
const multi=(name:string,label:string,options:Option[],optional=false):Entry=>({name,label,kind:'multi',options,optional});
const txt=(name:string,label:string,value='',optional=false,note?:string):Entry=>({name,label,value,optional,note});
function StateTag({value}:{value:string}){return <span className={`status status-${String(value).toLowerCase().replaceAll('_','-')}`}>{nice(value)}</span>;}

export default function LifecyclePanel({state,act,form,refresh,role='viewer',userId='',initialTab='twin'}:Props){
 const [tab,setTab]=useState(initialTab),[editor,setEditor]=useState<Editor|null>(null),[inspection,setInspection]=useState<any>(null),[localError,setLocalError]=useState(''),[impactSource,setImpactSource]=useState('');
 const snapshot=useMemo(()=>{const s=structuredClone(state);hydrateLifecycle(s);return s;},[state]);
 const e=snapshot.ext.lifecycle;
 const current=(collection:string)=>e[collection].filter((x:any)=>!e[collection].some((y:any)=>y.logicalId===x.logicalId&&y.revision>x.revision)).map((x:any)=>({...x,collection,status:effectiveStatus(snapshot,x.id)}));
 const entities=current('entities'),records=Object.keys(e).filter(k=>Array.isArray(e[k])&&!['decisions','invalidations'].includes(k)).flatMap(current),approvedFacts=snapshot.fields.filter((f:any)=>f.status==='APPROVED'&&snapshot.sources.some((s:any)=>s.id===f.sourceId&&s.hash===f.sourceHash&&s.version===f.sourceVersion&&s.status==='PARSED'));
 const canAuthor=['owner','admin','author'].includes(role),canReview=['owner','reviewer','approver'].includes(role),labelOptions=(items:any[]):Option[]=>items.map(x=>({value:x.id,label:`${x.kind?nice(x.kind)+' · ':''}${x.label||x.title||x.name||x.parameter} · r${x.revision||x.version} · ${nice(x.status)}`}));
 const entityOptions=(kind?:string)=>labelOptions(entities.filter((x:any)=>x.status==='APPROVED'&&(!kind||x.kind===kind)));
 const options=(c:string,approved=true)=>labelOptions(current(c).filter((x:any)=>!approved||x.status==='APPROVED'));
 const sourceOptions=labelOptions(snapshot.sources),factOptions=approvedFacts.map((f:any)=>({value:f.id,label:`${f.parameter} · ${f.value} ${f.unit} · ${f.batch} · r${f.revision}`}));
 const p=(id:string,input:any={}):any=>lifecycleProjection(snapshot,id,input).data;
 const open=(op:string,predecessor?:any)=>{
  setLocalError('');let entries:Entry[]=[],title='',description='',evidence=true,citation=false,optionalEvidence=false;
  const label=txt('label','Record title'),market=txt('market','Recorded market / jurisdiction'),section=txt('section','CTD section','3.2.P',false,'Supported sections begin with 2.3.S/P or 3.2.S/P.');
  switch(op){
   case 'entity':title='Register a source-backed CMC entity';description='The object identity must occur in selected fact metadata or the cited original text. Properties come from approved facts.';entries=[select('kind','Entity type',['product','substance','site','material','process','method','specification','batch','equipment'].map(v=>({value:v,label:v}))),txt('label','Exact source-backed identity')];citation=false;break;
   case 'relation':title='Record a genealogy relationship';description='Link independently approved objects using an exact original excerpt. The relationship stays a human-reviewed recorded candidate.';entries=[select('relationType','Relationship',RELATIONS.map(v=>({value:v,label:nice(v)}))),select('fromId','From entity',entityOptions()),select('toId','To entity',entityOptions())];citation=true;break;
   case 'requirement':title='Map a source-backed obligation';description='Quote the original requirement. The exact jurisdiction and parameter must occur in this excerpt; a qualified human decides applicability.';entries=[label,txt('parameter','Required parameter'),market,txt('sections','CTD section mappings (comma separated)','3.2.P'),{name:'minCount',label:'Minimum distinct facts',kind:'number',value:1}];citation=true;optionalEvidence=true;break;
   case 'rule':title='Create a versioned control rule';description='Only bounded declarative operators run. Rule selectors and any classification category must be present in the quoted source.';entries=[label,select('kind','Rule purpose',['REQUIREMENT','CLASSIFICATION','WORKFLOW'].map(v=>({value:v,label:nice(v)}))),market,txt('parameters','Parameters (comma separated)'),select('operator','Control operator',OPS.map(v=>({value:v,label:nice(v)}))),{name:'count',label:'Required count (count operator only)',kind:'number',value:1},txt('category','Exact cited category (classification only)','',true),multi('requirementIds','Approved obligation mappings',options('requirements'),true)];citation=true;optionalEvidence=true;break;
   case 'template':title='Create a controlled display template';description='Style changes affect presentation; scientific text and evidence remain exact. This does not certify publishing conformance.';entries=[label,txt('sections','Covered CTD sections','3.2.P'),select('headingCase','Heading style',[{value:'SENTENCE',label:'Sentence case'},{value:'TITLE',label:'Title case'}]),select('density','Density',[{value:'TECHNICAL',label:'Technical'},{value:'COMPACT',label:'Compact'}]),select('referenceStyle','Citation display',[{value:'EXACT_SPAN',label:'Exact original span'},{value:'SOURCE_ID_AND_REVISION',label:'Source ID and revision'}]),select('factOrder','Fact ordering',['PARAMETER','BATCH','SOURCE'].map(v=>({value:v,label:nice(v)})))];citation=true;optionalEvidence=true;break;
   case 'contentBlock':title='Freeze approved draft content';description='Choose an exact approved draft with passing QC. Its statements are copied without scientific rewriting into a new controlled candidate.';entries=[label,select('draftId','Approved draft',labelOptions(snapshot.drafts.filter((d:any)=>d.status==='APPROVED'&&d.qc?.passed))),market];evidence=false;break;
   case 'reuseContent':title='Reuse exact approved content';description='Target market, section, template and requirements are independently tracked. Approval never transfers automatically.';entries=[select('blockId','Approved content block',options('blocks')),market,section,select('templateId','Approved display template',options('templates'),true),multi('requirementIds','Approved obligations',options('requirements'),true),{name:'reason',label:'Reuse rationale',kind:'textarea'}];evidence=false;break;
   case 'dossier':title='Create a product–market–dossier record';description='Map exact source facts and approved requirements to a controlled section. A supplied filing record is evidence only; regulator acceptance is not inferred.';entries=[label,select('productId','Approved product',entityOptions('product')),market,section,multi('requirementIds','Approved market obligations',options('requirements')),multi('blockIds','Approved content (optional)',[...options('blocks'),...options('reuses')],true),select('stateLabel','Record maturity',[{value:'DRAFT',label:'Draft dossier record'},{value:'RECORDED_FILING',label:'Supplied filing record'}])];citation=true;break;
   case 'stability':title='Add an observed stability time point';description='Use an approved time fact and measured facts for the same batch and recorded condition. Only observed descriptive trends are calculated.';entries=[label,select('batchId','Approved batch',entityOptions('batch')),select('timeFieldId','Approved numeric time fact',factOptions.filter((f:any)=>/time|duration|age/i.test(f.label)))];break;
   case 'comparability':title='Compare recorded scientific evidence';description='Descriptive results require matching product, parameter, method, unit, condition and basis. Equivalence and product disposition remain human decisions.';entries=[label,multi('batchIds','Approved batches',entityOptions('batch'),true),multi('processIds','Approved processes',entityOptions('process'),true),multi('stabilityIds','Approved observed time points',options('observations'),true),select('changeId','Approved change (optional)',options('changes'),true)];break;
   case 'transfer':title='Map a technology-transfer evidence stage';description='A map needs distinct approved sites, process and batch evidence. The stage token must occur in the cited original; no facility qualification is asserted.';entries=[label,select('stage','Recorded stage',['DEVELOPMENT','SCALE_UP','COMMERCIAL'].map(v=>({value:v,label:nice(v)}))),select('fromSiteId','From approved site',entityOptions('site')),select('toSiteId','To approved site',entityOptions('site')),multi('processIds','Approved processes',entityOptions('process')),multi('batchIds','Approved batches',entityOptions('batch')),select('comparabilityId','Approved comparison (optional)',options('comparabilities'),true)];citation=true;break;
   case 'marketChange':title='Connect a source change to a product';description='Changed parameters must have exact approved facts from the selected new source and product. A later classification uses separately approved jurisdiction rules.';entries=[label,select('productId','Approved product',entityOptions('product')),select('oldSourceId','Previous source',sourceOptions),select('newSourceId','Current changed source',sourceOptions),txt('changedParameters','Changed parameters (comma separated)')];break;
   case 'classify':title='Prepare a market classification candidate';description='The local rules must be approved and match the exact market. Unknown or contradictory categories remain HOLD or CONFLICT.';entries=[label,select('changeId','Approved change',options('changes')),market,multi('ruleIds','Approved classification rules',labelOptions(current('rules').filter((r:any)=>r.status==='APPROVED'&&r.kind==='CLASSIFICATION')))];evidence=false;break;
   case 'simulation':title='Simulate a source change on a separate branch';description='Compare a baseline approved fact with a current candidate for the same product and parameter. The live scientific state is not changed and no merge is automatic.';entries=[label,select('sourceId','Baseline source',sourceOptions),select('fromFieldId','Baseline approved fact',factOptions),select('toFieldId','Proposed replacement fact',labelOptions(snapshot.fields.filter((f:any)=>!['STALE','REJECTED','MISSING'].includes(f.status)).map((f:any)=>({...f,label:`${f.parameter} · ${f.value} ${f.unit} · ${f.batch}`})))),multi('ruleIds','Proposed stored rule branches',options('rules',false),true),{name:'reason',label:'Simulation rationale',kind:'textarea'}];evidence=false;break;
   case 'regression':title='Execute a recorded regression check';description='Run actual bounded rule and dossier checks. The result stores its numerator, denominator, individual evidence and engineering scope.';entries=[label,multi('ruleIds','Stored rules to test',options('rules',false),true),multi('dossierIds','Stored dossiers to test',options('dossiers',false),true),select('branchId','Simulation branch (optional)',options('branches',false),true)];evidence=false;break;
   case 'haq':title='Record an actual health-authority question';description='The complete question must occur in the cited original source. Response statements are prepared only from selected current approved facts.';entries=[label,{name:'title',label:'Exact original question',kind:'textarea'},market,multi('dossierIds','Approved dossier mappings',options('dossiers'),true),multi('requirementIds','Approved obligation mappings',options('requirements'),true)];citation=true;break;
   case 'haqOutcome':title='Record an evidenced question outcome';description='Quote the supplied outcome evidence. Only independently approved, current outcomes are admitted to governed memory; acceptance is never inferred.';entries=[label,select('haqId','Approved actual question',options('haqs')),select('outcome','Exact recorded outcome token',['RESPONDED','ACKNOWLEDGED','MORE_INFORMATION','CLOSED_REPORTED','REJECTED'].map(v=>({value:v,label:nice(v)})))];citation=true;break;
   case 'closure':title='Define an evidence-based closure action';description='Select exact expected and actual facts. An independent human verifier runs the controlled check; the action can reopen when source evidence changes.';entries=[label,txt('owner','Action owner principal',userId),select('checkOperator','Expected versus actual control',['EQUAL','CONTEXT_MATCH','WITHIN_RECORDED_LIMITS','CURRENT_APPROVED'].map(v=>({value:v,label:nice(v)}))),select('expectedFieldId','Expected approved fact',factOptions),select('actualFieldId','Actual approved fact',factOptions),multi('dependencyIds','Approved downstream dependencies',labelOptions(records.filter((r:any)=>r.status==='APPROVED')),true)];evidence=false;break;
   case 'correction':title='Propagate a controlled content correction';description='Choose a newer independently approved version in the same content lineage. Dependent reuse gets new candidate versions and no previous approval is inherited.';entries=[label,select('fromBlockId','Previous content version',labelOptions(e.blocks)),select('toBlockId','New approved content version',options('blocks')),multi('reuseIds','Latest affected reuse records',options('reuses',false)),{name:'reason',label:'Correction rationale',kind:'textarea'}];evidence=false;break;
  }
  if(!title)return;
  setEditor({operation:op,title,description,entries,evidence,citation,optionalEvidence,predecessorId:predecessor?.id,initial:predecessor});
 };
 const submit=async(values:any,fieldIds:string[],citations:any[])=>{
  if(!editor)return;const op=editor.operation,ref=(id:string)=>{const f=snapshot.fields.find((x:any)=>x.id===id);if(!f)throw Error('Select a current stored fact.');return {fieldId:f.id,revision:f.revision};};
  const v:any={...values,operation:op};
  if(editor.predecessorId)v.predecessorId=editor.predecessorId;
  if(editor.evidence)v.evidenceRefs=fieldIds.map(ref);
  if(citations.length)v.citations=citations;
  for(const k of Object.keys(v))if(v[k]===''||v[k]===undefined)delete v[k];
  if(['requirement','template'].includes(op))v.sections=comma(v.sections);
  if(op==='requirement')v.minCount=Number(v.minCount);
  if(op==='rule'){v.parameters=comma(v.parameters);v.expression={op:v.operator,...(v.operator==='REQUIRED_PARAMETER'?{count:Number(v.count)}:{})};delete v.operator;delete v.count;if(v.kind!=='CLASSIFICATION')delete v.category;}
  if(op==='template'){v.style={headingCase:v.headingCase,density:v.density,referenceStyle:v.referenceStyle,factOrder:v.factOrder};for(const k of Object.keys(v.style))delete v[k];}
  if(op==='contentBlock'){const d=snapshot.drafts.find((d:any)=>d.id===v.draftId);if(!d)throw Error('Select a current approved draft.');v.draftRevision=d.revision;}
  if(op==='reuseContent'){const b=e.blocks.find((b:any)=>b.id===v.blockId);if(!b)throw Error('Select an approved block.');v.blockRevision=b.revision;}
  if(op==='stability'){v.timeRef=ref(v.timeFieldId);delete v.timeFieldId;}
  if(op==='marketChange')v.changedParameters=comma(v.changedParameters);
  if(op==='simulation'){const a=ref(v.fromFieldId),b=ref(v.toFieldId);v.replacements=[{fromFieldId:a.fieldId,fromRevision:a.revision,toFieldId:b.fieldId,toRevision:b.revision}];delete v.fromFieldId;delete v.toFieldId;}
  if(op==='closure'){v.expectedChecks=[{operator:v.checkOperator,expected:ref(v.expectedFieldId),actual:ref(v.actualFieldId)}];delete v.checkOperator;delete v.expectedFieldId;delete v.actualFieldId;}
  await act('lifecycle',v);setEditor(null);refresh?.();
 };
 const review=(r:any)=>form(`Review ${r.label||r.id}`,[{name:'choice',label:'Human decision',options:['APPROVE','REVISE','REQUEST_EVIDENCE','REJECT']},{name:'reason',label:'Exact evidence and decision rationale',type:'textarea'}],async(v:any)=>{await act('lifecycle',{operation:'approve',id:r.id,revision:r.revision,digest:r.digest,...v});},`Exact revision ${r.revision} · ${r.digest}. A different authorized human must review this authored record. The decision binds current source, dependencies and policy.`,true,'Record decision');
 const verify=(r:any)=>form('Independently verify closure',[{name:'reason',label:'Expected versus actual evidence rationale',type:'textarea'}],async(v:any)=>{await act('lifecycle',{operation:'verifyClosure',id:r.id,revision:r.revision,...v});},'The action owner and author cannot verify their own closure. All recorded expected checks must pass.',true,'Verify exact revision');
 const reopen=(r:any)=>form('Recheck closure effectiveness',[{name:'reason',label:'Recheck rationale',type:'textarea'}],async(v:any)=>{await act('lifecycle',{operation:'reopenCheck',id:r.id,...v});},'This on-demand check can reopen a previously verified action when its source evidence or recorded expected outcome changes.');
 const button=(op:string,label:string,reviewerOnly=false)=><button className="button small secondary" disabled={reviewerOnly?!canReview:!canAuthor} onClick={()=>open(op)}><Plus size={15}/>{label}</button>;
 const inspect=(r:any)=>{setInspection(r);setLocalError('');};
 const cards=(collection:string,empty:string)=><div className="lifecycle-record-grid">{current(collection).map((r:any)=><article className="panel lifecycle-record" key={r.id}><div className="panel-heading"><div><span className="eyebrow">{nice(r.kind||r.collection)} · r{r.revision}</span><h3>{r.label}</h3></div><StateTag value={r.status}/></div><p className="lifecycle-record-context">{[r.market,r.section,r.stage,r.candidateCategory,r.outcome].filter(Boolean).join(' · ')||`${r.evidenceRefs?.length||0} exact fact references · ${r.dependencies?.length||0} versioned dependencies`}</p>{r.text&&<p className="lifecycle-content-preview">{r.text.slice(0,240)}{r.text.length>240?'…':''}</p>}{r.groups&&<div className="lifecycle-results">{r.groups.map((g:any)=><span key={g.parameter}>{g.parameter}: {g.comparable?`${g.n} records · mean ${Number(g.mean).toFixed(3)}`:'context review required'}</span>)}</div>}{r.passed!==undefined&&<p className="subnote">{r.passed?'Recorded checks passed':'Recorded checks have blockers'} · {r.denominator} engineering checks</p>}<p className="subnote">{r.limitation||r.interpretation||'Current exact evidence and an independent human decision are required for controlled use.'}</p><div className="row-actions"><button className="inline-link" onClick={()=>inspect(r)}>Inspect evidence <ChevronRight size={14}/></button><button className="button small secondary" onClick={()=>review(r)} disabled={!canReview||r.status==='STALE'||r.createdBy===userId||collection==='verifications'}>Human review</button>{canAuthor&&!['regressions','verifications'].includes(collection)&&<button className="inline-link" onClick={()=>open({entities:'entity',relations:'relation',requirements:'requirement',rules:'rule',templates:'template',blocks:'contentBlock',reuses:'reuseContent',dossiers:'dossier',observations:'stability',comparabilities:'comparability',transfers:'transfer',changes:'marketChange',classifications:'classify',branches:'simulation',haqs:'haq',outcomes:'haqOutcome',closures:'closure',corrections:'correction'}[collection as string]||'',r)}>New revision</button>}</div></article>)}{!current(collection).length&&<div className="panel empty-state lifecycle-empty"><FileText size={24}/><h3>{empty}</h3><p>Create a source-backed candidate, then ask an independent authorized reviewer to inspect its exact revision.</p></div>}</div>;
 const sources=snapshot.sources;
 let impact:any=null;if(impactSource)try{impact=p('X40',{sourceId:impactSource});}catch(err:any){impact={error:err.message};}
 return <div className="lifecycle-workbench">
  <div className="lifecycle-summary-grid">{[['Controlled entities',entities.length],['Current approved records',records.filter((r:any)=>r.status==='APPROVED').length],['Candidates / review',records.filter((r:any)=>['CANDIDATE','NEEDS_REVIEW'].includes(r.status)).length],['Stale dependencies',records.filter((r:any)=>r.status==='STALE').length]].map(([label,count])=><div className="stat-card" key={label}><span>{label}</span><strong>{count}</strong><small>Current authorized workspace</small></div>)}</div>
  <div className="callout lifecycle-boundary"><ShieldCheck size={18}/><div><strong>Source evidence → controlled record → independent human gate.</strong><p>Scientific values come from exact approved facts. A recorded filing, rule match or technical check carries its own evidence boundary; release remains false.</p></div></div>
  <nav className="lifecycle-tabs" aria-label="Lifecycle modules">{TABS.map(([id,label])=><button className={`button small ${tab===id?'':'secondary'}`} key={id} onClick={()=>setTab(id)} aria-current={tab===id?'page':undefined}>{label}</button>)}</nav>
  {localError&&<p className="error-banner" role="alert">{localError}</p>}
  {tab==='twin'&&<><section className="panel"><div className="panel-heading"><div><span className="eyebrow">VERSIONED CMC EVIDENCE STATE</span><h3>Connect the product, sites and scientific lineage.</h3><p>Objects hold exact fact revisions. Causal dependencies and descriptive genealogy have distinct roles.</p></div><div className="row-actions">{button('entity','Register entity')}{button('relation','Connect lineage')}</div></div><div className="lifecycle-twin-map">{['product','site','batch','material','process','method','specification','equipment','substance'].map(kind=><div className="lifecycle-twin-column" key={kind}><span className="eyebrow">{kind}</span>{entities.filter((x:any)=>x.kind===kind).map((x:any)=><button key={x.id} className="lifecycle-node" onClick={()=>inspect(x)}><Layers size={15}/><strong>{x.label}</strong><StateTag value={x.status}/></button>)}{!entities.some((x:any)=>x.kind===kind)&&<small>No recorded object</small>}</div>)}</div></section>{cards('relations','No recorded lineage yet.')}</>}
  {tab==='controls'&&<><section className="panel"><div className="panel-heading"><div><span className="eyebrow">CURATED REQUIREMENTS · EXECUTABLE DSL</span><h3>Keep an obligation tied to its original source.</h3><p>Operators run bounded technical checks after independent approval. Jurisdiction applicability requires qualified review.</p></div><div className="row-actions">{button('requirement','Map obligation')}{button('rule','Create control rule')}</div></div></section>{cards('requirements','Map the first quoted obligation.')}{cards('rules','No approved executable rule configured.')}<section className="panel"><h3>Current rule execution</h3><div className="lifecycle-check-list">{p('X44').rules.map((r:any)=><button className="lifecycle-check-row" key={r.id} onClick={()=>inspect(r)}><span><strong>{r.label}</strong><small>{nice(r.expression.op)} · exact rule revision {r.revision}</small></span><StateTag value={r.execution.passed===true?'APPROVED':r.execution.state||'HOLD'}/><ChevronRight size={16}/></button>)}</div>{!current('rules').length&&<p className="subnote">Configure a source-backed rule to see its actual execution result.</p>}</section></>}
  {tab==='content'&&<><section className="panel"><div className="panel-heading"><div><span className="eyebrow">IMMUTABLE CONTENT · TRACKED REUSE</span><h3>Carry the approved text and its evidence together.</h3></div><div className="row-actions">{button('contentBlock','Freeze approved draft')}{button('template','Display template')}{button('reuseContent','Reuse content')}{button('correction','Propagate correction')}</div></div></section>{cards('blocks','No approved draft has been frozen into content.')}{cards('reuses','No controlled reuse records yet.')}{cards('templates','No controlled display template yet.')}{cards('corrections','No correction propagation recorded.')}</>}
  {tab==='dossiers'&&<><section className="panel"><div className="panel-heading"><div><span className="eyebrow">PRODUCT · MARKET · DOSSIER · SOURCE ID</span><h3>Review one connected market evidence map.</h3><p>Each dossier section holds approved requirements, facts and optional content. Source-linked filing snapshots are labelled as supplied records.</p></div>{button('dossier','Add dossier record')}</div><div className="table-scroll"><table><thead><tr><th>Product / market</th><th>Section</th><th>Source facts</th><th>Obligation coverage</th><th>Record state</th></tr></thead><tbody>{p('X36').markets.flatMap((m:any)=>m.dossiers.map((d:any)=><tr key={d.id}><td>{entities.find((x:any)=>x.id===m.productId)?.label||m.productId}<small>{m.market}</small></td><td><button className="inline-link" onClick={()=>inspect(d)}>{d.section} <ChevronRight size={13}/></button></td><td>{d.evidenceRefs.length}<small>{d.evidenceRefs.map((f:any)=>`${f.sourceId.slice(-6)}@${f.sourceVersion}`).join(', ')}</small></td><td>{d.structure.coverage.filter((c:any)=>c.covered).length}/{d.structure.coverage.length}<small>{d.structure.issues.join(', ')||'Declared technical checks passed'}</small></td><td><StateTag value={d.status}/><small>{nice(d.stateLabel)}</small></td></tr>))}</tbody></table></div>{!current('dossiers').length&&<p className="subnote">Approve a source-backed product and a market obligation, then map the evidence section.</p>}</section>{cards('dossiers','No controlled market dossier yet.')}</>}
  {tab==='analysis'&&<><section className="panel"><div className="panel-heading"><div><span className="eyebrow">OBSERVED EVIDENCE · DESCRIPTIVE ANALYSIS</span><h3>Show what was measured, with its context intact.</h3><p>Stability trends use observed points only. Comparisons and transfer maps carry separate human scientific decisions.</p></div><div className="row-actions">{button('stability','Observed time point')}{button('comparability','Compare evidence')}{button('transfer','Transfer evidence map')}</div></div></section><div className="lifecycle-record-grid">{p('X19').trends.map((t:any,i:number)=><article className="panel" key={`${t.batchId}-${i}`}><span className="eyebrow">{t.parameter} · {entities.find((x:any)=>x.id===t.batchId)?.label}</span><h3>{t.n} observed points</h3><ObservedTrend trend={t}/><p>{t.minimum}–{t.maximum} {t.unit} <small>· {t.condition}</small></p><p className="subnote">Slope: {t.descriptiveSlope===null?'Insufficient distinct time points':`${Number(t.descriptiveSlope).toPrecision(4)} ${t.unit}/${t.timeUnit}`} · extrapolation disabled · shelf life not assigned</p><button className="inline-link" onClick={()=>inspect(t)}>Inspect exact measured points <ArrowRight size={14}/></button></article>)}</div>{cards('observations','No observed stability points recorded.')}{cards('comparabilities','No controlled comparison recorded.')}{cards('transfers','No source-backed transfer map recorded.')}</>}
  {tab==='changes'&&<><section className="panel"><div className="panel-heading"><div><span className="eyebrow">SOURCE CHANGE · SIMULATION · REGRESSION</span><h3>Measure the recorded dependency path before action.</h3><p>A simulation keeps the live state intact. Non-impact means no path in this exact recorded graph; unrecorded relationships remain unknown.</p></div><div className="row-actions">{button('marketChange','Connect source change')}{button('classify','Market rule candidate')}{button('simulation','Simulate branch')}{button('regression','Run regression',true)}</div></div><label className="lifecycle-source-selector">Impact starting source<select value={impactSource} onChange={v=>setImpactSource(v.target.value)}><option value="">Select a recorded source</option>{sources.map((s:any)=><option key={s.id} value={s.id}>{s.name} · v{s.version}</option>)}</select></label>{impact&&!impact.error&&<div className="lifecycle-impact"><div><span className="eyebrow">RECORDED DEPENDENCY IMPACT</span><strong>{impact.included.length} connected objects</strong>{impact.included.slice(0,20).map((n:any)=><div key={n.id} className="lifecycle-impact-node"><GitBranch size={13}/><span>{n.label}</span><small>{n.pathReason?.reason||'Selected root'}</small></div>)}</div><div><span className="eyebrow">NO RECORDED DEPENDENCY PATH</span><strong>{impact.excluded.length} objects in this graph</strong><p className="subnote">This is a scoped graph exclusion, never a global scientific or legal non-impact claim.</p><button className="inline-link" onClick={()=>inspect(impact)}>Inspect paths and scoped proofs <ArrowRight size={14}/></button></div></div>}{impact?.error&&<p role="alert">{impact.error}</p>}</section>{cards('changes','No controlled source change connected yet.')}{cards('classifications','No market rule classification candidate yet.')}{cards('branches','No isolated simulation branch yet.')}{cards('regressions','No actual regression run recorded yet.')}</>}
  {tab==='queries'&&<><section className="panel"><div className="panel-heading"><div><span className="eyebrow">ACTUAL QUESTIONS · APPROVED OUTCOME MEMORY</span><h3>Keep authority questions apart from predictions.</h3><p>Actual questions quote an original source. Gap-derived candidates remain predictions and carry no calibrated probability.</p></div><div className="row-actions">{button('haq','Record actual question')}{button('haqOutcome','Record evidenced outcome')}</div></div></section>{cards('haqs','No actual authority question has been supplied.')}{cards('outcomes','No approved current outcome in memory.')}<section className="panel"><h3>Evidence-gap question candidates</h3><div className="lifecycle-check-list">{p('X58').candidates.map((q:any)=><button className="lifecycle-check-row" key={q.id} onClick={()=>inspect(q)}><span><strong>{q.question}</strong><small>{q.basis.dossierId||'Cross-dossier evidence check'}</small></span><StateTag value="PREDICTION"/></button>)}</div>{!p('X58').candidates.length&&<p className="subnote">No candidate question from the currently declared dossier requirements. This does not predict authority acceptance.</p>}<p className="subnote">Current governed outcome memory: {p('X57').memory.length} independently approved source-current records.</p></section></>}
  {tab==='closure'&&<><section className="panel"><div className="panel-heading"><div><span className="eyebrow">OWNER · EXPECTED RESULT · INDEPENDENT VERIFIER</span><h3>Closure holds only while its evidence holds.</h3><p>Source changes trigger dependency invalidation. Effectiveness checks also run on demand; a periodic scheduler is not configured.</p></div>{button('closure','Define closure action')}</div></section><div className="lifecycle-record-grid">{p('X64').actions.map((a:any)=><article className="panel lifecycle-record" key={a.id}><div className="panel-heading"><div><span className="eyebrow">Owner {a.owner} · r{a.revision}</span><h3>{a.label}</h3></div><StateTag value={a.actionStatus}/></div>{a.checks.map((c:any,i:number)=><div className="lifecycle-check-row" key={i}><span><strong>{nice(c.operator)}</strong><small>Expected {c.expectedValue??'—'} · actual {c.actualValue??'—'} {c.unit}</small></span><StateTag value={c.passed?'APPROVED':'HOLD'}/></div>)}<div className="row-actions"><button className="inline-link" onClick={()=>inspect(a)}>Inspect evidence <ChevronRight size={14}/></button><button className="button small" onClick={()=>verify(a)} disabled={!canReview||a.createdBy===userId||a.owner===userId||a.status==='STALE'}>Independent verification</button><button className="button small secondary" onClick={()=>reopen(a)} disabled={!canReview}>Recheck effectiveness</button></div></article>)}{!current('closures').length&&<div className="panel empty-state lifecycle-empty"><ShieldCheck size={24}/><h3>No closure action defined.</h3><p>Choose exact expected and actual evidence, an accountable owner and an independent verifier.</p></div>}</div></>}
  {editor&&<LifecycleEditor key={`${editor.operation}-${editor.predecessorId||'new'}`} editor={editor} sources={snapshot.sources} facts={approvedFacts} onSubmit={submit} onClose={()=>setEditor(null)}/>}
  {inspection&&<Inspection record={inspection} sources={sources} onClose={()=>setInspection(null)}/>}
 </div>;
}

function ObservedTrend({trend:t}:{trend:any}){
 const samples=t.samples,lo=Math.min(...samples.map((p:any)=>p.value)),hi=Math.max(...samples.map((p:any)=>p.value)),timeLo=Math.min(...samples.map((p:any)=>p.time)),timeHi=Math.max(...samples.map((p:any)=>p.time));
 const points=samples.map((p:any)=>`${25+(timeHi===timeLo?0:(p.time-timeLo)/(timeHi-timeLo)*280)},${110-(hi===lo?40:(p.value-lo)/(hi-lo)*85)}`).join(' ');
 return <svg className="lifecycle-trend" viewBox="0 0 340 155" role="img" aria-label={`${t.parameter}: ${samples.map((p:any)=>`${p.time} ${t.timeUnit}, ${p.value} ${t.unit}`).join('; ')}. Observed points only.`}><path d="M25 15 V120 H320" fill="none" stroke="currentColor" opacity=".25"/><polyline points={points} fill="none" stroke="var(--cyan,#61dded)" strokeWidth="2.5"/>{samples.map((p:any,i:number)=>{const [x,y]=points.split(' ')[i].split(',');return <g key={i}><circle cx={x} cy={y} r="4" fill="var(--cyan,#61dded)"/><text x={x} y="141" textAnchor="middle" fill="currentColor" fontSize="10">{p.time} {t.timeUnit}</text><title>{p.value} {t.unit} · {p.sourceId}@{p.sourceVersion}</title></g>;})}</svg>;
}

function useDialog(ref:React.RefObject<HTMLDivElement|null>,close:()=>void,busy=false){useEffect(()=>{const previous=document.activeElement as HTMLElement|null,previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLElement>('button,input,select,textarea')?.focus();const handle=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy){event.preventDefault();close();}if(event.key==='Tab'){const items=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')||[]);if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);document.body.style.overflow=previousOverflow;previous?.focus();};},[ref,close,busy]);}
function LifecycleEditor({editor,sources,facts,onSubmit,onClose}:{editor:Editor;sources:any[];facts:any[];onSubmit:(values:any,fieldIds:string[],citations:any[])=>Promise<void>;onClose:()=>void}){
 const original=editor.initial||{},initialCitation=original.citations?.[0],eligibleSources=sources.filter(s=>s.text&&!['SUPERSEDED','SOURCE_FAILED','REJECTED'].includes(s.status)),firstSource=eligibleSources.find(s=>s.id===initialCitation?.sourceId)||eligibleSources[0],defaults={...original,...original.style,operator:original.expression?.op,count:original.expression?.count,timeFieldId:original.timeRef?.fieldId,checkOperator:original.expectedChecks?.[0]?.operator,expectedFieldId:original.expectedChecks?.[0]?.expected?.fieldId,actualFieldId:original.expectedChecks?.[0]?.actual?.fieldId,fromFieldId:original.replacements?.[0]?.fromFieldId,toFieldId:original.replacements?.[0]?.toFieldId};
 const [values,setValues]=useState<any>(()=>Object.fromEntries(editor.entries.map(x=>{let value=defaults[x.name]??x.value??(x.kind==='multi'?[]:x.kind==='select'?x.optional?'':x.options?.[0]?.value||'':'');if(x.kind==='text'||!x.kind)value=Array.isArray(value)?value.join(', '):value;return [x.name,value];}))),[selected,setSelected]=useState<string[]>((original.evidenceRefs||[]).map((f:any)=>f.fieldId).filter((id:string)=>facts.some(f=>f.id===id))),[sourceId,setSourceId]=useState(firstSource?.id||''),[excerpt,setExcerpt]=useState(initialCitation&&firstSource?.id===initialCitation.sourceId?initialCitation.raw:firstSource?.text?.slice(0,6000)||''),[offset,setOffset]=useState(String(initialCitation&&firstSource?.id===initialCitation.sourceId?initialCitation.start:0)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const ref=useRef<HTMLDivElement>(null);useDialog(ref,onClose,busy);
 const source=sources.find(s=>s.id===sourceId),needCitation=editor.citation||(editor.operation==='entity'&&Boolean(excerpt&&sourceId)),toggle=(arr:string[],id:string)=>arr.includes(id)?arr.filter(v=>v!==id):[...arr,id];
 const save=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{for(const entry of editor.entries)if(entry.kind==='multi'&&!entry.optional&&!values[entry.name]?.length)throw Error(`Select at least one record for ${entry.label}.`);if(editor.evidence&&!editor.optionalEvidence&&!selected.length)throw Error('Select at least one exact approved fact.');let cites:any[]=[];if(needCitation){if(!source||!excerpt)throw Error('Choose an original source and exact excerpt.');const start=Number(offset);if(!Number.isSafeInteger(start)||start<0||source.text.slice(start,start+excerpt.length)!==excerpt)throw Error('The excerpt must exactly match the original text at the selected offset.');cites=[{sourceId:source.id,version:source.version,hash:source.hash,start,end:start+excerpt.length}];}await onSubmit(values,selected,cites);}catch(err:any){setError(err.message);}finally{setBusy(false);}};
 return <div className="modal-backdrop lifecycle-modal-backdrop"><div className="dialog lifecycle-dialog" ref={ref} role="dialog" aria-modal="true" aria-labelledby="lifecycle-editor-title"><button className="icon-button dialog-close" type="button" onClick={onClose} aria-label="Close lifecycle form" disabled={busy}><X size={21}/></button><span className="eyebrow">{editor.predecessorId?'NEW IMMUTABLE REVISION':'NEW SOURCE-BACKED CANDIDATE'}</span><h2 id="lifecycle-editor-title">{editor.title}</h2><p>{editor.description}</p><form onSubmit={save}><div className="lifecycle-form-grid">{editor.entries.map(f=><div key={f.name} className={`lifecycle-form-field ${f.kind==='textarea'||f.kind==='multi'?'wide':''}`}><label htmlFor={`lifecycle-${f.name}`}>{f.label}{f.optional?' (optional)':''}</label>{f.kind==='select'?<select id={`lifecycle-${f.name}`} required={!f.optional} value={values[f.name]} onChange={event=>setValues({...values,[f.name]:event.target.value})}>{f.optional&&<option value="">None</option>}{!f.optional&&!f.options?.length&&<option value="">No eligible approved record</option>}{f.options?.map(v=><option key={v.value} value={v.value}>{v.label}</option>)}</select>:f.kind==='multi'?<div className="lifecycle-selection-list" role="group" aria-label={f.label}>{f.options?.map(v=><label key={v.value} className="lifecycle-choice"><input type="checkbox" checked={(values[f.name]||[]).includes(v.value)} onChange={()=>setValues({...values,[f.name]:toggle(values[f.name]||[],v.value)})}/><span>{v.label}</span></label>)}{!f.options?.length&&<small>No eligible records. Create and independently approve the dependency first.</small>}</div>:f.kind==='textarea'?<textarea id={`lifecycle-${f.name}`} value={values[f.name]} required={!f.optional} maxLength={2000} rows={4} onChange={event=>setValues({...values,[f.name]:event.target.value})}/>:<input id={`lifecycle-${f.name}`} type={f.kind==='number'?'number':'text'} min={f.kind==='number'?1:undefined} max={f.kind==='number'?100:undefined} maxLength={500} value={values[f.name]} required={!f.optional} onChange={event=>setValues({...values,[f.name]:event.target.value})}/>} {f.note&&<small>{f.note}</small>}</div>)}</div>
 {editor.evidence&&<fieldset className="lifecycle-evidence-selector"><legend>Exact approved facts {editor.optionalEvidence?'(optional)':''}</legend><p className="subnote">Each selection freezes field revision, source ID, source revision, hash and original span. Values are never typed manually.</p><div className="lifecycle-selection-list">{facts.map(f=><label className="lifecycle-choice" key={f.id}><input type="checkbox" checked={selected.includes(f.id)} onChange={()=>setSelected(toggle(selected,f.id))}/><span><strong>{f.parameter} · {f.value} {f.unit}</strong><small>{f.batch} · {f.method||'method missing'} · fact r{f.revision} · source {f.sourceId.slice(-7)} v{f.sourceVersion}</small></span></label>)}{!facts.length&&<p>No current approved facts. Add a controlled source, extract candidates and complete field review first.</p>}</div></fieldset>}
 {(editor.citation||editor.operation==='entity')&&<fieldset className="lifecycle-evidence-selector"><legend>Exact original excerpt {editor.citation?'':'(optional for metadata-backed identity)'}</legend><label>Current original text source<select value={sourceId} onChange={event=>{const s=sources.find(s=>s.id===event.target.value);setSourceId(event.target.value);setExcerpt(s?.text?.slice(0,6000)||'');setOffset('0');}} required={editor.citation}><option value="">Choose preserved text source</option>{sources.filter(s=>s.text&&!['SUPERSEDED','SOURCE_FAILED','REJECTED'].includes(s.status)).map(s=><option key={s.id} value={s.id}>{s.name} · v{s.version}</option>)}</select></label><label>Verbatim original excerpt<textarea value={excerpt} onChange={event=>{const value=event.target.value;setExcerpt(value);const start=source?.text?.indexOf(value);if(start>=0)setOffset(String(start));}} rows={5} maxLength={6000} required={editor.citation}/></label><label>UTF-16 character start offset<input type="number" value={offset} min={0} onChange={event=>setOffset(event.target.value)}/></label><small>End offset {Number(offset)+(excerpt?.length||0)} · source v{source?.version||'—'} · hash {source?.hash?.slice(0,16)||'—'}</small>{source&&<details><summary>Inspect preserved original text</summary><pre>{source.text}</pre></details>}</fieldset>}
 {error&&<div className="error-banner" role="alert">{error}</div>}<label className="consent"><input type="checkbox" required/> I inspected the selected source evidence and understand that this creates a candidate requiring independent human review.</label><div className="dialog-actions"><button className="button secondary" type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="button" disabled={busy}>{busy?'Recording…':'Record candidate'}<ArrowRight size={16}/></button></div></form></div></div>;
}
function Inspection({record:r,sources,onClose}:{record:any;sources:any[];onClose:()=>void}){
 const ref=useRef<HTMLDivElement>(null);useDialog(ref,onClose);
 return <div className="modal-backdrop lifecycle-modal-backdrop"><div className="dialog lifecycle-dialog" ref={ref} role="dialog" aria-modal="true" aria-labelledby="lifecycle-inspect-title"><button className="icon-button dialog-close" type="button" onClick={onClose} aria-label="Close evidence inspection"><X size={21}/></button><span className="eyebrow">EXACT RECORDED EVIDENCE</span><h2 id="lifecycle-inspect-title">{r.label||r.question||r.parameter||'Dependency proof'}</h2>{r.status&&<StateTag value={r.status}/>}<dl className="lifecycle-detail-grid">{[['Record ID',r.id],['Revision',r.revision],['Market',r.market],['Section',r.section],['Author',r.createdBy],['Source / snapshot digest',r.digest||r.scientificSnapshotHash],['Scope',r.limitation||r.interpretation||r.scope]].filter(([,v])=>v!==undefined&&v!==null).map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd className={label?.includes('digest')?'mono':undefined}>{String(value)}</dd></div>)}</dl>{r.text&&<section><h3>Exact controlled text</h3><pre>{r.text}</pre></section>}{r.response?.length>0&&<section><h3>Source-backed response candidate</h3>{r.response.map((s:any,i:number)=><p key={i}>{s.text}<small>{s.sourceId} · v{s.sourceVersion}</small></p>)}</section>}{r.evidenceRefs?.length>0&&<section><h3>Frozen fact references</h3><div className="table-scroll"><table><thead><tr><th>Fact / revision</th><th>Recorded value</th><th>Source / revision</th><th>Exact original span</th></tr></thead><tbody>{r.evidenceRefs.map((f:any)=><tr key={f.fieldId}><td>{f.parameter}<small>{f.fieldId} · r{f.revision}</small></td><td>{f.value} {f.unit}<small>{f.method} · {f.batch}</small></td><td>{sources.find(s=>s.id===f.sourceId)?.name||f.sourceId}<small>v{f.sourceVersion} · {f.sourceHash?.slice(0,16)}</small></td><td><pre>{f.span?.raw||'See record evidence'}</pre><small>{f.span?.path||f.span?.location||f.span?.table}</small></td></tr>)}</tbody></table></div></section>}{r.citations?.length>0&&<section><h3>Original quoted source evidence</h3>{r.citations.map((c:any,i:number)=><div className="lifecycle-citation" key={i}><strong>{sources.find(s=>s.id===c.sourceId)?.name||c.sourceId} · v{c.sourceVersion}</strong><small>UTF-16 offsets {c.start}–{c.end} · {c.sourceHash?.slice(0,16)}</small><pre>{c.raw}</pre></div>)}</section>}{r.issues?.length>0&&<p className="error-banner">Current blockers: {r.issues.join(', ')}</p>}<details><summary>Complete technical record and dependency proof</summary><pre>{JSON.stringify(r,null,2)}</pre></details><div className="dialog-actions"><button className="button" onClick={onClose}>Close inspection <Check size={16}/></button></div></div></div>;
}
