'use client';
import {ArrowUpRight,ChevronRight,ShieldCheck,Files,ClipboardCheck,GitBranch,TriangleAlert} from 'lucide-react';
import {dependencyGraph,readiness} from '../lib/core.mjs';
import {evidenceOverview,GROUPS,workflowCockpit} from '../lib/visual-projections.mjs';
import {Status} from './ActionDialog';

export default function Overview({state,navigate}:{state:any;navigate:(view:string)=>void}){
 const graph=dependencyGraph(state),ready=readiness(state),data=evidenceOverview(state,graph),cockpit=workflowCockpit(state);
 const maxBatch=Math.max(1,...data.batches.map(b=>b.total)),origin=graph.nodes.find((n:any)=>n.type==='source'&&n.status==='PARSED')||graph.nodes.find((n:any)=>n.type==='source'),originLinks=origin?graph.edges.filter((e:any)=>e.from===origin.id).map((e:any)=>graph.nodes.find((n:any)=>n.id===e.to)).filter(Boolean):[];
 const metrics=[{label:'Controlled sources',value:state.sources.length,note:'Originals + versions',view:'sources',icon:Files,items:state.sources},{label:'Evidence conflicts',value:ready.openConflicts,note:'Named review required',view:'conflicts',icon:TriangleAlert,items:state.conflicts},{label:'Review candidates',value:ready.unreviewed+state.drafts.filter((d:any)=>d.status==='CANDIDATE').length,note:'Awaiting human decision',view:'reviews',icon:ClipboardCheck,items:[...state.fields,...state.drafts].filter((n:any)=>['CANDIDATE','NEEDS_REVIEW'].includes(n.status))},{label:'Exact source trace',value:`${ready.traceCoverage.numerator}/${ready.traceCoverage.denominator}`,note:'Linked / recorded fields',view:'graph',icon:GitBranch,items:state.fields.filter((f:any)=>f.span?.raw&&f.sourceId)}];
 const queues=[{title:'Conflicting evidence',count:ready.openConflicts,to:'conflicts',color:'#edbc7e'},{title:'Awaiting human review',count:ready.unreviewed,to:'reviews',color:'#a9a4f0'},{title:'Changed / stale facts',count:ready.stale,to:'changes',color:'#d591a3'},{title:'Required parameters missing',count:ready.missing.length,to:'conflicts',color:'#80b9e4'}];
 let cumulative=0;
 const segments=data.statuses.map(s=>{const start=cumulative;cumulative+=data.total?s.count/data.total*100:0;return {...s,start,length:cumulative-start};});
 return <div className="reference-overview">{!state.ext?.workingProof&&<section className="working-proof-entry"><div><strong>Inspect a saved synthetic CMC case</strong><p>Originals, exact facts, a gap assessment and a recorded HOLD decision in one read-only dashboard.</p></div><a className="button secondary" href="/working-proof">Open working proof</a></section>}
  <section className="forge-next-action"><div><span className="eyebrow">NEXT EVIDENCE STEP · REVISION {state.version}</span><h2>{cockpit.next.label}</h2><p>{cockpit.next.reason}</p></div><button className="button secondary" onClick={()=>navigate(cockpit.next.view)}>Inspect step <ArrowUpRight size={17}/></button><div className="next-action-boundary"><ShieldCheck size={16}/> Suggested navigation only. Source permissions and human authority still apply.</div></section>
  <section className="forge-workflow-cockpit" aria-label="Saved evidence workflow">{cockpit.stages.map((s,i)=><button key={s.label} onClick={()=>navigate(s.view)}><span className="cockpit-stage-number">{String(i+1).padStart(2,'0')}<ChevronRight size={14}/></span><h3>{s.label}<b>{s.value}</b></h3><p>{s.note}</p><Status value={s.state}/></button>)}</section>
  <div className="ref-metrics">{metrics.map((m,i)=><button className="ref-metric" key={m.label} onClick={()=>navigate(m.view)}><span>{m.label}<m.icon size={15}/></span><strong>{m.value}</strong><div className="metric-records" aria-label={`${m.items.length} saved records`}>{m.items.slice(-9).map((n:any,j:number)=><i key={n.id||j} style={{height:`${14+(['APPROVED','PARSED'].includes(n.status)?18:0)}px`,background:GROUPS[i%GROUPS.length].color}}/>)}</div><small>{m.note}<ArrowUpRight size={14}/></small></button>)}</div>
  <div className="ref-overview-middle">
   <section className="ref-panel batch-status-panel"><div className="ref-panel-head"><h2>Evidence by batch</h2><button className="icon-button" onClick={()=>navigate('batches')} aria-label="Open batch evidence"><ArrowUpRight size={17}/></button></div><p className="ref-panel-note">Recorded field counts · current snapshot</p><div className="ref-stacked-bars">{data.batches.length?data.batches.slice(0,8).map(b=><div className="ref-batch" key={b.label}><span>{b.label}</span><div className="ref-stacked-track" style={{height:`${Math.max(8,b.total/maxBatch*163)}px`}} aria-label={`${b.total} fields: ${b.segments.map(s=>`${s.count} ${s.label}`).join(', ')}`}>{b.segments.filter(s=>s.count>0).map(s=><i key={s.label} style={{height:`${s.count/b.total*100}%`,background:s.color}}/>)}</div><b>{b.total}</b></div>):<div className="ref-no-data"><Files size={25}/><span>No extracted batch records yet.</span><button className="inline-link" onClick={()=>navigate('sources')}>Start with a source <ArrowUpRight size={14}/></button></div>}</div><div className="ref-chart-legend">{data.statuses.map(s=><span key={s.label}><i style={{background:s.color}}/>{s.label}</span>)}</div>{data.batches.length>8&&<button className="inline-link" onClick={()=>navigate('batches')}>View all {data.batches.length} batches</button>}</section>
   <section className="ref-panel attention-panel"><div className="ref-panel-head"><h2>Needs attention</h2><button className="icon-button" onClick={()=>navigate('reviews')} aria-label="Open review queue"><ArrowUpRight size={17}/></button></div><p className="ref-panel-note">Evidence blockers remain visible.</p><div className="ref-attention">{queues.map(q=><button key={q.title} onClick={()=>navigate(q.to)}><i style={{background:q.color}}/><span>{q.title}</span><b>{q.count}</b><ChevronRight size={13}/></button>)}</div><div className="ref-gate"><ShieldCheck size={16}/><span>Human gate retained</span><Status value={ready.exportReady?'APPROVED':'HUMAN_REVIEW_REQUIRED'}/></div></section>
   <section className="ref-panel status-wheel-panel"><div className="ref-panel-head"><h2>Record status</h2><button className="icon-button" onClick={()=>navigate('graph')} aria-label="Open record graph"><ArrowUpRight size={17}/></button></div><div className="ref-donut"><svg viewBox="0 0 180 180" role="img" aria-label={`${data.total} saved graph records. ${data.statuses.map(s=>`${s.label}: ${s.count}`).join('. ')}`}><circle cx="90" cy="90" r="63" fill="none" stroke="#373c41" strokeWidth="22"/>{segments.filter(s=>s.count).map(s=><circle key={s.label} cx="90" cy="90" r="63" fill="none" stroke={s.color} strokeWidth="22" pathLength="100" strokeDasharray={`${Math.max(0,s.length-.7)} ${100-Math.max(0,s.length-.7)}`} strokeDashoffset={-s.start} transform="rotate(-90 90 90)"/>)}<text x="90" y="88" textAnchor="middle">{data.total}</text><text className="wheel-label" x="90" y="109" textAnchor="middle">saved records</text></svg></div><div className="ref-wheel-legend">{data.statuses.map(s=><span key={s.label}><i style={{background:s.color}}/>{s.label}<b>{s.count}</b></span>)}</div></section>
  </div>
  <div className="ref-overview-bottom"><section className="ref-panel dependency-preview"><div className="ref-panel-head"><h2>A connected evidence thread</h2><button className="inline-link" onClick={()=>navigate('graph')}>Explore graph <ArrowUpRight size={14}/></button></div><svg viewBox="0 0 590 220" role="img" aria-label={origin?`${origin.label}: ${originLinks.length} direct saved relationships`:'No source relationships yet'}><defs><radialGradient id="mini-thread-glow"><stop stopColor="#ada9e1" stopOpacity=".25"/><stop offset="1" stopColor="#ada9e1" stopOpacity="0"/></radialGradient></defs><circle cx="86" cy="110" r="70" fill="url(#mini-thread-glow)"/><circle cx="86" cy="110" r="38" fill="none" stroke="#96a5d6" strokeDasharray="1 4" strokeWidth="8"/><circle cx="86" cy="110" r="27" fill="#333745" stroke="#9892bd"/><text x="86" y="116" textAnchor="middle" fill="#d1d5e6">{state.sources.length}</text><text x="86" y="175" textAnchor="middle" className="mini-graph-label">source versions</text>{origin&&<><path d="M126 110H203" fill="none" stroke="#7b97c9"/><rect x="203" y="88" width="127" height="44" rx="10" fill="#27343e" stroke="#7592be"/><text x="266" y="107" textAnchor="middle" fill="#d5e2e8">Source → facts</text><text x="266" y="121" textAnchor="middle" className="mini-graph-label">{originLinks.length} direct links</text>{originLinks.slice(0,9).map((n:any,i:number)=>{const y=26+i*21,c=GROUPS[i%GROUPS.length].color;return <g key={n.id}><path d={`M330 110C410 110 405 ${y} 454 ${y}`} fill="none" stroke={c} strokeOpacity=".65"/><circle cx="454" cy={y} r="3.5" fill={c}/><text x="465" y={y+3} className="mini-graph-label">{n.label.slice(0,18)}</text></g>;})}</>}</svg><p className="ref-panel-note">{origin?`Source: ${origin.label}. ${Math.min(9,originLinks.length)} of ${originLinks.length} direct relationships shown.`:'Save an original to start the evidence thread.'} Workspace revision {state.version}.</p></section><section className="ref-panel recent-records"><div className="ref-panel-head"><h2>Latest recorded decisions</h2><button className="inline-link" onClick={()=>navigate('audit')}>Audit history <ArrowUpRight size={14}/></button></div>{state.decisions.length?<div className="ref-record-list">{[...state.decisions].slice(-5).reverse().map((d:any)=><button key={d.id} onClick={()=>navigate('reviews')}><div><strong>{String(d.action||'Review').replaceAll('_',' ')}</strong><small>{d.targetId} · revision {d.revision??'recorded'}</small></div><Status value={d.status||'RECORDED'}/><ArrowUpRight size={14}/></button>)}</div>:<div className="ref-no-data"><ClipboardCheck size={25}/><span>No human decisions recorded yet.</span><button className="inline-link" onClick={()=>navigate(state.fields.length?'reviews':'sources')}>Open {state.fields.length?'review queue':'source intake'} <ArrowUpRight size={14}/></button></div>}<div className="ref-release-note">Controlled evidence packages <b>{state.exports.length}</b><span>release = false</span></div></section></div>
 </div>;
}
