'use client';
import {useEffect,useState} from 'react';
import CollaborationPanel from './CollaborationPanel';
import {Dialog,type Modal} from './ActionDialog';
export default function PartnerPortal({userId,userName}:{userId:string;userName:string}){
 const [workspaces,setWorkspaces]=useState<any[]>([]),[selected,setSelected]=useState(''),[modal,setModal]=useState<Modal|null>(null),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/sharing').then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);setWorkspaces(d.workspaces||[]);setSelected(d.workspaces?.[0]?.id||'');}).catch(e=>setError(e.message));},[]);
 const form=(title:string,fields:any[],submit:any,description?:string,consent=true,button?:string)=>setModal({title,fields,description,consent,button,submit:async v=>{await submit(v);setModal(null);}});
 return <div className="forge-public"><header className="landing-nav"><a className="brand" href="/"><span className="brand-mark">F</span><span>FORGE<small>PARTNER EVIDENCE PORTAL</small></span></a><a className="button small secondary" href="/app">Internal workspace</a></header><main className="section" style={{paddingTop:60}}><div className="workspace-heading"><div><span className="eyebrow">SIGNED IN AS {userName}</span><h1>Evidence shared with you.</h1><p>Exact-object access. Your permissions and evidence boundary are visible.</p></div></div><section className="panel"><strong>Your account identity</strong><p className="mono">{userId}</p><p className="subnote">Share this ID with the owner for an exact-object grant. Manual email accounts require verified identity before shared access. Site access and object access are managed separately.</p></section>{error&&<p className="error-banner" role="alert">{error}</p>}{workspaces.length?<><label className="form-field"><span>Shared workspace</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.id} · {w.objectCount} objects</option>)}</select></label><CollaborationPanel workspaceId={selected} form={form} inspect={(title:string,body:any)=>setModal({title,body})}/></>:<section className="empty-state"><h3>No current object grants.</h3><p>An owner must expressly share an eligible revision. Expired, revoked and superseded grants do not expose records.</p></section>}</main>{modal&&<Dialog modal={modal} onClose={()=>setModal(null)} busy={false} error=""/>}</div>;
}
