"use client";
import {useEffect,useRef,useState} from 'react';
import {requestJSON} from '../lib/client-request';
export default function ProviderProofPanel({workspaceId}:{workspaceId?:string}){const [data,setData]=useState<any>(null),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const scope=workspaceId||'',endpoint='/api/provider-proof'+(workspaceId?'?workspace='+encodeURIComponent(workspaceId):''),headers={};const generation=useRef(0);
 async function read(expected=generation.current){const d=await requestJSON<any>(endpoint,{cache:'no-store',headers},15000,'Provider status is unavailable. Refresh the saved receipt.');if(expected===generation.current){setData(d);setError('');}}
 useEffect(()=>{const expected=++generation.current;setData(null);setError('');setConsent(false);setBusy(false);read(expected).catch(e=>{if(expected===generation.current)setError(e.message);});return()=>{generation.current++;};},[scope]);
 async function refresh(){const expected=generation.current;try{await read(expected);}catch(e:any){if(expected===generation.current)setError(e.message);}}
 async function run(){if(!consent||busy)return;const expected=generation.current;setBusy(true);setError('');try{await requestJSON<any>(endpoint,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify({consent:true,sourceId:'fda'})},120000,'Provider check could not complete. Refresh the saved receipt before trying again.');await read(expected);}catch(e:any){try{await read(expected);}catch{/* Keep the action failure visible; a failed read never becomes success. */}if(expected===generation.current)setError(e.message);}finally{if(expected===generation.current)setBusy(false);}}
 return <section className="panel" aria-busy={busy}><h3>Check configured providers</h3><p>Run a bounded check using one public FDA listing and synthetic facts. Groq checks candidates; Firecrawl retrieves discovery content. No private documents are sent and no regulatory decision is approved.</p><label style={{display:'flex',gap:10,alignItems:'flex-start',margin:'16px 0'}}><input type="checkbox" disabled={busy} checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I authorize up to four Groq calls and one Firecrawl scrape for this synthetic/public test. Provider credits may be used.</span></label><button className="button primary-action" disabled={!consent||busy} onClick={run}>{busy?'Checking providers…':'Run synthetic provider check'}</button><button className="button secondary" disabled={busy} onClick={refresh}>Refresh saved receipt</button>{error&&<p role="alert">{error}</p>}{data&&<><p>Groq: {data.configured?.groq?'configured; execution needs checking':'not configured'} · Firecrawl: {data.configured?.firecrawl?'configured; execution needs checking':'not configured'}</p>{data.latest?<><p><b>Saved check:</b> {data.latest.status} · {new Date(data.latest.at).toLocaleString()}</p><ul>{data.latest.checks?.map((c:any)=><li key={c.name}>{c.name}: {c.status}{c.reason?' - '+c.reason:''}</li>)}</ul><p>Tokens and latency describe this test only. Customer benefits, professional correctness and production restore remain separate.</p><details><summary>Inspect saved receipt</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(data.latest,null,2)}</pre></details></>:<p>No saved provider check yet.</p>}</>}</section>;}
