'use client';
import ProviderProofPanel from './provider-proof-panel';
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {Activity,RefreshCw,ShieldCheck} from 'lucide-react';
import {readiness} from '../lib/core.mjs';
import {Status} from './ActionDialog';
import release from '../lib/release-status.json';

const LABELS:Record<string,string>={database:'Saved records',migrations_and_queue:'Workflow storage',original_storage:'Original-file access',original_integrity_sample:'Sampled original integrity',signature_configuration:'Technical signature configuration',ai_provider:'Optional AI provider'};
export default function QualityPanel({state,workspaceId,demo,busy,inspect}:{state:any;workspaceId:string;demo:boolean;busy:boolean;inspect:(title:string,body:ReactNode)=>void}){
 const [probe,setProbe]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[watch,setWatch]=useState(false);
 const current=readiness(state),requestSequence=useRef(0);
 const refresh=useCallback(async()=>{if(demo||!workspaceId)return;const sequence=++requestSequence.current;setLoading(true);setError('');try{const r=await fetch(`/api/readiness?workspace=${encodeURIComponent(workspaceId)}`,{cache:'no-store'}),d:any=await r.json();if(!d.checks)throw Error(d.error||'Service inspection unavailable.');if(sequence===requestSequence.current)setProbe(d);}catch(e:any){if(sequence===requestSequence.current)setError(e.message);}finally{if(sequence===requestSequence.current)setLoading(false);}},[demo,workspaceId]);
 useEffect(()=>{requestSequence.current++;setProbe(null);setWatch(false);setError('');setLoading(false);return()=>{requestSequence.current++;};},[workspaceId,demo]);
 useEffect(()=>{if(!watch||demo)return;const id=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},30000);return()=>clearInterval(id);},[watch,demo,refresh]);
 return <>
  {!demo&&<ProviderProofPanel workspaceId={workspaceId}/>}
  <div className="stats-grid three"><div className="stat-card"><span>Current missing evidence</span><strong>{current.missing.length}</strong><small>Required parameters in this workspace</small></div><div className="stat-card"><span>Open conflicts</span><strong>{current.openConflicts}</strong><small>Human correction or evidence needed</small></div><div className="stat-card"><span>Qualification</span><strong className="small-value">REVIEW REQUIRED</strong><small>Independent professional validation pending</small></div></div>
  <section className="panel"><div className="panel-heading"><div><span className="eyebrow">CURRENT WORKSPACE · READ-ONLY</span><h3><Activity size={19}/> Service and evidence health</h3><p>Inspect saved records and original-file access without changing evidence or decisions.</p></div><div className="row-actions"><button className="button small secondary" onClick={()=>void refresh()} disabled={demo||busy||loading||!workspaceId}><RefreshCw size={15}/> {loading?'Inspecting…':'Check now'}</button><button className="button small secondary" disabled={demo||!workspaceId} aria-pressed={watch} onClick={()=>{setWatch(!watch);if(!watch)void refresh();}}>{watch?'Stop watching':'Watch while open'}</button></div></div>
   {error&&<p className="error-banner" role="alert">{error} Current health is unknown; no successful check is claimed.</p>}
   {!probe&&<p className="subnote">{demo?'This guided case uses labelled synthetic records. Sign in and select your workspace for actual dependency checks.':'No current service check yet. Choose Check now; an old check does not establish current health.'}</p>}
   {probe&&<><div className="row-between"><Status value={probe.status}/><small>Checked {new Date(probe.at).toLocaleString()} · {probe.latencyMs} ms for this probe</small></div><div className="module-grid">{probe.checks.map((c:any)=><article className="card" key={c.id}><strong>{LABELS[c.id]||'Service check'}</strong><Status value={c.status}/><p>{c.required?'Required dependency':'Optional or sampled check'}{c.id==='original_integrity_sample'?` · ${c.evidence?.checked||0} originals sampled`:''}</p>{c.code&&<small>{c.message}</small>}{c.id==='ai_provider'&&<small>Live inference and quality require a separate evaluation.</small>}</article>)}</div>{probe.operational&&<p className="callout">Recorded queue attention: {probe.operational.failedOrHeldJobs} held/failed jobs, {probe.operational.expiredLeases} expired leases, {probe.operational.overdueRunnableJobs} runnable jobs past the inspection window. Human review waits are shown separately: {probe.operational.humanWaitingWorkflows}. Periodic unattended execution is not established by this check.</p>}<p className="subnote">Watching refreshes read-only checks every 30 seconds while this page is visible. It does not run agents, grant approvals or establish round-the-clock monitoring.</p></>}
  </section>
  <section className="panel"><div className="panel-heading"><div><span className="eyebrow">SCOPED ENGINEERING EVIDENCE</span><h3><ShieldCheck size={19}/> What has been checked</h3><p>Separate results, with their actual scope. Test passes are not regulatory accuracy.</p></div></div><div className="module-grid">{release.suites.map(s=><article className="card" key={s.label}><strong>{s.label}</strong><h3>{s.passed}/{s.passed+s.failed}</h3><p>{s.scope}</p></article>)}</div><small>Recorded {new Date(release.at).toLocaleString()}. These results do not certify future runs.</small>
   <details><summary>Limits and next verification steps</summary><ul className="plain-list">{release.pending.map(v=><li key={v}>{v}</li>)}</ul></details>
  </section>
  <section className="panel"><h3>Your human decision boundary</h3><p>Inspect the original, resolve gaps, review the exact revision and check export conditions. Source changes require a fresh review; a service check never grants scientific approval, batch release or dossier submission.</p><button className="inline-link" onClick={()=>inspect('Current review blockers',<div><p>Current workspace snapshot only. Scientific relevance and regulatory applicability require your qualified review.</p><ul className="plain-list">{current.missing.map((x:string)=><li key={x}>Missing required evidence: {x}</li>)}</ul><p>{current.openConflicts} open conflicts · {current.anomalies} recorded value anomalies.</p></div>)}>Inspect review blockers</button></section>
 </>;
}
