"use client";
import {useEffect,useRef,useState} from 'react';
import {requestJSON} from '../lib/client-request';
export default function RecruiterCase({product,full=false}:{product:'FORGE'|'BEACON';full?:boolean}){
 const [proof,setProof]=useState<{sources:number;conflicts:number;exportReady:boolean;release:boolean}|null>(null);
 useEffect(()=>{if(product!=='FORGE'||!full)return;let active=true;requestJSON<any>('/api/working-proof',{cache:'no-store'}).then(p=>{if(active)setProof({sources:p.state.sources.length,conflicts:p.summary.openConflicts,exportReady:p.summary.exportReady,release:p.release});}).catch(()=>{if(active)setProof(null);});return()=>{active=false;};},[product,full]);
 const forge=product==='FORGE', dialog=useRef<HTMLDialogElement>(null),[destination,setDestination]=useState(''),[step,setStep]=useState(0);
 const steps=forge?[
 ['Original source','SYN-COA-A.json, SYN-BATCH-A.json and SYN-COA-B.json are the existing synthetic sources.','sources'],
 ['Source-backed fact','SYN-A assay is recorded as 98.6% in the COA and 99.1% in the batch source. Raw numbers, units and method IDs stay attached.','extraction'],
 ['Gap / conflict','Same-batch assay differs by 0.5 percentage points. Stability and actual tablet composition are not supplied.','conflicts'],
 ['Module 3 mapping','Candidate areas: 3.2.P.5.4 batch analyses, P.5.2 methods, P.5.3 validation and P.8 stability. Applicability requires review.','drafts'],
 ['HOLD / review','A missing or conflicting critical value cannot become an accepted fact. Inspect the existing gap and review gates.','reviews'],
 ['Human decision','Request evidence, reject or resolve with supporting records. No qualified professional decision is pre-populated. The saved work sample includes clearly labelled illustrative evidence requests. No qualified professional approval is claimed.','reviews'],
 ['Controlled output','The gap assessment communicates limits. Submission-ready output remains blocked until current evidence, QC and exact-revision review are satisfied.','exports']
 ]:[
 ['Previous / current sources','FDA Q9(R1): June 2022 draft and May 2023 final. The existing demo retains official links and short status excerpts.',''],
 ['Exact evidence','Draft PDF page 1; final PDF page 6 / printed page 1. Inspect the complete original source.',''],
 ['What changed','The narrow supported difference is draft-to-final guidance status; this is not a full substantive redline.',''],
 ['Uncertainty','Real product, site, process, SOP and dossier context are absent. Demo organization values are synthetic.',''],
 ['UNKNOWN / HOLD','Company applicability and impact remain unresolved. Do not turn missing context into a confirmed impact.',''],
 ['Human review','A qualified RA/QA professional reviews the exact evidence and context. No commercial approval is claimed.',''],
 ['Audit / closure','The existing workflow links recorded decisions and actions to revisions. Actual closure needs supporting evidence and independent review.','']
 ];
 function open(url:string){setDestination(url);dialog.current?.showModal();}
 const pdf=forge?'/work-samples/CMC_Gap_Assessment.pdf':'/work-samples/Regulatory_Change_Impact_Assessment.pdf';
 return <section className="recruiter-case" id="recruiter-case"><small>INDEPENDENT PORTFOLIO EXERCISE / {forge?'SYNTHETIC PRODUCT DATA':'PUBLIC OFFICIAL SOURCES'}</small><h2>{forge?'CMC documentation & submission readiness':'Regulatory intelligence & change impact'}</h2><p>{forge?'Drug X 100 mg immediate-release tablet is a hypothetical case wrapper for existing synthetic analytical fixtures. It is not a commercial submission, regulatory advice or evidence of commercial CMC experience.':'Q9(R1) draft-to-final status assessment. No company-specific applicability or commercial impact is invented.'}</p>
 <div className="recruiter-actions"><button onClick={()=>open(pdf)}>{forge?'VIEW CMC GAP ASSESSMENT':'VIEW REGULATORY CHANGE ASSESSMENT'} ↗</button>{forge&&<button onClick={()=>open('/working-proof')}>OPEN SAVED CMC WORKSPACE</button>}{!forge&&<button onClick={()=>open('/work-samples/Regulatory_Decision_Note.pdf')}>VIEW 1-PAGE DECISION NOTE ↗</button>}<a href={full?'#controlled-failure':'/recruiter#controlled-failure'}>SEE CONTROLLED FAILURE</a>{!full&&<a href="/recruiter#guided">60–90 SECOND GUIDED CASE →</a>}</div>
 <h3>From manual {forge?'CMC work':'monitoring'} to controlled {forge?'digital support':'regulatory review'}</h3><div className="recruiter-grid">{[
 ['MANUAL',forge?'Open records; search for facts; compare documents; identify gaps; prepare Module 3 content.':'Check authority sites; download sources; track versions; compare changes; assess possible impact.'],
 ['ASSISTED',forge?'Surface source-linked candidates; identify missing/conflicting information; organize evidence; prepare structured drafts.':'Monitor selected sources; preserve versions; compare evidence; surface changes; connect relevant context.'],
 ['CONTROLLED',forge?'Keep gaps and conflicts visible; retain source links and QC; require human review; reconnect source changes to downstream work.':'Keep uncertainty visible; allow UNKNOWN / HOLD; require named review; link actions to evidence and preserve audit history.']
 ].map(([title,copy])=><article className="recruiter-card" key={title}><small>{title}</small><p>{copy}</p></article>)}</div>
 {full&&<><div id="guided"><h2>Follow one case in 60–90 seconds.</h2><p>Read each step, then inspect the same stage in the existing workflow. This guide does not approve or release anything.</p><nav className="recruiter-step-selector" aria-label="Guided case steps">{steps.map(([label],i)=><button key={label} aria-current={step===i?"step":undefined} onClick={()=>setStep(i)}>{i+1}. {label}</button>)}</nav><article className="recruiter-card recruiter-step" aria-live="polite"><small>STEP {step+1} / {steps.length}</small><h3>{steps[step][0]}</h3><p>{steps[step][1]}</p><div className="recruiter-actions"><button onClick={()=>open(forge?'/working-proof?view='+steps[step][2]:'/demo')}>Inspect existing workflow ↗</button><button disabled={step===0} onClick={()=>setStep(step-1)}>← Back</button><button disabled={step===steps.length-1} onClick={()=>setStep(step+1)}>Next →</button></div></article></div>
 <div id="controlled-failure">{proof&&<p role="status">Saved synthetic working proof: {proof.sources} source records · {proof.conflicts} open conflict · export {proof.exportReady?'ready':'blocked'} · release {String(proof.release)}. Server-saved fixture assessment; no professional approval.</p>}<h2>Controlled failure. Visible uncertainty.</h2><div className="recruiter-hold"><b>{forge?'98.6% ≠ 99.1% · SAME BATCH':'COMPANY CONTEXT NOT PROVIDED'}</b><p>{forge?'Conflicting evidence → HOLD → REVIEW REQUIRED → human decision → decision recorded.':'Evidence gap → UNKNOWN / HOLD → human review → no unsupported impact claim → decision recorded.'}</p><p>No critical value is guessed. The recommended decision is to request evidence; a real professional approval remains pending.</p><div className="recruiter-actions"><button onClick={()=>open(forge?'/working-proof?view=conflicts':'/demo')}>Inspect the populated case ↗</button></div></div></div></>}
 <p>Qualified {forge?'CMC / RA / QA':'Regulatory / QA'} review remains required. The system supports professional work and does not replace professional judgement.</p><div className="recruiter-actions"><button onClick={()=>open('https://portfolio.r4dewangan.chatgpt.site/#regulatory-work')}>VIEW RELATED PORTFOLIO WORK ↗</button>{full&&<a href="/">← Return to {product}</a>}</div>
 <dialog ref={dialog}><button className="recruiter-close" onClick={()=>dialog.current?.close()} aria-label="Close navigation confirmation">Close ×</button><h3>Open selected evidence?</h3><p>{destination}</p><p>Opening a source, document or demonstration does not approve its content.</p><div className="recruiter-actions"><button onClick={()=>dialog.current?.close()}>Cancel</button><a href={destination} target="_blank" rel="noopener noreferrer" onClick={()=>dialog.current?.close()}>Continue ↗</a></div></dialog>
 </section>;
}
