'use client';
import {useCallback,useEffect,useState} from 'react';
import {Play,RefreshCw,Plus,Pause,GitBranch,ShieldCheck,Clock3} from 'lucide-react';
type Props={workspaceId:string;state:any;demo:boolean;form:any;inspect:any;refresh:()=>Promise<void>};
function Status({value}:{value:string}){return <span className={`status ${/COMPLETE/.test(value)?'good':/HOLD|WAIT|DLQ|FAILED|PAUSED/.test(value)?'warn':'neutral'}`}><i/>{value.replaceAll('_',' ')}</span>}
export default function RuntimePanel({workspaceId,state,demo,form,inspect,refresh}:Props){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const read=useCallback(async()=>{if(demo||!workspaceId)return;try{const r=await fetch(`/api/runtime?workspace=${encodeURIComponent(workspaceId)}`),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e:any){setError(e.message);}},[workspaceId,demo]);
 useEffect(()=>{read();},[read,state.version]);
 useEffect(()=>{if(data?.workflows?.some((w:any)=>w.cursorRevision>state.version))refresh();},[data,state.version]);
 useEffect(()=>{if(!data?.workflows?.some((w:any)=>['READY','RUNNING'].includes(w.status)))return;const t=setInterval(()=>{if(document.visibilityState==='visible')read();},4000);return()=>clearInterval(t);},[data,read]);
 async function write(input:any){setBusy(true);setError('');try{const r=await fetch('/api/runtime',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({workspaceId,...input})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await read();await refresh();return d;}catch(e:any){setError(e.message);throw e;}finally{setBusy(false);}}
 function enqueue(){const sources=state.sources.filter((s:any)=>s.status!=='SUPERSEDED');form('Queue an evidence-bound workflow',[{name:'goal',label:'Goal',options:['PREPARE_CMC_DRAFT','ASSESS_SOURCE_CHANGE','RESPOND_HAQ','CONTROLLED_EXPORT']},{name:'sourceId',label:'Source ID (choose a current source)',options:sources.map((s:any)=>s.id)},{name:'draftId',label:'Draft ID (required for controlled export)',required:false},{name:'section',label:'CMC section',options:['3.2.P','3.2.S']},{name:'title',label:'Candidate title',value:'Source-supported CMC review'},{name:'question',label:'Actual authority question (HAQ only)',type:'textarea',required:false},{name:'mode',label:'Execution mode',options:['DETERMINISTIC','AI_ASSISTED']}],async(v:any)=>{await write({action:'enqueue',expectedVersion:state.version,...v,providerPermission:v.mode==='AI_ASSISTED'});},'The persisted parent executes source checks, extraction and typed tasks. Human gates wait for actual recorded decisions. AI mode sends permitted facts to a bounded planner, up to two parallel authors and a distinct reviewer model. Deterministic QC and named human gates follow; absent configuration stays HOLD.',true,'Queue workflow');}
 function control(w:any,operation:string){form(`${operation.replaceAll(/([A-Z])/g,' $1')} workflow`,[{name:'reason',label:'Recorded reason',type:'textarea'}],async(v:any)=>{await write({action:'control',workflowId:w.id,expectedWorkflowVersion:w.version,control:operation,...v});},'This changes runtime control only. It grants no fact, draft, response or closure approval.',true,'Record control');}
 if(demo)return <section className="panel"><div className="panel-heading"><div><span className="eyebrow">PERSISTENT RUNTIME</span><h3>Execute in a private workspace.</h3></div><Clock3 size={24}/></div><p>The local synthetic case shows domain behavior. Durable queues, leases, retries and saved task traces run in the authenticated workspace.</p><a className="button small" href="/app?view=automation">Open persistent runtime <Play size={15}/></a></section>;
 return <section className="module-workbench"><div className="panel"><div className="panel-heading"><div><span className="eyebrow">DURABLE PARENT RUNTIME</span><h3>Plan. Execute. Hold for review.</h3></div><div className="row-actions"><button className="button small secondary" onClick={()=>read()} disabled={busy}><RefreshCw size={14}/> Refresh</button><button className="button small" disabled={busy||!workspaceId||!state.sources.length} onClick={enqueue}><Plus size={14}/> Queue goal</button></div></div><p>Persisted task dependencies, 90-second leases and initial invocation plus three eligible retries. Source changes stop affected work until a named replan.</p><div className="runtime-config"><span><ShieldCheck size={15}/> Approval: human only</span><span>Model team: {data?.runtime?.providerConfigured?'configured · execution proof required':'HOLD · provider setup required'}</span><span>Periodic scheduler: {data?.runtime?.schedulerConfigured?'configured':'not configured'}</span></div><button className="button small secondary" onClick={()=>form('Advance ready tasks',[],async()=>{await write({action:'tick',limit:3});},'Run up to three ready tasks under current membership. Tasks with human gates continue to wait.',true,'Run ready tasks')} disabled={busy||!workspaceId}><Play size={14}/> Run ready tasks</button>{error&&<p className="error-banner" role="alert">{error}</p>}</div>
 {!data?.workflows?.length&&<div className="empty-state"><GitBranch size={30}/><h3>No queued workflow yet.</h3><p>Choose an actual source and bounded goal. The saved task graph appears here.</p></div>}
 {data?.workflows?.map((w:any)=>{const jobs=data.jobs.filter((j:any)=>j.workflowId===w.id&&j.generation===w.generation);return <article className="panel" key={w.id}><div className="panel-heading"><div><span className="eyebrow">GENERATION {w.generation} · REVISION {w.version}</span><h3>{w.goal.replaceAll('_',' ')}</h3></div><Status value={w.status}/></div><p className="mono subnote">{w.id} · input revision {w.cursorRevision}</p>{w.pauseReason&&<p className="callout">{w.pauseReason}</p>}<div className="runtime-dag">{jobs.map((j:any)=><button className="runtime-node" key={j.id} onClick={()=>inspect('Exact task, dependencies and trace',<pre>{JSON.stringify(j,null,2)}</pre>)}><span className="eyebrow">{j.nodeKey}</span><strong>{j.kind.replaceAll('_',' ')}</strong><Status value={j.status}/><small>Invocation {j.attempts}/4 · {j.dependsOn.length} dependencies</small>{j.failure&&<small>{j.failure.code}</small>}</button>)}</div><div className="row-actions">{!['COMPLETE','CANCELLED'].includes(w.status)&&<><button className="button small secondary" disabled={busy} onClick={()=>control(w,w.status==='PAUSED'?'resume':'pause')}><Pause size={14}/> {w.status==='PAUSED'?'Resume':'Pause'}</button>{['HUMAN_WAIT','HOLD','ESCALATED'].includes(w.status)&&<button className="button small secondary" disabled={busy} onClick={()=>control(w,'resume')}>Recheck human gate</button>}<button className="button small secondary" disabled={busy} onClick={()=>control(w,'replan')}><GitBranch size={14}/> Replan</button><button className="button small secondary" disabled={busy} onClick={()=>control(w,'escalate')}>Escalate</button><button className="button small secondary" disabled={busy} onClick={()=>control(w,'manualFallback')}>Manual deterministic fallback</button><button className="button small secondary" disabled={busy} onClick={()=>control(w,'cancel')}>Cancel</button></>}<button className="inline-link" onClick={()=>inspect('Persisted workflow history',<pre>{JSON.stringify({workflow:w,jobs:data.jobs.filter((j:any)=>j.workflowId===w.id),events:data.events.filter((e:any)=>e.workflow_id===w.id)},null,2)}</pre>)}>Inspect all generations and events</button></div></article>})}
 </section>;
}
