'use client';
import {Status} from './ActionDialog';
export default function WorkingProofAssessment({proof,navigate}:{proof:any;navigate:(view:string)=>void}){
 const a=proof.assessment;
 return <div className="stack">
  <section className="panel"><div className="panel-heading"><div><span className="eyebrow">SAVED SYNTHETIC WORK SAMPLE</span><h3>{a.title}</h3></div><Status value={a.status}/></div><p>{proof.boundary}</p><dl><dt>Saved assessment</dt><dd>Revision {a.revision} · {new Date(proof.savedAt).toLocaleString()}</dd><dt>Decision</dt><dd>{a.decision}</dd><dt>Next evidence step</dt><dd>{a.nextProof}</dd></dl><p className="callout">{a.humanBoundary}</p><details><summary>Verify the saved record</summary><p className="mono">SHA-256 {proof.recordHash}</p><p>Assessment, source IDs, exact evidence and example decisions are loaded from the same saved server record. The recruiter view is read-only.</p></details></section>
  <div className="working-proof-steps" aria-label="Inspect the CMC workflow">{[['sources','Original sources'],['extraction','Source-backed facts'],['conflicts','Gap / conflict'],['drafts','Module 3 candidate'],['reviews','Example decisions'],['graph','Evidence graph'],['audit','Recorded history']].map(([view,label],i)=><button key={view} className="button secondary" onClick={()=>navigate(view)}><span>{i+1}.</span> {label}</button>)}</div>
  <section className="panel"><h3>Available evidence and unresolved gaps</h3><div className="table-scroll"><table><thead><tr><th>Item / Module 3 area</th><th>Source-backed observation</th><th>Gap / why it matters</th><th>Next action / review</th></tr></thead><tbody>{a.rows.map((r:any)=><tr key={r.item}><td><strong>{r.item}</strong><small>{r.module3}</small><Status value={r.sourceStatus}/></td><td>{r.observation}{r.evidence.length?<details><summary>{r.evidence.length} exact source references</summary>{r.evidence.map((e:any)=><div className="proof-source-reference" key={e.fieldId}><strong>{e.sourceName} · v{e.sourceVersion}</strong><small>Line {e.line} · field {e.fieldId}</small><code>{e.raw}</code></div>)}</details>:<small>No supporting source value supplied.</small>}</td><td>{r.gap}<small>{r.why}</small></td><td>{r.next}<small>{r.reviewStatus}</small></td></tr>)}</tbody></table></div></section>
  <section className="panel"><h3>Controlled result: HOLD</h3><p>The assessment is saved and inspectable. An accepted Module 3 output is blocked because the assay conflict and required missing evidence remain unresolved.</p><p>Missing dissolution stays missing. No shelf-life, submission readiness, professional validation or regulatory release is claimed.</p><a className="button secondary" href="/demo">Try the separate session-only sandbox</a></section>
 </div>;
}
