import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
const require=createRequire(import.meta.resolve('wrangler/package.json'));
const {Miniflare}=await import(pathToFileURL(require.resolve('miniflare')).href);
const base=path.resolve('.sites-runtime/integration');await fs.mkdir(path.join(base,'lib'),{recursive:true});
for(const file of ['scientific-review.mjs','statement-controls.mjs','http.mjs','capabilities.mjs','capability-labels.mjs','parser.mjs','core.mjs','agentic.mjs','signature.mjs','tool-adapters.mjs','model-gateway.mjs','provider-config.mjs','lifecycle.mjs','lifecycle-labels.mjs','branches.mjs','readiness.mjs','document-parser.mjs','sharing.mjs','format-export.mjs','export-font.mjs'])await fs.copyFile(`lib/${file}`,path.join(base,'lib',file));
await fs.copyFile('lib/source-registry.json',path.join(base,'lib/source-registry.json'));
async function compile(file){let code=await fs.readFile(file,'utf8');code=code.replace(/import \{\s*env\s*\} from ['"]cloudflare:workers['"];?/, 'const env=globalThis.__forgeEnv;').replace(/import \{getChatGPTUser\} from ['"][^'"]*chatgpt-auth['"];?/, 'const getChatGPTUser=async()=>globalThis.__forgeUser;').replace(/from ['"]([^'"]*repository)['"]/g, 'from "$1.mjs"');const output=ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;const dest=path.join(base,file.replace(/\.ts$/,'.mjs'));await fs.mkdir(path.dirname(dest),{recursive:true});await fs.writeFile(dest,output);}
await compile('lib/repository.ts');await compile('lib/sharing-repository.ts');await compile('app/api/forge/route.ts');await compile('app/api/upload/route.ts');await compile('app/api/files/[id]/route.ts');await compile('app/api/export/route.ts');await compile('app/api/readiness/route.ts');
const mf=new Miniflare({modules:true,script:'export default { fetch(){return new Response("test harness")}}',compatibilityDate:'2026-05-15',d1Databases:{DB:'test-forge'},r2Buckets:{BUCKET:'test-files'}});
const DB=await mf.getD1Database('DB'),BUCKET=await mf.getR2Bucket('BUCKET');globalThis.__forgeEnv={DB,BUCKET,FORGE_SIGNING_KEY:'test-only-encryption-key'.repeat(3)};globalThis.__forgeUser={userId:'user-1',displayName:'Fixture user',email:'fixture@example.test'};
for(const migration of (await fs.readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort()){const schema=await fs.readFile(`drizzle/${migration}`,'utf8');for(const statement of schema.split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean))await DB.prepare(statement).run();}
const repo=await import(pathToFileURL(path.join(base,'lib/repository.mjs')).href),api=await import(pathToFileURL(path.join(base,'app/api/forge/route.mjs')).href),upload=await import(pathToFileURL(path.join(base,'app/api/upload/route.mjs')).href),fileAPI=await import(pathToFileURL(path.join(base,'app/api/files/[id]/route.mjs')).href),exportAPI=await import(pathToFileURL(path.join(base,'app/api/export/route.mjs')).href);
const readinessAPI=await import(pathToFileURL(path.join(base,'app/api/readiness/route.mjs')).href);
const {probeReadiness}=await import('../lib/readiness.mjs');
const {command,SYNTHETIC_SOURCES,hash}=await import('../lib/core.mjs');const {totp}=await import('../lib/signature.mjs');let ws,factorSecret;const cases=[];
async function test(name,fn){try{await fn();cases.push({name,status:'PASS'});}catch(e){cases.push({name,status:'FAIL',error:e.message});console.error(name,e.stack);}}
function req(body,headers={}){return new Request('https://forge.example/api/forge',{method:'POST',headers:{Origin:'https://forge.example','Content-Type':'application/json','Idempotency-Key':crypto.randomUUID(),...headers},body:JSON.stringify(body)});}
await test('Authenticated workspace creation persists membership',async()=>{const r=await api.POST(req({action:'createWorkspace',name:'Integration workspace',product:'Synthetic'}));assert.equal(r.status,201);ws=await r.json();assert.equal((await repo.listWorkspaces('user-1')).length,1);});
await test('Cross-tenant workspace read is rejected',async()=>{await assert.rejects(()=>repo.loadWorkspace(ws.id,'user-2'),e=>e.code==='FORBIDDEN');});
await test('Anonymous API access is rejected',async()=>{const prior=globalThis.__forgeUser;globalThis.__forgeUser=null;assert.equal((await api.GET(new Request('https://forge.example/api/forge'))).status,401);globalThis.__forgeUser=prior;});
await test('Cross-origin write is rejected',async()=>{assert.equal((await api.POST(req({action:'createWorkspace',name:'x',product:'x'},{Origin:'https://evil.example'}))).status,403);});
await test('Stored intake and extraction survive fresh server read',async()=>{let r=await api.POST(req({action:'intake',workspaceId:ws.id,expectedVersion:0,...SYNTHETIC_SOURCES[0],permission:'Synthetic fixture'}));assert.equal(r.status,200);const first=await r.json();r=await api.POST(req({action:'extract',workspaceId:ws.id,expectedVersion:first.state.version,id:first.result.sourceId}));assert.equal(r.status,200);const fresh=await repo.loadWorkspace(ws.id,'user-1');assert.equal(fresh.state.fields.length,3);});
await test('Duplicate operation returns prior result without duplicate records',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),key=crypto.randomUUID(),body={action:'plan',goal:'PREPARE_CMC_DRAFT',workspaceId:ws.id,expectedVersion:fresh.state.version};const a=await api.POST(req(body,{'Idempotency-Key':key}));assert.equal(a.status,200);const b=await api.POST(req(body,{'Idempotency-Key':key}));assert.equal(b.status,200);assert.equal((await b.json()).idempotent,true);assert.equal((await repo.loadWorkspace(ws.id,'user-1')).state.plans.length,1);});
await test('Idempotency key reuse for different input is rejected',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),key=crypto.randomUUID(),body={action:'plan',goal:'PREPARE_CMC_DRAFT',workspaceId:ws.id,expectedVersion:fresh.state.version};await api.POST(req(body,{'Idempotency-Key':key}));const b=await api.POST(req({...body,goal:'CONTROLLED_EXPORT'},{'Idempotency-Key':key}));assert.equal(b.status,409);});
await test('Concurrent edits yield one winner and one stale rejection',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),body={action:'plan',goal:'PREPARE_CMC_DRAFT',workspaceId:ws.id,expectedVersion:fresh.state.version};const results=await Promise.all([api.POST(req(body)),api.POST(req(body))]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);});
await test('Revoked reviewer cannot commit a paused-workflow result',async()=>{await repo.addMember(ws.id,'user-1',{userId:'user-2',role:'reviewer',active:true});const fresh=await repo.loadWorkspace(ws.id,'user-2'),r=await command(fresh.state,{action:'runSpecialist',role:'A12',expectedVersion:fresh.state.version},{id:'user-2',role:'reviewer'});await repo.addMember(ws.id,'user-1',{userId:'user-2',role:'reviewer',active:false});await assert.rejects(()=>repo.commitWorkspace(ws.id,fresh.state,r.state,'user-2','reviewer','revoked-op','hash',r.result),e=>e.code==='STALE_REVISION');});
await test('Audit hash chain verifies actual persisted events',async()=>{const result=await repo.verifyAudit(ws.id,'user-1');assert.equal(result.passed,true);assert.ok(result.denominator>0);});
await test('Historical replay verifies exact revision hash',async()=>{const rows=await repo.history(ws.id,'user-1'),r=await repo.history(ws.id,'user-1',rows[0].version);assert.equal(await hash(JSON.stringify(r.state)),r.hash);assert.equal(r.state.version,rows[0].version);});
await test('Original upload bytes are stored and retrieved with permissions',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),form=new FormData();form.set('file',new File([SYNTHETIC_SOURCES[2].text],'original.json',{type:'application/json'}));form.set('workspaceId',ws.id);form.set('expectedVersion',String(fresh.state.version));form.set('permission','Synthetic bytes');const r=await upload.POST(new Request('https://forge.example/api/upload',{method:'POST',headers:{Origin:'https://forge.example','Idempotency-Key':crypto.randomUUID()},body:form}));assert.equal(r.status,200);const d=await r.json(),original=await fileAPI.GET(new Request('https://forge.example/api/files/'+d.result.sourceId),{params:Promise.resolve({id:d.result.sourceId})});assert.equal(original.status,200);assert.equal(await original.text(),SYNTHETIC_SOURCES[2].text);});
await test('Cross-tenant original file cannot be downloaded',async()=>{const row=await DB.prepare('SELECT source_id FROM source_files LIMIT 1').first();const prior=globalThis.__forgeUser;globalThis.__forgeUser={userId:'user-2',email:'other@example.test'};const r=await fileAPI.GET(new Request('https://forge.example/api/files/'+row.source_id),{params:Promise.resolve({id:row.source_id})});assert.equal(r.status,403);globalThis.__forgeUser=prior;});
await test('Signing factor is stored encrypted and enrollment is private',async()=>{const r=await api.POST(req({action:'factorSetup',workspaceId:ws.id}));assert.equal(r.status,200);const d=await r.json(),f=await DB.prepare('SELECT encrypted_secret FROM signature_factors WHERE user_id=?').bind('user-1').first();factorSecret=d.secret;assert.ok(d.secret);assert.ok(!f.encrypted_secret.includes(d.secret));});
await test('Source approval and draft review persist through actual API',async()=>{let fresh=await repo.loadWorkspace(ws.id,'user-1');for(const f of fresh.state.fields.filter(x=>x.status==='CANDIDATE')){const r=await api.POST(req({action:'review',workspaceId:ws.id,expectedVersion:fresh.state.version,kind:'field',id:f.id,revision:f.revision,choice:'APPROVE',reason:'Synthetic source reviewed against fixture.'}));assert.equal(r.status,200);fresh=await r.json();}let r=await api.POST(req({action:'draft',workspaceId:ws.id,expectedVersion:fresh.state.version,title:'Integration candidate'}));assert.equal(r.status,200);fresh=await r.json();const d=fresh.state.drafts.at(-1);r=await api.POST(req({action:'review',workspaceId:ws.id,expectedVersion:fresh.state.version,kind:'draft',id:d.id,revision:d.revision,choice:'APPROVE',reason:'Independent deterministic QC and source inspection.'}));assert.equal(r.status,200);assert.equal((await r.json()).state.drafts.at(-1).status,'APPROVED');});
await test('Client-supplied signature cannot finalize an export',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),r=await api.POST(req({action:'export',workspaceId:ws.id,expectedVersion:fresh.state.version,id:fresh.state.drafts.at(-1).id,verifiedSignature:{signer:'forged',revisionHash:'forged'}}));assert.equal(r.status,200);const d=await r.json();assert.equal(d.state.exports.at(-1).signature,null);assert.equal(d.state.exports.at(-1).finalized,false);});
await test('AI provider permission is mandatory before inference',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),r=await api.POST(req({action:'aiDraft',workspaceId:ws.id,expectedVersion:fresh.state.version}));assert.equal(r.status,403);assert.equal((await r.json()).code,'PROVIDER_PERMISSION_REQUIRED');});
await test('Missing AI configuration persists HOLD with no fabricated draft',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),r=await api.POST(req({action:'aiDraft',workspaceId:ws.id,expectedVersion:fresh.state.version,providerPermission:true}));assert.equal(r.status,200);const d=await r.json();assert.equal(d.result.state,'HOLD');assert.equal(d.state.jobs.at(-1).status,'HOLD');assert.equal(d.state.drafts.length,fresh.state.drafts.length);assert.equal((await repo.loadWorkspace(ws.id,'user-1')).state.jobs.at(-1).status,'HOLD');});
await test('Confirmed second factor signs the exact persisted evidence revision',async()=>{const counter=Math.floor(Date.now()/30000),r=await api.POST(req({action:'factorConfirm',workspaceId:ws.id,code:await totp(factorSecret,counter)}));assert.equal(r.status,200);const fresh=await repo.loadWorkspace(ws.id,'user-1'),signed=await api.POST(req({action:'export',workspaceId:ws.id,expectedVersion:fresh.state.version,id:fresh.state.drafts.at(-1).id,finalize:true,code:await totp(factorSecret,counter+1),signatureReason:'Technical Review'}));assert.equal(signed.status,200);const ex=(await signed.json()).state.exports.at(-1);assert.equal(ex.finalized,true);assert.equal(ex.signature.signer,'user-1');assert.equal(ex.signature.revisionHash,await hash(JSON.stringify(ex.manifest.signingPayload)));});
await test('Consumed signing code cannot finalize another package',async()=>{const f=await DB.prepare('SELECT last_counter FROM signature_factors WHERE user_id=?').bind('user-1').first(),fresh=await repo.loadWorkspace(ws.id,'user-1'),r=await api.POST(req({action:'export',workspaceId:ws.id,expectedVersion:fresh.state.version,id:fresh.state.drafts.at(-1).id,finalize:true,code:await totp(factorSecret,f.last_counter),signatureReason:'Technical Review'}));assert.equal(r.status,403);assert.equal((await r.json()).code,'AUTHENTICATION_FAILED');});
function exportRequest(id,query=''){return new Request(`https://forge.example/api/export?workspace=${encodeURIComponent(ws.id)}&id=${encodeURIComponent(id)}${query}`);}
await test('Authorized export preflight uses the exact persisted signed snapshot',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),record=fresh.state.exports.at(-1),r=await exportAPI.GET(exportRequest(record.id,'&preflight=1'));assert.equal(r.status,200);const report=await r.json();assert.equal(report.ok,true);assert.equal(report.manifestChecksum,record.hash);assert.equal(report.signatureState,'SIGNATURE_BOUND_TECHNICAL_RECORD');assert.equal(report.release,false);assert.equal(r.headers.get('cache-control'),'private, no-store');});
await test('Real PDF, Word, HTML and ZIP downloads resolve from stored evidence',async()=>{const record=(await repo.loadWorkspace(ws.id,'user-1')).state.exports.at(-1);for(const format of ['pdf','docx','html','zip']){const r=await exportAPI.GET(exportRequest(record.id,`&format=${format}&manifest=forged-client-input`));assert.equal(r.status,200);assert.equal(r.headers.get('x-forge-manifest-hash'),record.hash);assert.equal(r.headers.get('x-forge-release'),'false');const bytes=new Uint8Array(await r.arrayBuffer());assert.equal(r.headers.get('x-forge-artifact-hash'),await hash(bytes));if(format==='pdf')assert.equal(new TextDecoder().decode(bytes.slice(0,5)),'%PDF-');if(['zip','docx'].includes(format))assert.equal(new DataView(bytes.buffer).getUint32(0,true),0x04034b50);if(format==='html'){const html=new TextDecoder().decode(bytes);assert.ok(html.startsWith('<!doctype html>'));assert.ok(html.includes(record.signature.signer));assert.ok(!html.includes('forged-client-input'));}}});
await test('Anonymous and cross-tenant exports are rejected before formatting',async()=>{const record=(await repo.loadWorkspace(ws.id,'user-1')).state.exports.at(-1),prior=globalThis.__forgeUser;globalThis.__forgeUser=null;assert.equal((await exportAPI.GET(exportRequest(record.id))).status,401);globalThis.__forgeUser={userId:'user-2',email:'other@example.test'};assert.equal((await exportAPI.GET(exportRequest(record.id))).status,403);globalThis.__forgeUser=prior;});
await test('Unknown snapshot and unsupported format do not generate an artifact',async()=>{const record=(await repo.loadWorkspace(ws.id,'user-1')).state.exports.at(-1);assert.equal((await exportAPI.GET(exportRequest('missing-export'))).status,404);const r=await exportAPI.GET(exportRequest(record.id,'&format=exe'));assert.equal(r.status,422);assert.equal((await r.json()).code,'FORMAT_UNSUPPORTED');});
await test('Persisted checksum corruption blocks export with a controlled failure',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),changed=structuredClone(fresh.state),record=changed.exports.at(-1);record.manifest.product='altered snapshot';await DB.prepare('UPDATE workspaces SET state=? WHERE id=?').bind(JSON.stringify(changed),ws.id).run();try{const r=await exportAPI.GET(exportRequest(record.id,'&format=docx'));assert.equal(r.status,422);assert.equal((await r.json()).code,'EXPORT_PREFLIGHT_FAILED');}finally{await DB.prepare('UPDATE workspaces SET state=? WHERE id=?').bind(JSON.stringify(fresh.state),ws.id).run();}});
async function uploadXML(text,name){const fresh=await repo.loadWorkspace(ws.id,'user-1'),form=new FormData();form.set('file',new File([text],name,{type:'application/xml'}));form.set('workspaceId',ws.id);form.set('expectedVersion',String(fresh.state.version));form.set('permission','Synthetic original for controlled parser verification');const r=await upload.POST(new Request('https://forge.example/api/upload',{method:'POST',headers:{Origin:'https://forge.example','Idempotency-Key':crypto.randomUUID()},body:form}));assert.equal(r.status,200);return r.json();}
await test('Original XML extraction persists exact source span and unapproved raw value',async()=>{const xml='<parameters schema="pramanex-parameters/1"><row><parameter>assay</parameter><value>09.8700</value><unit>%</unit><method>HPLC 001</method><batch>XML-B001</batch><basis>mass</basis><low>09.5000</low><high>10.5000</high><condition>25 C</condition></row></parameters>',uploaded=await uploadXML(xml,'original.xml'),id=uploaded.result.sourceId,r=await api.POST(req({action:'documentExtract',workspaceId:ws.id,expectedVersion:uploaded.state.version,id}));assert.equal(r.status,200);const fresh=await repo.loadWorkspace(ws.id,'user-1'),field=fresh.state.fields.find(f=>f.sourceId===id),source=fresh.state.sources.find(s=>s.id===id);assert.equal(field.rawValue,'09.8700');assert.equal(field.status,'CANDIDATE');assert.equal(source.hash,await hash(xml));assert.equal(xml.slice(field.span.fields.value.start,field.span.fields.value.end),'<value>09.8700</value>');assert.equal(source.status,'PARSED');});
await test('Unsafe XML is held with no partial persisted facts',async()=>{const uploaded=await uploadXML('<!DOCTYPE parameters [<!ENTITY x SYSTEM "file:///private">]><parameters schema="pramanex-parameters/1"><row/></parameters>','unsafe.xml'),id=uploaded.result.sourceId,r=await api.POST(req({action:'documentExtract',workspaceId:ws.id,expectedVersion:uploaded.state.version,id}));assert.equal(r.status,200);const answer=await r.json(),fresh=await repo.loadWorkspace(ws.id,'user-1');assert.equal(answer.result.state,'HOLD');assert.equal(fresh.state.fields.filter(f=>f.sourceId===id).length,0);assert.equal(fresh.state.sources.find(s=>s.id===id).status,'NEEDS_REVIEW');});
let lifecycleCandidate;
await test('Lifecycle candidate persists exact source-backed batch through the API',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),field=fresh.state.fields.find(f=>f.status==='APPROVED'),r=await api.POST(req({action:'lifecycle',operation:'entity',workspaceId:ws.id,expectedVersion:fresh.state.version,kind:'batch',label:field.batch,evidenceRefs:[{fieldId:field.id,revision:field.revision}]}));assert.equal(r.status,200);lifecycleCandidate=(await r.json()).result;const stored=(await repo.loadWorkspace(ws.id,'user-1')).state.ext.lifecycle.entities.find(e=>e.id===lifecycleCandidate.recordId);assert.equal(stored.digest,lifecycleCandidate.digest);assert.equal(stored.status,'CANDIDATE');assert.equal(stored.evidenceRefs[0].sourceHash,field.sourceHash);});
await test('Lifecycle self-approval fails and an independent named reviewer persists approval',async()=>{let fresh=await repo.loadWorkspace(ws.id,'user-1');const body={action:'lifecycle',operation:'approve',workspaceId:ws.id,expectedVersion:fresh.state.version,id:lifecycleCandidate.recordId,revision:lifecycleCandidate.revision,digest:lifecycleCandidate.digest,choice:'APPROVE',reason:'Independent original source and exact lifecycle revision inspected.'};let r=await api.POST(req(body));assert.equal(r.status,403);assert.equal((await r.json()).code,'INDEPENDENT_REVIEW_REQUIRED');await repo.addMember(ws.id,'user-1',{userId:'lifecycle-reviewer',role:'reviewer',active:true});const prior=globalThis.__forgeUser;globalThis.__forgeUser={userId:'lifecycle-reviewer',email:'reviewer@example.test'};try{r=await api.POST(req(body));assert.equal(r.status,200);}finally{globalThis.__forgeUser=prior;}fresh=await repo.loadWorkspace(ws.id,'user-1');const decision=fresh.state.ext.lifecycle.decisions.at(-1);assert.equal(decision.reviewer,'lifecycle-reviewer');assert.equal(decision.digest,lifecycleCandidate.digest);assert.equal(decision.choice,'APPROVE');});
await test('Revoked lifecycle reviewer cannot commit a result prepared before revocation',async()=>{const fresh=await repo.loadWorkspace(ws.id,'lifecycle-reviewer'),prepared=await command(fresh.state,{action:'lifecycle',operation:'approve',expectedVersion:fresh.state.version,id:lifecycleCandidate.recordId,revision:lifecycleCandidate.revision,digest:lifecycleCandidate.digest,choice:'REJECT',reason:'Independent temporary prepared test decision.'},{id:'lifecycle-reviewer',role:'reviewer'});await repo.addMember(ws.id,'user-1',{userId:'lifecycle-reviewer',role:'reviewer',active:false});await assert.rejects(()=>repo.commitWorkspace(ws.id,fresh.state,prepared.state,'lifecycle-reviewer','reviewer','revoked-lifecycle-op','test-input-hash',prepared.result),e=>e.code==='STALE_REVISION');assert.equal((await repo.loadWorkspace(ws.id,'user-1')).state.ext.lifecycle.decisions.at(-1).choice,'APPROVE');});
await test('Uploaded original revision preserves both byte histories and selectively stales dependent facts',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),old=fresh.state.sources.find(s=>s.name==='original.xml'),changed=old.text.replace('09.8700','09.8800'),form=new FormData();form.set('file',new File([changed],'original-r2.xml',{type:'application/xml'}));form.set('workspaceId',ws.id);form.set('expectedVersion',String(fresh.state.version));form.set('permission','Synthetic controlled original revision');form.set('predecessorId',old.id);form.set('reason','Original XML evidence revised under a reasoned controlled replacement.');const r=await upload.POST(new Request('https://forge.example/api/upload',{method:'POST',headers:{Origin:'https://forge.example','Idempotency-Key':crypto.randomUUID()},body:form}));assert.equal(r.status,200);const stored=(await repo.loadWorkspace(ws.id,'user-1')).state,newSource=stored.sources.find(s=>s.id===(stored.changes.at(-1).newSourceId));assert.equal(stored.sources.find(s=>s.id===old.id).status,'SUPERSEDED');assert.equal(stored.sources.find(s=>s.id===old.id).hash,old.hash);assert.equal(newSource.version,old.version+1);assert.equal(newSource.predecessorId,old.id);assert.equal(newSource.hash,await hash(changed));assert.equal(await (await BUCKET.get(old.objectKey)).text(),old.text);assert.equal(await (await BUCKET.get(newSource.objectKey)).text(),changed);assert.equal(stored.fields.find(f=>f.sourceId===old.id).status,'STALE');assert.ok(stored.fields.filter(f=>f.sourceId!==old.id&&f.sourceId!==newSource.id).some(f=>f.status==='APPROVED'));});
await test('Invalid original replacement reason or bytes commits no source or original object',async()=>{let fresh=await repo.loadWorkspace(ws.id,'user-1'),count=(await BUCKET.list({prefix:ws.id+'/'})).objects.length;for(const invalid of ['reason','bytes']){const form=new FormData();form.set('file',new File(['<parameters schema="pramanex-parameters/1"/>'],invalid==='bytes'?'fake.docx':'missing-reason.xml',{type:invalid==='bytes'?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'application/xml'}));form.set('workspaceId',ws.id);form.set('expectedVersion',String(fresh.state.version));form.set('permission','Synthetic rejection fixture');form.set('predecessorId',fresh.state.sources.find(s=>s.name==='original-r2.xml').id);if(invalid==='bytes')form.set('reason','Invalid package bytes must not be accepted.');const r=await upload.POST(new Request('https://forge.example/api/upload',{method:'POST',headers:{Origin:'https://forge.example','Idempotency-Key':crypto.randomUUID()},body:form}));assert.equal(r.status,400);assert.equal((await repo.loadWorkspace(ws.id,'user-1')).state.sources.length,fresh.state.sources.length);assert.equal((await BUCKET.list({prefix:ws.id+'/'})).objects.length,count);}});
await test('Direct JSON replacement cannot bypass preserved original upload controls',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),r=await api.POST(req({action:'supersedeSource',workspaceId:ws.id,expectedVersion:fresh.state.version,id:fresh.state.sources[0].id,replacementId:fresh.state.sources.at(-1).id,reason:'A forged direct original handoff must fail.'}));assert.equal(r.status,400);assert.equal((await r.json()).code,'USE_UPLOAD');assert.equal((await repo.loadWorkspace(ws.id,'user-1')).state.version,fresh.state.version);});
await test('Upload idempotency binds original predecessor and recorded revision reason',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),predecessor=fresh.state.sources.find(s=>s.name==='original-r2.xml'),key=crypto.randomUUID();const submit=reason=>{const form=new FormData();form.set('file',new File([predecessor.text],'idempotent-revision.xml',{type:'application/xml'}));form.set('workspaceId',ws.id);form.set('expectedVersion',String(fresh.state.version));form.set('permission','Synthetic controlled idempotency fixture');form.set('predecessorId',predecessor.id);form.set('reason',reason);return upload.POST(new Request('https://forge.example/api/upload',{method:'POST',headers:{Origin:'https://forge.example','Idempotency-Key':key},body:form}));};assert.equal((await submit('First recorded original revision reason.')).status,200);const after=await repo.loadWorkspace(ws.id,'user-1'),count=(await BUCKET.list({prefix:ws.id+'/'})).objects.length,r=await submit('Different revision reason cannot reuse this operation.');assert.equal(r.status,409);assert.equal((await r.json()).code,'IDEMPOTENCY_CONFLICT');assert.equal((await repo.loadWorkspace(ws.id,'user-1')).state.version,after.state.version);assert.equal((await BUCKET.list({prefix:ws.id+'/'})).objects.length,count);});
await test('UTF8 BOM JSON upload preserves original hash and exact extraction offsets',async()=>{const fresh=await repo.loadWorkspace(ws.id,'user-1'),text='\uFEFF'+SYNTHETIC_SOURCES[0].text,form=new FormData();form.set('file',new File([text],'bom.json',{type:'application/json'}));form.set('workspaceId',ws.id);form.set('expectedVersion',String(fresh.state.version));form.set('permission','Synthetic BOM-bearing preserved original');const uploaded=await upload.POST(new Request('https://forge.example/api/upload',{method:'POST',headers:{Origin:'https://forge.example','Idempotency-Key':crypto.randomUUID()},body:form}));assert.equal(uploaded.status,200);const data=await uploaded.json(),id=data.result.sourceId,r=await api.POST(req({action:'extract',workspaceId:ws.id,expectedVersion:data.state.version,id}));assert.equal(r.status,200);const stored=(await repo.loadWorkspace(ws.id,'user-1')).state,source=stored.sources.find(s=>s.id===id),fields=stored.fields.filter(f=>f.sourceId===id);assert.equal(source.text,text);assert.equal(source.hash,await hash(new TextEncoder().encode(text)));assert.equal(fields.length,3);for(const f of fields)assert.equal(text.slice(f.span.start,f.span.end),f.span.raw);assert.equal(new Uint8Array(await (await BUCKET.get(source.objectKey)).arrayBuffer())[0],239);});
await test('UTF8 BOM XML upload and document extraction preserve original value spans',async()=>{const base=(await repo.loadWorkspace(ws.id,'user-1')).state.sources.find(s=>s.name==='original-r2.xml').text,text='\uFEFF'+base,uploaded=await uploadXML(text,'bom.xml'),id=uploaded.result.sourceId,r=await api.POST(req({action:'documentExtract',workspaceId:ws.id,expectedVersion:uploaded.state.version,id}));assert.equal(r.status,200);const stored=(await repo.loadWorkspace(ws.id,'user-1')).state,source=stored.sources.find(s=>s.id===id),field=stored.fields.find(f=>f.sourceId===id);assert.equal(source.text,text);assert.equal(source.hash,await hash(new TextEncoder().encode(text)));assert.equal(field.rawValue,'09.8800');assert.equal(text.slice(field.span.fields.value.start,field.span.fields.value.end),'<value>09.8800</value>');});
await test('Audit tampering is detected rather than reported as valid',async()=>{await DB.prepare('UPDATE audit_events SET payload=? WHERE workspace_id=? AND sequence=1').bind('{"altered":true}',ws.id).run();assert.equal((await repo.verifyAudit(ws.id,'user-1')).passed,false);});
await test('Restored database snapshot reconstructs the same filing state',async()=>{const before=await repo.loadWorkspace(ws.id,'user-1');const backup=await DB.prepare('SELECT state,version FROM workspaces WHERE id=?').bind(ws.id).first();await DB.prepare('UPDATE workspaces SET state=?,version=0 WHERE id=?').bind('{}',ws.id).run();await DB.prepare('UPDATE workspaces SET state=?,version=? WHERE id=?').bind(backup.state,backup.version,ws.id).run();const after=await repo.loadWorkspace(ws.id,'user-1');assert.deepEqual(after.state,before.state);});

await test('Readiness probes actual D1 migrations, queue and scoped R2 originals',async()=>{const r=await readinessAPI.GET(new Request('https://forge.example/api/readiness?workspace='+ws.id));assert.equal(r.status,200);const d=await r.json();assert.equal(d.ready,true);assert.equal(d.checks.find(c=>c.id==='migrations_and_queue').evidence.requiredTableCount,18);assert.equal(d.checks.find(c=>c.id==='original_storage').status,'PASS');assert.ok(d.measures.fieldTraceability.denominator>0);assert.ok(d.measures.sourceFreshness.period.includes('Current workspace snapshot'));assert.equal(d.checks.find(c=>c.id==='migrations_and_queue').evidence.periodicScheduling,'NOT_ESTABLISHED');assert.ok(!JSON.stringify(d).includes(globalThis.__forgeEnv.FORGE_SIGNING_KEY));});
await test('Readiness denies anonymous and cross-tenant inspection',async()=>{const prior=globalThis.__forgeUser;try{globalThis.__forgeUser=null;assert.equal((await readinessAPI.GET(new Request('https://forge.example/api/readiness?workspace='+ws.id))).status,401);globalThis.__forgeUser={userId:'foreign-user'};assert.equal((await readinessAPI.GET(new Request('https://forge.example/api/readiness?workspace='+ws.id))).status,403);}finally{globalThis.__forgeUser=prior;}});
await test('Missing provider readiness remains HOLD rather than advertised healthy',async()=>{const r=await readinessAPI.GET(new Request('https://forge.example/api/readiness?workspace='+ws.id+'&profile=VISION'));assert.equal(r.status,503);const d=await r.json();assert.equal(d.ready,false);assert.equal(d.checks.find(c=>c.id==='ai_provider').evidence.liveInference,'NOT_PROBED');});
await test('Database dependency failure cannot report ready',async()=>{const state=(await repo.loadWorkspace(ws.id,'user-1')).state,d=await probeReadiness({db:{prepare(){throw Error('Synthetic outage');}},bucket:BUCKET,state,workspaceId:ws.id});assert.equal(d.ready,false);assert.equal(d.checks.find(c=>c.id==='database').status,'HOLD');assert.equal(d.checks.find(c=>c.id==='migrations_and_queue').status,'HOLD');});
await test('Queue migration loss blocks readiness despite database liveness',async()=>{const state=(await repo.loadWorkspace(ws.id,'user-1')).state,db={prepare(sql){if(sql.includes('sqlite_master'))return {all:async()=>({results:[]})};return DB.prepare(sql);}},d=await probeReadiness({db,bucket:BUCKET,state,workspaceId:ws.id});assert.equal(d.checks.find(c=>c.id==='database').status,'PASS');assert.equal(d.ready,false);assert.equal(d.checks.find(c=>c.id==='migrations_and_queue').code,'MIGRATION_INCOMPLETE');});
await test('Storage binding with failed reads stays on HOLD',async()=>{const state=(await repo.loadWorkspace(ws.id,'user-1')).state,d=await probeReadiness({db:DB,bucket:{list:async()=>{throw Error('Synthetic R2 outage');},get:async()=>null},state,workspaceId:ws.id});assert.equal(d.ready,false);assert.equal(d.checks.find(c=>c.id==='original_storage').status,'HOLD');assert.equal(d.checks.find(c=>c.id==='original_integrity_sample').status,'HOLD');});
await test('Corrupt sampled original blocks readiness before returning healthy',async()=>{const state=(await repo.loadWorkspace(ws.id,'user-1')).state,source=state.sources.filter(s=>s.objectKey&&s.status!=='SUPERSEDED')[0],before=await (await BUCKET.get(source.objectKey)).arrayBuffer();await BUCKET.put(source.objectKey,'corrupt fixture');try{const d=await probeReadiness({db:DB,bucket:BUCKET,state,workspaceId:ws.id});assert.equal(d.ready,false);assert.equal(d.checks.find(c=>c.id==='original_integrity_sample').code,'ORIGINAL_INTEGRITY_FAILED');}finally{await BUCKET.put(source.objectKey,before);}});
await test('Exact branch API persists candidates and blocks revoked reviewer replay',async()=>{const ownerState=(await repo.loadWorkspace(ws.id,'user-1')).state,draft=ownerState.drafts.find(d=>d.status==='APPROVED');assert.ok(draft);let r=await api.POST(req({action:'branch',operation:'create',workspaceId:ws.id,expectedVersion:ownerState.version,kind:'DRAFT',targetId:draft.id,name:'API controlled branch',reason:'Synthetic persisted proposal test.'}));assert.equal(r.status,200);let a=await r.json(),branch=a.state.ext.controlledBranches.records.at(-1);r=await api.POST(req({action:'branch',operation:'update',workspaceId:ws.id,expectedVersion:a.state.version,id:branch.id,revision:branch.revision,digest:branch.digest,statementId:branch.candidate.statements[0].id,text:branch.candidate.statements[0].text+' Source inspected.',reason:'Exact proposal text.'}));assert.equal(r.status,200);a=await r.json();branch=a.state.ext.controlledBranches.records.at(-1);r=await api.POST(req({action:'branch',operation:'submit',workspaceId:ws.id,expectedVersion:a.state.version,id:branch.id,revision:branch.revision,digest:branch.digest,reason:'Independent reviewer needed.'}));assert.equal(r.status,200);a=await r.json();branch=a.state.ext.controlledBranches.records.at(-1);await repo.addMember(ws.id,'user-1',{userId:'branch-reviewer',role:'reviewer',active:true});const prior=globalThis.__forgeUser,key=crypto.randomUUID(),body={action:'branch',operation:'review',workspaceId:ws.id,expectedVersion:a.state.version,id:branch.id,revision:branch.revision,digest:branch.digest,choice:'APPROVE',reason:'Independent exact proposal checked.'};try{globalThis.__forgeUser={userId:'branch-reviewer',email:'review@example.test'};assert.equal((await api.POST(req(body,{'Idempotency-Key':key}))).status,200);globalThis.__forgeUser=prior;await repo.addMember(ws.id,'user-1',{userId:'branch-reviewer',role:'reviewer',active:false});globalThis.__forgeUser={userId:'branch-reviewer'};assert.equal((await api.POST(req(body,{'Idempotency-Key':key}))).status,403);}finally{globalThis.__forgeUser=prior;}const stored=(await repo.loadWorkspace(ws.id,'user-1')).state;assert.equal(stored.ext.controlledBranches.records.at(-1).status,'APPROVED');assert.equal(stored.drafts.find(d=>d.id===draft.id).revision,draft.revision);});


await test('Revoked proposal reviewer blocks merge including the final commit race',async()=>{let fresh=await repo.loadWorkspace(ws.id,'user-1'),branch=fresh.state.ext.controlledBranches.records.at(-1),input={action:'branch',operation:'merge',workspaceId:ws.id,expectedVersion:fresh.state.version,id:branch.id,revision:branch.revision,digest:branch.digest,reason:'Attempt merge after review authority changed.'};let r=await api.POST(req(input));assert.equal(r.status,403);assert.equal((await r.json()).code,'BRANCH_REVIEWER_REVOKED');await repo.addMember(ws.id,'user-1',{userId:'branch-reviewer',role:'reviewer',active:true});fresh=await repo.loadWorkspace(ws.id,'user-1');const prepared=await command(fresh.state,input,{id:'user-1',role:'owner'});await repo.addMember(ws.id,'user-1',{userId:'branch-reviewer',role:'reviewer',active:false});await assert.rejects(()=>repo.commitWorkspace(ws.id,fresh.state,prepared.state,'user-1','owner','merge-revocation-race','fixture-digest',prepared.result,undefined,[{userId:'branch-reviewer',role:'reviewer'}]),e=>e.code==='STALE_REVISION');assert.equal((await repo.loadWorkspace(ws.id,'user-1')).state.ext.controlledBranches.records.at(-1).status,'APPROVED');});

await test('Scientific completeness uses actual API, D1 readback and evidence gap state',async()=>{const current=await repo.loadWorkspace(ws.id,'user-1');const response=await api.POST(req({action:'scientific',operation:'assess',type:'METHOD',evidence:[],workspaceId:ws.id,expectedVersion:current.state.version}));assert.equal(response.status,200);const saved=await response.json();assert.equal(saved.result.status,'HOLD');const readback=await repo.loadWorkspace(ws.id,'user-1');const assessment=readback.state.ext.scientific.records.find(r=>r.id===saved.result.recordId);assert.equal(assessment.missing.length,7);assert.equal(assessment.author,'user-1');assert.equal(readback.state.audit.at(-1).action,'scientific');});

const passed=cases.filter(c=>c.status==='PASS').length,failed=cases.length-passed;await fs.mkdir('docs/proof',{recursive:true});await fs.writeFile('docs/proof/integration-results.json',JSON.stringify({at:new Date().toISOString(),passed,failed,cases,boundary:'Actual local D1/R2 and API-handler integration checks; hosted sign-in and browser interaction remain separate.'},null,2));console.log(JSON.stringify({passed,failed,total:cases.length}));await mf.dispose();if(failed)process.exitCode=1;
