import assert from 'node:assert/strict';
import {scientificAction,scientificOverview,scientificDraftIssues,SCIENTIFIC_PROFILES} from '../lib/scientific-review.mjs';
import {initialState,command} from '../lib/core.mjs';
const source={id:'source',version:1,hash:'a'.repeat(64),status:'PARSED',permission:'Authorized synthetic fixture',text:'Synthetic procedure revision 2, validation protocol and results. This is not actual validation evidence.'};
const fresh=()=>({...initialState(),sources:[structuredClone(source)]});
const author={id:'author',role:'author'},reviewer={id:'reviewer',role:'reviewer'};let count=0;
async function check(name,fn){await fn();count++;console.log('PASS '+name);}
await check('Missing method evidence is saved as HOLD without invented content',async()=>{const s=fresh();const r=await scientificAction(s,{operation:'assess',type:'METHOD',evidence:[]},author);assert.equal(r.status,'HOLD');assert.equal(s.ext.scientific.records[0].missing.length,7);});
await check('Forged source wording is rejected',async()=>{await assert.rejects(scientificAction(fresh(),{operation:'assess',type:'METHOD',evidence:[{item:'procedure and revision',sourceId:'source',version:1,hash:source.hash,start:0,end:9,raw:'invented'}]},author),e=>e.code==='SCIENTIFIC_SPAN');});
await check('Stale source revision cannot become scientific evidence',async()=>{await assert.rejects(scientificAction(fresh(),{operation:'assess',type:'METHOD',evidence:[{item:'procedure and revision',sourceId:'source',version:0,hash:source.hash,start:0,end:9,raw:'Synthetic'}]},author),e=>e.code==='SCIENTIFIC_SOURCE');});
const s=fresh();await scientificAction(s,{operation:'assess',type:'METHOD',evidence:SCIENTIFIC_PROFILES.METHOD.items.map(item=>({item,sourceId:'source',version:1,hash:source.hash,start:0,end:source.text.length,raw:source.text}))},author);const record=s.ext.scientific.records[0];
await check('Author cannot approve their own completeness assessment',async()=>{await assert.rejects(scientificAction(s,{operation:'review',id:record.id,digest:record.digest,choice:'APPROVE',reason:'Synthetic coverage review'}, {...author,role:'owner'}),e=>e.code==='INDEPENDENT_REVIEW_REQUIRED');});
await check('Independent review binds exact digest and preserves limited scope',async()=>{await scientificAction(s,{operation:'review',id:record.id,digest:record.digest,choice:'APPROVE',reason:'Synthetic checklist coverage inspected, no scientific validation claimed'},reviewer);assert.equal(scientificOverview(s).records[0].status,'REVIEWED_COMPLETENESS_ONLY');assert.equal(scientificOverview(s).qualified,false);});
await check('Changed original invalidates current completeness review',async()=>{s.sources[0].version=2;assert.equal(scientificOverview(s).records[0].status,'STALE');});
await check('Missing scientific review blocks validation-specific draft',async()=>{assert.equal(scientificDraftIssues(fresh(),{section:'3.2.P.5.3',fieldIds:[]})[0].code,'SCIENTIFIC_COMPLETENESS_REVIEW_REQUIRED');});
await check('Draft preview requires explicit non-submission acknowledgement',async()=>{await assert.rejects(scientificAction(fresh(),{operation:'profile',profile:'M4Q_R2_PREVIEW'},{id:'owner',role:'owner'}),e=>e.code==='DRAFT_PROFILE');});
await check('Scientific action uses existing revision and audit persistence contract',async()=>{const state=fresh();const r=await command(state,{action:'scientific',operation:'assess',type:'STABILITY',evidence:[],expectedVersion:state.version},author);assert.equal(r.state.version,state.version+1);assert.equal(r.state.audit.at(-1).action,'scientific');assert.equal(r.state.ext.scientific.records[0].missing.length,7);});
await check('Changing structure profile stales current draft approvals without deleting history',async()=>{const st=fresh();st.drafts=[{id:'d',status:'APPROVED'}];st.decisions=[{kind:'draft',status:'CURRENT',targetId:'d'}];await scientificAction(st,{operation:'profile',profile:'M4Q_R2_PREVIEW',confirmDraftPreview:true},{id:'owner',role:'owner'});assert.equal(st.drafts[0].status,'STALE');assert.equal(st.decisions[0].status,'STALE');assert.equal(st.decisions.length,1);});
console.log(JSON.stringify({passed:count,failed:0,scope:'Synthetic source-binding and workflow controls; not scientific validation.'}));
