/** Nine-part agentic control plane: planning, typed specialists, governed memory and runtime. */
import {uid,now,ForgeError,readiness,checkState,comparison,dependencyGraph,blastRadius,qcDraft,snapshotDiff} from './core.mjs';
import {lifecycleProjection,hydrateLifecycle,effectiveStatus} from './lifecycle.mjs';
export const AGENTIC_PARTS=[
 {id:1,name:'Goal Interpretation & Planning Engine',layers:['L08'],artifact:'lib/agentic.mjs: makePlan / replan',boundary:'Only bounded goals; missing evidence creates a human task.'},
 {id:2,name:'Tool Integration Layer',layers:['L03','L12'],artifact:'lib/tool-adapters.mjs and API repository/storage adapters',boundary:'Allowlisted endpoints, explicit configuration; absent integration stays unavailable.'},
 {id:3,name:'Memory Store & Access Layer',layers:['L04','L07'],artifact:'retrieveMemory + source-bound lifecycle outcomes/templates + versioned D1 revisions',boundary:'Approved, current records only; original evidence remains authority.'},
 {id:4,name:'Orchestration & Runtime Environment',layers:['L08','L09'],artifact:'lib/runtime-repository.ts: persisted DAG jobs, CAS leases, parent plans and revision guards',boundary:'Bounded attempts; visible pause/HOLD/DLQ; idempotent writes.'},
 {id:5,name:'Multi-Agent Collaboration Framework',layers:['L09'],artifact:'executeRole A1–A18 + runtime specialists + scoped object sharing and independent QC',boundary:'Typed specialists and object-specific grants; no specialist can grant human approval.'},
 {id:6,name:'Human-in-the-Loop Interface',layers:['L02','L10'],artifact:'independent exact-record four-action review, durable runtime pause/escalate and TOTP signature gate',boundary:'Named reviewer and exact revision.'},
 {id:7,name:'Safety & Policy Enforcement Layer',layers:['L01','L06','L10'],artifact:'tenant permissions, object grant expiry/revocation, strict source schemas and provenance guards',boundary:'Untrusted documents are data, never tool instructions.'},
 {id:8,name:'Observability & Evaluation Stack',layers:['L11'],artifact:'persistent runtime event/lease/retry history, trace IDs, engineering tests and audit verification',boundary:'Unknown cost/quality metrics remain NOT_MEASURED.'},
 {id:9,name:'Governance & Compliance Module',layers:['L04','L10','L11'],artifact:'policy versions, memberships, retention, audit replay',boundary:'Technical controls do not certify organizational compliance.'}
];
export const ROLE_NAMES=['Source Connector Guardian','Multimodal Parser','CMC Fact Extractor','Unit & Method Normalizer','Consistency Critic','Batch / Process Genealogy Agent','Regulatory Requirement Agent','Comparability Agent','Blast-Radius Agent','Structured Authoring Agent','Independent QC Agent','Submission Readiness Agent','Variation Classification Agent','Reviewer Query Predictor','HAQ Response Agent','Decision Integrity Agent','Closure Verifier','Audit & Replay Agent'];
export function makePlan(state,goal,sourceId){const kinds={PREPARE_CMC_DRAFT:['CHECK_SOURCES','EXTRACT','CHECK_EVIDENCE','HUMAN_FACT_REVIEW','AUTHOR','INDEPENDENT_QC','HUMAN_DRAFT_REVIEW','CONTROLLED_EXPORT'],ASSESS_SOURCE_CHANGE:['SELECT_SOURCE','SIMULATE_IMPACT','HUMAN_CHANGE_REVIEW','REGISTER_REVISION','EXTRACT','REGRESSION','HUMAN_FACT_REVIEW','AUTHOR','INDEPENDENT_QC'],RESPOND_HAQ:['CHECK_EVIDENCE','HUMAN_FACT_REVIEW','RETRIEVE_APPROVED_PRECEDENT','RESPONSE_CANDIDATE','INDEPENDENT_QC','HUMAN_RESPONSE_REVIEW'],CONTROLLED_EXPORT:['CHECK_EVIDENCE','INDEPENDENT_QC','HUMAN_DRAFT_REVIEW','CONTROLLED_EXPORT']};if(!kinds[goal])throw new ForgeError('UNSUPPORTED_GOAL','Select a supported CMC goal; free-form instructions cannot authorize operations.');const p={id:uid('plan'),goal,sourceId:sourceId||null,inputRevision:state.version,status:'READY',createdAt:now(),steps:kinds[goal].map((type,i)=>({id:uid('step'),order:i+1,type,status:'PENDING',dependsOn:i?i:null})),replans:0};return replan(state,p);}
export function replan(state,plan){const p=structuredClone(plan),r=readiness(state);p.revision=state.version;p.blockers=[];if(!state.sources.length)p.blockers.push('SOURCE_REQUIRED');if(state.sources.some(s=>['UPLOADED','SOURCE_FAILED','NEEDS_REVIEW'].includes(s.status)))p.blockers.push('EXTRACTION_OR_MANUAL_VERIFICATION');if(r.missing.length)p.blockers.push(`REQUIRED_PARAMETERS: ${r.missing.join(', ')}`);if(r.openConflicts)p.blockers.push('HUMAN_CONFLICT_RESOLUTION');if(r.anomalies)p.blockers.push('HUMAN_ANOMALY_REVIEW');if(r.unreviewed)p.blockers.push('HUMAN_FACT_REVIEW');p.status=p.blockers.length?'WAITING_FOR_EVIDENCE_OR_HUMAN':'READY';p.replans=(p.replans||0)+1;p.updatedAt=now();for(const st of p.steps){if(st.type==='CHECK_SOURCES')st.status=state.sources.length?'COMPLETE':'WAITING';if(st.type==='EXTRACT')st.status=state.sources.length&&state.sources.every(s=>s.status==='PARSED'||s.status==='SUPERSEDED')?'COMPLETE':'WAITING';if(st.type==='CHECK_EVIDENCE')st.status=!r.missing.length&&!r.openConflicts&&!r.anomalies?'COMPLETE':'WAITING';if(st.type==='HUMAN_FACT_REVIEW')st.status=state.fields.some(f=>f.status==='APPROVED')&&!r.unreviewed?'COMPLETE':'WAITING';if(st.type==='AUTHOR')st.status=state.drafts.length?'COMPLETE':'PENDING';if(st.type==='INDEPENDENT_QC')st.status=state.drafts.some(d=>d.qc?.passed&&d.status!=='STALE')?'COMPLETE':'WAITING';if(st.type==='HUMAN_DRAFT_REVIEW')st.status=state.drafts.some(d=>d.status==='APPROVED')?'COMPLETE':'WAITING';if(st.type==='CONTROLLED_EXPORT')st.status=state.exports.length?'COMPLETE':'WAITING';}return p;}
export function retrieveMemory(state,query='',limit=20){
 const snapshot=structuredClone(state);hydrateLifecycle(snapshot);
 const currentFact=f=>f.status==='APPROVED'&&snapshot.sources.some(s=>s.id===f.sourceId&&s.status==='PARSED'&&s.version===f.sourceVersion&&s.hash===f.sourceHash)&&Boolean(f.span?.raw);
 const current=collection=>snapshot.ext.lifecycle[collection].filter(x=>!snapshot.ext.lifecycle[collection].some(y=>y.logicalId===x.logicalId&&y.revision>x.revision)&&effectiveStatus(snapshot,x.id)==='APPROVED');
 const records=[...snapshot.fields.filter(currentFact).map(f=>({id:f.id,type:'approved fact',text:`${f.parameter} ${f.value} ${f.unit} ${f.batch}`,sourceId:f.sourceId,sourceVersion:f.sourceVersion,sourceHash:f.sourceHash,revision:f.revision,span:f.span})),...lifecycleProjection(snapshot,'X57').data.memory.map(o=>({id:o.id,type:'approved HA outcome',text:`${o.question.title} ${o.outcome}`,revision:o.revision,digest:o.digest,evidenceRefs:o.evidenceRefs,citations:o.citations,questionId:o.haqId,regulatorAcceptance:false})),...current('templates').map(t=>({id:t.id,type:'approved template',text:`${t.label} ${t.sections.join(' ')} ${JSON.stringify(t.style)}`,revision:t.revision,digest:t.digest,citations:t.citations})),...current('blocks').map(b=>({id:b.id,type:'approved content',text:b.text,revision:b.revision,digest:b.digest,evidenceRefs:b.evidenceRefs,citations:b.citations}))];
 const words=String(query).toLowerCase().slice(0,500).split(/\W+/).filter(w=>w.length>2),boundedLimit=Number.isSafeInteger(limit)?Math.max(0,Math.min(limit,50)):20;
 return records.map(r=>({...r,score:words.filter(w=>r.text.toLowerCase().includes(w)).length,humanAuthority:false,memoryScope:'EXACT_APPROVED_CURRENT_SOURCE_BOUND_RECORD'})).filter(r=>!words.length||r.score>0).sort((a,b)=>b.score-a.score).slice(0,boundedLimit);
}
export function executeRole(state,role,input={}){if(!/^A(?:[1-9]|1[0-8])$/.test(role))throw new ForgeError('INVALID_ROLE','Choose a source-defined specialist role.');const n=Number(role.slice(1)),snapshot=structuredClone(state);hydrateLifecycle(snapshot);const project=(id,args={})=>lifecycleProjection(snapshot,id,args).data;let output;
 switch(n){
 case 1:output={sources:state.sources.map(s=>({id:s.id,type:s.type,status:s.status,hash:s.hash,permission:s.permission,version:s.version})),missingPermission:state.sources.filter(s=>!s.permission).map(s=>s.id)};break;
 case 2:output={supported:state.sources.filter(s=>['application/json','text/csv','text/plain','application/xml','text/xml','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'].includes(s.type)).map(s=>({id:s.id,type:s.type,status:s.status,parser:s.parser})),multimodal:state.sources.filter(s=>['application/pdf','image/png','image/jpeg'].includes(s.type)).map(s=>({id:s.id,status:s.status,parser:s.parser||null})),documentBytesBoundary:'XML/DOCX/XLSX extraction verifies server-stored original bytes and hash before controlled schema parsing.',visionAvailability:'CHECK_AUTHENTICATED_SERVER_CONFIGURATION',visionBoundary:'A typed projection cannot infer whether provider credentials are configured. Exact page/region candidates require separate source verification.'};break;
 case 3:output={facts:state.fields.filter(f=>f.status!=='STALE').map(f=>({id:f.id,parameter:f.parameter,raw:f.rawValue,span:f.span,status:f.status}))};break;
 case 4:output={normalizations:state.fields.filter(f=>f.normalization).map(f=>({fieldId:f.id,...f.normalization})),uncertain:state.fields.filter(f=>f.status==='NEEDS_REVIEW').map(f=>f.id)};break;
 case 5:output=checkState(state);break;
 case 6:output={genealogy:project('X12'),process:project('X13'),limitation:'Source-linked controlled genealogy; semantic relationships remain separate from causal evidence dependencies.'};break;
 case 7:output={requirements:project('X09'),coverage:project('X45'),legalApplicability:'QUALIFIED_HUMAN_REVIEW_REQUIRED'};break;
 case 8:output={recordedAssessments:project('X20'),descriptiveEvidence:project('X21'),equivalenceAuthority:false};break;
 case 9:if(!input.sourceId)throw new ForgeError('SOURCE_REQUIRED','Select the source for impact analysis.');output=blastRadius(state,input.sourceId);break;
 case 10:output={eligibleFacts:state.fields.filter(f=>f.status==='APPROVED').map(f=>f.id),instruction:'Create a source-bound draft through the parent workflow.',mode:'DETERMINISTIC_TEMPLATE_AVAILABLE',llmStatus:'CONFIGURATION_REQUIRED'};break;
 case 11:output={results:state.drafts.filter(d=>d.status!=='STALE').map(d=>({draftId:d.id,...qcDraft(state,d)}))};break;
 case 12:output=readiness(state);break;
 case 13:output={classifications:project('X37'),marketImpact:project('X38'),limitation:'Actual approved local-rule matches remain human classification candidates; unknown/conflicting matches HOLD.'};break;
 case 14:output={...project('X58'),requiredParameterGaps:readiness(state).missing.map(parameter=>({question:`What controlled evidence supports ${parameter}?`,basis:'Recorded evidence gap',state:'PREDICTION',probability:null})),limitation:'Transparent gap/rule-derived candidates; not a trained authority-query prediction model.'};break;
 case 15:output={sourceBoundQuestions:project('X55'),approvedOutcomeMemory:project('X57'),legacyResponseCandidates:state.queries.map(q=>({id:q.id,status:q.status,response:q.response,limitation:'Legacy response record is not evidence of a historical authority outcome.'}))};break;
 case 16:output={decisions:state.decisions.map(d=>({id:d.id,target:d.targetId,status:d.status,revision:d.revision,reviewer:d.reviewer})),lifecycleDecisions:snapshot.ext.lifecycle?.decisions||[],stale:state.decisions.filter(d=>d.status==='STALE').length};break;
 case 17:output={...project('X64'),independentVerifierRequired:true,automaticScientificDisposition:false};break;
 case 18:output={eventCount:state.audit.length,currentRevision:state.version,events:state.audit.slice(-50),limitation:'Database history and hash-chain verification are separate server operations.'};break;
 }
 return {schema:'FORGE specialist result/1',role,name:ROLE_NAMES[n-1],principal:`specialist/${role}/deterministic-1`,mode:'DETERMINISTIC',inputRevision:state.version,output,state:'CANDIDATE_ONLY',humanAuthority:false,at:now()};}
export function mergeSpecialistOutputs(results){const conflicts=[];for(let i=0;i<results.length;i++)for(let j=i+1;j<results.length;j++)if(results[i].inputRevision!==results[j].inputRevision)conflicts.push({left:results[i].role,right:results[j].role,reason:'Different input revisions; merge is blocked.'});return {status:conflicts.length?'HOLD':'CANDIDATE_READY',results,conflicts,approvalGranted:false};}
export function debtRegister(state){return [...state.conflicts.filter(c=>c.status==='OPEN').map(c=>({id:c.id,type:'conflict',status:c.status})),...state.decisions.filter(d=>d.status==='STALE').map(d=>({id:d.id,type:'stale decision',status:d.status})),...state.actions.filter(a=>a.status!=='CLOSED_WITH_EVIDENCE').map(a=>({id:a.id,type:'action',status:a.status,overdue:Boolean(a.due&&new Date(a.due)<new Date())}))];}
export function drift(state){return state.exports.flatMap(e=>snapshotDiff(e.manifest,state).filter(d=>d.divergent).map(d=>({...d,exportId:e.id})));}
