import {ForgeError,hash,uid,now,requireValue,qcDraft,audit} from './core.mjs';
import {hydrateLifecycle,lifecycleAction,effectiveStatus} from './lifecycle.mjs';

/** D08/D09: isolated draft/rule proposals, exact revision review and guarded merge. */
export const BRANCH_VERSION='forge-controlled-branch/1';
const authors=['owner','admin','author'];
const reviewers=['owner','reviewer','approver'];
const fail=(code,message,status=409)=>{throw new ForgeError(code,message,status);};
function role(actor,roles){if(!roles.includes(actor.role))fail('FORBIDDEN','Your role cannot perform this branch operation.',403);}
function strict(input,keys){for(const k of Object.keys(input))if(!['action','expectedVersion','workspaceId','operation',...keys].includes(k))fail('BRANCH_SCHEMA',`Unsupported branch property: ${k}.`,400);}
export function hydrateBranches(state){state.ext??={};state.ext.controlledBranches??={version:BRANCH_VERSION,records:[],reviews:[]};const b=state.ext.controlledBranches;if(b.version!==BRANCH_VERSION)fail('BRANCH_VERSION','Controlled branches require an explicit schema migration.');return b;}
function target(state,kind,id){const x=kind==='DRAFT'?state.drafts.find(x=>x.id===id):kind==='RULE'?hydrateLifecycle(state).rules.find(x=>x.id===id):null;if(!x)fail('BRANCH_TARGET','Select a draft or controlled lifecycle rule in this workspace.',404);return x;}
function currentTarget(state,kind,id){const x=target(state,kind,id);if(kind==='DRAFT'){if(['STALE','REJECTED'].includes(x.status))fail('STALE_BRANCH_BASE','The base draft is stale or rejected.');if(!qcDraft(structuredClone(state),x).passed)fail('BRANCH_QC_FAILED','The base draft needs passing technical QC.');}else if(['STALE','REJECTED'].includes(effectiveStatus(state,id)))fail('STALE_BRANCH_BASE','The base rule is stale or rejected.');return x;}
function draftBody(x){return {title:x.title,section:x.section,fieldIds:structuredClone(x.fieldIds),statements:structuredClone(x.statements)};}
function ruleBody(x){return {label:x.label,kind:x.kind,market:x.market,parameters:structuredClone(x.parameters),expression:structuredClone(x.expression),...(x.kind==='CLASSIFICATION'?{category:x.category}:{}),requirementIds:structuredClone(x.requirementIds),evidenceRefs:x.evidenceRefs.map(r=>({fieldId:r.fieldId,revision:r.revision})),citations:x.citations.map(c=>({sourceId:c.sourceId,version:c.sourceVersion,start:c.start,end:c.end,hash:c.sourceHash}))};}
async function baseDigest(kind,x){return hash(JSON.stringify(kind==='DRAFT'?{revision:x.revision,status:x.status,...draftBody(x)}:{id:x.id,revision:x.revision,digest:x.digest,status:x.status}));}
function pins(state,kind,x){const fields=kind==='DRAFT'?x.fieldIds.map(id=>state.fields.find(f=>f.id===id)):x.evidenceRefs.map(r=>state.fields.find(f=>f.id===r.fieldId));const sourceIds=new Set([...fields.filter(Boolean).map(f=>f.sourceId),...(x.citations||[]).map(c=>c.sourceId)]);return {policyVersion:state.policy.version,fields:fields.map(f=>{if(!f||f.status!=='APPROVED')fail('STALE_BRANCH_EVIDENCE','Current approved exact facts are required.');return {id:f.id,revision:f.revision,sourceHash:f.sourceHash,sourceVersion:f.sourceVersion,value:f.value,unit:f.unit};}),sources:[...sourceIds].map(id=>{const s=state.sources.find(s=>s.id===id);if(!s||['SUPERSEDED','SOURCE_FAILED','REJECTED'].includes(s.status))fail('STALE_BRANCH_EVIDENCE','Branch evidence is unavailable or superseded.');return {id:s.id,hash:s.hash,version:s.version};})};}
async function freshness(state,b){const x=currentTarget(state,b.kind,b.targetId);if(x.revision!==b.baseRevision||await baseDigest(b.kind,x)!==b.baseDigest)fail('STALE_BRANCH_BASE','The base changed. Create a new branch; no silent rebase is permitted.');if(JSON.stringify(pins(state,b.kind,x))!==JSON.stringify(b.evidencePins))fail('STALE_BRANCH_EVIDENCE','A cited fact, source or governing policy changed.');return x;}
async function digest(b){return hash(JSON.stringify({version:BRANCH_VERSION,id:b.id,kind:b.kind,targetId:b.targetId,baseRevision:b.baseRevision,baseDigest:b.baseDigest,evidencePins:b.evidencePins,revision:b.revision,candidate:b.candidate,contributors:b.contributors}));}
function snapshot(b,actor,reason){return {revision:b.revision,digest:b.digest,candidate:structuredClone(b.candidate),actor:actor.id,reason,at:now()};}
function exact(b,input){if(input.revision!==b.revision||input.digest!==b.digest)fail('STALE_BRANCH_REVISION','Inspect the exact current branch revision and digest before this action.');}
async function validate(state,b){if(b.kind==='DRAFT'){const qc=qcDraft(structuredClone(state),{...target(state,b.kind,b.targetId),...b.candidate});if(!qc.passed)fail('BRANCH_QC_FAILED','Branch statements failed source/value/unit/citation QC.');return {passed:true,kind:'DETERMINISTIC_DRAFT_QC',checks:qc.checks};}const copy=structuredClone(state);await lifecycleAction(copy,{operation:'rule',...b.candidate,predecessorId:b.targetId},{id:b.createdBy,role:'author'});return {passed:true,kind:'BOUNDED_RULE_SCHEMA_AND_EXACT_SOURCE',checks:['typed operators','verbatim jurisdiction/category/parameters','current evidence','requirement dependencies']};}
export async function branchAction(state,input,actor){const branches=hydrateBranches(state),op=input.operation;let b,result;
 if(op==='create'){
  role(actor,authors);strict(input,['kind','targetId','name','reason']);if(branches.records.length>=100)fail('BRANCH_QUOTA','At most 100 controlled branches are supported.',413);const x=currentTarget(state,input.kind,input.targetId),reason=requireValue(input.reason,'Branch reason',2000);
  b={id:uid('branch'),name:requireValue(input.name,'Branch name',160),kind:input.kind,targetId:x.id,baseRevision:x.revision,baseDigest:await baseDigest(input.kind,x),evidencePins:pins(state,input.kind,x),base:input.kind==='DRAFT'?draftBody(x):ruleBody(x),candidate:input.kind==='DRAFT'?draftBody(x):ruleBody(x),revision:1,createdBy:actor.id,contributors:[actor.id],createdAt:now(),status:'WORKING',history:[],release:false};b.digest=await digest(b);b.history.push(snapshot(b,actor,reason));branches.records.push(b);result={branchId:b.id,revision:b.revision,digest:b.digest};
 }else{
  b=branches.records.find(x=>x.id===input.id);if(!b)fail('BRANCH_NOT_FOUND','This branch is unavailable in the authorized workspace.',404);strict(input,['id','revision','digest','reason',...(op==='update'?['statementId','text','candidate']:op==='review'?['choice']:[])]);exact(b,input);
  const reason=requireValue(input.reason,'Branch action reason',2000);
  if(['MERGED','ABANDONED'].includes(b.status))fail('BRANCH_CLOSED','This branch is already closed.');
  if(op==='abandon'){role(actor,authors);if(actor.id!==b.createdBy&&actor.role!=='owner')fail('FORBIDDEN','Only the branch author or owner may abandon it.',403);b.status='ABANDONED';b.closedBy=actor.id;b.closedAt=now();b.closeReason=reason;}
  else {
   await freshness(state,b);
   if(op==='update'){
    role(actor,authors);if(actor.id!==b.createdBy)fail('BRANCH_AUTHOR_REQUIRED','Only the named branch author may revise this proposal.',403);if(!['WORKING','NEEDS_REVIEW','REJECTED','APPROVED'].includes(b.status))fail('BRANCH_REVIEW_PENDING','Withdraw or obtain a review outcome before editing a submitted branch.');
    if(b.history.length>=50)fail('BRANCH_HISTORY_QUOTA','Create a new branch after 50 candidate revisions.',413);
    if(b.kind==='DRAFT'){if(input.candidate!==undefined)fail('BRANCH_SCHEMA','Draft updates preserve citations, values and units; edit one statement text.',400);const st=b.candidate.statements.find(s=>s.id===input.statementId);if(!st)fail('BRANCH_STATEMENT','Select a statement in this branch.',404);st.text=requireValue(input.text,'Statement text',2000);}
    else {if(input.text!==undefined||input.statementId!==undefined)fail('BRANCH_SCHEMA','Rule branches use a complete typed candidate.',400);if(!input.candidate||Array.isArray(input.candidate)||typeof input.candidate!=='object')fail('BRANCH_SCHEMA','Provide a typed rule candidate.',400);const candidate=structuredClone(input.candidate);for(const k of Object.keys(candidate))if(!['label','kind','market','parameters','expression','category','requirementIds','evidenceRefs','citations'].includes(k))fail('BRANCH_SCHEMA',`Unsupported rule candidate property: ${k}.`,400);const scratch=structuredClone(state);await lifecycleAction(scratch,{...candidate,operation:'rule',predecessorId:b.targetId},actor);b.candidate=candidate;}
    b.revision++;b.status='WORKING';b.review=null;b.contributors=[...new Set([...b.contributors,actor.id])];b.digest=await digest(b);b.history.push(snapshot(b,actor,reason));b.updatedAt=now();
   }else if(op==='submit'){
    role(actor,authors);if(actor.id!==b.createdBy)fail('BRANCH_AUTHOR_REQUIRED','The branch author must submit this exact proposal.',403);if(b.status!=='WORKING')fail('BRANCH_STATE','Only a working proposal can be submitted.');if(JSON.stringify(b.base)===JSON.stringify(b.candidate))fail('BRANCH_NO_CHANGE','No content or rule change has been proposed.');b.qc=await validate(state,b);b.status='WAITING_HUMAN_REVIEW';b.submittedAt=now();
   }else if(op==='review'){
    role(actor,reviewers);if(b.contributors.includes(actor.id))fail('INDEPENDENT_REVIEW_REQUIRED','A branch contributor cannot review their own proposal.',403);if(!['WAITING_HUMAN_REVIEW','APPROVED'].includes(b.status))fail('BRANCH_STATE','Submit this exact candidate before independent review.');if(!['APPROVE','REQUEST_EVIDENCE','REJECT'].includes(input.choice))fail('BRANCH_DECISION','Choose approve, request evidence or reject.',400);b.qc=await validate(state,b);const review={id:uid('branchReview'),branchId:b.id,revision:b.revision,digest:b.digest,reviewer:actor.id,role:actor.role,choice:input.choice,reason,at:now()};branches.reviews.push(review);b.review=review;b.status={APPROVE:'APPROVED',REQUEST_EVIDENCE:'NEEDS_REVIEW',REJECT:'REJECTED'}[input.choice];
   }else if(op==='merge'){
    role(actor,authors);if(b.status!=='APPROVED'||!b.review||b.review.choice!=='APPROVE'||b.review.revision!==b.revision||b.review.digest!==b.digest||b.contributors.includes(b.review.reviewer))fail('BRANCH_APPROVAL_REQUIRED','Merge requires an independent approval of this exact current proposal.');await validate(state,b);
    if(b.kind==='DRAFT'){const x=target(state,b.kind,b.targetId);Object.assign(x,structuredClone(b.candidate));x.revision++;x.lastEditedBy=actor.id;x.editContributors=[...new Set([...(x.editContributors||[]),...b.contributors,actor.id])];x.status='CANDIDATE';x.qc=qcDraft(state,x);x.branchMerge={branchId:b.id,branchRevision:b.revision,branchDigest:b.digest,reviewId:b.review.id,mergedBy:actor.id,at:now()};for(const d of state.decisions.filter(d=>d.targetId===x.id))d.status='STALE';b.mergedTarget={id:x.id,revision:x.revision,status:'CANDIDATE'};}
    else {const r=await lifecycleAction(state,{operation:'rule',...b.candidate,predecessorId:b.targetId},actor);b.mergedTarget={id:r.recordId,revision:r.revision,status:'CANDIDATE'};}
    b.status='MERGED';b.mergedAt=now();b.mergedBy=actor.id;b.mergeReason=reason;
   }else fail('BRANCH_OPERATION','Unsupported controlled branch operation.',400);
  }
  result={branchId:b.id,revision:b.revision,digest:b.digest,status:b.status,mergedTarget:b.mergedTarget||null};
 }
 audit(state,actor,`branch:${op}`,b.id,{branchRevision:b.revision,digest:b.digest,baseRevision:b.baseRevision,status:b.status,reason:input.reason,release:false});return result;
}
export async function branchOverview(state){const copy=structuredClone(state),b=hydrateBranches(copy);const records=[];for(const x of b.records){let problem=null;if(!['MERGED','ABANDONED'].includes(x.status))try{await freshness(copy,x);}catch(e){problem={code:e.code,message:e.message};}records.push({...x,effectiveStatus:problem?'STALE':x.status,problem});}return {version:BRANCH_VERSION,records,reviews:b.reviews,authority:'Merge creates a new unapproved candidate. Scientific approval and release are separate human gates.'};}
