/** Compact labels for bounded capability results; excludes full requirements, pages, architecture and proposals. */
export const CAPABILITY_LABELS={
  "X01": "Enterprise CMC Source Connector Mesh",
  "X02": "Source Adapter SDK",
  "X03": "Source Contract Monitor",
  "X04": "Multimodal CMC Ingestion",
  "X05": "Paper Batch Record Intelligence",
  "X06": "Atomic CMC Fact Compiler",
  "X07": "Unit + Scientific Context Engine",
  "X08": "CMC Ontology",
  "X09": "CMC Regulatory Knowledge Base",
  "X10": "Requirement-to-Data Mapper",
  "X11": "CMC Digital Twin",
  "X12": "Batch Genealogy Graph",
  "X13": "Process Genealogy Graph",
  "X14": "CMC Evidence Graph",
  "X15": "Dependency Graph",
  "X16": "Cross-Document Consistency Guardian",
  "X17": "Cross-Dossier Consistency Guardian",
  "X18": "Specification Consistency Engine",
  "X19": "Stability Intelligence",
  "X20": "Comparability Evidence Engine",
  "X21": "Statistical / Trend Analysis Workspace",
  "X22": "Scale-Up & Tech-Transfer Evidence Map",
  "X23": "Structured CMC Content Library",
  "X24": "Modular Module 3 Authoring",
  "X25": "Evidence-Bound Data-to-Text",
  "X26": "Controlled Content Reuse",
  "X27": "Template & Style Engine",
  "X28": "AI CMC Authoring Agent",
  "X29": "Independent CMC QC Agent",
  "X30": "Technical Formatting Engine",
  "X31": "Module 3 Structural Validator",
  "X32": "eCTD Technical Preflight",
  "X33": "Submission Readiness Engine",
  "X34": "CMC Readiness Scorecard",
  "X35": "CDMO Collaboration Workspace",
  "X36": "Global Market CMC Matrix",
  "X37": "Change Classification Assistant",
  "X38": "Market-Specific Variation Mapper",
  "X39": "Global CMC Change Simulator",
  "X40": "CMC Blast-Radius Engine",
  "X41": "Proof-of-Non-Impact",
  "X42": "Selective Staleness Propagation",
  "X43": "CMC Regression Engine",
  "X44": "CMC Policy-as-Code",
  "X45": "Regulatory Requirement Test Coverage",
  "X46": "Decision Dependency Graph",
  "X47": "Revision-Bound CMC Decision Contract",
  "X48": "Automatic Approval Invalidation",
  "X49": "Historical CMC Decision Replay",
  "X50": "CMC State Time Machine",
  "X51": "Submission Snapshot",
  "X52": "As-Submitted vs Current-State Comparator",
  "X53": "Health Authority Question Intake",
  "X54": "Similar HAQ / Precedent Retrieval",
  "X55": "Source-Linked HA Response Drafting",
  "X56": "Query-to-Dossier Dependency Map",
  "X57": "Query Outcome Memory",
  "X58": "Reviewer Query Risk Predictor",
  "X59": "CMC Decision Debt Register",
  "X60": "Continuous CMC Drift Detection",
  "X61": "Controlled Correction Propagation",
  "X62": "Submission / RIM Handoff",
  "X63": "QMS Change-Control Handoff",
  "X64": "Closure Evidence Verification",
  "X65": "Persistent Closure Monitoring",
  "X66": "CMC Knowledge Memory",
  "X67": "Portfolio CMC Command Center",
  "X68": "Executive CMC Change Radar"
};
