import {comparison,dependencyGraph,blastRadius,readiness,qcDraft,snapshotDiff,ForgeError} from './core.mjs';
import {retrieveMemory,debtRegister,drift} from './agentic.mjs';
import {ADAPTER_CONTRACT} from './tool-adapters.mjs';
import {lifecycleProjection,LIFECYCLE_IDS} from './lifecycle.mjs';
import {CAPABILITY_LABELS} from './capability-labels.mjs';
/** Explicit source-defined capability projections. Unconfigured capabilities never fabricate output. */
export function capability(state,id,input={}){const def=Object.hasOwn(CAPABILITY_LABELS,id)?{name:CAPABILITY_LABELS[id]}:null;if(!def)throw new ForgeError('UNKNOWN_CAPABILITY','Unknown source-defined capability.');if(LIFECYCLE_IDS.includes(id))return lifecycleProjection(state,id,input);let data,status='AVAILABLE';const active=state.fields.filter(f=>!['STALE','REJECTED'].includes(f.status));switch(id){
 case 'X01':case 'X02':data={contract:ADAPTER_CONTRACT,connectors:['LIMS','MES','QMS','RIM','PUBLISHING'].map(kind=>({kind,status:'UNCONFIGURED'}))};status='CONFIGURATION_REQUIRED';break;
 case 'X03':data={sourceContracts:state.sources.map(s=>({id:s.id,version:s.version,permissionPresent:Boolean(s.permission),hashPresent:Boolean(s.hash),parser:s.parser,status:s.status}))};break;
 case 'X04':case 'X05':data={storedOriginals:state.sources.filter(s=>['application/pdf','image/png','image/jpeg'].includes(s.type)).map(s=>({id:s.id,status:s.status})),documentVisionParser:'NOT_CONFIGURED'};status='CONFIGURATION_REQUIRED';break;
 case 'X06':data={facts:active,rawValuesPreserved:true};break;
 case 'X07':data={normalizations:active.filter(f=>f.normalization),uncertain:active.filter(f=>f.status==='NEEDS_REVIEW')};break;
 case 'X08':data={recordedTerms:[...new Set(active.map(f=>f.parameter))],relationships:state.lineage,ontologyProfile:'USER_REVIEW_REQUIRED'};status='BOUNDED_IMPLEMENTATION';break;
 case 'X09':case 'X10':data={requirements:state.requirements.map(r=>({...r,evidence:active.filter(f=>f.parameter===r.parameter&&f.status==='APPROVED').map(f=>f.id)}))};break;
 case 'X11':data={product:state.product,revision:state.version,sources:state.sources.map(({text,...s})=>s),batches:[...new Set(active.map(f=>f.batch))],facilities:[...new Set(active.map(f=>f.facility).filter(Boolean))],markets:state.markets};break;
 case 'X12':case 'X13':case 'X22':data={recordedRelationships:state.lineage,limitation:'Only manually recorded source-linked lineage; no inferred process, scale-up or technology-transfer proof.'};status='BOUNDED_IMPLEMENTATION';break;
 case 'X14':case 'X15':case 'X46':data=dependencyGraph(state);break;
 case 'X16':data={conflicts:state.conflicts,unresolved:state.conflicts.filter(c=>c.status==='OPEN')};break;
 case 'X17':data={draftQC:state.drafts.map(d=>({id:d.id,...qcDraft(state,d)})),filedCurrentDrift:drift(state)};break;
 case 'X18':data={contexts:comparison(state).map(c=>({parameter:c.parameter,comparable:c.comparable,reason:c.reason,fields:c.fields.map(f=>({id:f.id,method:f.method,unit:f.unit,low:f.low,high:f.high}))}))};break;
 case 'X19':data={recordedStability:active.filter(f=>/stability|time|degrad/i.test(f.parameter)),missingProtocol:!state.sources.some(s=>/stability/i.test(s.name)),limitation:'No validated stability model or extrapolation.'};status='BOUNDED_IMPLEMENTATION';break;
 case 'X20':case 'X21':data={comparisons:comparison(state),interpretation:'Descriptive statistics only; no autonomous product disposition.'};break;
 case 'X23':case 'X26':data={approvedContent:state.drafts.filter(d=>d.status==='APPROVED'),approvedTemplates:state.templates.filter(t=>t.status==='APPROVED'),staleContent:state.drafts.filter(d=>d.status==='STALE')};break;
 case 'X24':case 'X25':case 'X28':data={drafts:state.drafts,authoringModes:['deterministic-source-template','configured-AI-candidate'],humanReviewRequired:true};break;
 case 'X27':data={templates:state.templates,styleProfile:'CONTROLLED_TEMPLATE_REVIEW_REQUIRED'};status='BOUNDED_IMPLEMENTATION';break;
 case 'X29':case 'X31':data={results:state.drafts.map(d=>({draftId:d.id,sectionSupported:['3.2.S','3.2.P'].includes(d.section),...qcDraft(state,d)}))};break;
 case 'X30':data={exports:state.exports.map(e=>({id:e.id,format:e.manifest.format,hash:e.hash})),formats:['JSON evidence snapshot','PDF','DOCX','HTML','Technical handoff ZIP'],endpoint:'/api/export',technicalProfile:'FORGE_TECHNICAL_HANDOFF/1',limitation:'Authenticates the server-owned frozen record; technical preflight does not establish eCTD conformity, PDF/A or agency acceptance.'};status='BOUNDED_IMPLEMENTATION';break;
 case 'X32':data={status:'PUBLISHING_PROFILE_REQUIRED',blockedReasons:['Jurisdiction-specific publishing profile not configured','Qualified publishing-system preflight not executed'],conformanceClaim:false};status='CONFIGURATION_REQUIRED';break;
 case 'X33':case 'X34':data=readiness(state);break;
 case 'X35':data={objectScopedPartnerAccess:'EXACT_OBJECT_REVISION',objectKinds:['source','field','draft','query','action'],endpoint:'/api/sharing',guestPortal:'/collaboration',controls:['permission basis','expiry','revoke','redacted dependencies','explicit source-original permission','shared notes','review requests'],verification:'QUERY_AUTHORIZED_SERVER_RECORDS',limitation:'A grant does not grant Site audience access, whole-workspace membership or scientific authority.'};status='BOUNDED_IMPLEMENTATION';break;
 case 'X36':case 'X38':data={markets:state.markets.map(m=>({...m,affectedChanges:state.changes.filter(c=>m.sourceIds.includes(c.oldSourceId)).map(c=>c.id),reportingCategory:'HUMAN_REVIEW_REQUIRED'}))};break;
 case 'X37':data={changes:state.changes.map(c=>({id:c.id,category:'UNKNOWN',candidateBoundary:'Approved jurisdiction-specific classification rules and human decision required.'}))};status='CONFIGURATION_REQUIRED';break;
 case 'X39':case 'X40':case 'X41':if(!input.sourceId)throw new ForgeError('SOURCE_REQUIRED','Select the controlled source for impact analysis.');data=blastRadius(state,input.sourceId);break;
 case 'X42':case 'X48':data={staleFacts:state.fields.filter(f=>f.status==='STALE'),staleDrafts:state.drafts.filter(d=>d.status==='STALE'),invalidatedDecisions:state.decisions.filter(d=>d.status==='STALE'),changes:state.changes};break;
 case 'X43':data={revision:state.version,readiness:readiness(state),draftChecks:state.drafts.filter(d=>d.status!=='STALE').map(d=>qcDraft(state,d))};break;
 case 'X44':case 'X45':data={policy:state.policy,requirements:state.requirements.map(r=>({...r,coverage:active.some(f=>f.parameter===r.parameter&&f.status==='APPROVED')?'EVIDENCE_PRESENT':'GAP',executableRegulatoryRule:'NOT_CONFIGURED'}))};status='BOUNDED_IMPLEMENTATION';break;
 case 'X47':data={decisions:state.decisions,contractFields:['source hashes','candidate revision','reviewer','rule version','workflow version','model version']};break;
 case 'X49':case 'X50':data={historyEndpoint:'/api/forge?workspace=<authorized workspace>&history=1',currentRevision:state.version,serverHashVerificationRequired:true};break;
 case 'X51':data={snapshots:state.exports.map(e=>({id:e.id,hash:e.hash,at:e.at,manifest:e.manifest}))};break;
 case 'X52':data={comparisons:state.exports.map(e=>({exportId:e.id,comparison:snapshotDiff(e.manifest,state)}))};break;
 case 'X53':case 'X55':case 'X56':data={queries:state.queries,dependencyEdges:state.queries.flatMap(q=>q.fieldIds.map(fieldId=>({from:fieldId,to:q.id,reason:'HA response evidence'})))};break;
 case 'X54':case 'X57':case 'X66':data={memory:retrieveMemory(state,input.query||'',50)};break;
 case 'X58':data={predictions:readiness(state).missing.map(p=>({question:`What controlled evidence supports ${p}?`,state:'PREDICTION',basis:'Current evidence gap'})),trainedModel:'NOT_ESTABLISHED'};status='BOUNDED_IMPLEMENTATION';break;
 case 'X59':case 'X67':case 'X68':data={readiness:readiness(state),debt:debtRegister(state),markets:state.markets,queries:state.queries,changes:state.changes,scope:'Current authorized workspace; cross-product aggregation not established.'};break;
 case 'X60':data={divergences:drift(state),mode:'ON_DEMAND',continuousScheduler:'NOT_CONFIGURED'};status='BOUNDED_IMPLEMENTATION';break;
 case 'X61':data={revisedFields:active.filter(f=>f.correction),staleDependents:state.drafts.filter(d=>d.status==='STALE'),humanReReviewRequired:true};break;
 case 'X62':case 'X63':data={handoffKind:id==='X62'?'RIM/PUBLISHING':'QMS',adapterContract:ADAPTER_CONTRACT,liveStatus:'UNCONFIGURED',automaticRelease:false};status='CONFIGURATION_REQUIRED';break;
 case 'X64':case 'X65':data={actions:state.actions,independentVerifierRequired:true,reopeningOnSourceChange:true,continuousScheduler:'NOT_CONFIGURED'};status='BOUNDED_IMPLEMENTATION';break;
 }
 return {id,name:def.name,status,inputRevision:state.version,data,humanAuthority:false,limitation:'Scope shown above is the implemented bounded projection. External integrations, scientific qualification and expanded interpretation require their own proof.'};}
