import {env} from 'cloudflare:workers';
import bcrypt from './vendor/bcrypt.cjs';
import {AUTH_COOKIE,LOGGED_OUT_COOKIE,SESSION_SECONDS,cookie,cookieValue,randomToken,tokenDigest} from './auth-policy';
export type ForgeIdentity={userId:string;displayName:string;email:string;fullName:string|null;emailVerified:boolean;displayEmail:string;authProvider:string;accountId:string};
export type Account={id:string;email:string;display_name:string;password_hash:string|null;email_verified:number;provider:string;provider_subject:string|null;active:number;legacy_user_id?:string|null;legacy_email?:string|null};
export class AuthError extends Error{constructor(message:string,public status=400){super(message);}}
export function authDB(){if(!env.DB)throw new AuthError('Account storage is temporarily unavailable.',503);return env.DB;}
export async function readOwnSession(cookieHeader:string|null):Promise<ForgeIdentity|null>{const token=cookieValue(cookieHeader,AUTH_COOKIE);if(!token||token.length!==43)return null;const account=await authDB().prepare('SELECT a.*,l.legacy_user_id,l.legacy_email FROM forge_auth_sessions s JOIN forge_auth_accounts a ON a.id=s.account_id LEFT JOIN forge_auth_legacy_links l ON l.account_id=a.id WHERE s.token_hash=? AND s.expires_at>? AND s.revoked=0 AND a.active=1').bind(await tokenDigest(token),new Date().toISOString()).first<Account>();if(!account)return null;return {userId:account.legacy_user_id||account.id,accountId:account.id,displayName:account.display_name,email:account.legacy_email||account.email,fullName:account.display_name,emailVerified:!!account.legacy_user_id||account.email_verified===1,displayEmail:account.email,authProvider:account.provider};}
export async function authRateLimit(request:Request,email:string,kind:string){const now=Date.now(),window=Math.floor(now/900000);const ip=request.headers.get('cf-connecting-ip')||'unknown';const limits:[string,number][]=[[`${kind}:ip:${ip}:${window}`,30]];if(kind!=='google')limits.push([`${kind}:account:${email}:${window}`,8]);for(const [key,limit] of limits){const hash=await tokenDigest(key);const row=await authDB().prepare('INSERT INTO forge_auth_attempts(bucket_hash,attempts,expires_at) VALUES(?,1,?) ON CONFLICT(bucket_hash) DO UPDATE SET attempts=attempts+1 RETURNING attempts').bind(hash,new Date(now+1800000).toISOString()).first<{attempts:number}>();if(!row||row.attempts>limit)throw new AuthError('Too many account requests. Try again after 15 minutes.',429);}await authDB().prepare('DELETE FROM forge_auth_attempts WHERE expires_at<?').bind(new Date(now).toISOString()).run();}
export async function passwordHash(password:string){return bcrypt.hash(password,12);}
export async function passwordMatches(password:string,hash:string){return bcrypt.compare(password,hash);}
export async function openSession(accountId:string,oldCookie:string|null){const now=Date.now(),token=randomToken(),db=authDB();const previous=cookieValue(oldCookie,AUTH_COOKIE);if(previous)await db.prepare('UPDATE forge_auth_sessions SET revoked=1 WHERE token_hash=?').bind(await tokenDigest(previous)).run();await db.batch([db.prepare('DELETE FROM forge_auth_sessions WHERE expires_at<?').bind(new Date(now).toISOString()),db.prepare('INSERT INTO forge_auth_sessions(token_hash,account_id,created_at,expires_at,revoked) VALUES(?,?,?,?,0)').bind(await tokenDigest(token),accountId,new Date(now).toISOString(),new Date(now+SESSION_SECONDS*1000).toISOString())]);const h=new Headers({'cache-control':'no-store','content-type':'application/json'});h.append('set-cookie',cookie(AUTH_COOKIE,token,SESSION_SECONDS));h.append('set-cookie',cookie(LOGGED_OUT_COOKIE,'1',365*86400));return h;}
export async function closeSession(cookieHeader:string|null){const token=cookieValue(cookieHeader,AUTH_COOKIE);if(token)await authDB().prepare('UPDATE forge_auth_sessions SET revoked=1 WHERE token_hash=?').bind(await tokenDigest(token)).run();const h=new Headers({'cache-control':'no-store','content-type':'application/json'});h.append('set-cookie',cookie(AUTH_COOKIE,'',0));h.append('set-cookie',cookie(LOGGED_OUT_COOKIE,'1',365*86400));return h;}
export function authFailure(error:unknown){const status=error instanceof AuthError?error.status:error instanceof SyntaxError?400:error instanceof Error&&error.message==='BODY_TOO_LARGE'?413:error instanceof Error&&/Same-origin/.test(error.message)?403:503;return Response.json({error:error instanceof AuthError?error.message:status===403?'Same-origin request required.':status===400?'Invalid account request.':status===413?'Account request exceeds 4 KB.':'Account request could not complete. Please retry.'},{status,headers:{'cache-control':'no-store'}});}
export function googleConfigured(){return !!env.GOOGLE_CLIENT_ID&&!!env.GOOGLE_CLIENT_SECRET&&!!env.GOOGLE_REDIRECT_URI;}
