/** Names needed by implemented user workflows only; full design register stays server-side. */
export const LIFECYCLE_LABELS={
  "X08": "CMC Ontology",
  "X09": "CMC Regulatory Knowledge Base",
  "X10": "Requirement-to-Data Mapper",
  "X11": "CMC Digital Twin",
  "X12": "Batch Genealogy Graph",
  "X13": "Process Genealogy Graph",
  "X17": "Cross-Dossier Consistency Guardian",
  "X18": "Specification Consistency Engine",
  "X19": "Stability Intelligence",
  "X20": "Comparability Evidence Engine",
  "X21": "Statistical / Trend Analysis Workspace",
  "X22": "Scale-Up & Tech-Transfer Evidence Map",
  "X23": "Structured CMC Content Library",
  "X26": "Controlled Content Reuse",
  "X27": "Template & Style Engine",
  "X31": "Module 3 Structural Validator",
  "X36": "Global Market CMC Matrix",
  "X37": "Change Classification Assistant",
  "X38": "Market-Specific Variation Mapper",
  "X39": "Global CMC Change Simulator",
  "X40": "CMC Blast-Radius Engine",
  "X41": "Proof-of-Non-Impact",
  "X42": "Selective Staleness Propagation",
  "X43": "CMC Regression Engine",
  "X44": "CMC Policy-as-Code",
  "X45": "Regulatory Requirement Test Coverage",
  "X46": "Decision Dependency Graph",
  "X53": "Health Authority Question Intake",
  "X54": "Similar HAQ / Precedent Retrieval",
  "X55": "Source-Linked HA Response Drafting",
  "X56": "Query-to-Dossier Dependency Map",
  "X57": "Query Outcome Memory",
  "X58": "Reviewer Query Risk Predictor",
  "X61": "Controlled Correction Propagation",
  "X64": "Closure Evidence Verification",
  "X65": "Persistent Closure Monitoring"
};
