import {ForgeError,hash,uid,now} from './core.mjs';
import {LIFECYCLE_LABELS} from './lifecycle-labels.mjs';

/** Source-defined lifecycle controls. All output remains bounded engineering evidence. */
export const LIFECYCLE_VERSION='forge-lifecycle/2';
export const LIFECYCLE_IDS=['X08','X09','X10','X11','X12','X13','X17','X18','X19','X20','X21','X22','X23','X26','X27','X31','X36','X37','X38','X39','X40','X41','X42','X43','X44','X45','X46','X53','X54','X55','X56','X57','X58','X61','X64','X65'];
const COLLECTIONS=['entities','relations','requirements','rules','templates','blocks','reuses','dossiers','observations','comparabilities','transfers','changes','classifications','branches','regressions','haqs','outcomes','closures','verifications','corrections'];
const TYPES=['product','substance','site','material','process','method','specification','batch','equipment'];
const SECTIONS=/^(2\.3(?:\.[SP](?:\.\d{1,2})*)?|3\.2\.[SP](?:\.\d{1,2})*)$/;
const OPS=new Set(['ALL_APPROVED','NO_OPEN_CONFLICTS','HAS_SOURCE_CONTEXT','REQUIRED_PARAMETER','SOURCE_REVISION_CURRENT']);
const RELATIONS={RAW_MATERIAL_TO_INTERMEDIATE:['material','material'],INTERMEDIATE_TO_BATCH:['material','batch'],BATCH_TO_FINISHED_PRODUCT:['batch','product'],PROCESS_STEP_TO_CPP:['process','specification'],PROCESS_STEP_TO_CQA:['process','specification'],USES_EQUIPMENT:['process','equipment'],AT_SITE:['process','site'],USES_MATERIAL:['process','material'],USES_METHOD:['process','method'],HAS_SPECIFICATION:['product','specification'],PROCESS_STEP_TO_STEP:['process','process']};
const AUTHOR_ROLES=['owner','admin','author'];
const REVIEW_ROLES=['owner','reviewer','approver'];
const DENY_KEYS=new Set(['__proto__','constructor','prototype']);
const fail=(code,msg,status=400)=>{throw new ForgeError(code,msg,status);};
const copy=x=>structuredClone(x);
function text(x,label,max=500){if(typeof x!=='string'||!x.trim()||x.length>max)fail('LIFECYCLE_INPUT',`${label} is required and must fit ${max} characters.`);return x.trim();}
function list(x,label,max=100){if(!Array.isArray(x)||x.length>max)fail('LIFECYCLE_INPUT',`${label} must be an array with at most ${max} entries.`);return x;}
function schema(x,allowed){if(!x||typeof x!=='object'||Array.isArray(x))fail('LIFECYCLE_INPUT','Use a structured lifecycle operation.');for(const k of Object.keys(x))if(DENY_KEYS.has(k)||!allowed.includes(k))fail('LIFECYCLE_SCHEMA',`Unsupported lifecycle property: ${k}. Scientific properties must be exact source/fact references.`);}
function integer(x,label,min=0,max=1000000){if(!Number.isSafeInteger(x)||x<min||x>max)fail('LIFECYCLE_INPUT',`${label} is outside supported integer bounds.`);return x;}
function enumValue(x,values,label){if(!values.includes(x))fail('LIFECYCLE_INPUT',`Unsupported ${label}.`);return x;}
function section(x){const v=text(x,'CTD section',40);if(!SECTIONS.test(v))fail('LIFECYCLE_INPUT','Use a supported Module 2.3 or 3.2.S / 3.2.P section identifier.');return v;}
function role(actor,roles){if(!actor?.id)fail('UNAUTHENTICATED','A verified workspace principal is required.',401);if(!roles.includes(actor.role))fail('FORBIDDEN','Your workspace role cannot perform this lifecycle operation.',403);}
export function hydrateLifecycle(state){state.ext??={};state.ext.lifecycle??={version:LIFECYCLE_VERSION,decisions:[],invalidations:[]};const e=state.ext.lifecycle;if(e.version!==LIFECYCLE_VERSION)fail('LIFECYCLE_VERSION','This lifecycle schema needs an explicit migration.',409);for(const c of COLLECTIONS)e[c]??=[];return e;}
function all(state){const e=hydrateLifecycle(state);return COLLECTIONS.flatMap(c=>e[c].map(x=>({...x,collection:c})));}
function found(state,id){const x=all(state).find(x=>x.id===id);if(!x)fail('LIFECYCLE_NOT_FOUND','The lifecycle record is unavailable in this authorized workspace.',404);return x;}
function latest(state,x){return !hydrateLifecycle(state)[x.collection].some(y=>y.logicalId===x.logicalId&&y.revision>x.revision);}
function src(state,id,requireText=false){const s=state.sources.find(x=>x.id===id);if(!s)fail('EVIDENCE_SOURCE','Source does not exist in this workspace.',404);if(['SUPERSEDED','SOURCE_FAILED','REJECTED'].includes(s.status))fail('STALE_EVIDENCE','Use a current non-failed source revision.',409);if(!s.permission||!s.hash||!Number.isInteger(s.version))fail('EVIDENCE_SOURCE','Source permission, integrity hash and revision are required.',409);if(requireText&&(!s.text||typeof s.text!=='string'))fail('SOURCE_TEXT_REQUIRED','A preserved original text span is required for this control.',409);return s;}
function fact(state,ref,{approved=true}={}){schema(ref,['fieldId','revision']);const f=state.fields.find(x=>x.id===ref.fieldId);if(!f)fail('EVIDENCE_FACT','Fact does not exist in this workspace.',404);if(ref.revision!==f.revision)fail('STALE_EVIDENCE','The exact fact revision changed.',409);const s=src(state,f.sourceId);if(s.hash!==f.sourceHash||s.version!==f.sourceVersion||s.status!=='PARSED'||!f.span?.raw)fail('STALE_EVIDENCE','Fact must bind the exact parsed source hash, revision and span.',409);if(['STALE','REJECTED','MISSING'].includes(f.status)||(approved&&f.status!=='APPROVED'))fail('UNAPPROVED_EVIDENCE','Current approved facts are required.',409);if(f.value===null||!Number.isFinite(f.value))fail('EVIDENCE_FACT','Numeric evidence cannot be invented or non-finite.',409);return f;}
function refs(state,input,required=true){const a=list(input||[],'Evidence refs');if(required&&!a.length)fail('EVIDENCE_REQUIRED','At least one current source-backed fact revision is required.',409);const seen=new Set();return a.map(r=>{const f=fact(state,r);if(seen.has(f.id))fail('DUPLICATE_EVIDENCE','A fact cannot be repeated to inflate coverage.');seen.add(f.id);return {fieldId:f.id,revision:f.revision,sourceId:f.sourceId,sourceVersion:f.sourceVersion,sourceHash:f.sourceHash,value:f.value,unit:f.unit,parameter:f.parameter,product:f.product,facility:f.facility,batch:f.batch,method:f.method,basis:f.basis,condition:f.condition,low:f.low,high:f.high,span:copy(f.span)};});}
function citations(state,input,required=false){const a=list(input||[],'Source citations',20);if(required&&!a.length)fail('CITATION_REQUIRED','An exact preserved source excerpt is required.',409);return a.map(r=>{schema(r,['sourceId','version','start','end','hash']);const s=src(state,r.sourceId,true);if(r.version!==s.version||r.hash&&r.hash!==s.hash)fail('STALE_EVIDENCE','Citation must match the current exact source revision.',409);const start=integer(r.start,'Citation start',0,s.text.length),end=integer(r.end,'Citation end',1,s.text.length);if(end<=start||end-start>6000)fail('CITATION_BOUNDS','Use a non-empty bounded original source excerpt.');return {sourceId:s.id,sourceVersion:s.version,sourceHash:s.hash,start,end,raw:s.text.slice(start,end),offsetKind:'UTF-16 character offsets'};});}
function dependencies(state,ids=[],approved=true){return list(ids,'Dependencies').map(id=>{const x=found(state,id);if(!latest(state,x)||effectiveStatus(state,x.id)==='STALE')fail('STALE_DEPENDENCY','A dependency has a new or stale revision.',409);if(approved&&effectiveStatus(state,x.id)!=='APPROVED')fail('UNAPPROVED_DEPENDENCY','An independent approval of the exact dependency revision is required.',409);return {id:x.id,revision:x.revision,digest:x.digest};});}
function currentProblems(state,x,seen=new Set()){if(seen.has(x.id))return ['DEPENDENCY_CYCLE'];seen.add(x.id);const issues=[];if(!latest(state,x))issues.push('SUPERSEDED_RECORD');if(hydrateLifecycle(state).invalidations.some(i=>i.recordId===x.id))issues.push('INVALIDATED_DEPENDENCY');for(const r of x.evidenceRefs||[])try{const f=fact(state,{fieldId:r.fieldId,revision:r.revision});if(f.value!==r.value||f.unit!==r.unit||f.sourceHash!==r.sourceHash||f.sourceVersion!==r.sourceVersion)issues.push('EVIDENCE_BINDING_MISMATCH');}catch(e){issues.push(e.code);}for(const c of x.citations||[])try{const s=src(state,c.sourceId,true);if(s.version!==c.sourceVersion||s.hash!==c.sourceHash||s.text.slice(c.start,c.end)!==c.raw)issues.push('STALE_CITATION');}catch(e){issues.push(e.code);}for(const d of x.dependencies||[]){try{const dep=found(state,d.id);if(dep.digest!==d.digest||dep.revision!==d.revision||currentProblems(state,dep,new Set(seen)).length)issues.push('STALE_DEPENDENCY');const decision=hydrateLifecycle(state).decisions.findLast(y=>y.targetId===dep.id&&y.digest===dep.digest&&y.revision===dep.revision);if(x.collection!=='branches'&&d.approvalRequired!==false&&decision?.choice!=='APPROVE')issues.push('DEPENDENCY_DECISION_CHANGED');}catch(e){issues.push(e.code);}}if(x.draftId){const draft=state.drafts.find(d=>d.id===x.draftId);if(!draft||draft.revision!==x.draftRevision||draft.status!=='APPROVED'||JSON.stringify(draft.statements)!==JSON.stringify(x.statements))issues.push('STALE_DRAFT');}for(const r of x.candidateRefs||[])try{fact(state,{fieldId:r.fieldId,revision:r.revision},{approved:false});}catch(e){issues.push(e.code);}return [...new Set(issues)];}
export function effectiveStatus(state,id){const x=found(state,id);if(currentProblems(state,x).length)return 'STALE';const d=hydrateLifecycle(state).decisions.findLast(y=>y.targetId===id&&y.digest===x.digest&&y.revision===x.revision);return d?{APPROVE:'APPROVED',REJECT:'REJECTED',REQUEST_EVIDENCE:'NEEDS_REVIEW',REVISE:'NEEDS_REVIEW'}[d.choice]:'CANDIDATE';}
function project(state,x){return {...copy(x),status:effectiveStatus(state,x.id),issues:currentProblems(state,x),humanAuthority:false};}
async function append(state,collection,body,input,actor){const e=hydrateLifecycle(state);if(all(state).length>=1500)fail('LIFECYCLE_LIMIT','The bounded workspace lifecycle limit is 1500 versions.',413);let prior;if(input.predecessorId){prior=found(state,input.predecessorId);if(prior.collection!==collection||!latest(state,prior))fail('PREDECESSOR_REVISION','Supersede only the latest version in the same record collection.',409);}const record={id:uid(collection.slice(0,10)),logicalId:prior?.logicalId||uid('controlled'),revision:prior?prior.revision+1:1,predecessorId:prior?.id||null,createdBy:actor.id,createdAt:now(),workflowVersion:LIFECYCLE_VERSION,inputWorkspaceRevision:state.version,status:'CANDIDATE',evidenceRefs:[],citations:[],dependencies:[],...body};record.digest=await hash(JSON.stringify(record));e[collection].push(record);return record;}
function supportedLabel(label,evidence,cites){const v=text(label,'Source-backed object label',160);const terms=evidence.flatMap(f=>[f.parameter,f.batch,f.method,f.product,f.facility]).filter(Boolean);if(!terms.includes(v)&&!cites.some(c=>c.raw.includes(v)))fail('UNSUPPORTED_LABEL','Object identity must occur in cited source text or exact fact metadata.');return v;}
function descriptor(state,r){const f=fact(state,{fieldId:r.fieldId,revision:r.revision});return {fieldId:f.id,revision:f.revision,parameter:f.parameter,value:f.value,unit:f.unit,batch:f.batch,method:f.method,basis:f.basis,condition:f.condition,low:f.low,high:f.high,sourceId:f.sourceId,sourceVersion:f.sourceVersion,sourceHash:f.sourceHash,product:f.product,facility:f.facility,timePoint:f.timePoint??null,timeUnit:f.timeUnit||''};}
function context(f){return JSON.stringify([f.parameter,f.product,f.method,f.unit,f.low,f.high,f.condition,f.basis]);}
function comparable(fs){const ok=fs.length>1&&fs.every(f=>f.product&&f.method&&f.unit&&f.condition&&f.basis)&&new Set(fs.map(context)).size===1;const values=fs.map(x=>x.value),n=values.length,mean=n?values.reduce((a,b)=>a+b,0)/n:null;return {comparable:ok,n,minimum:ok?Math.min(...values):null,maximum:ok?Math.max(...values):null,mean:ok?mean:null,sampleSD:ok&&n>1?Math.sqrt(values.reduce((s,x)=>s+(x-mean)**2,0)/(n-1)):null,reason:ok?'Recorded parameter, product, method, unit, limits, condition and basis match.':'At least two records with equal recorded method, unit, limits, condition and basis are required.',interpretation:'Descriptive recorded evidence only; no product disposition, equivalence or scientific qualification.'};}
function ruleCheck(state,rule){const fs=state.fields.filter(f=>f.status==='APPROVED'&&!(()=>{try{fact(state,{fieldId:f.id,revision:f.revision});return false;}catch{return true;}})());let passed=false,evidence=[];const expr=rule.expression;switch(expr.op){case 'ALL_APPROVED':evidence=rule.evidenceRefs.map(r=>r.fieldId);passed=rule.evidenceRefs.length>0&&currentProblems(state,rule).length===0;break;case 'NO_OPEN_CONFLICTS':evidence=state.conflicts.filter(c=>c.status==='OPEN').map(c=>c.id);passed=!evidence.length;break;case 'HAS_SOURCE_CONTEXT':evidence=fs.filter(f=>rule.parameters.includes(f.parameter)&&f.method&&f.unit&&f.basis&&f.condition).map(f=>f.id);passed=rule.parameters.every(p=>fs.some(f=>f.parameter===p&&f.method&&f.unit&&f.basis&&f.condition));break;case 'REQUIRED_PARAMETER':evidence=fs.filter(f=>rule.parameters.includes(f.parameter)).map(f=>f.id);passed=rule.parameters.every(p=>fs.filter(f=>f.parameter===p).length>=expr.count);break;case 'SOURCE_REVISION_CURRENT':evidence=rule.evidenceRefs.map(r=>r.fieldId);passed=!currentProblems(state,rule).length;break;}
return {ruleId:rule.id,revision:rule.revision,digest:rule.digest,operator:expr.op,passed,evidence,authority:'LOCAL_APPROVED_CONTROL_ONLY',interpretation:'A passed technical check is not regulatory acceptance or validation.'};}
function requirementCoverage(state,record){const fs=(record.evidenceRefs||[]).map(r=>{try{return fact(state,{fieldId:r.fieldId,revision:r.revision});}catch{return null;}}).filter(Boolean);const reqs=(record.requirementIds||[]).map(id=>found(state,id));return reqs.map(req=>{const matching=fs.filter(f=>f.parameter===req.parameter);return {requirementId:req.id,revision:req.revision,parameter:req.parameter,requiredCount:req.minCount,availableCount:matching.length,covered:effectiveStatus(state,req.id)==='APPROVED'&&record.market===req.market&&matching.length>=req.minCount&&req.sections.some(s=>record.section===s||record.section?.startsWith(s+'.')),fieldIds:matching.map(f=>f.id),sourceCitations:req.citations,legalConclusion:false};});}
function onlyEntity(state,id,type){const x=found(state,id);if(x.collection!=='entities'||type&&x.kind!==type)fail('ENTITY_TYPE','Select a source-backed entity of the required type.');if(effectiveStatus(state,id)!=='APPROVED')fail('UNAPPROVED_DEPENDENCY','Use the independently approved current entity revision.',409);return x;}
function selected(state,c){const a=hydrateLifecycle(state)[c].map(x=>({...x,collection:c}));return a.filter(x=>latest(state,x)).map(x=>project(state,x));}
function rawRefs(records){return [...new Map(records.flatMap(x=>x.evidenceRefs||[]).map(r=>[`${r.fieldId}@${r.revision}`,{fieldId:r.fieldId,revision:r.revision}])).values()];}
function closureChecks(state,x){return x.expectedChecks.map(check=>{try{const expected=fact(state,check.expected),actual=fact(state,check.actual);const sameContext=context(expected)===context(actual);let passed=check.operator==='CURRENT_APPROVED'||check.operator==='EQUAL'&&sameContext&&actual.value===expected.value||check.operator==='CONTEXT_MATCH'&&sameContext||check.operator==='WITHIN_RECORDED_LIMITS'&&sameContext&&(expected.low!==null||expected.high!==null)&&(expected.low===null||actual.value>=expected.low)&&(expected.high===null||actual.value<=expected.high);return {...check,passed,expectedValue:expected.value,actualValue:actual.value,unit:actual.unit,sourceId:actual.sourceId,sourceHash:actual.sourceHash,reason:passed?'Exact current source-backed check passed.':'Recorded actual evidence does not meet this controlled expected check.'};}catch(e){return {...check,passed:false,reason:e.code};}});}
function signatureRevision(state,x){return {id:x.id,revision:x.revision,digest:x.digest,evidence:x.evidenceRefs.map(r=>({fieldId:r.fieldId,revision:r.revision,sourceId:r.sourceId,sourceVersion:r.sourceVersion,sourceHash:r.sourceHash})),dependencies:x.dependencies,workflowVersion:LIFECYCLE_VERSION,policyVersion:state.policy.version};}

/** Mutates an already cloned authorized workspace. Parent command owns CAS, persistence and audit. */
export async function lifecycleAction(state,input,actor){
 const e=hydrateLifecycle(state),op=text(input.operation,'Lifecycle operation',60);
 role(actor,['owner','admin','author','reviewer','approver']);
 const universal=['action','expectedVersion','operation'];
 const valid=(keys)=>schema(input,[...universal,...keys]);
 const common=['label','evidenceRefs','citations','predecessorId'];
 const author=()=>role(actor,AUTHOR_ROLES),reviewer=()=>role(actor,REVIEW_ROLES);
 let record,result;
 switch(op){
 case 'entity':{
  author();valid([...common,'kind']);const kind=enumValue(input.kind,TYPES,'CMC entity type'),evidenceRefs=refs(state,input.evidenceRefs),cites=citations(state,input.citations);const label=supportedLabel(input.label,evidenceRefs,cites);
  record=await append(state,'entities',{kind,label,evidenceRefs,citations:cites,scientificProperties:evidenceRefs.map(r=>descriptor(state,r)),interpretation:'Source-backed controlled entity; identity does not establish facility qualification or product approval.'},input,actor);break;
 }
 case 'relation':{
  author();valid([...common,'fromId','toId','relationType']);const pair=RELATIONS[input.relationType];if(!pair)fail('RELATION_TYPE','Choose a controlled genealogy relationship.');const from=onlyEntity(state,input.fromId,pair[0]),to=onlyEntity(state,input.toId,pair[1]);if(from.id===to.id)fail('GENEALOGY_CYCLE','A genealogy relation cannot point to itself.');const evidenceRefs=refs(state,input.evidenceRefs),cites=citations(state,input.citations,true);const domain=e.relations.filter(r=>!currentProblems(state,{...r,collection:'relations'}).length);const seen=new Set([to.id]);let again=true;while(again){again=false;for(const r of domain)if(seen.has(r.fromId)&&!seen.has(r.toId)){seen.add(r.toId);again=true;}}if(seen.has(from.id))fail('GENEALOGY_CYCLE','Genealogy must remain an acyclic recorded lineage.');record=await append(state,'relations',{label:text(input.label||`${from.label} → ${to.label}`,'Relationship label',320),fromId:from.id,toId:to.id,relationType:input.relationType,evidenceRefs,citations:cites,dependencies:dependencies(state,[from.id,to.id]),relationshipState:'SOURCE_LINKED_CANDIDATE'},input,actor);break;
 }
 case 'requirement':{
  author();valid([...common,'parameter','market','sections','minCount']);const cites=citations(state,input.citations,true),parameter=text(input.parameter,'Required parameter',100).toLowerCase();if(!cites.some(c=>c.raw.toLowerCase().includes(parameter)))fail('UNSUPPORTED_REQUIREMENT','The required parameter must occur in the exact rule source excerpt.');const sections=list(input.sections,'Requirement sections',20).map(section);if(!sections.length)fail('LIFECYCLE_INPUT','A requirement needs its dossier section mapping.');const market=text(input.market,'Rule jurisdiction',100);if(!cites.some(c=>c.raw.includes(market)))fail('UNSUPPORTED_REQUIREMENT','Jurisdiction must occur in the exact cited requirement excerpt.');record=await append(state,'requirements',{label:text(input.label||parameter,'Requirement label',160),parameter,market,sections,minCount:integer(input.minCount??1,'Minimum evidence count',1,100),evidenceRefs:refs(state,input.evidenceRefs,false),citations:cites,executableControl:'REQUIRED_PARAMETER_COUNT_AND_SECTION',limitation:'Locally curated requirement interpretation; current legal applicability needs a qualified human.'},input,actor);break;
 }
 case 'rule':{
  author();valid([...common,'kind','market','parameters','expression','category','requirementIds']);const cites=citations(state,input.citations,true),kind=enumValue(input.kind,['REQUIREMENT','CLASSIFICATION','WORKFLOW'],'policy kind'),market=text(input.market,'Rule jurisdiction',100);if(!cites.some(c=>c.raw.includes(market)))fail('UNSUPPORTED_RULE','Rule jurisdiction must occur in the cited source.');const parameters=list(input.parameters,'Rule parameters',30).map(p=>text(p,'Parameter',100).toLowerCase());if(!parameters.length||parameters.some(p=>!cites.some(c=>c.raw.toLowerCase().includes(p))))fail('UNSUPPORTED_RULE','Every parameter selector must occur in the cited rule excerpt.');schema(input.expression,['op','count']);if(!OPS.has(input.expression.op))fail('UNSAFE_RULE','Only the bounded declarative policy operators are supported.');const expression={op:input.expression.op,...(input.expression.op==='REQUIRED_PARAMETER'?{count:integer(input.expression.count??1,'Rule evidence count',1,100)}:{})};let category=null;if(kind==='CLASSIFICATION'){category=text(input.category,'Cited reporting category',100);if(!cites.some(c=>c.raw.includes(category)))fail('UNSUPPORTED_CLASSIFICATION','A reporting category cannot be invented; quote it from the exact rule source.');}else if(input.category!==undefined)fail('LIFECYCLE_SCHEMA','A category belongs only to a classification rule.');const requirementIds=list(input.requirementIds||[],'Rule requirement mappings',30);for(const id of requirementIds)if(found(state,id).collection!=='requirements')fail('DEPENDENCY_TYPE','A rule requirement mapping must refer to a requirement.');record=await append(state,'rules',{label:text(input.label,'Rule label',160),kind,market,parameters,expression,category,requirementIds,citations:cites,evidenceRefs:refs(state,input.evidenceRefs,false),dependencies:dependencies(state,requirementIds),machineExecution:'BOUNDED_DECLARATIVE_DSL',authority:'LOCAL_REVIEWED_RULE_CANDIDATE'},input,actor);break;
 }
 case 'template':{
  author();valid([...common,'sections','style']);const cites=citations(state,input.citations,true),sections=list(input.sections,'Template sections',30).map(section);if(!sections.length)fail('LIFECYCLE_INPUT','Provide controlled template sections.');schema(input.style,['headingCase','density','referenceStyle','factOrder']);const style={headingCase:enumValue(input.style.headingCase,['SENTENCE','TITLE'],'heading case'),density:enumValue(input.style.density,['COMPACT','TECHNICAL'],'template density'),referenceStyle:enumValue(input.style.referenceStyle,['SOURCE_ID_AND_REVISION','EXACT_SPAN'],'reference style'),factOrder:enumValue(input.style.factOrder,['PARAMETER','BATCH','SOURCE'],'fact order')};record=await append(state,'templates',{label:text(input.label,'Template label',160),sections,style,citations:cites,evidenceRefs:refs(state,input.evidenceRefs,false),limitation:'Controlled display/style profile; no jurisdiction-specific publishing conformance assertion.'},input,actor);break;
 }
 case 'contentBlock':{
  author();valid([...common,'draftId','draftRevision','market']);const d=state.drafts.find(x=>x.id===input.draftId);if(!d||d.revision!==input.draftRevision||d.status!=='APPROVED'||!d.qc?.passed)fail('APPROVED_DRAFT_REQUIRED','Reuse begins only from an exact approved draft with passing independent QC.',409);const decision=state.decisions.findLast(x=>x.targetId===d.id&&x.revision===d.revision&&x.action==='APPROVE'&&x.status==='CURRENT');if(!decision)fail('APPROVED_DRAFT_REQUIRED','A current exact draft approval is required.',409);const evidenceRefs=refs(state,d.fieldIds.map(id=>({fieldId:id,revision:state.fields.find(x=>x.id===id)?.revision})));record=await append(state,'blocks',{label:text(input.label||d.title,'Content-block label',160),market:text(input.market,'Content market context',100),section:section(d.section),draftId:d.id,draftRevision:d.revision,draftDecisionId:decision.id,evidenceRefs,citations:citations(state,input.citations),statements:copy(d.statements),text:d.statements.map(s=>s.text).join('\n'),draftDigest:await hash(JSON.stringify({id:d.id,revision:d.revision,statements:d.statements})),limitation:'Approved draft copied exactly into a reusable candidate; reuse needs its own review.'},input,actor);break;
 }
 case 'reuseContent':{
  author();valid(['blockId','blockRevision','market','section','templateId','requirementIds','predecessorId','reason']);const b=found(state,input.blockId);if(b.collection!=='blocks'||b.revision!==input.blockRevision)fail('CONTENT_REVISION','Select the exact current content-block revision.',409);const targetSection=section(input.section),depIds=[b.id,...(input.requirementIds||[])];let tpl=null;if(input.templateId){tpl=found(state,input.templateId);if(tpl.collection!=='templates'||!tpl.sections.some(s=>s===targetSection||targetSection.startsWith(s+'.')))fail('TEMPLATE_SECTION','The selected template does not cover this dossier section.',409);depIds.push(tpl.id);}for(const id of input.requirementIds||[])if(found(state,id).collection!=='requirements')fail('DEPENDENCY_TYPE','Select controlled requirement records.');const dependenciesList=dependencies(state,depIds);record=await append(state,'reuses',{label:`${b.label} · ${text(input.market,'Target market',100)}`,market:input.market,section:targetSection,blockId:b.id,blockRevision:b.revision,templateId:tpl?.id||null,requirementIds:input.requirementIds||[],evidenceRefs:refs(state,rawRefs([b])),citations:copy(b.citations),dependencies:dependenciesList,statements:copy(b.statements),text:b.text,style:tpl?.style||null,reuseReason:text(input.reason,'Controlled reuse reason',1000),scientificTextChanged:false},input,actor);break;
 }
 case 'dossier':{
  author();valid([...common,'productId','market','section','blockIds','requirementIds','stateLabel']);const product=onlyEntity(state,input.productId,'product'),blockIds=list(input.blockIds||[],'Dossier blocks',50),requirementIds=list(input.requirementIds||[],'Dossier requirements',50);for(const id of blockIds)if(!['blocks','reuses'].includes(found(state,id).collection))fail('DEPENDENCY_TYPE','Dossier content must refer to controlled blocks or reuse records.');for(const id of requirementIds)if(found(state,id).collection!=='requirements')fail('DEPENDENCY_TYPE','Dossier requirement mappings must refer to controlled requirements.');const deps=dependencies(state,[product.id,...blockIds,...requirementIds]);const evidenceRefs=refs(state,input.evidenceRefs),stateLabel=enumValue(input.stateLabel||'DRAFT',['DRAFT','RECORDED_FILING'],'dossier evidence label');const cites=citations(state,input.citations,stateLabel==='RECORDED_FILING');record=await append(state,'dossiers',{label:text(input.label,'Dossier record label',160),productId:product.id,market:text(input.market,'Dossier market',100),section:section(input.section),blockIds,requirementIds,evidenceRefs,citations:cites,dependencies:deps,stateLabel,filingClaim:'SUPPLIED_RECORD_ONLY',facts:evidenceRefs.map(r=>descriptor(state,r)),limitation:'A recorded filing snapshot does not prove regulator acceptance or successful submission.'},input,actor);break;
 }
 case 'stability':{
  author();valid([...common,'batchId','timeRef']);const batch=onlyEntity(state,input.batchId,'batch'),time=fact(state,input.timeRef);if(!/time|duration|age/i.test(time.parameter)||!['h','hour','hours','day','days','week','weeks','month','months','year','years'].includes(time.unit.toLowerCase())||time.value<0)fail('STABILITY_TIME','Observation time requires an exact approved numeric time fact in a recorded time unit.');const evidenceRefs=refs(state,input.evidenceRefs);if(evidenceRefs.some(r=>r.batch!==batch.label)||time.batch!==batch.label)fail('BATCH_CONTEXT','Stability observations must match the exact recorded batch identity.');if(evidenceRefs.some(r=>r.fieldId===time.id)||evidenceRefs.some(r=>!r.condition))fail('STABILITY_CONTEXT','Each measured observation needs its recorded condition; time is a separate typed fact.');record=await append(state,'observations',{label:text(input.label||`Stability · ${batch.label}`,'Observation label',160),batchId:batch.id,timeRef:{fieldId:time.id,revision:time.revision},recordedTime:time.value,timeUnit:time.unit,evidenceRefs:refs(state,[...input.evidenceRefs,input.timeRef]),measurementRefs:input.evidenceRefs.map(copy),citations:citations(state,input.citations),dependencies:dependencies(state,[batch.id]),extrapolationAllowed:false},input,actor);break;
 }
 case 'comparability':{
  author();valid([...common,'changeId','batchIds','processIds','stabilityIds']);const entityIds=[...list(input.batchIds||[],'Comparison batches',50),...list(input.processIds||[],'Comparison processes',50)];for(const id of input.batchIds||[])onlyEntity(state,id,'batch');for(const id of input.processIds||[])onlyEntity(state,id,'process');const obs=list(input.stabilityIds||[],'Stability evidence',100);for(const id of obs)if(found(state,id).collection!=='observations')fail('DEPENDENCY_TYPE','Select stored stability observation revisions.');const evidenceRefs=refs(state,input.evidenceRefs);const deps=[...entityIds,...obs];if(input.changeId){if(found(state,input.changeId).collection!=='changes')fail('DEPENDENCY_TYPE','Select a controlled change candidate.');deps.push(input.changeId);}const groups=[...Map.groupBy(evidenceRefs,x=>x.parameter)].map(([parameter,rs])=>({parameter,...comparable(rs)}));record=await append(state,'comparabilities',{label:text(input.label,'Comparability assessment label',160),changeId:input.changeId||null,batchIds:input.batchIds||[],processIds:input.processIds||[],stabilityIds:obs,evidenceRefs,citations:citations(state,input.citations),dependencies:dependencies(state,deps),groups,conclusion:'HUMAN_SCIENTIFIC_REVIEW_REQUIRED',equivalenceEstablished:false},input,actor);break;
 }
 case 'transfer':{
  author();valid([...common,'stage','fromSiteId','toSiteId','processIds','batchIds','comparabilityId']);const from=onlyEntity(state,input.fromSiteId,'site'),to=onlyEntity(state,input.toSiteId,'site');if(from.id===to.id)fail('TRANSFER_CONTEXT','A site transfer requires distinct source-backed sites.');const processIds=list(input.processIds,'Transfer processes',50),batchIds=list(input.batchIds,'Transfer batches',50);if(!processIds.length||!batchIds.length)fail('TRANSFER_CONTEXT','A transfer needs process and batch evidence.');for(const id of processIds)onlyEntity(state,id,'process');for(const id of batchIds)onlyEntity(state,id,'batch');const depIds=[from.id,to.id,...processIds,...batchIds];if(input.comparabilityId){if(found(state,input.comparabilityId).collection!=='comparabilities')fail('DEPENDENCY_TYPE','Select a controlled comparability assessment.');depIds.push(input.comparabilityId);}const stage=enumValue(input.stage,['DEVELOPMENT','SCALE_UP','COMMERCIAL'],'transfer stage'),cites=citations(state,input.citations,true);if(!cites.some(c=>c.raw.includes(stage)))fail('UNSUPPORTED_TRANSFER','Transfer stage must be present in the cited evidence.');record=await append(state,'transfers',{label:text(input.label,'Transfer map label',160),stage,fromSiteId:from.id,toSiteId:to.id,processIds,batchIds,comparabilityId:input.comparabilityId||null,evidenceRefs:refs(state,input.evidenceRefs),citations:cites,dependencies:dependencies(state,depIds),qualificationClaim:false},input,actor);break;
 }
 case 'marketChange':{
  author();valid([...common,'productId','oldSourceId','newSourceId','changedParameters']);const product=onlyEntity(state,input.productId,'product');const old=state.sources.find(s=>s.id===input.oldSourceId),current=src(state,input.newSourceId);if(!old||old.id===current.id)fail('CHANGE_SOURCE','Select distinct existing old and current source revisions.');const changedParameters=list(input.changedParameters,'Changed parameters',30).map(p=>text(p,'Changed parameter',100).toLowerCase());const evidenceRefs=refs(state,input.evidenceRefs);if(evidenceRefs.some(r=>r.sourceId!==current.id||r.product!==product.label))fail('CHANGE_CONTEXT','Changed facts must bind the selected current source and product.',409);if(!changedParameters.length||changedParameters.some(p=>!evidenceRefs.some(r=>r.parameter===p)))fail('UNSUPPORTED_CHANGE','Changed parameters must be supported by the current approved facts.');record=await append(state,'changes',{label:text(input.label,'Change label',160),productId:product.id,oldSourceId:old.id,newSourceId:current.id,oldSourceHash:old.hash,newSourceHash:current.hash,changedParameters,evidenceRefs,citations:citations(state,input.citations),dependencies:dependencies(state,[product.id]),classificationState:'HUMAN_REVIEW_REQUIRED',release:false},input,actor);break;
 }
 case 'classify':{
  author();valid(['changeId','ruleIds','market','label','predecessorId']);const change=found(state,input.changeId);if(change.collection!=='changes')fail('DEPENDENCY_TYPE','Select a controlled market change.');const market=text(input.market,'Classification market',100),rules=list(input.ruleIds,'Classification rules',30).map(id=>found(state,id));if(!rules.length||rules.some(r=>r.collection!=='rules'||r.kind!=='CLASSIFICATION'||r.market!==market))fail('CLASSIFICATION_RULE','Use approved classification rules for the exact recorded jurisdiction.');const depIds=[change.id,...rules.map(r=>r.id)],deps=dependencies(state,depIds);const matching=rules.filter(r=>r.parameters.some(p=>change.changedParameters.includes(p))).map(r=>({ruleId:r.id,ruleRevision:r.revision,category:r.category,sourceCitations:copy(r.citations),check:ruleCheck(state,r)}));const categories=[...new Set(matching.filter(m=>m.check.passed).map(m=>m.category))];record=await append(state,'classifications',{label:text(input.label||`${market} classification candidate`,'Classification label',160),changeId:change.id,market,matchingRules:matching,candidateCategory:categories.length===1?categories[0]:'UNKNOWN',candidateState:categories.length===1?'NEEDS_HUMAN_DECISION':categories.length>1?'CONFLICT':'HOLD',evidenceRefs:refs(state,rawRefs([change,...rules])),citations:rules.flatMap(r=>copy(r.citations)),dependencies:deps,regulatoryAuthority:false,automaticFiling:false,limitation:'Source-grounded local rule match only; legal applicability and actual reporting category require an authorized regulatory professional.'},input,actor);break;
 }
 case 'simulation':{
  author();valid(['label','sourceId','replacements','ruleIds','predecessorId','reason']);const source=src(state,input.sourceId),replacements=list(input.replacements||[],'Proposed replacements',30).map(r=>{schema(r,['fromFieldId','fromRevision','toFieldId','toRevision']);const from=fact(state,{fieldId:r.fromFieldId,revision:r.fromRevision}),to=fact(state,{fieldId:r.toFieldId,revision:r.toRevision},{approved:false});if(from.sourceId!==source.id||from.parameter!==to.parameter||from.product!==to.product)fail('SIMULATION_CONTEXT','Replacement candidates must address the same product and parameter.');return {fromFieldId:from.id,fromRevision:from.revision,toFieldId:to.id,toRevision:to.revision,fromValue:from.value,toValue:to.value,fromUnit:from.unit,toUnit:to.unit,sourceId:to.sourceId,sourceHash:to.sourceHash,approvalRequired:to.status!=='APPROVED'};});const ruleIds=list(input.ruleIds||[],'Proposed rule branches',30);for(const id of ruleIds)if(found(state,id).collection!=='rules')fail('DEPENDENCY_TYPE','A policy branch must refer to a stored rule candidate revision.');const dependenciesList=dependencies(state,ruleIds,false),impact=impactFor(state,source.id);const evidenceRefs=refs(state,replacements.map(r=>({fieldId:r.fromFieldId,revision:r.fromRevision})),false);record=await append(state,'branches',{label:text(input.label,'Simulation label',160),sourceId:source.id,sourceHash:source.hash,replacements,ruleIds,evidenceRefs,candidateRefs:replacements.map(r=>({fieldId:r.toFieldId,revision:r.toRevision})),citations:[],dependencies:dependenciesList,impact:copy(impact),scientificSnapshotHash:await hash(JSON.stringify({sources:state.sources.map(s=>({id:s.id,hash:s.hash,version:s.version,status:s.status})),fields:state.fields.map(f=>({id:f.id,revision:f.revision,value:f.value,unit:f.unit,status:f.status})),policy:state.policy})),branchPolicy:{simulationOnly:true,release:false,autoMerge:false,scientificWrite:'NEW_SOURCE_THEN_INDEPENDENT_FACT_REVIEW'},reason:text(input.reason,'Simulation rationale',1000)},input,actor);break;
 }
 case 'regression':{
  reviewer();valid(['label','sourceId','ruleIds','dossierIds','branchId','predecessorId']);if(input.sourceId&&!state.sources.some(s=>s.id===input.sourceId))fail('EVIDENCE_SOURCE','Select a recorded source.');const rules=list(input.ruleIds||[],'Regression rules',100).map(id=>found(state,id)),dossiers=list(input.dossierIds||[],'Regression dossiers',100).map(id=>found(state,id));if(rules.some(r=>r.collection!=='rules')||dossiers.some(d=>d.collection!=='dossiers'))fail('DEPENDENCY_TYPE','Regression targets must be rules and dossier records.');if(!rules.length&&!dossiers.length)fail('REGRESSION_SCOPE','Select at least one actual rule or dossier revision.');const checks=rules.map(r=>({name:`Rule ${r.label}`,targetId:r.id,passed:effectiveStatus(state,r.id)==='APPROVED'&&ruleCheck(state,r).passed,details:ruleCheck(state,r)}));for(const d of dossiers){const check=structural(state,d);checks.push({name:`Dossier ${d.label}`,targetId:d.id,passed:check.passed,details:check});}const branch=input.branchId?found(state,input.branchId):null;if(branch&&branch.collection!=='branches')fail('DEPENDENCY_TYPE','Select a stored simulation branch.');const evidenceRefs=refs(state,rawRefs([...rules,...dossiers]),false);record=await append(state,'regressions',{label:text(input.label||'Lifecycle regression','Regression label',160),sourceId:input.sourceId||null,ruleIds:rules.map(r=>r.id),dossierIds:dossiers.map(d=>d.id),branchId:branch?.id||null,checks,passed:checks.every(c=>c.passed),denominator:checks.length,executedAt:now(),evidenceRefs,citations:[],dependencies:[...rules,...dossiers,...(branch?[branch]:[])].map(x=>({id:x.id,revision:x.revision,digest:x.digest,approvalRequired:false})),testScope:'CURRENT_SOURCE_DEPENDENCY_REQUIREMENT_CONSISTENCY',noRegulatoryValidationClaim:true},input,actor);break;
 }
 case 'approve':{
  reviewer();valid(['id','revision','choice','reason','digest']);const target=found(state,input.id);if(input.revision!==target.revision||input.digest&&input.digest!==target.digest)fail('STALE_REVISION','Review the exact current lifecycle revision and digest.',409);if(target.createdBy===actor.id)fail('INDEPENDENT_REVIEW_REQUIRED','A different authorized human must review authored lifecycle records.',403);if(!latest(state,target)||currentProblems(state,target).length)fail('STALE_EVIDENCE','Stale lifecycle records require a new source-backed revision.',409);const choice=enumValue(input.choice,['APPROVE','REVISE','REQUEST_EVIDENCE','REJECT'],'human review choice');if(choice==='APPROVE'){if(target.collection==='classifications'&&target.candidateState!=='NEEDS_HUMAN_DECISION')fail('CLASSIFICATION_HOLD','Unknown or conflicting classification rules cannot be approved.',409);if(target.collection==='dossiers'||target.collection==='reuses'){const coverage=requirementCoverage(state,target);if(target.collection==='dossiers'&&!target.requirementIds.length)fail('REQUIREMENT_GAP','Configure a controlled market requirement profile before dossier approval.',409);if(coverage.some(c=>!c.covered))fail('REQUIREMENT_GAP','Resolve uncovered section/parameter requirements before approval.',409);}for(const d of target.dependencies){if(effectiveStatus(state,d.id)!=='APPROVED'&&target.collection!=='branches')fail('UNAPPROVED_DEPENDENCY','All production dependencies need exact independent approvals.',409);}}
  if(e.decisions.length>=1500)fail('LIFECYCLE_LIMIT','Lifecycle decision limit reached.',413);const binding=signatureRevision(state,target),decision={id:uid('lcdecision'),targetId:target.id,revision:target.revision,digest:target.digest,choice,reason:text(input.reason,'Human decision reason',2000),reviewer:actor.id,reviewedAt:now(),inputWorkspaceRevision:state.version,binding,bindingHash:await hash(JSON.stringify(binding)),scientificAuthority:'AUTHORIZED_HUMAN_ONLY',release:false};e.decisions.push(decision);result={decisionId:decision.id,targetId:target.id,status:effectiveStatus(state,target.id)};break;
 }
 case 'haq':{
  author();valid([...common,'title','market','dossierIds','requirementIds']);const cites=citations(state,input.citations,true),title=text(input.title,'Original HA question',2000);if(!cites.some(c=>c.raw.includes(title)))fail('QUESTION_SOURCE','The actual HA question must occur in the exact original source excerpt.');const market=text(input.market,'HAQ market',100);if(!cites.some(c=>c.raw.includes(market)))fail('QUESTION_SOURCE','The actual question jurisdiction must occur in the quoted source.',409);const evidenceRefs=refs(state,input.evidenceRefs),dossierIds=list(input.dossierIds||[],'Question dossier mappings',50),requirementIds=list(input.requirementIds||[],'Question requirement mappings',50);for(const id of dossierIds)if(found(state,id).collection!=='dossiers')fail('DEPENDENCY_TYPE','Select controlled dossier revisions.');for(const id of requirementIds)if(found(state,id).collection!=='requirements')fail('DEPENDENCY_TYPE','Select controlled requirement revisions.');record=await append(state,'haqs',{label:text(input.label||title,'HAQ label',160),title,market,dossierIds,requirementIds,evidenceRefs,citations:cites,dependencies:dependencies(state,[...dossierIds,...requirementIds]),response:evidenceRefs.map(r=>({fieldId:r.fieldId,revision:r.revision,text:`The recorded ${r.parameter} for batch ${r.batch} is ${r.value} ${r.unit}, using ${r.method}; source ${r.sourceId}, revision ${r.sourceVersion}.`,sourceId:r.sourceId,sourceVersion:r.sourceVersion,span:copy(r.span)})),responseState:'CANDIDATE',regulatorAcceptance:false},input,actor);break;
 }
 case 'haqOutcome':{
  author();valid([...common,'haqId','outcome']);const q=found(state,input.haqId);if(q.collection!=='haqs')fail('DEPENDENCY_TYPE','Select a source-backed HA question.');const outcome=enumValue(input.outcome,['RESPONDED','ACKNOWLEDGED','MORE_INFORMATION','CLOSED_REPORTED','REJECTED'],'recorded outcome'),cites=citations(state,input.citations,true);if(!cites.some(c=>c.raw.includes(outcome)))fail('OUTCOME_SOURCE','Recorded outcome needs its exact supplied evidence token; do not infer regulator acceptance.');record=await append(state,'outcomes',{label:text(input.label||`${q.label} outcome`,'Outcome label',160),haqId:q.id,outcome,evidenceRefs:refs(state,input.evidenceRefs),citations:cites,dependencies:dependencies(state,[q.id]),knowledgeEligibility:'EXACT_APPROVED_CURRENT_RECORD_ONLY',regulatorAcceptance:false},input,actor);break;
 }
 case 'closure':{
  author();valid([...common,'owner','expectedChecks','dependencyIds']);const owner=text(input.owner||actor.id,'Action owner principal',160),checks=list(input.expectedChecks,'Expected outcome checks',30);if(!checks.length)fail('CLOSURE_EXPECTATION','Specify source-backed expected-versus-actual checks.');const expectedChecks=checks.map(c=>{schema(c,['operator','expected','actual']);const operator=enumValue(c.operator,['EQUAL','CONTEXT_MATCH','WITHIN_RECORDED_LIMITS','CURRENT_APPROVED'],'closure check');fact(state,c.expected);fact(state,c.actual);return {operator,expected:copy(c.expected),actual:copy(c.actual)};});const evidenceRefs=refs(state,expectedChecks.flatMap(c=>[c.expected,c.actual]).filter((r,i,a)=>a.findIndex(x=>x.fieldId===r.fieldId)===i));record=await append(state,'closures',{label:text(input.label,'Closure action label',160),owner,expectedChecks,evidenceRefs,citations:citations(state,input.citations),dependencies:dependencies(state,input.dependencyIds||[]),requiredOutcome:'ALL_CURRENT_SOURCE_BACKED_EXPECTED_CHECKS_PASS',actionStatus:'OPEN',closureAuthority:'INDEPENDENT_HUMAN_VERIFIER'},input,actor);break;
 }
 case 'verifyClosure':{
  reviewer();valid(['id','revision','reason']);const a=found(state,input.id);if(a.collection!=='closures'||a.revision!==input.revision)fail('STALE_REVISION','Review the exact closure action revision.',409);if(actor.id===a.owner||actor.id===a.createdBy)fail('INDEPENDENT_REVIEW_REQUIRED','The action owner/author cannot verify their own closure.',403);if(!latest(state,a)||currentProblems(state,a).length)fail('STALE_EVIDENCE','Use current closure evidence.',409);const checks=closureChecks(state,a),passed=checks.every(c=>c.passed);record=await append(state,'verifications',{label:`Verification · ${a.label}`,closureId:a.id,closureRevision:a.revision,closureDigest:a.digest,verifiedBy:actor.id,expectedChecks:copy(a.expectedChecks),checks,passed,denominator:checks.length,actionStatus:passed?'CLOSED_WITH_EVIDENCE':'OPEN',evidenceRefs:refs(state,rawRefs([a])),citations:copy(a.citations),dependencies:[{id:a.id,revision:a.revision,digest:a.digest}],reason:text(input.reason,'Independent closure reason',2000),effectivenessClaim:'RECORDED_EXPECTED_VERSUS_ACTUAL_CHECKS_ONLY',monitoringMode:'ON_DEMAND_AND_SOURCE_CHANGE'}, {},actor);break;
 }
 case 'reopenCheck':{
  reviewer();valid(['id','reason']);const a=found(state,input.id);if(a.collection!=='closures')fail('DEPENDENCY_TYPE','Select a stored closure action.');const verified=e.verifications.findLast(v=>v.closureId===a.id&&v.passed),issues=currentProblems(state,a),checks=closureChecks(state,a);const reopen=Boolean(verified&&(issues.length||checks.some(c=>!c.passed)));if(reopen&&!e.invalidations.some(i=>i.recordId===a.id&&i.reason==='CLOSURE_EFFECTIVENESS_CHANGED'))e.invalidations.push({id:uid('invalidate'),recordId:a.id,sourceId:null,reason:'CLOSURE_EFFECTIVENESS_CHANGED',at:now(),reviewer:actor.id,note:text(input.reason,'Reopen reason',1000)});result={closureId:a.id,actionStatus:reopen?'REOPENED':verified?'CLOSED_WITH_EVIDENCE':'OPEN',checks,issues,continuousScheduler:'NOT_CONFIGURED'};break;
 }
 case 'correction':{
  author();valid(['fromBlockId','toBlockId','reuseIds','reason','label','predecessorId']);const old=found(state,input.fromBlockId),next=found(state,input.toBlockId);if(old.collection!=='blocks'||next.collection!=='blocks'||next.logicalId!==old.logicalId||next.revision<=old.revision||effectiveStatus(state,next.id)!=='APPROVED')fail('CORRECTION_LINEAGE','A correction needs a newer independently approved block in the same logical lineage.',409);const reuseIds=list(input.reuseIds,'Dependent reuse selections',100);if(!reuseIds.length)fail('CORRECTION_SCOPE','Select actual downstream reuse records.');const created=[];for(const id of reuseIds){const reuse=found(state,id);if(reuse.collection!=='reuses'||reuse.blockId!==old.id||!latest(state,reuse))fail('CORRECTION_SCOPE','Only latest dependent reuse versions of the corrected predecessor can be propagated.');const newDeps=dependencies(state,[next.id,...reuse.requirementIds,...(reuse.templateId?[reuse.templateId]:[])]);const updated=await append(state,'reuses',{label:reuse.label,market:reuse.market,section:reuse.section,blockId:next.id,blockRevision:next.revision,templateId:reuse.templateId,requirementIds:copy(reuse.requirementIds),evidenceRefs:refs(state,rawRefs([next])),citations:copy(next.citations),dependencies:newDeps,statements:copy(next.statements),text:next.text,style:copy(reuse.style),reuseReason:text(input.reason,'Correction propagation reason',1000),scientificTextChanged:true,previousApprovalTransferred:false},{predecessorId:reuse.id},actor);created.push(updated.id);}record=await append(state,'corrections',{label:text(input.label||'Controlled correction propagation','Correction label',160),fromBlockId:old.id,toBlockId:next.id,reuseIds,createdReuseIds:created,evidenceRefs:refs(state,rawRefs([next])),citations:copy(next.citations),dependencies:dependencies(state,[next.id]),reason:text(input.reason,'Correction reason',1000),humanReReviewRequired:true},input,actor);break;
 }
 default:fail('UNKNOWN_LIFECYCLE_ACTION','This lifecycle operation is not implemented.');
 }
 return record?{recordId:record.id,collection:found(state,record.id).collection,revision:record.revision,digest:record.digest,status:effectiveStatus(state,record.id)}:result;
}

/** The graph distinguishes causal dependencies from semantic genealogy and version history. */
export function lifecycleGraph(state){
 const nodes=[],edges=[],records=all(state),seen=new Set();
 for(const s of state.sources){nodes.push({id:s.id,type:"source",label:s.name,status:s.status});seen.add(s.id);}
 for(const f of state.fields){nodes.push({id:f.id,type:"fact",label:`${f.parameter} · ${f.batch}`,status:f.status});seen.add(f.id);edges.push({from:f.sourceId,to:f.id,reason:"exact source span",dependency:true});}
 for(const d of state.drafts){nodes.push({id:d.id,type:"draft",label:d.title,status:d.status});seen.add(d.id);for(const id of d.fieldIds)edges.push({from:id,to:d.id,reason:"statement evidence",dependency:true});}
 for(const d of state.decisions){nodes.push({id:d.id,type:"decision",label:d.action,status:d.status});seen.add(d.id);edges.push({from:d.targetId,to:d.id,reason:"revision-bound decision",dependency:true});}
 for(const x of state.exports){nodes.push({id:x.id,type:"export",label:x.name,status:x.status});seen.add(x.id);edges.push({from:x.draftId,to:x.id,reason:"approved snapshot",dependency:true});}
 const node=(id,type,label,status)=>{if(!seen.has(id)){nodes.push({id,type,label,status});seen.add(id);}};
 for(const x of records){node(x.id,x.collection,x.label||x.id,effectiveStatus(state,x.id));for(const r of x.evidenceRefs||[])edges.push({from:r.fieldId,to:x.id,reason:'exact approved fact revision',dependency:true,revision:r.revision,sourceHash:r.sourceHash});for(const c of x.citations||[])edges.push({from:c.sourceId,to:x.id,reason:'exact source excerpt',dependency:true,sourceHash:c.sourceHash});for(const d of x.dependencies||[])edges.push({from:d.id,to:x.id,reason:'exact controlled record revision',dependency:true,revision:d.revision,digest:d.digest});for(const r of x.candidateRefs||[])edges.push({from:r.fieldId,to:x.id,reason:'proposed candidate evidence in simulation',dependency:true,revision:r.revision});if(x.predecessorId)edges.push({from:x.predecessorId,to:x.id,reason:'immutable predecessor history',dependency:false});if(x.draftId)edges.push({from:x.draftId,to:x.id,reason:'exact approved draft revision',dependency:true,revision:x.draftRevision});if(x.collection==='relations')edges.push({from:x.fromId,to:x.toId,via:x.id,reason:x.relationType,dependency:false});if(x.collection==='branches')edges.push({from:x.sourceId,to:x.id,reason:'source change simulation',dependency:true});}
 for(const d of hydrateLifecycle(state).decisions){node(d.id,'lifecycle-decision',d.choice,effectiveStatus(state,d.targetId)==='STALE'?'STALE':'HISTORICAL_DECISION');edges.push({from:d.targetId,to:d.id,reason:'revision-bound human decision',dependency:true,revision:d.revision,digest:d.digest});}
 for(const q of state.queries||[]){node(q.id,'haq',q.title,q.status);for(const id of q.fieldIds||[])edges.push({from:id,to:q.id,reason:'HA response evidence',dependency:true});}
 for(const a of state.actions||[]){node(a.id,'action',a.title,a.status);for(const id of a.sourceIds||[])edges.push({from:id,to:a.id,reason:'source-backed closure dependency',dependency:true});}
 if(nodes.length>10000||edges.length>30000)fail('GRAPH_LIMIT','Recorded dependency graph exceeds supported bounded workspace limits.',413);
 return {nodes,edges,revision:state.version,workflowVersion:LIFECYCLE_VERSION,scope:'Recorded authorized workspace dependencies; absence of a path is not scientific or legal proof of universal non-impact.'};
}
function impactFor(state,rootId){const graph=lifecycleGraph(state);if(!graph.nodes.some(n=>n.id===rootId))fail('IMPACT_ROOT','Select an existing source, fact, rule or controlled object.',404);const included=new Set([rootId]),parents=new Map();let again=true;while(again){again=false;for(const e of graph.edges)if(e.dependency&&included.has(e.from)&&!included.has(e.to)){included.add(e.to);parents.set(e.to,e);again=true;}}return {rootId,graphRevision:graph.revision,included:graph.nodes.filter(n=>included.has(n.id)).map(n=>({...n,pathReason:parents.get(n.id)||null})),excluded:graph.nodes.filter(n=>!included.has(n.id)).map(n=>({...n,proof:{type:'NO_RECORDED_DEPENDENCY_PATH',rootId,graphRevision:graph.revision,workflowVersion:LIFECYCLE_VERSION},reason:'No causal dependency path in this exact recorded graph; external or unrecorded scientific relationships remain unknown.'})),globalNonImpactClaim:false};}
/** Append invalidations; scientific records and past decision payloads are never rewritten. */
export function invalidateLifecycle(state,sourceId){const e=hydrateLifecycle(state),impact=impactFor(state,sourceId),ids=new Set(impact.included.map(x=>x.id)),invalidated=[];for(const x of all(state).filter(x=>ids.has(x.id))){if(!e.invalidations.some(i=>i.recordId===x.id&&i.sourceId===sourceId)){if(e.invalidations.length>=3000)fail('LIFECYCLE_LIMIT','Invalidation history limit reached.',413);const i={id:uid('invalidate'),recordId:x.id,revision:x.revision,digest:x.digest,sourceId,at:now(),reason:'DEPENDENCY_SOURCE_CHANGED',priorStatus:effectiveStatus(state,x.id),closureStatus:x.collection==='closures'?'REOPENED':null};e.invalidations.push(i);invalidated.push(i);}}return {sourceId,invalidated,impact,selective:true,historyRewritten:false};}
function stabilityTrends(state){const obs=selected(state,'observations').filter(o=>o.status==='APPROVED'),entries=[];for(const o of obs)for(const r of o.measurementRefs){try{const f=fact(state,r);entries.push({observationId:o.id,batchId:o.batchId,time:o.recordedTime,timeUnit:o.timeUnit,...descriptor(state,r),key:JSON.stringify([o.batchId,f.parameter,f.method,f.unit,f.low,f.high,f.condition,f.basis,o.timeUnit])});}catch{}}
 return [...Map.groupBy(entries,e=>e.key)].map(([,group])=>{const samples=group.sort((a,b)=>a.time-b.time),uniqueTimes=new Set(samples.map(s=>s.time)),n=samples.length,mean=n?samples.reduce((s,x)=>s+x.value,0)/n:null,meanTime=n?samples.reduce((s,x)=>s+x.time,0)/n:null,den=samples.reduce((s,x)=>s+(x.time-meanTime)**2,0),slope=n>1&&uniqueTimes.size===n&&den>0?samples.reduce((s,x)=>s+(x.time-meanTime)*(x.value-mean),0)/den:null;return {batchId:samples[0].batchId,parameter:samples[0].parameter,method:samples[0].method,condition:samples[0].condition,unit:samples[0].unit,timeUnit:samples[0].timeUnit,samples,n,minimum:Math.min(...samples.map(x=>x.value)),maximum:Math.max(...samples.map(x=>x.value)),mean,descriptiveSlope:slope,duplicateTimes:uniqueTimes.size!==n,extrapolation:false,predictedShelfLife:null,interpretation:'Slope describes only approved observed points in the exact recorded time unit. No extrapolation, shelf-life assignment or stability acceptance.'};});}
function dossierConsistency(state){const records=selected(state,'dossiers').filter(d=>d.status!=='STALE'),entries=records.flatMap(d=>d.facts.map(f=>({...f,dossierId:d.id,section:d.section,market:d.market,productId:d.productId})));return [...Map.groupBy(entries,f=>JSON.stringify([f.productId,f.batch,f.parameter]))].map(([key,items])=>({key,parameter:items[0].parameter,batch:items[0].batch,items,scientificValueConflict:new Set(items.map(x=>JSON.stringify([x.value,x.unit]))).size>1,contextConflict:new Set(items.map(x=>JSON.stringify([x.method,x.low,x.high,x.condition,x.basis]))).size>1,sectionCoverage:[...new Set(items.map(x=>x.section))],interpretation:'Cross-dossier evidence/context check; differences require qualified review.'}));}
function specifications(state){const fs=state.fields.filter(f=>f.status==='APPROVED').filter(f=>{try{fact(state,{fieldId:f.id,revision:f.revision});return true;}catch{return false;}});return [...Map.groupBy(fs,f=>JSON.stringify([f.product,f.parameter]))].map(([,items])=>({parameter:items[0].parameter,product:items[0].product,specificationProfiles:[...new Map(items.map(f=>[JSON.stringify([f.method,f.unit,f.low,f.high,f.basis,f.condition]),{method:f.method,unit:f.unit,low:f.low,high:f.high,basis:f.basis,condition:f.condition,fieldIds:items.filter(x=>context(x)===context(f)).map(x=>x.id),sourceVersions:items.filter(x=>context(x)===context(f)).map(x=>({sourceId:x.sourceId,version:x.sourceVersion,hash:x.sourceHash}))}])).values()],contextConflict:new Set(items.map(context)).size>1,interpretation:'Different recorded profiles are a review flag, not automatic non-compliance.'}));}
function structural(state,d){const coverage=requirementCoverage(state,d),issues=currentProblems(state,d);if(!d.requirementIds.length)issues.push('REQUIREMENT_PROFILE_NOT_CONFIGURED');if(coverage.some(c=>!c.covered))issues.push('REQUIRED_CONTENT_GAP');for(const id of d.blockIds){const block=found(state,id);if(!block.evidenceRefs.every(r=>d.evidenceRefs.some(f=>f.fieldId===r.fieldId&&f.revision===r.revision)))issues.push('BLOCK_DOSSIER_EVIDENCE_MISMATCH');}return {dossierId:d.id,revision:d.revision,section:d.section,coverage,issues:[...new Set(issues)],passed:!issues.length,technicalScope:'Declared controlled section and requirement profile only',eCTDConformance:false};}
function marketMatrix(state){const dossiers=selected(state,'dossiers');return [...Map.groupBy(dossiers,d=>`${d.productId}|${d.market}`)].map(([key,ds])=>({key,productId:ds[0].productId,market:ds[0].market,dossiers:ds.map(d=>({...d,structure:structural(state,d),filedCurrent:d.stateLabel==='RECORDED_FILING'?d.facts.map(old=>{const current=state.fields.filter(f=>f.parameter===old.parameter&&f.batch===old.batch&&f.product===old.product&&f.status==='APPROVED').filter(f=>{try{fact(state,{fieldId:f.id,revision:f.revision});return true;}catch{return false;}});return {fieldId:old.fieldId,recorded:old,current:current.map(f=>descriptor(state,{fieldId:f.id,revision:f.revision})),divergent:!current.some(f=>f.value===old.value&&context(f)===context(old))};}):[]})),globalMarketCoverage:false}));}
function riskCandidates(state){const risks=[];for(const d of selected(state,'dossiers')){const check=structural(state,d);for(const c of check.coverage.filter(c=>!c.covered))risks.push({id:`prediction:${d.id}:${c.requirementId}`,question:`What controlled evidence supports ${c.parameter} in section ${d.section}?`,basis:{dossierId:d.id,requirementId:c.requirementId,revision:c.revision,availableCount:c.availableCount,requiredCount:c.requiredCount,sourceCitations:c.sourceCitations},state:'PREDICTION',probability:null,notAHistoricalAuthorityQuestion:true});if(d.status==='STALE')risks.push({id:`prediction:${d.id}:stale`,question:`Which current source revisions support the recorded ${d.section} statements?`,basis:{dossierId:d.id,issues:d.issues},state:'PREDICTION',probability:null,notAHistoricalAuthorityQuestion:true});}for(const c of dossierConsistency(state).filter(x=>x.scientificValueConflict||x.contextConflict))risks.push({id:`prediction:${c.key}:consistency`,question:`How are the recorded ${c.parameter} differences reconciled across dossier sections?`,basis:c,state:'PREDICTION',probability:null,notAHistoricalAuthorityQuestion:true});return {candidates:risks,trainedModel:false,interpretation:'Transparent gap/rule-derived query candidates, not actual regulator questions or calibrated risk probabilities.'};}
function closureProjection(state){const e=hydrateLifecycle(state);return selected(state,'closures').map(a=>{const v=e.verifications.findLast(v=>v.closureId===a.id&&v.passed),checks=closureChecks(state,a),invalid=a.status==='STALE'||checks.some(c=>!c.passed);return {...a,verification:v?copy(v):null,checks,actionStatus:v?(invalid?'REOPENED':'CLOSED_WITH_EVIDENCE'):'OPEN',continuousScheduler:'NOT_CONFIGURED',scope:'Source-change-triggered and on-demand checks, no autonomous clinical/regulatory effectiveness claim.'};});}
/** Pure bounded projection. Exact original X identifiers are preserved. */
export function lifecycleProjection(state,id,input={}){
 if(!LIFECYCLE_IDS.includes(id))fail('UNKNOWN_LIFECYCLE_CAPABILITY','This lifecycle capability identifier is not implemented.');const def={name:LIFECYCLE_LABELS[id]},e=hydrateLifecycle(state);let data;
 switch(id){
 case 'X08':data={controlledTypes:TYPES,entities:selected(state,'entities'),ontologyAuthority:'SOURCE_BACKED_LOCAL_REVIEW'};break;
 case 'X09':data={requirements:selected(state,'requirements'),rules:selected(state,'rules'),jurisdictionCoverage:'SUPPLIED_RULES_ONLY'};break;
 case 'X10':data={requirements:selected(state,'requirements').map(r=>({...r,mappedDossiers:selected(state,'dossiers').filter(d=>d.requirementIds.includes(r.id)).map(d=>({id:d.id,section:d.section,coverage:requirementCoverage(state,d).find(c=>c.requirementId===r.id)})),mappedContent:selected(state,'reuses').filter(d=>d.requirementIds.includes(r.id)).map(d=>({id:d.id,section:d.section,coverage:requirementCoverage(state,d).find(c=>c.requirementId===r.id)}))}))};break;
 case 'X11':data={entities:selected(state,'entities'),relations:selected(state,'relations'),dossiers:selected(state,'dossiers'),sourceHashes:state.sources.map(s=>({id:s.id,version:s.version,hash:s.hash,status:s.status})),digitalTwinScope:'RECORDED_CMC_EVIDENCE_STATE',physicalTwinValidation:false};break;
 case 'X12':case 'X13':{const types=id==='X12'?['RAW_MATERIAL_TO_INTERMEDIATE','INTERMEDIATE_TO_BATCH','BATCH_TO_FINISHED_PRODUCT']:Object.keys(RELATIONS).filter(k=>!['RAW_MATERIAL_TO_INTERMEDIATE','INTERMEDIATE_TO_BATCH','BATCH_TO_FINISHED_PRODUCT'].includes(k));const rs=selected(state,'relations').filter(r=>types.includes(r.relationType)),ids=new Set(rs.flatMap(r=>[r.fromId,r.toId]));data={nodes:selected(state,'entities').filter(x=>ids.has(x.id)),edges:rs.map(r=>({...r,from:r.fromId,to:r.toId})),relationshipTruth:'INDEPENDENTLY_REVIEWED_RECORDED_EVIDENCE_ONLY'};break;}
 case 'X17':data={checks:dossierConsistency(state),denominator:selected(state,'dossiers').length};break;
 case 'X18':data={specifications:specifications(state)};break;
 case 'X19':data={observations:selected(state,'observations'),trends:stabilityTrends(state),extrapolation:false,shelfLifeAssignment:false};break;
 case 'X20':data={assessments:selected(state,'comparabilities'),scientificEquivalenceEstablished:false};break;
 case 'X21':{const fs=state.fields.filter(f=>f.status==='APPROVED').filter(f=>{try{fact(state,{fieldId:f.id,revision:f.revision});return true;}catch{return false;}});data={groups:[...Map.groupBy(fs,context)].map(([,group])=>({parameter:group[0].parameter,method:group[0].method,unit:group[0].unit,facts:group.map(f=>descriptor(state,{fieldId:f.id,revision:f.revision})),...comparable(group)})),stabilityTrends:stabilityTrends(state),dispositionAuthority:false};break;}
 case 'X22':data={transfers:selected(state,'transfers'),stageOrder:['DEVELOPMENT','SCALE_UP','COMMERCIAL'],qualificationEstablished:false};break;
 case 'X23':data={blocks:selected(state,'blocks'),immutableVersions:e.blocks.length};break;
 case 'X26':data={reuses:selected(state,'reuses'),dependencyTracked:true,approvalTransferred:false};break;
 case 'X27':data={templates:selected(state,'templates'),formattedReuse:selected(state,'reuses').map(r=>({id:r.id,style:r.style,section:r.section,text:r.text,citations:r.evidenceRefs.map(f=>({sourceId:f.sourceId,revision:f.sourceVersion,span:f.span}))})),scientificTextRewrite:false};break;
 case 'X31':data={results:selected(state,'dossiers').map(d=>structural(state,d)),eCTDConformance:false};break;
 case 'X36':data={markets:marketMatrix(state),coverage:'RECORDED_PRODUCT_MARKET_DOSSIER_MATRIX'};break;
 case 'X37':data={classifications:selected(state,'classifications'),automaticReportingCategory:false,regulatoryAuthority:false};break;
 case 'X38':data={changes:selected(state,'changes').map(c=>{const impact=impactFor(state,c.oldSourceId),included=new Set(impact.included.map(n=>n.id));return {changeId:c.id,productId:c.productId,markets:marketMatrix(state).filter(m=>m.productId===c.productId).map(m=>({market:m.market,dossiers:m.dossiers.map(d=>({id:d.id,scope:included.has(d.id)?'RECORDED_DEPENDENCY_IMPACT':'NO_RECORDED_DEPENDENCY_PATH'})),rules:selected(state,'rules').filter(r=>r.kind==='CLASSIFICATION'&&r.market===m.market&&r.parameters.some(p=>c.changedParameters.includes(p))),actionRequired:'QUALIFIED_HUMAN_REVIEW'}))};}),globalLegalClassification:false};break;
 case 'X39':data={branches:selected(state,'branches'),productionStateMutated:false,branchMergePolicy:'NEW_SOURCE_AND_INDEPENDENT_EXACT_REVISION_REVIEW',autoMerge:false};break;
 case 'X40':data=impactFor(state,input.sourceId||input.id);break;
 case 'X41':{const impact=impactFor(state,input.sourceId||input.id);data={rootId:impact.rootId,graphRevision:impact.graphRevision,proofs:impact.excluded,globalNonImpactClaim:false};break;}
 case 'X42':data={invalidations:copy(e.invalidations),staleRecords:all(state).filter(x=>effectiveStatus(state,x.id)==='STALE').map(x=>project(state,x)),historyRewritten:false};break;
 case 'X43':data={runs:selected(state,'regressions'),executedChecks:e.regressions.reduce((n,r)=>n+r.denominator,0),lastRun:e.regressions.at(-1)||null,engineeringChecksOnly:true};break;
 case 'X44':data={operators:[...OPS],rules:selected(state,'rules').map(r=>({...r,execution:r.status==='APPROVED'?ruleCheck(state,r):{state:'HOLD',reason:'Exact independently approved rule revision is required.'}})),arbitraryCodeExecution:false};break;
 case 'X45':data={coverage:selected(state,'requirements').map(r=>{const rules=selected(state,'rules').filter(p=>p.requirementIds.includes(r.id));return {requirementId:r.id,revision:r.revision,sourceCitations:r.citations,rules:rules.map(p=>({id:p.id,revision:p.revision,status:p.status,executable:p.status==='APPROVED',check:p.status==='APPROVED'?ruleCheck(state,p):null})),executableCoverage:rules.some(p=>p.status==='APPROVED'),dossierEvidence:selected(state,'dossiers').filter(d=>d.requirementIds.includes(r.id)).flatMap(d=>requirementCoverage(state,d).filter(c=>c.requirementId===r.id))};}),legalCompleteness:false};break;
 case 'X46':data={graph:lifecycleGraph(state),decisions:e.decisions.map(d=>({...copy(d),current:effectiveStatus(state,d.targetId)!=='STALE'&&e.decisions.findLast(x=>x.targetId===d.targetId)?.id===d.id})),binding:['exact record digest','evidence/source revisions','dependency revisions','human reviewer','policy version','workflow version']};break;
 case 'X53':case 'X55':case 'X56':data={questions:selected(state,'haqs'),dependencyMap:selected(state,'haqs').map(q=>({queryId:q.id,dossierIds:q.dossierIds,requirementIds:q.requirementIds,evidenceRefs:q.evidenceRefs})),responsesAreCandidates:true};break;
 case 'X54':case 'X57':{const query=typeof input.query==='string'?input.query.toLowerCase().slice(0,500):'',terms=query.split(/\W+/).filter(t=>t.length>3);data={memory:selected(state,'outcomes').filter(o=>o.status==='APPROVED').map(o=>({...o,question:found(state,o.haqId)})).filter(o=>!terms.length||terms.some(t=>JSON.stringify([o.label,o.question.title,o.outcome]).toLowerCase().includes(t))),approvedCurrentOutcomesOnly:true};break;}
 case 'X58':data=riskCandidates(state);break;
 case 'X61':data={corrections:selected(state,'corrections'),reuses:selected(state,'reuses'),newIndependentApprovalRequired:true};break;
 case 'X64':case 'X65':data={actions:closureProjection(state),verifications:copy(e.verifications),monitoringMode:'SOURCE_CHANGE_TRIGGERED_AND_ON_DEMAND',continuousScheduler:'NOT_CONFIGURED'};break;
 }
 return {id,name:def?.name||id,status:'BOUNDED_EXECUTABLE',inputRevision:state.version,workflowVersion:LIFECYCLE_VERSION,data,humanAuthority:false,maturityNotAutomaticallyPromoted:true,limitation:'Executed local source-bound workflows; no legal/global completeness, scientific qualification, regulator acceptance or production validation claim.'};
}
