import {hash} from './core.mjs';
export const READINESS_VERSION='forge-dependency-readiness/2';
const REQUIRED_TABLES=['workspaces','memberships','workspace_revisions','audit_events','idempotent_operations','source_files','signature_factors','request_limits','object_grants','shared_notes','runtime_workflows','runtime_jobs','runtime_events','forge_auth_accounts','forge_auth_sessions','forge_auth_attempts','forge_auth_oauth','forge_auth_legacy_links'];
/** Dependency probes are bounded, read-only and workspace scoped. No binding flag proves health. */
export async function probeReadiness({db,bucket,state,workspaceId,config={},profile='DETERMINISTIC'}){
 const start=performance.now(),checks=[],at=new Date().toISOString();let operational=null;
 async function probe(id,required,fn){const t=performance.now();try{const evidence=await fn();checks.push({id,status:'PASS',required,latencyMs:Math.round(performance.now()-t),evidence});}catch(e){checks.push({id,status:'HOLD',required,latencyMs:Math.round(performance.now()-t),code:e.code||'DEPENDENCY_UNAVAILABLE',message:'The dependency probe failed. Inspect service logs before retrying.'});}}
 await probe('database',true,async()=>{if(!db)throw Object.assign(Error(),{code:'DATABASE_UNAVAILABLE'});const r=await db.prepare('SELECT 1 AS value').first();if(r?.value!==1)throw Error();return {operation:'SELECT 1',readOnly:true};});
 await probe('migrations_and_queue',true,async()=>{if(!db)throw Error();const tables=(await db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all()).results.map(x=>x.name),missing=REQUIRED_TABLES.filter(x=>!tables.includes(x));if(missing.length)throw Object.assign(Error(),{code:'MIGRATION_INCOMPLETE'});const queue=await db.prepare("SELECT COUNT(*) AS denominator, SUM(CASE WHEN status='RUNNING' AND lease_until<? THEN 1 ELSE 0 END) AS expiredLeases FROM runtime_jobs WHERE workspace_id=?").bind(Date.now(),workspaceId).first();const latest=await db.prepare('SELECT e.created_at,e.action FROM runtime_events e JOIN runtime_workflows w ON w.id=e.workflow_id WHERE w.workspace_id=? ORDER BY e.created_at DESC LIMIT 1').bind(workspaceId).first();const windowMs=30*60*1000,clock=Date.now();const q=await db.prepare("SELECT COUNT(*) AS observedJobs,SUM(CASE WHEN j.status IN ('HOLD','DLQ') AND j.generation=w.generation AND w.status!='CANCELLED' THEN 1 ELSE 0 END) AS failedOrHeldJobs,SUM(CASE WHEN j.status IN ('QUEUED','RETRY_WAIT') AND j.available_at<? AND w.status IN ('READY','RUNNING') AND j.generation=w.generation AND NOT EXISTS (SELECT 1 FROM json_each(j.depends_on) dep WHERE NOT EXISTS (SELECT 1 FROM runtime_jobs p WHERE p.workflow_id=j.workflow_id AND p.generation=j.generation AND p.node_key=dep.value AND p.status='COMPLETE')) THEN 1 ELSE 0 END) AS overdueRunnableJobs FROM runtime_jobs j JOIN runtime_workflows w ON w.id=j.workflow_id WHERE j.workspace_id=?").bind(clock-windowMs,workspaceId).first();const human=await db.prepare("SELECT COUNT(*) AS total FROM runtime_workflows WHERE workspace_id=? AND status='HUMAN_WAIT'").bind(workspaceId).first();operational={observedJobs:Number(q?.observedJobs||0),failedOrHeldJobs:Number(q?.failedOrHeldJobs||0),expiredLeases:Number(queue?.expiredLeases||0),overdueRunnableJobs:Number(q?.overdueRunnableJobs||0),humanWaitingWorkflows:Number(human?.total||0),attentionRequired:Boolean(Number(q?.failedOrHeldJobs||0)+Number(q?.overdueRunnableJobs||0)+Number(queue?.expiredLeases||0)),inspectionWindowMinutes:30,at,periodicScheduling:'NOT_ESTABLISHED',workerProcessHealth:'NOT_ESTABLISHED',scope:'Current authorized workspace; overdue runnable jobs are operational attention, never a successful no-change result.'};return {requiredTableCount:REQUIRED_TABLES.length,queueStorage:'D1',observedJobs:Number(queue?.denominator||0),expiredLeases:Number(queue?.expiredLeases||0),lastEvent:latest||null,workerProcessHealth:'NOT_ESTABLISHED',periodicScheduling:'NOT_ESTABLISHED',readOnly:true};});
 await probe('original_storage',true,async()=>{if(!bucket)throw Object.assign(Error(),{code:'STORAGE_UNAVAILABLE'});const list=await bucket.list({prefix:workspaceId+'/',limit:1});if(!Array.isArray(list.objects))throw Error();return {operation:'workspace-scoped R2 list',objectsSampled:list.objects.length,writePermission:'NOT_PROBED',readOnly:true};});
 const sourceMap=new Map(state.sources.map(s=>[s.id,s])),fields=state.fields.filter(f=>!['STALE','REJECTED'].includes(f.status));let traced=0;for(const f of fields){const s=sourceMap.get(f.sourceId);if(s&&s.status==='PARSED'&&s.hash===f.sourceHash&&s.version===f.sourceVersion&&f.span?.raw)traced++;}
 const original=state.sources.filter(s=>s.objectKey&&s.status!=='SUPERSEDED').slice(0,3);
 await probe('original_integrity_sample',original.length>0,async()=>{const evidence=[];for(const s of original){const o=await bucket?.get(s.objectKey);if(!o||await hash(await o.arrayBuffer())!==s.hash)throw Object.assign(Error(),{code:'ORIGINAL_INTEGRITY_FAILED'});evidence.push({sourceId:s.id,version:s.version,hash:s.hash});}return {checked:evidence.length,denominator:state.sources.filter(s=>s.objectKey&&s.status!=='SUPERSEDED').length,sampleLimit:3,sources:evidence,wholeWorkspaceVerified:false};});
 const signingReady=typeof config.signingKey==='string'&&config.signingKey.length>=32;checks.push({id:'signature_configuration',status:signingReady?'PASS':'HOLD',required:false,evidence:{configured:signingReady,cryptographicAndIdentityQualification:'NOT_PROBED'}});
 const providerRequired=profile!=='DETERMINISTIC',model=profile==='VISION'?config.visionModel:config.model,configured=Boolean(config.apiKey&&model&&(profile==='VISION'||(config.reviewerModel&&config.reviewerModel!==config.model)));checks.push({id:'ai_provider',status:providerRequired?'HOLD':configured?'CONFIGURED_NOT_PROBED':'NOT_CONFIGURED',required:providerRequired,evidence:{configured,model:model||null,reviewerModel:profile==='VISION'?null:config.reviewerModel||null,multiModelConfigured:Boolean(config.apiKey&&config.model&&config.reviewerModel&&config.model!==config.reviewerModel),liveInference:'NOT_PROBED',reason:providerRequired?'Provider-required readiness requires a separately consented live evaluation.':'Optional provider does not block deterministic work.'}});
 const ready=checks.filter(c=>c.required).every(c=>c.status==='PASS');return {version:READINESS_VERSION,at,profile,ready,status:ready?(operational?.attentionRequired?'DEPENDENCIES_PROBED_WITH_GAPS':'DEPENDENCIES_PROBED'):'HOLD',checks,operational,latencyMs:Math.round(performance.now()-start),measures:{fieldTraceability:{numerator:traced,denominator:fields.length,period:'Current workspace snapshot at '+at,percentage:fields.length?100*traced/fields.length:null},sourceFreshness:{numerator:fields.filter(f=>{const s=sourceMap.get(f.sourceId);return s&&s.status==='PARSED'&&s.hash===f.sourceHash&&s.version===f.sourceVersion;}).length,denominator:fields.length,period:'Current workspace snapshot at '+at}},boundary:'Read-only dependency and current-snapshot engineering measurements. This does not prove a worker heartbeat, storage write/restore, production SLO, hosted-user journey, provider quality, scientific accuracy or organization qualification.'};
}
