import {env} from 'cloudflare:workers';
import {ForgeError,initialState,hash,uid,now} from './core.mjs';
export type User={userId:string;displayName:string;email:string};
export function database(){if(!env.DB)throw new ForgeError('DATABASE_UNAVAILABLE','Persistent storage is unavailable. Contact the workspace administrator.',503);return env.DB;}
export async function membership(workspaceId:string,userId:string){const m=await database().prepare('SELECT role FROM memberships WHERE workspace_id=? AND user_id=? AND active=1').bind(workspaceId,userId).first<{role:string}>();if(!m)throw new ForgeError('FORBIDDEN','You do not have access to this workspace.',403);return m;}
export async function listWorkspaces(userId:string){return (await database().prepare('SELECT w.id,w.name,w.version,w.updated_at,m.role FROM workspaces w JOIN memberships m ON m.workspace_id=w.id WHERE m.user_id=? AND m.active=1 ORDER BY w.updated_at DESC LIMIT 100').bind(userId).all()).results;}
export async function createWorkspace(user:User,name:string,product:string){const db=database();const count=await db.prepare('SELECT COUNT(*) AS n FROM workspaces WHERE owner_id=?').bind(user.userId).first<{n:number}>();if((count?.n||0)>=20)throw new ForgeError('WORKSPACE_QUOTA','This release supports 20 workspaces per owner.',409);const id=uid('ws'),state=initialState(name,product),at=now();const saved=await db.batch([db.prepare('INSERT INTO workspaces(id,name,owner_id,state,version,created_at,updated_at) SELECT ?,?,?,?,0,?,? WHERE (SELECT COUNT(*) FROM workspaces WHERE owner_id=?)<20').bind(id,name,user.userId,JSON.stringify(state),at,at,user.userId),db.prepare('INSERT INTO memberships(id,workspace_id,user_id,role,active,created_at) SELECT ?,?,?,\'owner\',1,? WHERE EXISTS(SELECT 1 FROM workspaces WHERE id=? AND owner_id=?)').bind(uid('member'),id,user.userId,at,id,user.userId)]);if(!saved[0].meta.changes)throw new ForgeError('WORKSPACE_QUOTA','Workspace limit reached. No additional workspace was created.',409);return {id,state,role:'owner'};}
export async function loadWorkspace(id:string,userId:string){const m=await membership(id,userId);const row=await database().prepare('SELECT id,state,version,owner_id FROM workspaces WHERE id=?').bind(id).first<{id:string;state:string;version:number;owner_id:string}>();if(!row)throw new ForgeError('NOT_FOUND','Workspace unavailable.',404);return {id:row.id,state:JSON.parse(row.state),role:m.role,ownerId:row.owner_id};}
export async function rateLimit(userId:string){const minute=Math.floor(Date.now()/60000),key=`${userId}:${minute}`;const row=await database().prepare('INSERT INTO request_limits(id,count,expires_at) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(key,new Date((minute+2)*60000).toISOString()).first<{count:number}>();if((row?.count||0)>60)throw new ForgeError('RATE_LIMITED','Too many operations. Wait a minute before retrying.',429);if(minute%10===0)await database().prepare('DELETE FROM request_limits WHERE expires_at<?').bind(now()).run();}
export async function previousOperation(workspaceId:string,userId:string,key:string,requestHash:string){const r=await database().prepare('SELECT result,request_hash FROM idempotent_operations WHERE id=? AND workspace_id=? AND user_id=?').bind(key,workspaceId,userId).first<{result:string;request_hash:string}>();if(r&&r.request_hash!==requestHash)throw new ForgeError('IDEMPOTENCY_CONFLICT','This operation key was already used for different input.',409);return r?JSON.parse(r.result):null;}
export async function commitWorkspace(id:string,before:any,after:any,userId:string,role:string,key:string,requestHash:string,result:any,file?:any,authorities:Array<{userId:string;role:string}>=[]){const db=database(),token=uid('commit'),stateText=JSON.stringify(after);if(stateText.length>4_000_000)throw new ForgeError('WORKSPACE_QUOTA','Workspace evidence limit reached. Archive this project before adding more records.',413);const last=await db.prepare('SELECT hash FROM audit_events WHERE workspace_id=? ORDER BY sequence DESC LIMIT 1').bind(id).first<{hash:string}>();let prior=last?.hash||null;const authorityGuard=authorities.map(()=> ' AND EXISTS(SELECT 1 FROM memberships WHERE workspace_id=? AND user_id=? AND active=1 AND role=?)').join(''),authorityBinds=authorities.flatMap(a=>[id,a.userId,a.role]);const commands=[db.prepare('UPDATE workspaces SET state=?,version=?,last_commit=?,updated_at=? WHERE id=? AND version=? AND EXISTS(SELECT 1 FROM memberships WHERE workspace_id=? AND user_id=? AND active=1 AND role=?)'+authorityGuard).bind(stateText,after.version,token,now(),id,before.version,id,userId,role,...authorityBinds),db.prepare('INSERT INTO workspace_revisions(id,workspace_id,version,state,hash,actor_id,created_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM workspaces WHERE id=? AND last_commit=?)').bind(uid('rev'),id,after.version,stateText,await hash(stateText),userId,now(),id,token)];
 for(const e of after.audit.slice(before.audit.length)){const payload=JSON.stringify(e);const digest=await hash(`${prior||''}:${payload}`);commands.push(db.prepare('INSERT INTO audit_events(id,workspace_id,sequence,actor_id,action,object_id,payload,hash,previous_hash,created_at) SELECT ?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM workspaces WHERE id=? AND last_commit=?)').bind(e.id,id,e.sequence,userId,e.action,e.objectId,payload,digest,prior,e.at,id,token));prior=digest;}
 commands.push(db.prepare('INSERT INTO idempotent_operations(id,workspace_id,user_id,request_hash,result,created_at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM workspaces WHERE id=? AND last_commit=?)').bind(key,id,userId,requestHash,JSON.stringify(result),now(),id,token));
 if(file)commands.push(db.prepare('INSERT INTO source_files(id,workspace_id,source_id,object_key,hash,mime,name,size,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM workspaces WHERE id=? AND last_commit=?)').bind(file.id,id,file.sourceId,file.objectKey,file.hash,file.mime,file.name,file.size,now(),id,token));
 const saved=await db.batch(commands);if(!saved[0].meta.changes)throw new ForgeError('STALE_REVISION','Workspace changed or membership was revoked. Refresh before continuing.',409);return after;}
export async function addMember(workspaceId:string,userId:string,input:any){const m=await membership(workspaceId,userId);if(m.role!=='owner')throw new ForgeError('FORBIDDEN','Only the owner manages membership.',403);if(input.active!==false&&String(input.userId).startsWith('forge:')){const verified=await database().prepare('SELECT id FROM forge_auth_accounts WHERE id=? AND email_verified=1 AND active=1').bind(input.userId).first();if(!verified)throw new ForgeError('IDENTITY_UNVERIFIED','Shared membership requires a verified identity.',403);}if(input.userId===userId)throw new ForgeError('OWNER_PROTECTED','The owner cannot remove their own access.',409);if(!['admin','author','reviewer','approver','viewer'].includes(input.role))throw new ForgeError('INVALID_ROLE','Unsupported role.');await database().prepare('INSERT INTO memberships(id,workspace_id,user_id,role,active,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(workspace_id,user_id) DO UPDATE SET role=excluded.role,active=excluded.active').bind(uid('member'),workspaceId,input.userId,input.role,input.active===false?0:1,now()).run();}
export async function history(workspaceId:string,userId:string,revision?:number){await membership(workspaceId,userId);if(revision!==undefined){const r=await database().prepare('SELECT state,hash,created_at,version FROM workspace_revisions WHERE workspace_id=? AND version=?').bind(workspaceId,revision).first<{state:string;hash:string;created_at:string;version:number}>();if(!r)throw new ForgeError('NOT_FOUND','Historical revision unavailable.',404);if(await hash(r.state)!==r.hash)throw new ForgeError('INTEGRITY_FAILED','Historical revision hash check failed.',409);return {...r,state:JSON.parse(r.state)};}return (await database().prepare('SELECT version,hash,actor_id,created_at FROM workspace_revisions WHERE workspace_id=? ORDER BY version DESC LIMIT 100').bind(workspaceId).all()).results;}
export async function verifyAudit(workspaceId:string,userId:string){await membership(workspaceId,userId);const rows=(await database().prepare('SELECT payload,hash,previous_hash,sequence FROM audit_events WHERE workspace_id=? ORDER BY sequence').bind(workspaceId).all<{payload:string;hash:string;previous_hash:string|null;sequence:number}>()).results;let prior:string|null=null;for(let i=0;i<rows.length;i++){const r=rows[i];if(r.previous_hash!==prior||r.sequence!==i+1||r.hash!==await hash(`${prior||''}:${r.payload}`))return {passed:false,checked:i,denominator:rows.length,limitation:'Application hash chain; a privileged database administrator remains in the threat model.'};prior=r.hash;}return {passed:true,checked:rows.length,denominator:rows.length,limitation:'Application hash chain; not an independently notarized immutable ledger.'};}
