import {providerConfig,providerConfigured} from './provider-config.mjs';
import {env} from 'cloudflare:workers';
import {database,loadWorkspace,membership} from './repository';
import {ForgeError,hash,uid,audit,actorCan} from './core.mjs';
import {createRuntimePlan,claimRuntimeJob,executeRuntimeJob,failureTransition,controlRuntime,ACTIVE_WORKFLOW,MAX_ATTEMPTS,RUNTIME_VERSION} from './runtime.mjs';
type Any=Record<string,any>;
const readableReason=(value:any)=>{if(!value)return null;try{return JSON.parse(value).reason||value;}catch{return value;}};
const workflow=(r:Any)=>({id:r.id,workspaceId:r.workspace_id,createdBy:r.created_by,goal:r.goal,status:r.status,generation:r.generation,version:r.version,cursorRevision:r.cursor_revision,cursorHash:r.cursor_hash,config:JSON.parse(r.config),pauseReason:readableReason(r.pause_reason),createdAt:r.created_at,updatedAt:r.updated_at});
const job=(r:Any)=>({id:r.id,workflowId:r.workflow_id,workspaceId:r.workspace_id,generation:r.generation,nodeKey:r.node_key,kind:r.kind,status:r.status,dependsOn:JSON.parse(r.depends_on),payload:JSON.parse(r.payload),inputRevision:r.input_revision,inputHash:r.input_hash,sourceRefs:JSON.parse(r.source_refs),attempts:r.attempts,availableAt:r.available_at,leaseToken:r.lease_token,leaseUntil:r.lease_until,version:r.version,output:r.output?JSON.parse(r.output):null,failure:r.failure?JSON.parse(r.failure):null,createdAt:r.created_at,updatedAt:r.updated_at});
async function readWorkflow(id:string){const r=await database().prepare('SELECT * FROM runtime_workflows WHERE id=?').bind(id).first<Any>();if(!r)throw new ForgeError('NOT_FOUND','Workflow unavailable.',404);return workflow(r);}
async function readJobs(id:string){return (await database().prepare('SELECT * FROM runtime_jobs WHERE workflow_id=? ORDER BY created_at,node_key').bind(id).all<Any>()).results.map(job);}
function eventSQL(workflowId:string,jobId:string|null,action:string,actorId:string,payload:Any,guard:string,binds:any[]){return database().prepare(`INSERT INTO runtime_events(id,workflow_id,job_id,action,actor_id,payload,created_at) SELECT ?,?,?,?,?,?,? WHERE ${guard}`).bind(uid('runtimeEvent'),workflowId,jobId,action,actorId,JSON.stringify(payload),new Date().toISOString(),...binds);}
function jobInsert(j:Any,workspaceId:string,guard:string,binds:any[]){return database().prepare(`INSERT INTO runtime_jobs(id,workflow_id,workspace_id,generation,node_key,kind,status,depends_on,payload,source_refs,attempts,available_at,version,created_at,updated_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE ${guard}`).bind(j.id,j.workflowId,workspaceId,j.generation,j.nodeKey,j.kind,j.status,JSON.stringify(j.dependsOn),JSON.stringify(j.payload),JSON.stringify(j.sourceRefs),j.attempts,j.availableAt,j.version,j.createdAt,j.updatedAt,...binds);}
export async function runtimeOverview(workspaceId:string,userId:string){await membership(workspaceId,userId);const flows=(await database().prepare('SELECT * FROM runtime_workflows WHERE workspace_id=? ORDER BY created_at DESC LIMIT 30').bind(workspaceId).all<Any>()).results.map(workflow);const ids=flows.map(f=>f.id);const jobs=[];for(const id of ids)jobs.push(...await readJobs(id));const events=(await database().prepare('SELECT e.* FROM runtime_events e JOIN runtime_workflows w ON w.id=e.workflow_id WHERE w.workspace_id=? ORDER BY e.created_at DESC LIMIT 100').bind(workspaceId).all()).results;return {workflows:flows,jobs,events,runtime:{version:RUNTIME_VERSION,durable:true,maximumRetries:3,maximumInvocations:4,independentWorkerConfigured:Boolean((env as Any).FORGE_WORKER_TOKEN),providerConfigured:providerConfigured(env),schedulerConfigured:false,schedulerState:'NOT_ESTABLISHED',authority:'HUMAN_ONLY',externalEffectSemantics:'At-least-once invocation with stable provider operation ID; scientific commits are guarded and idempotent.'}};}
export async function enqueueRuntime(workspaceId:string,userId:string,key:string,input:Any){
 const db=database(),ws=await loadWorkspace(workspaceId,userId);
 if(!actorCan(ws.role,'plan'))throw new ForgeError('FORBIDDEN','Your role cannot create or replay runtime plans.',403);
 const digest=await hash(JSON.stringify(input)),prior=await db.prepare('SELECT * FROM runtime_workflows WHERE workspace_id=? AND created_by=? AND op_key=?').bind(workspaceId,userId,key).first<Any>();
 if(prior){if(prior.request_hash!==digest)throw new ForgeError('IDEMPOTENCY_CONFLICT','Operation key already used for different workflow input.',409);return {workflow:workflow(prior),idempotent:true};}
 const active=await db.prepare("SELECT COUNT(*) AS n FROM runtime_workflows WHERE workspace_id=? AND status NOT IN ('COMPLETE','CANCELLED')").bind(workspaceId).first<{n:number}>();
 if((active?.n||0)>=100)throw new ForgeError('RUNTIME_QUOTA','This release supports 100 unfinished workflows per workspace.',409);
 const p=await createRuntimePlan(ws.state,input,{id:userId,role:ws.role}),w=p.workflow;
 const guard='EXISTS(SELECT 1 FROM runtime_workflows WHERE id=? AND request_hash=?)',binds=[w.id,digest];
 const statements=[db.prepare('INSERT INTO runtime_workflows(id,workspace_id,created_by,op_key,request_hash,goal,status,generation,version,cursor_revision,cursor_hash,config,created_at,updated_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM workspaces WHERE id=? AND version=?) AND EXISTS(SELECT 1 FROM memberships WHERE workspace_id=? AND user_id=? AND active=1 AND role=?)').bind(w.id,workspaceId,userId,key,digest,w.goal,w.status,w.generation,w.version,w.cursorRevision,w.cursorHash,JSON.stringify(w.config),w.createdAt,w.updatedAt,workspaceId,ws.state.version,workspaceId,userId,ws.role),...p.jobs.map((j:Any)=>jobInsert(j,workspaceId,guard,binds)),eventSQL(w.id,null,'ENQUEUE',userId,{goal:w.goal,inputRevision:w.cursorRevision,inputHash:w.cursorHash,config:w.config},guard,binds)];
 let saved;try{saved=await db.batch(statements);}catch(e){
   const current=await membership(workspaceId,userId);
   if(!actorCan(current.role,'plan'))throw new ForgeError('FORBIDDEN','Your role no longer permits runtime plans.',403);
   const duplicate=await db.prepare('SELECT * FROM runtime_workflows WHERE workspace_id=? AND created_by=? AND op_key=?').bind(workspaceId,userId,key).first<Any>();
   if(duplicate&&duplicate.request_hash===digest)return {workflow:workflow(duplicate),idempotent:true};throw e;
 }
 if(!saved[0].meta.changes)throw new ForgeError('STALE_REVISION','Workspace changed or membership was revoked before enqueue.',409);
 return {workflow:{...w,workspaceId},jobs:p.jobs};
}
export async function controlDurableRuntime(workflowId:string,userId:string,input:Any){const db=database(),w=await readWorkflow(workflowId),ws=await loadWorkspace(w.workspaceId,userId);if(w.version!==input.expectedWorkflowVersion)throw new ForgeError('STALE_WORKFLOW','Workflow changed before control.',409);const jobs=await readJobs(w.id),r=controlRuntime(w,jobs,input.control,input.reason,{id:userId,role:ws.role},ws.state);let next=r.workflow,nextJobs=r.jobs;
 if(['resume','manualFallback','replan'].includes(input.control)){next.cursorRevision=ws.state.version;next.cursorHash=await hash(JSON.stringify(ws.state));}
 if(input.control==='replan'){const p=await createRuntimePlan(ws.state,{...w.config,goal:w.goal,expectedVersion:ws.state.version},{id:userId,role:ws.role});next.generation=w.generation+1;nextJobs=[...jobs.map(j=>j.status==='COMPLETE'?j:{...j,status:'CANCELLED',version:j.version+1,leaseToken:null,leaseUntil:null}),...p.jobs.map((j:Any)=>({...j,workflowId:w.id,generation:next.generation}))];}
 // A nonce in control evidence makes subsequent writes belong to this exact winning CAS.
 const token=uid('control'),recorded=JSON.stringify({reason:next.pauseReason,token});const statements=[db.prepare('UPDATE runtime_workflows SET status=?,generation=?,version=?,cursor_revision=?,cursor_hash=?,config=?,pause_reason=?,updated_at=? WHERE id=? AND version=? AND EXISTS(SELECT 1 FROM workspaces WHERE id=? AND version=? AND state=?) AND EXISTS(SELECT 1 FROM memberships WHERE workspace_id=? AND user_id=? AND active=1 AND role=?)').bind(next.status,next.generation,next.version,next.cursorRevision,next.cursorHash,JSON.stringify(next.config),recorded,next.updatedAt,w.id,w.version,w.workspaceId,ws.state.version,JSON.stringify(ws.state),w.workspaceId,userId,ws.role)];const guard='EXISTS(SELECT 1 FROM runtime_workflows WHERE id=? AND version=? AND pause_reason=?)',binds=[w.id,next.version,recorded];for(const j of nextJobs){if(jobs.some(old=>old.id===j.id))statements.push(db.prepare(`UPDATE runtime_jobs SET status=?,version=?,payload=?,attempts=?,lease_token=?,lease_until=?,available_at=?,updated_at=? WHERE id=? AND ${guard}`).bind(j.status,j.version,JSON.stringify(j.payload),j.attempts,j.leaseToken,j.leaseUntil,j.availableAt,j.updatedAt,j.id,...binds));else statements.push(jobInsert(j,w.workspaceId,guard,binds));}statements.push(eventSQL(w.id,null,input.control.toUpperCase(),userId,r.event,guard,binds));const results=await db.batch(statements);if(!results[0].meta.changes)throw new ForgeError('STALE_WORKFLOW','Concurrent workspace/control change or revoked membership prevented this change.',409);return {workflow:await readWorkflow(w.id),jobs:await readJobs(w.id)};}
async function finish(w:Any,j:Any,ws:Any,result:Any,clock:number){const db=database(),token=uid('runtimeCommit'),after=result.state||structuredClone(ws.state);if(!result.state){audit(after,{id:w.createdBy,role:ws.role,traceId:w.id},result.status==='HUMAN_WAIT'||result.status==='COMPLETE'?'runtimeHumanGate':'runtimeTaskFailure',j.id,{kind:j.kind,status:result.status,inputHash:j.inputHash,output:result.output,humanApprovalGranted:false});after.version++;}const stateText=JSON.stringify(after);if(stateText.length>4_000_000)throw new ForgeError('WORKSPACE_QUOTA','Workspace evidence quota exceeded.',413);const all=await readJobs(w.id),nextStatus=result.status==='COMPLETE'&&all.filter(x=>x.generation===w.generation&&x.id!==j.id).every(x=>x.status==='COMPLETE')?'COMPLETE':result.status==='HUMAN_WAIT'?'HUMAN_WAIT':['HOLD','DLQ'].includes(result.status)?result.status:'RUNNING';const at=new Date(clock).toISOString();
 const claimGuard='EXISTS(SELECT 1 FROM runtime_jobs WHERE id=? AND version=? AND status=\'RUNNING\' AND lease_token=? AND lease_until>?) AND EXISTS(SELECT 1 FROM runtime_workflows WHERE id=? AND version=? AND generation=? AND status IN (\'READY\',\'RUNNING\')) AND EXISTS(SELECT 1 FROM memberships WHERE workspace_id=? AND user_id=? AND active=1 AND role=?)';const claimBinds=[j.id,j.version,j.leaseToken,clock,w.id,w.version,w.generation,w.workspaceId,w.createdBy,ws.role];const commands=[db.prepare(`UPDATE workspaces SET state=?,version=?,last_commit=?,updated_at=? WHERE id=? AND version=? AND ${claimGuard}`).bind(stateText,after.version,token,at,w.workspaceId,ws.state.version,...claimBinds)];const guard='EXISTS(SELECT 1 FROM workspaces WHERE id=? AND last_commit=?)',binds=[w.workspaceId,token];
 commands.push(db.prepare(`INSERT INTO workspace_revisions(id,workspace_id,version,state,hash,actor_id,created_at) SELECT ?,?,?,?,?,?,? WHERE ${guard}`).bind(uid('rev'),w.workspaceId,after.version,stateText,await hash(stateText),w.createdBy,at,...binds));const last=await db.prepare('SELECT hash FROM audit_events WHERE workspace_id=? ORDER BY sequence DESC LIMIT 1').bind(w.workspaceId).first<Any>();let prior=last?.hash||null;for(const e of after.audit.slice(ws.state.audit.length)){const payload=JSON.stringify(e),digest=await hash(`${prior||''}:${payload}`);commands.push(db.prepare(`INSERT INTO audit_events(id,workspace_id,sequence,actor_id,action,object_id,payload,hash,previous_hash,created_at) SELECT ?,?,?,?,?,?,?,?,?,? WHERE ${guard}`).bind(e.id,w.workspaceId,e.sequence,w.createdBy,e.action,e.objectId,payload,digest,prior,e.at,...binds));prior=digest;}
 commands.push(db.prepare(`UPDATE runtime_jobs SET status=?,version=version+1,output=?,failure=?,available_at=?,lease_token=NULL,lease_until=NULL,updated_at=? WHERE id=? AND ${guard}`).bind(result.status,JSON.stringify(result.output||{}),result.failure?JSON.stringify(result.failure):null,result.availableAt||clock,at,j.id,...binds));commands.push(db.prepare(`UPDATE runtime_workflows SET status=?,version=version+1,cursor_revision=?,cursor_hash=?,updated_at=? WHERE id=? AND ${guard}`).bind(nextStatus,after.version,await hash(stateText),at,w.id,...binds));commands.push(eventSQL(w.id,j.id,result.status,w.createdBy,{inputRevision:j.inputRevision,inputHash:j.inputHash,attempts:j.attempts,output:result.output,failure:result.failure||null,resultRevision:after.version,automaticApproval:false},guard,binds));const saved=await db.batch(commands);if(!saved[0].meta.changes)throw new ForgeError('RUNTIME_COMMIT_CONFLICT','Lease expired, workspace changed, control interrupted or membership was revoked. No candidate committed.',409);return {jobId:j.id,status:result.status,workspaceVersion:after.version};}
async function claimOne(workspaceId?:string,userId?:string,clock=Date.now()){
 const db=database();const rows=(await db.prepare(`SELECT * FROM runtime_workflows WHERE status IN ('READY','RUNNING') ${workspaceId?'AND workspace_id=?':''} ORDER BY updated_at LIMIT 30`).bind(...(workspaceId?[workspaceId]:[])).all<Any>()).results;
 for(const row of rows){const w=workflow(row);if(userId){const m=await membership(w.workspaceId,userId);if(!actorCan(m.role,'planControl'))throw new ForgeError('FORBIDDEN','Your role cannot advance runtime work.',403);}let ws;try{ws=await loadWorkspace(w.workspaceId,w.createdBy);}catch(e){await db.prepare("UPDATE runtime_workflows SET status='HOLD',pause_reason='CREATOR_MEMBERSHIP_REVOKED',version=version+1 WHERE id=? AND version=?").bind(w.id,w.version).run();continue;}const jobs=await readJobs(w.id);
 for(const j of jobs.filter(x=>x.generation===w.generation)){if(j.status==='RUNNING'&&j.leaseUntil<=clock&&j.attempts>=MAX_ATTEMPTS){await db.batch([db.prepare("UPDATE runtime_jobs SET status='DLQ',failure=?,version=version+1,lease_token=NULL,lease_until=NULL WHERE id=? AND version=? AND lease_until<=?").bind(JSON.stringify({code:'LEASE_RECOVERY_EXHAUSTED',manualFallback:true}),j.id,j.version,clock),db.prepare("UPDATE runtime_workflows SET status='DLQ',version=version+1 WHERE id=? AND version=?").bind(w.id,w.version)]);continue;}let claimed;try{claimed=await claimRuntimeJob(j,w,jobs,ws.state,clock);}catch(e:any){if(e.code==='RUNTIME_STALE_REVISION'){await db.prepare("UPDATE runtime_workflows SET status='HOLD',pause_reason='STALE_WORKSPACE_REPLAN_REQUIRED',version=version+1 WHERE id=? AND version=?").bind(w.id,w.version).run();break;}throw e;}if(!claimed)continue;
 const saved=await db.batch([db.prepare("UPDATE runtime_jobs SET status='RUNNING',attempts=?,lease_token=?,lease_until=?,input_revision=?,input_hash=?,source_refs=?,version=?,updated_at=? WHERE id=? AND version=? AND (status IN ('QUEUED','RETRY_WAIT') OR (status='RUNNING' AND lease_until<=?)) AND EXISTS(SELECT 1 FROM runtime_workflows WHERE id=? AND version=? AND status IN ('READY','RUNNING')) AND EXISTS(SELECT 1 FROM memberships WHERE workspace_id=? AND user_id=? AND active=1 AND role=?)").bind(claimed.attempts,claimed.leaseToken,claimed.leaseUntil,claimed.inputRevision,claimed.inputHash,JSON.stringify(claimed.sourceRefs),claimed.version,claimed.updatedAt,j.id,j.version,clock,w.id,w.version,w.workspaceId,w.createdBy,ws.role),eventSQL(w.id,j.id,'CLAIM',w.createdBy,{inputRevision:claimed.inputRevision,inputHash:claimed.inputHash,attempt:claimed.attempts,reclaimed:j.status==='RUNNING'},'EXISTS(SELECT 1 FROM runtime_jobs WHERE id=? AND lease_token=?)',[j.id,claimed.leaseToken])]);if(saved[0].meta.changes)return {workflow:w,job:claimed,ws,jobs};}
 }return null;
}
export async function tickDurableRuntime(options:{workspaceId?:string;userId?:string;limit?:number;clock?:number;adapters?:Any}={}){if(options.userId){if(!options.workspaceId)throw new ForgeError('WORKSPACE_REQUIRED','Authenticated ticks require a workspace.',422);const current=await membership(options.workspaceId,options.userId);if(!actorCan(current.role,'planControl'))throw new ForgeError('FORBIDDEN','Your role cannot advance runtime work.',403);}const limit=Math.max(1,Math.min(options.userId?3:8,Number(options.limit)||1)),results=[];for(let n=0;n<limit;n++){const clock=options.clock||Date.now(),claimed=await claimOne(options.workspaceId,options.userId,clock);if(!claimed)break;const {workflow:w,job:j,ws,jobs}=claimed;const context=jobs.filter(x=>x.generation===w.generation&&x.status==='COMPLETE').reduce((a,j)=>({...a,...j.output}),{});const cfg={...providerConfig(env),readOriginal:async(source:Any)=>{const bytes=await env.BUCKET?.get(source.objectKey);return bytes?.arrayBuffer();},...options.adapters};try{const result=await executeRuntimeJob(j,ws.state,{id:w.createdBy,role:ws.role},cfg,context);results.push(await finish(w,j,ws,result,options.clock||Date.now()));}catch(e:any){if(e.code==='RUNTIME_COMMIT_CONFLICT'){results.push({jobId:j.id,status:'RECOVERY_PENDING',code:e.code});continue;}const failed=failureTransition(j,e,options.clock||Date.now());try{results.push(await finish(w,j,ws,{status:failed.status,state:null,output:{completed:false,costState:'NOT_MEASURED',tokenState:'NOT_MEASURED'},failure:failed.failure,availableAt:failed.availableAt},options.clock||Date.now()));}catch(conflict:any){results.push({jobId:j.id,status:'RECOVERY_PENDING',code:conflict.code||'COMMIT_FAILED'});}}}return {processed:results.length,results,automaticApproval:false};}

/** Trusted worker hook entry: no browser lifetime dependency; bounded cycle only. */
export async function workerCycle(options:{workspaceId?:string;userId?:string;limit?:number}={}){return tickDurableRuntime({workspaceId:options.workspaceId,userId:options.userId,limit:Math.min(8,options.limit||8)});}
