import {ForgeError,hash,requireValue} from './core.mjs';

/** Exact-object external collaboration. Grants confer access, never scientific authority. */
export const SHARING_VERSION='forge-object-sharing/1';
export const SHARED_TYPES={source:'sources',field:'fields',draft:'drafts',query:'queries',action:'actions'};
export const SHARING_PERMISSIONS=['view','comment','requestReview'];
const fail=(code,message,status=400)=>{throw new ForgeError(code,message,status);};
export function sharingObject(state,type,id){const collection=SHARED_TYPES[type];if(!collection)fail('INVALID_OBJECT_TYPE','Share a source, field, draft, query or action.');const object=state[collection]?.find(x=>x.id===id);if(!object)fail('OBJECT_UNAVAILABLE','Object unavailable in this workspace.',403);return object;}
export function objectSourceIds(state,type,object){if(type==='source')return [object.id];if(type==='field')return [object.sourceId];if(type==='draft'||type==='query')return [...new Set((object.fieldIds||[]).map(id=>sharingObject(state,'field',id).sourceId))];return [...new Set(object.sourceIds||[])];}
export async function sharingRevision(state,type,id){const o=sharingObject(state,type,id);return `${o.version??o.revision??1}:${await hash(JSON.stringify(o))}`;}
export async function verifyShareableObject(state,type,id){const o=sharingObject(state,type,id);if(['STALE','SUPERSEDED','REJECTED'].includes(o.status))fail('STALE_OBJECT','Share the current supported object revision.',409);const ids=objectSourceIds(state,type,o);if(!ids.length)fail('EVIDENCE_REQUIRED','An external object requires recorded source evidence.',409);for(const sourceId of ids){const src=sharingObject(state,'source',sourceId);if(src.status==='SUPERSEDED'||!src.permission||!src.hash)fail('EVIDENCE_REQUIRED','Current source permission and hash are required.',409);if((src.text||!src.objectKey)&&src.text!==undefined&&src.text!==null&&await hash(src.text)!==src.hash)fail('SOURCE_HASH_MISMATCH','The recorded source text fails its evidence hash.',409);if(!src.text&&!src.objectKey)fail('EVIDENCE_REQUIRED','A preserved source original is required.',409);}
const fields=type==='field'?[o]:(type==='draft'||type==='query')?(o.fieldIds||[]).map(fid=>sharingObject(state,'field',fid)):[];for(const f of fields){const src=sharingObject(state,'source',f.sourceId);if(['STALE','REJECTED'].includes(f.status)||f.sourceHash!==src.hash||f.sourceVersion!==src.version||!f.span?.raw)fail('EVIDENCE_REQUIRED','Facts require current source hashes and original spans.',409);}return {object:o,revision:await sharingRevision(state,type,id),sourceIds:ids};}
export function validSharingUser(value){const id=requireValue(value,'Stable platform user ID',160);if(/\s|@|[<>"'`]/.test(id))fail('INVALID_USER_ID','Use the exact platform user ID, not an email or a display name.');return id;}
export function validateGrantInput(input,at=new Date().toISOString()){const granteeId=validSharingUser(input.granteeId);if(input.permissionConfirmed!==true)fail('PERMISSION_REQUIRED','Confirm your authority to share this exact object externally.',403);const permissionBasis=safeSharedNote(requireValue(input.permissionBasis,'External sharing permission basis',1000)),reason=safeSharedNote(requireValue(input.reason,'Sharing reason',1000));const permissions=[...new Set(input.permissions||[])];if(!permissions.includes('view')||permissions.some(p=>!SHARING_PERMISSIONS.includes(p)))fail('INVALID_PERMISSION','Select view and optional comment or requestReview.');if(input.allowOriginal&&input.objectType!=='source')fail('INVALID_PERMISSION','Original access requires an explicit source grant.');const end=Date.parse(input.expiresAt),start=Date.parse(at);if(!Number.isFinite(end)||end<=start||end-start>90*86400000)fail('INVALID_EXPIRY','Choose an expiry in the next 90 days.');return {granteeId,permissions,allowOriginal:input.allowOriginal===true,permissionBasis,reason,expiresAt:new Date(end).toISOString()};}
export function liveGrant(grant,userId,at=new Date().toISOString()){return grant.workspaceId&&grant.granteeId===userId&&grant.status==='ACTIVE'&&Date.parse(grant.expiresAt)>Date.parse(at);}
export async function authorizedGrant(state,grants,userId,type,id,permission='view',at=new Date().toISOString()){const revision=await sharingRevision(state,type,id);return grants.find(g=>liveGrant(g,userId,at)&&g.objectType===type&&g.objectId===id&&g.objectRevision===revision&&g.permissions.includes(permission))||null;}
export function safeSharedNote(value){const body=requireValue(value,'Shared note',2000);if(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/.test(body)||/<\/?[a-z][^>]*>/i.test(body))fail('UNSAFE_NOTE','Use plain text without active markup or control characters.');if(/[\w.+-]+@[\w.-]+\.[a-z]{2,}/i.test(body)||/(?<!\w)(?:\+?\d[\s()-]*){10,}(?!\w)/.test(body)||/\b(patient\s*(?:name|id)|aadhaar|social security|passport number)\s*[:=]/i.test(body))fail('PERSONAL_DATA_BLOCKED','Do not include personal identifiers or contact details in shared notes.');return body;}
/** Projections expose only explicitly granted objects. Dependency IDs/content are independently checked. */
export async function sharedProjection(state,grants,userId,notes=[],at=new Date().toISOString()){
 const active=[];for(const g of grants){if(!liveGrant(g,userId,at))continue;try{if(g.objectRevision===await sharingRevision(state,g.objectType,g.objectId)&&g.permissions.includes('view'))active.push(g);}catch{}}
 const allowed=new Set(active.map(g=>`${g.objectType}:${g.objectId}`)),has=(t,id)=>allowed.has(`${t}:${id}`);const items=[];
 for(const g of active){const o=sharingObject(state,g.objectType,g.objectId),item={id:o.id,type:g.objectType,objectRevision:g.objectRevision,grantId:g.id,grantRevision:g.revision,permissions:g.permissions,expiresAt:g.expiresAt,status:o.status||'CURRENT',title:o.title||o.name||o.parameter||g.objectType};
 if(g.objectType==='source')Object.assign(item,{mime:o.type,version:o.version,hash:o.hash,dataLabel:o.dataLabel||'OWNER_PERMISSION_REQUIRED',originalAvailable:g.allowOriginal===true,originalPath:g.allowOriginal?`/api/files/${encodeURIComponent(o.id)}`:null});
 if(g.objectType==='field')Object.assign(item,{parameter:o.parameter,rawValue:o.rawValue,rawUnit:o.rawUnit,value:o.value,unit:o.unit,method:o.method,basis:o.basis,revision:o.revision,sourceId:has('source',o.sourceId)?o.sourceId:null,sourceRedacted:!has('source',o.sourceId),span:has('source',o.sourceId)?o.span:null});
 if(g.objectType==='draft'){const statements=(o.statements||[]).filter(st=>has('field',st.fieldId)).map(st=>{const f=sharingObject(state,'field',st.fieldId);return {fieldId:st.fieldId,text:`Recorded ${f.parameter}: ${f.value} ${f.unit}.`,presentation:'SAFE_FACT_PROJECTION'};});Object.assign(item,{section:o.section,revision:o.revision,statements,redactedStatementCount:(o.statements||[]).length-statements.length,fieldIds:(o.fieldIds||[]).filter(fid=>has('field',fid)),approvalAuthority:false});}
 if(g.objectType==='query'){const response=(o.response||[]).filter(st=>has('field',st.fieldId)).map(st=>{const f=sharingObject(state,'field',st.fieldId);return {fieldId:st.fieldId,text:`Recorded ${f.parameter}: ${f.value} ${f.unit}.`,presentation:'SAFE_FACT_PROJECTION'};});Object.assign(item,{market:o.market,response,redactedResponseCount:(o.response||[]).length-response.length,fieldIds:(o.fieldIds||[]).filter(fid=>has('field',fid)),approvalAuthority:false});}
 if(g.objectType==='action')Object.assign(item,{due:o.due,expected:o.expected,sourceIds:(o.sourceIds||[]).filter(sid=>has('source',sid)),redactedSourceCount:(o.sourceIds||[]).filter(sid=>!has('source',sid)).length,closureAuthority:false});
 item.notes=notes.filter(n=>n.objectType===g.objectType&&n.objectId===g.objectId&&n.objectRevision===g.objectRevision).map(n=>({id:n.id,kind:n.kind,body:n.body,status:n.status,at:n.createdAt,author:n.authorId===userId?'YOU':'AUTHORIZED_COLLABORATOR'}));items.push(item);}
 return {sharingVersion:SHARING_VERSION,items,authority:{approve:false,reviseScientificFact:false,close:false,export:false,grant:false},limitation:'Exact-object collaboration only. A review request is routed to authorized workspace reviewers; it is not a scientific decision.'};
}
export function grantFromRow(r){return {id:r.id,workspaceId:r.workspace_id,objectType:r.object_type,objectId:r.object_id,objectRevision:r.object_revision,granteeId:r.grantee_id,permissions:JSON.parse(r.permissions),allowOriginal:r.allow_original===1,status:r.status,revision:r.revision,grantedBy:r.granted_by,reason:r.reason,permissionBasis:r.permission_basis,expiresAt:r.expires_at,createdAt:r.created_at,revokedAt:r.revoked_at};}
export function noteFromRow(r){return {id:r.id,workspaceId:r.workspace_id,grantId:r.grant_id,objectType:r.object_type,objectId:r.object_id,objectRevision:r.object_revision,authorId:r.author_id,kind:r.kind,body:r.body,status:r.status,createdAt:r.created_at};}
