import {ForgeError,hash,now} from './core.mjs';
export const base32=bytes=>{const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,v=0,out='';for(const b of bytes){v=(v<<8)|b;bits+=8;while(bits>=5){out+=chars[(v>>>(bits-5))&31];bits-=5;}}if(bits)out+=chars[(v<<(5-bits))&31];return out;};
export function unbase32(s){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,v=0,out=[];for(const c of s.replace(/=+$/,'')){const n=chars.indexOf(c);if(n<0)throw new ForgeError('INVALID_FACTOR','Invalid authenticator secret.');v=(v<<5)|n;bits+=5;if(bits>=8){out.push((v>>>(bits-8))&255);bits-=8;}}return new Uint8Array(out);}
export async function totp(secret,counter){const key=await crypto.subtle.importKey('raw',unbase32(secret),{name:'HMAC',hash:'SHA-1'},false,['sign']);const b=new Uint8Array(8);new DataView(b.buffer).setBigUint64(0,BigInt(counter));const h=new Uint8Array(await crypto.subtle.sign('HMAC',key,b)),o=h[19]&15;return String(((h[o]&127)<<24|h[o+1]<<16|h[o+2]<<8|h[o+3])%1000000).padStart(6,'0');}
export async function verifyTOTP(secret,code,lastCounter=-1,time=Date.now()){if(!/^\d{6}$/.test(code||''))throw new ForgeError('INVALID_OTP','Enter the six-digit authenticator code.');const c=Math.floor(time/30000);for(const counter of [c-1,c,c+1]){if(counter>lastCounter&&await totp(secret,counter)===code)return counter;}throw new ForgeError('AUTHENTICATION_FAILED','Code invalid, expired or already used.',403);}
async function cipherKey(secret){if(!secret||secret.length<32)throw new ForgeError('SIGNATURE_UNAVAILABLE','Signing encryption secret is not configured.',503);return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function encryptSecret(text,secret){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await cipherKey(secret),data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(text)));return JSON.stringify({iv:[...iv],data:[...data]});}
export async function decryptSecret(value,secret){const {iv,data}=JSON.parse(value),key=await cipherKey(secret);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(iv)},key,new Uint8Array(data)));}
export async function signatureRecord(userId,role,reason,revision){if(!['Authored','Technical Review','Regulatory Approval'].includes(reason))throw new ForgeError('SIGNATURE_REASON_REQUIRED','Select a controlled reason for signature.');return {signer:userId,role,reason,at:now(),revisionHash:await hash(JSON.stringify(revision)),authentication:'Sites identity + enrolled TOTP',scope:'Exact evidence package revision',limitation:'Part 11-oriented technical control; production identity procedures and organizational validation are not established.'};}
