import {initialState,command,SYNTHETIC_SOURCES,readiness,hash} from './core.mjs';
export const WORKING_PROOF_ID='synthetic-cmc-working-proof-v1';
export const WORKING_PROOF_VERSION='CMC-working-proof/1';

/** All scientific values originate in explicit synthetic fixtures. No model or real reviewer is impersonated. */
export async function buildWorkingProof(){
 let state=initialState('Drug X · saved CMC work sample','Drug X 100 mg immediate-release tablet (synthetic)');
 state.policy.required=[...state.policy.required,'dissolution'];
 const author={id:'synthetic-example-author',role:'author'},reviewer={id:'synthetic-example-reviewer',role:'reviewer'};
 async function apply(input,actor=author){const r=await command(state,{...input,expectedVersion:state.version},actor);state=r.state;return r.result;}
 for(const source of SYNTHETIC_SOURCES){const r=await apply({action:'intake',...source,permission:'Synthetic portfolio fixture only; no confidential or commercial data.',dataLabel:'SYNTHETIC'});await apply({action:'extract',id:r.sourceId});}
 for(const field of state.fields){await apply({action:'review',kind:'field',id:field.id,revision:field.revision,choice:field.issues?.length?'REQUEST_EVIDENCE':'APPROVE',reason:field.issues?.length?'Illustrative review: conflicting SYN-A assay values remain unresolved; request the original supporting record.':'Illustrative fixture check only: value, unit and source span match. This is not a qualified professional approval.'},reviewer);}
 const draft=await apply({action:'draft',title:'Drug X · source-linked Module 3 draft candidate',section:'3.2.P'});
 await apply({action:'qc',id:draft.draftId},reviewer);
 await apply({action:'review',kind:'draft',id:draft.draftId,revision:1,choice:'REQUEST_EVIDENCE',reason:'Illustrative decision: HOLD. Resolve the assay conflict and supply dissolution, composition, method-validation and stability evidence before considering an accepted output.'},reviewer);
 const facts=parameter=>state.fields.filter(f=>f.parameter===parameter);
 const evidence=fields=>fields.map(f=>({sourceId:f.sourceId,sourceName:state.sources.find(s=>s.id===f.sourceId).name,sourceVersion:f.sourceVersion,sourceHash:f.sourceHash,fieldId:f.id,raw:f.span.raw,line:f.span.line,start:f.span.start,end:f.span.end}));
 const rows=[
  {item:'Product and scope',sourceStatus:'HYPOTHETICAL',observation:'Drug X 100 mg immediate-release tablet is an illustrative case label. Strength and dosage form are assumptions, not verified product facts.',gap:'Actual product definition and composition not supplied.',module3:'3.2.P.1',why:'A case label cannot establish actual product composition.',next:'Obtain an authorized product/composition record.',reviewStatus:'REVIEW REQUIRED',evidence:[]},
  {item:'SYN-A assay',sourceStatus:'CONFLICT',observation:'COA: 98.6%; batch record: 99.1%. Same batch and method; difference is 0.5 percentage points.',gap:'No source supports choosing either result as the accepted value.',module3:'3.2.P.5.4',why:'Conflicting results cannot support an accepted batch-analysis statement.',next:'Request the original result and a qualified discrepancy assessment.',reviewStatus:'HOLD',evidence:evidence(facts('assay').filter(f=>f.batch==='SYN-A'))},
  {item:'Water and impurity results',sourceStatus:'AVAILABLE',observation:'SYN-A water 0.3%, impurity 0.08%; SYN-B water 0.4%, impurity 0.09%.',gap:'These are synthetic analytical records, not commercial batch evidence.',module3:'3.2.P.5.4',why:'Values remain useful only with batch, method, unit and exact source attached.',next:'Verify against permitted real originals before professional use.',reviewStatus:'ILLUSTRATIVE CHECK ONLY',evidence:evidence([...facts('water'),...facts('impurity')])},
  {item:'SYN-B assay normalization',sourceStatus:'AVAILABLE',observation:'Raw 986 mg/g is retained alongside the recorded mass-basis conversion to 98.6%.',gap:'The conversion does not resolve the separate SYN-A conflict.',module3:'3.2.P.5.4',why:'A normalized value must not conceal the original unit or batch context.',next:'Confirm conversion basis and applicable specification with a professional.',reviewStatus:'ILLUSTRATIVE CHECK ONLY',evidence:evidence(facts('assay').filter(f=>f.batch==='SYN-B'))},
  {item:'Dissolution',sourceStatus:'MISSING',observation:'No dissolution result is provided. It is an explicit required item in this synthetic exercise.',gap:'Result, procedure and acceptance criteria are absent.',module3:'3.2.P.5.1 / 3.2.P.5.2',why:'The missing critical value must remain missing, never guessed.',next:'Request the relevant permitted dissolution evidence.',reviewStatus:'HOLD',evidence:[]},
  {item:'Analytical procedures and validation',sourceStatus:'INCOMPLETE',observation:'Only synthetic method identifiers are supplied.',gap:'Full procedures and validation evidence are unavailable.',module3:'3.2.P.5.2 / 3.2.P.5.3',why:'A method identifier is not evidence of validated performance.',next:'Obtain procedures and validation records for qualified review.',reviewStatus:'REVIEW REQUIRED',evidence:evidence(state.fields)},
  {item:'Stability',sourceStatus:'MISSING',observation:'No timepoints, storage conditions or stability results are supplied.',gap:'No shelf-life or storage claim is supported.',module3:'3.2.P.8',why:'Analytical fixture values cannot establish stability.',next:'Request an authorized stability data package.',reviewStatus:'HOLD',evidence:[]},
 ];
 const assessment={title:'CMC GAP ASSESSMENT',status:'HOLD',revision:state.version,rows,decision:'Request evidence; do not select an unsupported assay value or invent a missing result.',humanBoundary:'Qualified CMC / RA / QA review remains required. Recorded example decisions are synthetic and are not professional sign-off.',nextProof:'Resolve the discrepancy using supplied evidence, then recheck the changed revision before named human review.'};
 state.ext={...state.ext,workingProof:{id:WORKING_PROOF_ID,version:WORKING_PROOF_VERSION,synthetic:true,readOnly:true,assessment}};
 return {id:WORKING_PROOF_ID,fixtureVersion:WORKING_PROOF_VERSION,state,assessment,summary:readiness(state),synthetic:true,readOnly:true,release:false,providerExecution:false,boundary:'Independent portfolio exercise. Synthetic product data. Not a commercial submission, regulatory advice or evidence of commercial CMC experience.'};
}
export async function workingProofHash(payload){return hash(typeof payload==='string'?payload:JSON.stringify(payload));}
