import {capability} from './capabilities.mjs';
import {jsonSpans,csvRows} from './parser.mjs';
import {makePlan,replan,executeRole,mergeSpecialistOutputs} from './agentic.mjs';
import {hydrateLifecycle,lifecycleAction,lifecycleGraph,invalidateLifecycle} from './lifecycle.mjs';
import {branchAction} from './branches.mjs';
import {statementIssues} from './statement-controls.mjs';
/** FORGE domain engine. Pure deterministic state transitions; no network or UI authority. */
export const VERSION='forge-2.1.0';
export const PARSER='forge-typed-parser/1';
export const uid=(prefix='obj')=>`${prefix}_${crypto.randomUUID()}`;
export const now=()=>new Date().toISOString();
export class ForgeError extends Error{constructor(code,message,status=400){super(message);this.code=code;this.status=status;}}
const fail=(code,message,status=400)=>{throw new ForgeError(code,message,status)};
export const requireValue=(value,label,max=500)=>{if(typeof value!=='string'||!value.trim()||value.length>max)fail('INVALID_INPUT',`${label} is required (maximum ${max} characters).`);return value.trim();};
export async function hash(value){const bytes=typeof value==='string'?new TextEncoder().encode(value):value;return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export function initialState(name='CMC workspace',product='Synthetic formulation'){
 return {version:0,name,product,purpose:'Controlled CMC evidence and draft preparation',createdAt:now(),policy:{version:'policy/1',required:['assay','water','impurity'],reviewerSeparation:true,release:false},sources:[],fields:[],conflicts:[],drafts:[],decisions:[],changes:[],exports:[],queries:[],actions:[],mappings:[],requirements:[],templates:[],jobs:[],audit:[],markets:[],lineage:[],validationRuns:[],plans:[],agentRuns:[],retention:{days:365,status:'ORGANIZATION_REVIEW_REQUIRED'}};
}
export function actorCan(role,action){const authoring=['intake','extract','normalize','draft','editDraft','change','supersedeSource','query','action','mapping','market','lineage','template','simulate','runSpecialist','plan','replan','planControl','collaborate','capability','lifecycle','branch'];const allowed={owner:['*'],admin:[...authoring,'qc'],author:authoring,reviewer:['review','resolveConflict','qc','close','query','queryDecision','action','simulate','runSpecialist','plan','replan','planControl','collaborate','capability','lifecycle','branch'],approver:['review','resolveConflict','qc','export','close','query','queryDecision','simulate','runSpecialist','plan','replan','planControl','collaborate','capability','lifecycle','branch'],viewer:[]};return (allowed[role]||[]).some(x=>x==='*'||x===action);}
export function audit(state,actor,action,objectId,details={}){const event={id:uid('event'),sequence:state.audit.length+1,actor:actor.id,role:actor.role,action,objectId,details,at:now(),traceId:actor.traceId||uid('run'),revision:state.version+1};state.audit.push(event);return event;}
export function getObject(state,kind,id){const o=state[kind]?.find(x=>x.id===id);if(!o)fail('NOT_FOUND','This record is unavailable in the current workspace.',404);return o;}
function numeric(raw){if(raw===null||raw===undefined||String(raw).trim()==='')return null;const lexeme=String(raw).trim();if(!/^[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?$/.test(lexeme))return null;const value=Number(lexeme),significant=lexeme.split(/[eE]/)[0].replace(/^[+-]/,'').replace('.','').replace(/^0+/,'').replace(/0+$/,'');return Number.isFinite(value)&&significant.length<=15&&(!Number.isInteger(value)||Number.isSafeInteger(value))&&!(value===0&&/[1-9]/.test(lexeme.split(/[eE]/)[0]))?value:null;}
function parseCSV(text){let rows;try{rows=csvRows(text);}catch(e){fail('PARSE_FAILED',e.message);}if(rows.length<2)fail('PARSE_FAILED','CSV needs a header and parameter row.');const headers=rows.shift().cells.map(x=>x.trim().toLowerCase());if(new Set(headers).size!==headers.length||headers.some(h=>!h))fail('PARSE_FAILED','Duplicate or empty CSV headers are ambiguous.');if(rows.some(r=>r.cells.length!==headers.length))fail('PARSE_FAILED','CSV rows must match the controlled header field count.');if(!headers.includes('parameter')||!headers.includes('value'))fail('PARSE_FAILED','CSV requires parameter and value columns.');return rows.map((r,i)=>({...Object.fromEntries(headers.map((h,j)=>[h,r.cells[j]||''])),_line:r.line,_raw:r.raw,_path:`rows[${i+1}].value`,_start:r.start,_end:r.end}));}
export function parseSource(text,type){
 if(typeof text!=='string'||text.length>1_000_000)fail('INPUT_TOO_LARGE','Source text exceeds the supported limit.',413);
 if(/<(script|iframe|object)\b/i.test(text))fail('UNSAFE_INPUT','Active HTML is not an accepted CMC source.');
 let rows;if(type==='application/json'){let doc;try{doc=JSON.parse(text.replace(/^\uFEFF/,''));}catch{fail('PARSE_FAILED','The source is not valid JSON.');}rows=Array.isArray(doc)?doc:doc.parameters;if(!Array.isArray(rows)||!rows.length)fail('PARSE_FAILED','JSON needs a non-empty parameters array.');const locations=jsonSpans(text);const prefix=Array.isArray(doc)?'':'parameters';rows=rows.map((r,i)=>{const path=`${prefix}[${i}]`,span=locations.get(path),valueSpan=locations.get(`${path}.value`);return {...r,_line:span?.line||null,_raw:span?.token||'',_valueToken:valueSpan?.token,_lowToken:locations.get(`${path}.low`)?.token,_highToken:locations.get(`${path}.high`)?.token,_timePointToken:locations.get(`${path}.timePoint`)?.token,_path:`${path}.value`,_start:span?.start,_end:span?.end};});}else if(type==='text/csv'||type==='text/plain')rows=parseCSV(text);else fail('PARSER_UNAVAILABLE','This file is preserved, but requires a configured document/vision parser.');
 if(rows.length>500)fail('INPUT_TOO_LARGE','Maximum 500 parameters per source in this release.',413);
 return rows.map((r,i)=>{if(!r||typeof r!=='object')fail('PARSE_FAILED','Each parameter must be an object.');const parameter=requireValue(r.parameter,'Parameter',100).toLowerCase();const rawValue=r.value===null||r.value===undefined?'':typeof r.value==='number'&&r._valueToken?r._valueToken:String(r.value);const rawLow=(typeof r.low==='number'?r._lowToken:null)??(r.low===undefined||r.low===null?'':String(r.low)),rawHigh=(typeof r.high==='number'?r._highToken:null)??(r.high===undefined||r.high===null?'':String(r.high));for(const lexeme of [rawValue,rawLow,rawHigh,typeof r.timePoint==='number'?r._timePointToken:null].filter(x=>x!==null&&x!==undefined))if(lexeme&&lexeme!=='null'&&/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/.test(lexeme.trim())&&numeric(lexeme)===null)fail('AMBIGUOUS_NUMBER','Original numeric precision or range requires controlled decimal review.');const unit=String(r.unit||'').trim();const method=String(r.method||'').trim();return {parameter,rawValue,rawUnit:unit,method,batch:String(r.batch||'UNSPECIFIED'),product:String(r.product||''),facility:String(r.facility||''),low:numeric(rawLow),high:numeric(rawHigh),rawLowLexeme:rawLow,rawHighLexeme:rawHigh,condition:String(r.condition||''),timePoint:r.timePoint??null,timeUnit:String(r.timeUnit||''),rawTimePoint:r._timePointToken??(r.timePoint===undefined?null:String(r.timePoint)),basis:String(r.basis||''),span:{page:null,line:r._line,table:'parameters',row:i+1,column:'value',raw:r._raw,path:r._path,start:r._start,end:r._end,offsetKind:'UTF-16 character offsets',valueToken:r._valueToken||null}};});
}
export function normalizeField(field){let value=numeric(field.rawValue),unit=field.rawUnit.toLowerCase(),rule=null,status='CANDIDATE';if(value===null)status=field.rawValue.trim()?'NEEDS_REVIEW':'MISSING';if(!field.method||field.batch==='UNSPECIFIED'||!unit)status='NEEDS_REVIEW';let low=field.low,high=field.high; if(value!==null&&field.method&&(!['mg/g','g/kg'].includes(unit)||field.basis==='mass')){if(unit==='mg/g'){value=value/10;low=low===null?null:low/10;high=high===null?null:high/10;unit='%';rule='approved-unit-rule/1: mg/g to percent (mass basis)';}else if(unit==='g/kg'){value=value/10;low=low===null?null:low/10;high=high===null?null:high/10;unit='%';rule='approved-unit-rule/1: g/kg to percent (mass basis)';}else if(!['%','mg','g','ppm','mg/ml','ph','mmol/l'].includes(unit))status='NEEDS_REVIEW';}if(['mg/g','g/kg'].includes(unit)&&field.basis!=='mass')status='NEEDS_REVIEW';return {...field,rawLow:field.low,rawHigh:field.high,low,high,value,unit,status,normalization:rule?{rule,rawValue:field.rawValue,rawUnit:field.rawUnit,value,unit,at:now(),basis:field.basis}:null};}
function key(f){return `${f.parameter}|${f.batch}|${f.product}|${f.method}|${f.condition}|${f.basis}|${f.timePoint??''}|${f.timeUnit||''}`;}
export function checkState(state){
 const active=state.fields.filter(f=>!['STALE','REJECTED'].includes(f.status));const existing=new Map(state.conflicts.map(c=>[c.key,c]));let conflicts=[];
 const groups=new Map();for(const f of active){const k=key(f);groups.set(k,[...(groups.get(k)||[]),f]);}
 for(const [k,fs] of groups){const values=new Set(fs.filter(f=>f.value!==null).map(f=>`${f.value}|${f.unit}`));if(values.size>1){const prior=existing.get(k);const resolved=prior?.status==='RESOLVED'&&fs.some(f=>f.id===prior.selectedId);conflicts.push({...prior,id:prior?.id||uid('conflict'),key:k,type:'VALUE_CONFLICT',fieldIds:fs.map(f=>f.id),parameter:fs[0].parameter,batch:fs[0].batch,status:resolved?'RESOLVED':'OPEN',at:prior?.at||now()});}}
 state.conflicts=[...state.conflicts.filter(c=>!conflicts.some(n=>n.key===c.key)).map(c=>c.status==='OPEN'?{...c,status:'STALE'}:c),...conflicts];
 for(const f of active){f.issues=[];if(f.value===null)f.issues.push(f.rawValue.trim()?'NON_NUMERIC_VALUE':'MISSING_VALUE');if(!f.method)f.issues.push('MISSING_METHOD');if(f.batch==='UNSPECIFIED')f.issues.push('MISSING_BATCH');if(!f.rawUnit)f.issues.push('MISSING_UNIT');if(f.value!==null&&((f.low!==null&&f.value<f.low)||(f.high!==null&&f.value>f.high)))f.issues.push('OUTSIDE_RECORDED_LIMIT');if(conflicts.some(c=>c.status==='OPEN'&&c.fieldIds.includes(f.id)))f.issues.push('UNRESOLVED_CONFLICT');if(f.issues.length&&f.status==='APPROVED')f.status='NEEDS_REVIEW';}
 const present=new Set(active.filter(f=>f.value!==null).map(f=>f.parameter));return {missing:state.policy.required.filter(p=>!present.has(p)),conflicts:conflicts.filter(c=>c.status==='OPEN'),anomalies:active.filter(f=>f.issues?.includes('OUTSIDE_RECORDED_LIMIT')),uncertain:active.filter(f=>['NEEDS_REVIEW','MISSING'].includes(f.status))};
}
export function comparison(state){const fs=state.fields.filter(f=>!['STALE','REJECTED'].includes(f.status));const groups=new Map();for(const f of fs)groups.set(f.parameter,[...(groups.get(f.parameter)||[]),f]);return [...groups].map(([parameter,fields])=>{const contexts=new Set(fields.map(f=>JSON.stringify([f.method,f.unit,f.low,f.high,f.condition,f.basis,f.timePoint??null,f.timeUnit||''])));const comparable=contexts.size===1&&fields.every(f=>f.value!==null&&f.method&&f.rawUnit&&f.low!==null&&f.high!==null&&f.basis);const vs=fields.map(f=>f.value).filter(x=>x!==null);return {parameter,fields,comparable,reason:comparable?'Recorded methods, units, limits and available context match; missing context remains unrecorded.':'Method, unit, limits or conditions are missing or differ.',min:comparable?Math.min(...vs):null,max:comparable?Math.max(...vs):null,mean:comparable?vs.reduce((a,b)=>a+b,0)/vs.length:null,interpretation:'Descriptive evidence only. Variation does not establish batch failure or equivalence.'};});}
export function dependencyGraph(state){const nodes=[],edges=[];for(const s of state.sources)nodes.push({id:s.id,type:'source',label:s.name,status:s.status});for(const f of state.fields){nodes.push({id:f.id,type:'fact',label:`${f.parameter} · ${f.batch}`,status:f.status});edges.push({from:f.sourceId,to:f.id,reason:'exact source span'});}for(const d of state.drafts){nodes.push({id:d.id,type:'draft',label:d.title,status:d.status});for(const id of d.fieldIds)edges.push({from:id,to:d.id,reason:'statement evidence'});}for(const d of state.decisions){nodes.push({id:d.id,type:'decision',label:d.action,status:d.status});edges.push({from:d.targetId,to:d.id,reason:'revision-bound decision'});}for(const ex of state.exports){nodes.push({id:ex.id,type:'export',label:ex.name,status:ex.status});edges.push({from:ex.draftId,to:ex.id,reason:'approved snapshot'});}const extended=lifecycleGraph(structuredClone(state));nodes.push(...extended.nodes.filter(n=>!nodes.some(x=>x.id===n.id)));edges.push(...extended.edges.filter(e=>!edges.some(x=>x.from===e.from&&x.to===e.to)));return {nodes,edges};}
export function blastRadius(state,sourceId){getObject(state,'sources',sourceId);const g=dependencyGraph(state);const affected=new Set([sourceId]);let changed=true;while(changed){changed=false;for(const e of g.edges)if(e.dependency!==false&&affected.has(e.from)&&!affected.has(e.to)){affected.add(e.to);changed=true;}}return {included:g.nodes.filter(n=>affected.has(n.id)),excluded:g.nodes.filter(n=>!affected.has(n.id)).map(n=>({...n,reason:`No dependency path from source ${sourceId} in recorded graph revision ${state.version}.`}))};}
export function qcDraft(state,draft){const check=checkState(state);const issues=[];if(!draft.statements.length)issues.push({code:'EMPTY_DRAFT',message:'No supported statements.'});for(const st of draft.statements){const f=state.fields.find(x=>x.id===st.fieldId);if(!f){issues.push({code:'MISSING_CITATION',message:'Statement has no valid field citation.'});continue;}const source=state.sources.find(x=>x.id===f.sourceId);if(!source||source.status!=='PARSED'||source.hash!==f.sourceHash||!f.span?.raw)issues.push({code:'SOURCE_GAP',fieldId:f.id,message:'Exact current source span is required.'});if(f.status!=='APPROVED')issues.push({code:'UNAPPROVED_FACT',fieldId:f.id,message:'Fact is not approved for use.'});if(st.value!==f.value||st.unit!==f.unit)issues.push({code:'VALUE_MISMATCH',fieldId:f.id,message:'Draft value/unit differs from the cited fact.'});for(const message of statementIssues(st.text,f))issues.push({code:'TEXT_CONTEXT_OR_QUANTITY',fieldId:f.id,message});const expected=String(st.value);if(!st.text.includes(expected)||!st.text.includes(st.unit))issues.push({code:'TEXT_VALUE_MISMATCH',fieldId:f.id,message:'Statement text does not preserve the cited value and unit.'});const textNumbers=st.text.replaceAll(f.method,'').replaceAll(f.batch,'').match(/[-+]?\d+(?:\.\d+)?/g)||[];const allowed=new Set([String(f.value)]);if(textNumbers.some(n=>!allowed.has(n)))issues.push({code:'UNSUPPORTED_NUMBER',fieldId:f.id,message:'An unsupported numeric assertion appears in the statement.'});}
 if(check.missing.length)issues.push({code:'REQUIRED_DATA_MISSING',message:`Missing required parameters: ${check.missing.join(', ')}.`});return {id:uid('qc'),principal:'independent-qc/rules-1',authorPrincipal:draft.authorPrincipal,at:now(),passed:!issues.length,issues,denominator:draft.statements.length,checks:['source revision','field approval','numeric value','unit','citation','parameter / batch / method wording','quantity-unit pairing','required parameter coverage'],limitation:'Deterministic technical checks; qualified scientific/regulatory review is still required.'};}
export function readiness(state){const c=checkState(structuredClone(state));return {missing:c.missing,openConflicts:c.conflicts.length,uncertain:c.uncertain.length,anomalies:c.anomalies.length,unreviewed:state.fields.filter(f=>['CANDIDATE','NEEDS_REVIEW'].includes(f.status)).length,stale:state.fields.filter(f=>f.status==='STALE').length,traceCoverage:{numerator:state.fields.filter(f=>f.span?.raw&&f.sourceId).length,denominator:state.fields.length},approvedDrafts:state.drafts.filter(d=>d.status==='APPROVED').length,exportReady:state.drafts.some(d=>d.status==='APPROVED'&&d.qc?.passed)&&!c.missing.length&&!c.conflicts.length,release:false};}
export function snapshotDiff(snapshot,state){const old=snapshot.fields||[];return old.map(f=>{const current=state.fields.filter(n=>n.parameter===f.parameter&&n.batch===f.batch&&!['STALE','REJECTED'].includes(n.status));return {fieldId:f.id,parameter:f.parameter,batch:f.batch,submitted:f.value,submittedUnit:f.unit,current:current.map(n=>({value:n.value,unit:n.unit,status:n.status})),divergent:!current.some(n=>n.value===f.value&&n.unit===f.unit)};});}
export function signaturePayload(state,draft){return {draftId:draft.id,revision:draft.revision,title:draft.title,section:draft.section,statements:draft.statements,authorPrincipal:draft.authorPrincipal,modelVersion:draft.modelVersion,fields:draft.fieldIds.map(id=>{const f=getObject(state,'fields',id);return {id:f.id,revision:f.revision,value:f.value,unit:f.unit,sourceId:f.sourceId,sourceVersion:f.sourceVersion,sourceHash:f.sourceHash};}),decisionId:state.decisions.findLast(d=>d.targetId===draft.id&&d.status==='CURRENT'&&d.action==='APPROVE')?.id||null,policyVersion:state.policy.version,workflowVersion:VERSION};}
export const SYNTHETIC_SOURCES=[
 {name:'SYN-COA-A.json',type:'application/json',text:JSON.stringify({parameters:[{parameter:'assay',value:98.6,unit:'%',method:'HPLC-SYN-01',batch:'SYN-A',low:95,high:105,basis:'mass'},{parameter:'water',value:0.3,unit:'%',method:'KF-SYN-01',batch:'SYN-A',low:0,high:1,basis:'mass'},{parameter:'impurity',value:0.08,unit:'%',method:'HPLC-SYN-02',batch:'SYN-A',low:0,high:0.2,basis:'mass'}]},null,2)},
 {name:'SYN-BATCH-A.json',type:'application/json',text:JSON.stringify({parameters:[{parameter:'assay',value:99.1,unit:'%',method:'HPLC-SYN-01',batch:'SYN-A',low:95,high:105,basis:'mass'}]},null,2)},
 {name:'SYN-COA-B.json',type:'application/json',text:JSON.stringify({parameters:[{parameter:'assay',value:986,unit:'mg/g',method:'HPLC-SYN-01',batch:'SYN-B',low:950,high:1050,basis:'mass'},{parameter:'water',value:0.4,unit:'%',method:'KF-SYN-01',batch:'SYN-B',low:0,high:1,basis:'mass'},{parameter:'impurity',value:0.09,unit:'%',method:'HPLC-SYN-02',batch:'SYN-B',low:0,high:0.2,basis:'mass'}]},null,2)}
];
export async function command(before,input,actor){const s=structuredClone(before);const action=requireValue(input.action,'Action',50);if(!actor?.id)fail('UNAUTHENTICATED','Sign in to continue.',401);if(!actorCan(actor.role,action))fail('FORBIDDEN','Your workspace role does not permit this action.',403);if(input.expectedVersion!==s.version)fail('STALE_REVISION','The workspace changed. Refresh and review the current revision.',409);let result={};
 switch(action){
 case 'branch':{result=await branchAction(s,input,actor);break;}
 case 'lifecycle':{const {action:_,expectedVersion:__,workspaceId:___,...payload}=input;result=await lifecycleAction(s,payload,actor);break;}
 case 'capability':{result=capability(s,input.capabilityId,{sourceId:input.sourceId,query:input.query});s.agentRuns.push({id:uid('capabilityRun'),...result,traceId:actor.traceId||uid('run'),at:now()});break;}
 case 'plan':{const p=makePlan(s,input.goal,input.sourceId);s.plans.push(p);result={planId:p.id};break;}
 case 'replan':{const p=getObject(s,'plans',input.id),updated=replan(s,p);Object.assign(p,updated);result={plan:p};break;}
 case 'planControl':{const p=getObject(s,'plans',input.id);if(!['PAUSED','ESCALATED','READY'].includes(input.status))fail('INVALID_STATE','Choose pause, escalate or resume.');p.status=input.status;p.controlReason=requireValue(input.reason,'Control reason');p.controlledBy=actor.id;p.updatedAt=now();break;}
 case 'collaborate':{const roles=input.roles||['A3','A5','A11','A12'];if(!Array.isArray(roles)||roles.length>6)fail('ROLE_LIMIT','At most six specialists per collaboration run.');const start=performance.now();const runs=roles.map(role=>executeRole(s,role,{sourceId:input.sourceId}));const merged=mergeSpecialistOutputs(runs);const run={id:uid('collaboration'),...merged,latencyMs:Math.round(performance.now()-start),cost:null,costState:'NOT_MEASURED',traceId:actor.traceId||uid('run'),at:now()};s.agentRuns.push(run);result={runId:run.id,status:run.status};break;}
 case 'intake':{requireValue(input.permission,'Source permission',200);const name=requireValue(input.name,'Filename',180);if(name.includes('/')||name.includes('\\')||name.includes('..'))fail('UNSAFE_FILENAME','Use a plain filename.');const allowed=['application/json','text/csv','text/plain','application/pdf','image/png','image/jpeg','application/xml','text/xml','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'];if(!allowed.includes(input.type))fail('UNSUPPORTED_TYPE','Supported intake: JSON, CSV, text, XML, Word, Excel, PDF, PNG or JPEG.');if(input.purpose&&input.purpose!==s.purpose)fail('WRONG_PURPOSE','The source purpose must match this workspace.');const content=input.text||'';if(input.hash&&['application/json','text/csv','text/plain'].includes(input.type)&&input.hash!==await hash(content))fail('SOURCE_HASH_MISMATCH','Supplied content does not match the original hash.');const source={id:uid('src'),logicalId:input.logicalId||uid('doc'),name,type:input.type,hash:input.hash||await hash(content),text:content,objectKey:input.objectKey||null,permission:input.permission,purpose:s.purpose,version:1,status:'UPLOADED',at:now(),parser:PARSER,product:s.product,dataLabel:input.dataLabel||'USER_SUPPLIED',uploadedBy:actor.id};s.sources.push(source);result={sourceId:source.id};break;}
 case 'extract':{const source=getObject(s,'sources',input.id);if(source.status==='SUPERSEDED')fail('STALE_SOURCE','Extract the current source revision.',409);if(source.status==='PARSED'){result={sourceId:source.id,idempotent:true};break;}try{const rows=parseSource(source.text,source.type);s.fields.push(...rows.map(r=>normalizeField({...r,id:uid('fact'),sourceId:source.id,sourceVersion:source.version,sourceHash:source.hash,product:r.product||s.product,revision:1,at:now()})));source.status='PARSED';source.extractedAt=now();source.failure=null;checkState(s);result={count:rows.length};}catch(e){source.status=e.code==='PARSER_UNAVAILABLE'?'NEEDS_REVIEW':'SOURCE_FAILED';source.failure=e.message;result={failure:e.message,state:source.status};}break;}
 case 'normalize':{const f=getObject(s,'fields',input.id);if(f.status==='STALE')fail('STALE_SOURCE','Use current facts.',409);if(f.normalization)fail('ALREADY_NORMALIZED','This fact already has a recorded normalization.');const permitted={'mg:g':0.001,'g:mg':1000,'ppm:%':0.0001};const to=requireValue(input.unit,'Target unit',30);const rule=`${f.rawUnit}:${to}`;if(!(rule in permitted)||numeric(f.rawValue)===null||!f.method||!f.basis)fail('AMBIGUOUS_CONVERSION','An approved rule, numeric value, method and basis are required.');f.value=Number(f.rawValue)*permitted[rule];f.unit=to;f.normalization={rule:`reviewed-conversion/${rule}`,rawValue:f.rawValue,rawUnit:f.rawUnit,value:f.value,unit:to,reason:requireValue(input.reason,'Reason'),reviewer:actor.id,at:now()};f.revision++;f.status='CANDIDATE';checkState(s);break;}
 case 'resolveConflict':{const c=getObject(s,'conflicts',input.id);if(c.status!=='OPEN')fail('ALREADY_RESOLVED','Conflict is no longer open.',409);if(!c.fieldIds.includes(input.selectedId))fail('INVALID_SELECTION','Selected fact is not part of the conflict.');c.status='RESOLVED';c.selectedId=input.selectedId;c.reason=requireValue(input.reason,'Scientific review reason');c.reviewer=actor.id;c.resolvedAt=now();for(const id of c.fieldIds){const f=getObject(s,'fields',id);if(id!==input.selectedId)f.status='REJECTED';}checkState(s);break;}
 case 'review':{const collection=input.kind==='field'?'fields':'drafts';const obj=getObject(s,collection,input.id);if(input.revision!==obj.revision)fail('STALE_REVISION','This candidate revision changed.',409);if(['STALE','REJECTED'].includes(obj.status))fail('INVALID_STATE','A stale or rejected candidate cannot be approved.',409);const choice=input.choice;if(!['APPROVE','REVISE','REQUEST_EVIDENCE','REJECT'].includes(choice))fail('INVALID_DECISION','Choose one of the four review actions.');const reason=requireValue(input.reason,'Decision reason',2000);if(choice==='APPROVE'){if(obj.lastEditedBy===actor.id||obj.editContributors?.includes(actor.id)||obj.correction?.reviewer===actor.id)fail('INDEPENDENT_REVIEW_REQUIRED','A different authorized reviewer must approve human-authored corrections or edited content.',403);if(collection==='fields'){checkState(s);if(obj.issues?.length||obj.value===null)fail('EVIDENCE_GAP','Resolve missing information, anomalies and conflicts before approval.',409);}else{obj.qc=qcDraft(s,obj);if(!obj.qc.passed)fail('QC_FAILED','Independent QC found blockers. Resolve them before approval.',409);}}if(choice==='REVISE'){if(collection==='fields'){const value=numeric(input.value);if(value===null)fail('INVALID_VALUE','Correction requires a numeric value.');if(value!==normalizeField(obj).value)fail('UNSUPPORTED_CORRECTION','Correction must match the exact source value under its approved conversion. Upload a new source revision for a changed scientific value.');obj.originalValue=obj.value;obj.value=value;obj.correction={reason,reviewer:actor.id,at:now(),sourceId:obj.sourceId,originalValue:obj.originalValue};obj.revision++;obj.status='CANDIDATE';for(const d of s.drafts.filter(d=>d.fieldIds.includes(obj.id)))d.status='STALE';}else{obj.revision++;obj.status='CANDIDATE';} }else obj.status={APPROVE:'APPROVED',REQUEST_EVIDENCE:'NEEDS_REVIEW',REJECT:'REJECTED'}[choice];const decision={id:uid('decision'),targetId:obj.id,kind:input.kind,revision:obj.revision,workspaceRevision:s.version,sourceHashes:collection==='fields'?[obj.sourceHash]:obj.fieldIds.map(id=>getObject(s,'fields',id).sourceHash),ruleVersion:s.policy.version,workflowVersion:VERSION,modelVersion:obj.modelVersion||'deterministic/no-model',reviewer:actor.id,action:choice,reason,status:'CURRENT',at:now()};s.decisions.push(decision);result={decisionId:decision.id};break;}
 case 'draft':{const fields=s.fields.filter(f=>f.status==='APPROVED'&&(!input.fieldIds||input.fieldIds.includes(f.id)));if(!fields.length)fail('NO_APPROVED_FACTS','Approve supported facts before creating a draft.',409);const draft={id:uid('draft'),title:requireValue(input.title||'Module 3 · Quality evidence draft','Draft title',180),section:input.section==='3.2.S'?'3.2.S':'3.2.P',revision:1,authorPrincipal:'author/deterministic-template-1',modelVersion:'deterministic/no-model',fieldIds:fields.map(f=>f.id),statements:fields.map(f=>({id:uid('statement'),fieldId:f.id,value:f.value,unit:f.unit,text:`The recorded ${f.parameter} for batch ${f.batch} is ${f.value} ${f.unit}, determined using ${f.method}.`,sourceId:f.sourceId,sourceVersion:f.sourceVersion,span:f.span})),status:'CANDIDATE',at:now(),limitation:'Technical draft from approved facts. No autonomous scientific disposition or eCTD conformance claim.'};draft.qc=qcDraft(s,draft);s.drafts.push(draft);result={draftId:draft.id};break;}
 case 'editDraft':{const d=getObject(s,'drafts',input.id);if(d.status==='STALE')fail('STALE_REVISION','Create a new draft from current facts.',409);const st=d.statements.find(x=>x.id===input.statementId);if(!st)fail('NOT_FOUND','Statement is unavailable.',404);st.text=requireValue(input.text,'Statement text',2000);if(input.value!==undefined)st.value=numeric(input.value);d.revision++;d.lastEditedBy=actor.id;d.status='CANDIDATE';d.qc=qcDraft(s,d);for(const dec of s.decisions.filter(x=>x.targetId===d.id))dec.status='STALE';break;}
 case 'qc':{const d=getObject(s,'drafts',input.id);d.qc=qcDraft(s,d);result={qc:d.qc};break;}
 case 'change':{const old=getObject(s,'sources',input.id);if(old.status==='SUPERSEDED')fail('STALE_SOURCE','This source has already been superseded.',409);const radius=blastRadius(s,old.id);requireValue(input.text,'Revised source text',1_000_000);const source={...old,id:uid('src'),hash:await hash(input.text),text:input.text,objectKey:input.objectKey||null,version:old.version+1,status:'UPLOADED',at:now(),predecessorId:old.id,uploadedBy:actor.id};old.status='SUPERSEDED';s.sources.push(source);invalidateLifecycle(s,old.id);const ids=new Set(radius.included.map(x=>x.id));for(const f of s.fields)if(ids.has(f.id))f.status='STALE';for(const d of s.drafts)if(ids.has(d.id))d.status='STALE';for(const d of s.decisions)if(ids.has(d.id))d.status='STALE';for(const a of s.actions)if(a.sourceIds?.includes(old.id)&&a.status==='CLOSED_WITH_EVIDENCE'){a.status='REOPENED';a.reopenReason='New source revision invalidates closure dependency.';}s.changes.push({id:uid('change'),oldSourceId:old.id,newSourceId:source.id,reason:requireValue(input.reason,'Change reason'),included:radius.included,excluded:radius.excluded,at:now(),classification:'HUMAN_REVIEW_REQUIRED'});checkState(s);result={sourceId:source.id,impact:radius};break;}
 case 'supersedeSource':{const old=getObject(s,'sources',input.id),source=getObject(s,'sources',input.replacementId);if(old.id===source.id||old.status==='SUPERSEDED'||source.status!=='UPLOADED'||!source.objectKey)fail('INVALID_REPLACEMENT','Use a newly uploaded original and a current predecessor.',409);const reason=requireValue(input.reason,'Original revision reason',2000),radius=blastRadius(s,old.id);source.version=old.version+1;source.predecessorId=old.id;old.status='SUPERSEDED';invalidateLifecycle(s,old.id);const ids=new Set(radius.included.map(x=>x.id));for(const f of s.fields)if(ids.has(f.id))f.status='STALE';for(const d of s.drafts)if(ids.has(d.id))d.status='STALE';for(const d of s.decisions)if(ids.has(d.id))d.status='STALE';for(const a of s.actions)if(a.sourceIds?.includes(old.id)&&a.status==='CLOSED_WITH_EVIDENCE'){a.status='REOPENED';a.reopenReason='Original source revision changed.';}s.changes.push({id:uid('change'),oldSourceId:old.id,newSourceId:source.id,reason,included:radius.included,excluded:radius.excluded,at:now(),classification:'HUMAN_REVIEW_REQUIRED'});checkState(s);result={sourceId:source.id,impact:radius};break;}
 case 'simulate':{result={impact:blastRadius(s,input.id),simulated:true,productionStateChanged:false};break;}
 case 'export':{const d=getObject(s,'drafts',input.id);if(d.status!=='APPROVED')fail('UNAPPROVED_DRAFT','Only an approved current draft can be exported.',409);d.qc=qcDraft(s,d);if(!d.qc.passed)fail('QC_FAILED','Current evidence does not pass technical QC.',409);const decision=s.decisions.findLast(x=>x.targetId===d.id&&x.action==='APPROVE'&&x.status==='CURRENT'&&x.revision===d.revision);if(!decision)fail('STALE_APPROVAL','A current exact-revision approval is required.',409);const manifest=structuredClone({format:'FORGE controlled evidence package/1',product:s.product,draft:structuredClone(d),fields:s.fields.filter(f=>d.fieldIds.includes(f.id)),sources:s.sources.filter(src=>d.fieldIds.some(id=>getObject(s,'fields',id).sourceId===src.id)).map(({text,...meta})=>meta),decision,policyVersion:s.policy.version,workflowVersion:VERSION,release:false,signingPayload:signaturePayload(s,d),createdAt:now()});if(input.verifiedSignature&&input.verifiedSignature.revisionHash!==await hash(JSON.stringify(manifest.signingPayload)))fail('SIGNATURE_HASH_MISMATCH','Signature does not bind the exact current evidence revision.',409);const ex={id:uid('export'),name:`${d.section} evidence package`,draftId:d.id,revision:d.revision,status:'SNAPSHOT',manifest,hash:await hash(JSON.stringify(manifest)),at:now(),signature:input.verifiedSignature||null,finalized:Boolean(input.verifiedSignature),limitation:input.verifiedSignature?'Signature-bound evidence package; organization-specific qualification remains required.':'Unsigned controlled evidence package; not a finalized dossier.'};s.exports.push(ex);result={exportId:ex.id};break;}
 case 'query':{const title=requireValue(input.title,'HA question',2000);const fieldIds=(input.fieldIds||[]).filter(id=>s.fields.some(f=>f.id===id&&f.status==='APPROVED'));const precedents=s.queries.filter(q=>q.status==='APPROVED'&&q.verifiedOutcome===true&&title.toLowerCase().split(/\W+/).filter(w=>w.length>4).some(w=>q.title.toLowerCase().includes(w))).map(q=>q.id);const q={id:uid('haq'),createdBy:actor.id,revision:1,title,market:input.market||'UNSPECIFIED',fieldIds,precedents,status:'CANDIDATE',response:fieldIds.length?fieldIds.map(id=>{const f=getObject(s,'fields',id);return {fieldId:id,text:`Recorded ${f.parameter}: ${f.value} ${f.unit}; source ${f.sourceId}, revision ${f.sourceVersion}.`};}):[],at:now(),limitation:'Candidate response; no authority expectation or invented precedent.'};s.queries.push(q);result={queryId:q.id};break;}
 case 'queryDecision':{const q=getObject(s,'queries',input.id);if(input.revision!==q.revision)fail('STALE_REVISION','The inquiry revision changed; refresh before review.',409);if(q.createdBy===actor.id)fail('INDEPENDENT_REVIEW_REQUIRED','The inquiry author cannot approve their own response.',403);if(!['owner','reviewer','approver'].includes(actor.role))fail('FORBIDDEN','Review permission required.',403);if(!q.fieldIds.length||q.fieldIds.some(id=>{const f=getObject(s,'fields',id),src=getObject(s,'sources',f.sourceId);return f.status!=='APPROVED'||f.sourceHash!==src.hash||f.sourceVersion!==src.version||src.status==='SUPERSEDED';}))fail('EVIDENCE_GAP','Current approved source evidence is required to review this response.',409);q.status='APPROVED';q.reviewNote=requireValue(input.reason,'Response review reason',2000);q.outcomeEvidence='NOT_RECORDED';q.verifiedOutcome=false;q.reviewer=actor.id;q.reviewedRevision=q.revision;q.approvedAt=now();break;}
 case 'action':{const a={id:uid('action'),title:requireValue(input.title,'Action title',200),owner:requireValue(input.owner||actor.id,'Action owner',100),createdBy:actor.id,due:input.due||null,status:'OPEN',sourceIds:(input.sourceIds||[]).map(id=>getObject(s,'sources',id).id),expected:requireValue(input.expected,'Expected outcome',1000),at:now(),evidence:[]};s.actions.push(a);result={actionId:a.id};break;}
 case 'close':{const a=getObject(s,'actions',input.id);if(actor.id===a.owner||actor.id===a.createdBy)fail('INDEPENDENT_REVIEW_REQUIRED','An independent reviewer must verify this closure.',403);const evidence=requireValue(input.evidence,'Actual implementation evidence',2000);if(!a.sourceIds.length||a.sourceIds.some(id=>getObject(s,'sources',id).status!=='PARSED'))fail('EVIDENCE_GAP','Current source-linked closure evidence is required.',409);a.evidence.push({text:evidence,reviewer:actor.id,at:now()});a.status='CLOSED_WITH_EVIDENCE';a.closedAt=now();break;}
 case 'mapping':{const status=input.status||'UNMAPPED';if(!['UNMAPPED','MATCHED','CONFLICT','RETIRED'].includes(status))fail('INVALID_MAPPING','Unsupported mapping state.');const localId=requireValue(input.localId,'Local ID',100);const externalSystem=requireValue(input.externalSystem,'External system',100);const externalUuid=requireValue(input.externalUuid,'External UUID',100);const prior=s.mappings.find(m=>m.localId===localId&&m.externalSystem===externalSystem);s.mappings.push({id:uid('map'),localId,entity:input.entity||'Product_ID',externalUuid,externalSystem,status,predecessorId:prior?.id||null,at:now(),reason:requireValue(input.reason,'Mapping reason')});break;}
 case 'market':{s.markets.push({id:uid('market'),market:requireValue(input.market,'Market',100),product:s.product,dossier:requireValue(input.dossier,'Dossier ID',100),sourceIds:(input.sourceIds||[]).map(id=>getObject(s,'sources',id).id),submittedState:input.submittedState||'NOT_RECORDED',at:now(),classification:'HUMAN_REVIEW_REQUIRED'});break;}
 case 'lineage':{const from=requireValue(input.from,'From object',100),to=requireValue(input.to,'To object',100);s.lineage.push({id:uid('edge'),from,to,type:input.type||'batch-process',sourceId:getObject(s,'sources',input.sourceId).id,reason:requireValue(input.reason,'Evidence reason'),at:now()});break;}
 case 'template':{const title=requireValue(input.title,'Template name',100);s.templates.push({id:uid('template'),title,section:input.section||'3.2.P',text:requireValue(input.text,'Template text',5000),status:'CANDIDATE',version:1,author:actor.id,at:now()});break;}
 case 'requirement':{if(!['owner','admin'].includes(actor.role))fail('FORBIDDEN','Policy administration required.',403);s.requirements.push({id:uid('req'),title:requireValue(input.title,'Requirement',300),sourceId:getObject(s,'sources',input.sourceId).id,parameter:requireValue(input.parameter,'Parameter',100),market:input.market||'UNSPECIFIED',status:'SPECIFIED',at:now()});break;}
 case 'retry':{const j=getObject(s,'jobs',input.id);if(j.attempts>=4)fail('RETRY_EXHAUSTED','Initial invocation and three retries exhausted. An owned manual path is required.',409);j.attempts++;j.status='QUEUED';j.nextAttemptAt=new Date(Date.now()+1000*2**j.attempts).toISOString();break;}
 case 'runSpecialist':{const role=requireValue(input.role,'Specialist role',100);const start=performance.now(),output=executeRole(s,role,{sourceId:input.sourceId});const run={id:uid('agentRun'),...output,latencyMs:Math.round(performance.now()-start),cost:null,costState:'NOT_MEASURED',traceId:actor.traceId||uid('run')};s.agentRuns.push(run);result={runId:run.id,state:output.state};break;}
 default:fail('UNKNOWN_ACTION','Unsupported workflow action.');
 }
 audit(s,actor,action,input.id||result.sourceId||result.draftId||result.exportId||'workspace',{result,reason:input.reason||null});s.version++;return {state:s,result};
}
export async function seedSynthetic(){let s=initialState('Synthetic CMC review','Synthetic formulation');const actor={id:'demo-human',role:'owner'};for(const src of SYNTHETIC_SOURCES){let r=await command(s,{action:'intake',expectedVersion:s.version,...src,permission:'Synthetic fixture supplied for public-safe demonstration',dataLabel:'SYNTHETIC'},actor);s=r.state;r=await command(s,{action:'extract',expectedVersion:s.version,id:r.result.sourceId},actor);s=r.state;}return s;}
