import ProofNavigation from '../proof-navigation';
import Link from 'next/link';
export const metadata={title:'FORGE | CMC documentation support and working proof',description:'Explore the problem, source-to-review workflow, synthetic CMC case and honest operating boundaries.'};
export default function Page(){return <main className="pow-page"><Link href="/">← FORGE home</Link><div className="pow-hero"><span>CMC DOCUMENTATION / WORKING PORTFOLIO PROOF</span><h1>From scattered records<br/>to reviewable CMC evidence.</h1><p>FORGE supports a professional documentation workflow. Source-linked facts, visible gaps, candidate Module 3 drafts and exact-revision human review stay connected.</p><div className="pow-actions"><Link href="/demo">TRY SYNTHETIC SANDBOX ↗</Link><Link href="/recruiter#guided">FOLLOW THE GUIDED CASE →</Link></div></div>
<ProofNavigation items={[["problem","Problem"],["how","How it works"],["proof","Working proof"],["limits","Limits & next evidence"]]}/>
<section id="problem"><h2>The documentation problem.</h2><div className="pow-grid"><article className="pow-card"><h3>Facts spread across records</h3><p>Numbers, units, methods and batch context must be checked against their originals.</p></article><article className="pow-card"><h3>Gaps can hide inside drafts</h3><p>A candidate statement can look complete while composition, validation or stability evidence is absent.</p></article><article className="pow-card"><h3>Changes affect downstream work</h3><p>A revised source can make an earlier fact, draft or approval stale.</p></article></div><p>FORGE organizes this evidence and highlights the next review action. Qualified CMC / RA / QA judgement remains required.</p></section>
<section id="how"><h2>One controlled evidence thread.</h2><ol className="pow-stage-list">{[['Preserve','Retain the permitted original, version and evidence identity.'],['Extract','Keep raw facts, units, batch context and source locations.'],['Check','Surface conflicts, missing information and unsupported candidates.'],['Prepare','Map supported facts into candidate Module 3 content.'],['Review','A named authorized person decides on the exact current revision.'],['Control output','Record evidence and review state; do not imply submission acceptance.']].map(([title,copy],i)=><li key={title}><small>STEP {i+1}</small><h3>{title}</h3><p>{copy}</p></li>)}</ol></section>
<section id="proof"><h2>Inspect the result, not just the illustration.</h2><p>The existing synthetic fixture has three source records and conflicting assay values of 98.6% and 99.1% for SYN-A. The recruiter page runs the fixture engine and shows the open conflict and blocked export state. The sandbox lets you inspect sources, facts, drafts, review and history without creating an account.</p><div className="pow-actions"><Link href="/recruiter#controlled-failure">SEE CONTROLLED FAILURE →</Link><Link href="/recruiter">VIEW CMC WORK SAMPLE →</Link><Link href="/demo?view=graph">INSPECT EVIDENCE GRAPH ↗</Link></div><p>Public demo records are synthetic and session-only. Sign-in opens a separate saved workspace. A public demo decision is not a professional validation.</p></section>
<section id="limits"><h2>Clear operating boundaries.</h2><div className="pow-boundary"><p>Recorded engineering checks are separate from regulatory accuracy, commercial CMC experience and production qualification. Live synthetic Groq collaboration and public Firecrawl discovery have passed a bounded check with saved readback. Qualified review and professional pilot evidence remain pending.</p><p>No invented time-saving percentage, client results, integration logos or live service-level benchmark. Provider/API integration claims require an actually configured and tested connection.</p></div><div className="pow-actions"><Link href="/mvp-checklist">TEN-STEP ENGINEERING EVIDENCE →</Link><Link href="/login?mode=signup">CREATE A WORKSPACE ↗</Link><Link href="https://portfolio.r4dewangan.chatgpt.site/#regulatory-work" target="_blank" rel="noopener noreferrer">RA / CMC PORTFOLIO ↗</Link></div></section></main>;}
