import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {database,loadWorkspace,listWorkspaces,commitWorkspace} from '../../../lib/repository';
import {ForgeError,hash,actorCan,audit,uid} from '../../../lib/core.mjs';
import {providerConfig,firecrawlKey} from '../../../lib/provider-config.mjs';
import {inferCollaboration} from '../../../lib/model-gateway.mjs';
import {firecrawlDiscovery,PUBLIC_REFERENCES} from '../../../lib/public-discovery.mjs';
import {boundedBody} from '../../../lib/http.mjs';
import {statementIssues} from '../../../lib/statement-controls.mjs';
export const dynamic='force-dynamic';
const headers={'cache-control':'no-store','x-content-type-options':'nosniff'};
async function context(request:Request){const u=await getChatGPTUser();if(!u)throw new ForgeError('UNAUTHENTICATED','Sign in for provider checks.',401);const requested=new URL(request.url).searchParams.get('workspace'),list=await listWorkspaces(u.userId),candidate=requested||list[0]?.id,id=typeof candidate==='string'?candidate:null;return {u,ws:id?await loadWorkspace(id,u.userId):null};}
const flags=()=>({groq:Boolean((env as any).GROQ_API_KEY),firecrawl:Boolean(firecrawlKey(env))});
export async function GET(request:Request){try{const {ws}=await context(request);return Response.json({configured:flags(),latest:ws?.state.providerProofs?.at(-1)||null},{headers});}catch(e:any){return Response.json({error:e instanceof ForgeError?e.message:'Provider inspection unavailable.'},{status:e.status||503,headers});}}
export async function POST(request:Request){try{
 if(request.headers.get('origin')!==new URL(request.url).origin)throw new ForgeError('CROSS_ORIGIN_BLOCKED','Same-origin request required.',403);
 const input=JSON.parse(new TextDecoder().decode(await boundedBody(request,1000)));if(input.consent!==true||input.sourceId!=='fda')throw new ForgeError('CONSENT_REQUIRED','Approve the fixed synthetic/public check.',403);
 const {u,ws}=await context(request);if(!ws)throw new ForgeError('WORKSPACE_REQUIRED','Create a workspace first.',409);if(!actorCan(ws.role,'draft'))throw new ForgeError('FORBIDDEN','Provider checks require authoring permission.',403);
 const window=Math.floor(Date.now()/600000),key='provider-proof:'+u.userId+':'+window,count=await database().prepare('INSERT INTO request_limits(id,count,expires_at) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(key,new Date((window+2)*600000).toISOString()).first<{count:number}>();if((count?.count||0)>1)throw new ForgeError('RATE_LIMITED','One bounded provider check per account per 10 minutes.',429);
 const result:any={id:uid('providerProof'),at:new Date().toISOString(),label:'SYNTHETIC_PUBLIC_PROVIDER_SMOKE',checks:[],professionalValidation:false,customerBenefitProven:false,release:false};
 try{const candidate=await inferCollaboration([{id:'probe-assay',parameter:'assay',value:98.6,unit:'%',batch:'SYN-A',method:'HPLC',sourceVersion:1,sourceHash:'synthetic-probe-v1',status:'APPROVED'},{id:'probe-weight',parameter:'weight',value:100,unit:'mg',batch:'SYN-A',method:'gravimetric',sourceVersion:1,sourceHash:'synthetic-probe-v1',status:'APPROVED'}],{...providerConfig(env),operationId:result.id});const facts=[{id:'probe-assay',parameter:'assay',value:98.6,unit:'%',batch:'SYN-A',method:'HPLC'},{id:'probe-weight',parameter:'weight',value:100,unit:'mg',batch:'SYN-A',method:'gravimetric'}];for(const f of facts){const st=candidate.statements.find((s:any)=>s.fieldId===f.id);if(!st||statementIssues(st.text,f).length)throw new ForgeError('PROBE_FACT_MISMATCH','Synthetic numbers or units did not survive the candidate.',409);}result.checks.push({name:'Groq bounded model team',status:'PASS',models:[candidate.model,candidate.reviewerModel],runs:candidate.runs,usage:candidate.usage,latencyMs:candidate.latencyMs,evidenceHash:candidate.evidenceHash});}catch(e:any){result.checks.push({name:'Groq bounded model team',status:'HOLD',reason:e.code||'PROVIDER_FAILED'});}
 try{const ref=PUBLIC_REFERENCES.fda,d=await firecrawlDiscovery(ref.url,firecrawlKey(env),ref.hosts);result.checks.push({name:'Firecrawl public FDA discovery',status:'PASS',url:d.url,retrievalMode:d.retrievalMode,originalBytesVerified:false,latencyMs:d.latencyMs,htmlCharacters:d.html.length});}catch(e:any){result.checks.push({name:'Firecrawl public FDA discovery',status:'HOLD',reason:/^[A-Z_0-9]+$/.test(e.message)?e.message:'PROVIDER_FAILED'});}
 result.status=result.checks.every((c:any)=>c.status==='PASS')?'SYNTHETIC_SMOKE_PASSED':'HOLD';const after=structuredClone(ws.state);after.providerProofs=[...(after.providerProofs||[]).slice(-19),result];audit(after,{id:u.userId,role:ws.role,traceId:result.id},'providerSmoke',result.id,{status:result.status,synthetic:true,release:false});after.version++;
 await commitWorkspace(ws.id,ws.state,after,u.userId,ws.role,result.id,await hash(JSON.stringify(input)),result);return Response.json({saved:true,result},{headers});
 }catch(e:any){return Response.json({error:e instanceof ForgeError?e.message:'Provider check could not be saved. No successful saved check is claimed.'},{status:e.status||503,headers});}}
